### ISSUE TITLE
USB keyboards and mice not working when Logitech G810 keyboard is plugged in

### ISSUE THREAD

**Issue by xternal7** [sddm/sddm#1003]
I have a Logitech G810 keyboard. SDDM doesn't work with this keyboard if I soft-restart my laptop (`reboot`, `reboot -f`, if I click the 'reboot' option on Windows and boot into Linux). Not only does the keyboard not work on SDDM (keypresses don't get registered), the USB mouse doesn't work either (doesn't move) if G810 is plugged in.

However:

1. Laptop keyboard and touchpad both work fine, and so does (a different keyboard (different model)) at work.¹  
2. G810 works just fine in rEFInd and GRUB¹
3. G810 and mouse start working the moment I log in¹
4. If I switch to TTY2 (via laptop keyboard), G810 will work in TTY2 _and also_ when I switch back to the graphical session²
5. If I disable SDDM autostart and launch it from TTY manually (via `systemctl start`), G810 will work just fine²
6. G810 will often (but not always!) work on cold boots (when laptop was turned off completely)¹

2., 3., 4. and 5. seem to suggest that this _is_ a SDDM issue.

**dmesg logs:**
* Normal boot: [dmesg_G810_sddm.log](https://github.com/sddm/sddm/files/1848972/dmesg_G810_sddm.log)
* Boot without SDDM (for baseline): [logitech_dmesg_NOsddm.log](https://github.com/sddm/sddm/files/1848980/logitech_dmesg_NOsddm.log)

**Other system info**
* sddm version:  `sddm-0.17.0-5`
* manjaro/arch packages
* Display server: X11/xorg

---

¹ Extensively tested
² Not extensively tested

**Comment by davidedmundson** [comment]
>2., 3., 4. and 5. seem to suggest that this is a SDDM issue.

It doesn't. It suggests there's an issue with your keyboard setup and X. 

If another display manager works fine and SDDM doesn't, feel free to reopen it, till then check your X setup
