### ISSUE TITLE
sddm doesn't unlock kwallet

### ISSUE THREAD

**Issue by caderobinson** [sddm/sddm#1004]
With the default sddm pam stack that has the system-login include before the pam_kwallet5 line, kwallet will not automatically unlock when logging in.
If I move the system-login lines to below the pam_kwallet5 lines then unlocking works.

I am running Arch with sddm 0.17.0-5

This doesn't work to unlock:
```
auth            include         system-login
-auth           optional        pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so

account         include         system-login

password        include         system-login
-password       optional        pam_gnome_keyring.so use_authtok

session         optional        pam_keyinit.so force revoke
session         include         system-login
-session                optional        pam_gnome_keyring.so auto_start

```
This does:
```
-auth           optional        pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so
auth            include         system-login

account         include         system-login

-password       optional        pam_gnome_keyring.so use_authtok
password        include         system-login

session         optional        pam_keyinit.so force revoke
-session                optional        pam_gnome_keyring.so auto_start
-session  optional  pam_kwallet5.so auto_start
session         include         system-login
```

**Comment by meijieru** [comment]
Same issue for gnome keyring

**Comment by davidedmundson** [comment]
> If I move the system-login lines to below the pam_kwallet5 lines then unlocking works.

Why does that make it work?

**Comment by Maryse47** [comment]
Perhaps  it depends on what `system-login` and `system-auth` look like on user machine. I guess when someone has module with `sufficient` state and it succeeds then `pam_kwallet5` won't be called when it's put below it.

On the other hand putting pam_kwallet5/gnome_keyring above all pam modules isn't desirable as general solution.

For a scenario described above I would recommend instead to add manually pam_kwallet5/gnome_keyring above module with `sufficient` state.

**Comment by caderobinson** [comment]
4 years later I am finally building a new PC and reinstalling.
Reviewing this and it is the order with sufficient.
system-login calls system-auth and in there I have a sufficient for sssd.
