### ISSUE TITLE
sddm make me wait 90s at shutdown

### ISSUE THREAD

**Issue by kyawthusoe3142** [sddm/sddm#1005]
Mar 29 19:27:00 laptop sddm-helper[2942]: [PAM] Starting...
Mar 29 19:27:00 laptop sddm-helper[2942]: [PAM] Authenticating...
Mar 29 19:27:00 laptop sddm-helper[2942]: [PAM] returning.
Mar 29 19:27:04 laptop sddm[552]: Display server stopped.
Mar 29 19:27:04 laptop sddm[552]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
Mar 29 19:27:04 laptop sddm[552]: QProcess: Destroyed while process ("/usr/lib/sddm/sddm-helper") is still running.
Mar 29 19:27:04 laptop systemd[1]: Stopped Simple Desktop Display Manager.
Mar 29 19:28:22 laptop systemd[599]: dbus.service: State 'stop-final-sigterm' timed out. Killing.
Mar 29 19:28:22 laptop systemd[599]: dbus.service: Killing process 816 (gconfd-2) with signal SIGKILL.
Mar 29 19:28:22 laptop systemd[599]: dbus.service: Failed with result 'timeout'.
Mar 29 19:28:22 laptop systemd[599]: Stopped D-Bus User Message Bus.
Mar 29 19:28:22 laptop systemd[599]: Stopped target Basic System.
Mar 29 19:28:22 laptop systemd[599]: Stopped target Sockets.

**Comment by davidedmundson** [comment]
In that log SDDM stopped within the same second of being told to

What makes you say it's sddm at fault?
