### ISSUE TITLE
Sddm is not displayed when using nvidia 390 driver

### ISSUE THREAD

**Issue by matheusfillipe** [sddm/sddm#1019]
This is a problem that was already reported on ubuntu launchpad: https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1762885

I have installed the package nvidia-384 that offers the drivers version 390.48. My gpu is a gtx 1050 ti. Without this driver sddm works perfectly. The interesting fact is that it is just not being displayed, so I figured out that if I type my password and hit enter on that black screen it logs in.

**Comment by kupp1** [comment]
I have the same problem after update 390.48 nvidia driver from debian repo to 390.59 from nvidia site.
Info about system https://pastebin.com/1EnmmMSn

**Comment by swex** [comment]
same here, I have fedora 31 laptop, with driver version 390.132.
Xserver and sddm runs without any errors in logs. I can log in blindly (thanks I have only one user and password input focused by default) and after that login lock screen starts to work properly.

**Comment by matheusfillipe** [comment]
@swex  this driver is already old, are you sure is the latest version you can have? I am now using nvidia 440.44 and is working flawlessly.
