### ISSUE TITLE
Choose session should focus on first line and allow keys to choose other

### ISSUE THREAD

**Issue by casquinhas** [sddm/sddm#1023]
When session session prompts, I cannot use the keyboard to choose a session and press enter to go.
It should allow keys to move on the list and also tab key between fields.
I think once I manged to do that but I don't know why cannot do that again, so I have to use the mouse and I it should not be necessary.

**Comment by davidedmundson** [comment]
Which theme?

**Comment by Pointedstick** [comment]
No response, assuming it was a 3rd-party theme issue because themes have to handle this themselves.
