### ISSUE TITLE
CC BY [SA] 3.0 is a non-free license

### ISSUE THREAD

**Issue by luke-jr** [sddm/sddm#1033]
> [4] c. Except as otherwise agreed in writing by the Licensor or as may be
    otherwise permitted by applicable law, if You Reproduce, Distribute or
    Publicly Perform the Work either by itself or as part of any
    Adaptations or Collections, **You must not distort, mutilate, modify or
    take other derogatory action in relation to the Work which would be
    prejudicial to the Original Author's honor or reputation.**

Any reason not to use the free 4.0 versions?

**Comment by plfiorini** [comment]
The original picture we took from Wikipedia uses that, see:
https://github.com/sddm/sddm/tree/develop/data/themes/maldives

**Comment by luke-jr** [comment]
I suggest changing it, or at least making non-free themes optional.

**Comment by plfiorini** [comment]
It is considered FSF Free according to this: https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing
Besides we cannot change the license of someone else's work and CC-BY-SA is not non-free, it is Free Cultural work (equivalent of the Free Software Definition, https://www.gnu.org/philosophy/free-sw.html) see https://creativecommons.org/share-your-work/public-domain/freeworks/

**Comment by plfiorini** [comment]
Possible CC-BY-SA 4.0 alternatives below:

* https://commons.wikimedia.org/wiki/File:Bathala_(Maldives)_6.jpg

but first I would like to hear the opinion of an expert. Perhaps @jriddell can help with his experience with distros.

**Comment by davidedmundson** [comment]
It seems a complete non-issue in any real situation.

If someone wanted to edit that specific photo, they would need to follow the rules of that specific photo

If someone wanted to alter a different photo then they'd be editing a different photo.
(whether we happened to ship it or not makes no difference)



At which point we're making changes in order to accomodate anyone who specifically wants to modify the picture we ship (regardless of what photo that actually is!) in a way which would be prejudicial to the Original Author's honor or reputation.  It seems going out of the way to create an issue.

**Comment by luke-jr** [comment]
@plfiorini Fedora is not the FSF, and Fedora is okay with quite a few non-free licenses. The FSF's [license page](https://www.gnu.org/licenses/license-list.html) only vouches for the 4.0 versions.

@davidedmundson There is the matter of principle involved in using/bundling only freely licensed software/content. If a license prohibits modifications that promote Nazism, we can all agree that clause is it itself probably not a bad clause, but it would still make the license non-free because of such a restriction.

**Comment by plfiorini** [comment]
FSF says CC-BY-SA 4.0 can be converted to GPL.
CC-BY-SA 3.0 still is free because it guarantees freedoms of the Free Cultural Works.
The clause you are talking about is pretty fair.

**Comment by jriddell** [comment]
The honour paragraph is a silly inclusion to keep the Japanese happy.  Nobody takes it seriously and the CC-BY-SA 3.0 is considered Free by Debian and Ubuntu and KDE and anyone else.  Regardless it was removed in CC-BY-SA 4.0 and as a compatible licence this can be upgraded without issues either in SDDM directly or by whoever wants to ship it.
https://wiki.creativecommons.org/wiki/ShareAlike_compatibility
"For BY-SA 3.0, all future versions of BY-SA and all ports of BY-SA 3.0 or later are automatically compatible"
