### ISSUE TITLE
Fedora 28 KDE hang on logout

### ISSUE THREAD

**Issue by isedev** [sddm/sddm#1034]
When logging out of a fresh install of Fedora 28 KDE Spin, the sddm-helper process does not react to the startkde script terminating and the logout process never completes.

Initial setup:
- install F28 KDE spin to disk
- dnf update -x kernel*
- logout of KDE and hangs
- login to other tty and check processes: no startkde, but sddm-helper still running

Then I rebuilt the sddm package from source. Same issue.

After much messing around, applied the following patch and rebuilt:

```
--- sddm-0.17.0-old/src/helper/HelperApp.cpp    2017-12-05 16:00:16.000000000 +0000
+++ sddm-0.17.0-new/src/helper/HelperApp.cpp    2018-05-29 16:49:44.270509954 +0100
@@ -235,6 +235,7 @@
     }

     void HelperApp::sessionOpened(bool success) {
+       qInfo() << "HelperApp::sessionOpened: enter";
         Msg m = Msg::MSG_UNKNOWN;
         SafeDataStream str(m_socket);
         str << Msg::SESSION_STATUS << success;
@@ -244,6 +245,7 @@
         if (m != SESSION_STATUS) {
             qCritical() << "Received a wrong opcode instead of SESSION_STATUS:" << m;
         }
+       qInfo() << "HelperApp::sessionOpened: exit";
     }
```

The following messages are produced when login in:

> May 29 16:53:16 localhost.localdomain sddm[5308]: Authentication information: "Last failed login: Tue May 29 16:53:13 BST 2018"
> May 29 16:53:16 localhost.localdomain sddm-helper[5401]: Starting: "/etc/X11/xinit/Xsession \"/usr/bin/startkde\""
> May 29 16:53:16 localhost.localdomain sddm-helper[5401]: HelperApp::sessionOpened: enter
> May 29 16:53:16 localhost.localdomain sddm[5308]: Authentication information: "There were 12 failed login attempts since the last successful login."

Note that the "exit" message is not logged.

Applied the following additional patch:

```
--- sddm-0.17.0-old/src/auth/Auth.cpp   2017-12-05 16:00:16.000000000 +0000
+++ sddm-0.17.0-new/src/auth/Auth.cpp   2018-05-29 17:07:06.315543046 +0100
@@ -191,11 +191,13 @@
                 break;
             }
             case SESSION_STATUS: {
+               qInfo() << "Auth::Private::dataPending: rx SESSION_STATUS";
                 bool status;
                 str >> status;
                 Q_EMIT auth->session(status);
                 str.reset();
                 str << SESSION_STATUS;
+               qInfo() << "Auth::Private::dataPending: tx SESSION_STATUS";
                 str.send();
                 break;
             }
```

Login messages remained the same (in particular, no rx/tx SESSION_STATUS messages seen).

Tried the following additional patch:

```
--- sddm-0.17.0-old/src/auth/Auth.cpp   2017-12-05 16:00:16.000000000 +0000
+++ sddm-0.17.0-new/src/auth/Auth.cpp   2018-05-29 17:16:18.476962930 +0100
@@ -163,6 +163,7 @@
                 break;
             }
             case INFO: {
+               qInfo() << "Auth::Private::dataPending: rx INFO";
                 QString message;
                 Info type = INFO_NONE;
                 str >> message >> type;
@@ -176,6 +177,7 @@
                 break;
             }
             case AUTHENTICATED: {
+               qInfo() << "Auth::Private::dataPending: rx AUTHENTICATED";
                 QString user;
                 str >> user;
                 if (!user.isEmpty()) {
@@ -183,6 +185,7 @@
                     Q_EMIT auth->authentication(user, true);
                     str.reset();
                     str << AUTHENTICATED << environment << cookie;
+                   qInfo() << "Auth::Private::dataPending: tx AUTHENTICATED";
                     str.send();
                 }
                 else {
@@ -191,11 +194,13 @@
                 break;
             }
             case SESSION_STATUS: {
+               qInfo() << "Auth::Private::dataPending: rx SESSION_STATUS";
                 bool status;
                 str >> status;
                 Q_EMIT auth->session(status);
                 str.reset();
                 str << SESSION_STATUS;
+               qInfo() << "Auth::Private::dataPending: tx SESSION_STATUS";
                 str.send();
                 break;
             }
```

Now the messages at login showed normal function:

> May 29 17:18:33 localhost.localdomain sddm[12507]: Auth::Private::dataPending: rx INFO
> May 29 17:18:33 localhost.localdomain sddm[12507]: Authentication information: "Last failed login: Tue May 29 16:53:13 BST 2018"
> May 29 17:18:33 localhost.localdomain sddm[12507]: Auth::Private::dataPending: rx INFO
> May 29 17:18:33 localhost.localdomain sddm[12507]: Authentication information: "There were 12 failed login attempts since the last successful login."
> May 29 17:18:33 localhost.localdomain sddm-helper[12590]: Starting: "/etc/X11/xinit/Xsession \"/usr/bin/startkde\""
> May 29 17:18:33 localhost.localdomain sddm-helper[12590]: HelperApp::sessionOpened: enter
> May 29 17:18:33 localhost.localdomain sddm[12507]: Auth::Private::dataPending: rx SESSION_STATUS
> May 29 17:18:33 localhost.localdomain sddm[12507]: Auth::Private::dataPending: tx SESSION_STATUS
> May 29 17:18:33 localhost.localdomain sddm-helper[12590]: HelperApp::sessionOpened: exit

Oh boy, a few print statements and things start working... Logic hasn't changed, then... ok, timing.

So tried this patch instead:

```
--- sddm-0.17.0-old/src/auth/Auth.cpp   2017-12-05 16:00:16.000000000 +0000
+++ sddm-0.17.0-new/src/auth/Auth.cpp   2018-05-29 17:24:37.965392094 +0100
@@ -191,6 +191,7 @@
                 break;
             }
             case SESSION_STATUS: {
+               usleep(1000);
                 bool status;
                 str >> status;
                 Q_EMIT auth->session(status);
--- sddm-0.17.0-old/src/helper/HelperApp.cpp    2017-12-05 16:00:16.000000000 +0000
+++ sddm-0.17.0-new/src/helper/HelperApp.cpp    2018-05-29 16:49:44.270509954 +0100
@@ -235,6 +235,7 @@
     }

     void HelperApp::sessionOpened(bool success) {
+       qInfo() << "HelperApp::sessionOpened: enter";
         Msg m = Msg::MSG_UNKNOWN;
         SafeDataStream str(m_socket);
         str << Msg::SESSION_STATUS << success;
@@ -244,6 +245,7 @@
         if (m != SESSION_STATUS) {
             qCritical() << "Received a wrong opcode instead of SESSION_STATUS:" << m;
         }
+       qInfo() << "HelperApp::sessionOpened: exit";
     }

     UserSession *HelperApp::session() {
```

Yup, still works:

> May 29 17:26:49 localhost.localdomain sddm-helper[16959]: HelperApp::sessionOpened: enter
> May 29 17:26:49 localhost.localdomain sddm-helper[16959]: HelperApp::sessionOpened: exit

Now it is time for somebody smarter than me to figure out why. 
In the meantime, I can at least logout of KDE ;)

**Comment by pdubois95** [comment]
Just installed the KDE Fedora 28 spin on my laptop.   Logout hangs as reported. 
Disabling the WIFI before logging out allows KDE to logout normally.

**Comment by brockers** [comment]
Same here, KDE Fedora 28 spin.  Plasma version 5.13.3, Framework 5.48.0, Qt, 5.10.1, SDDM 0.17.0

Any suggestions?

**Comment by plfiorini** [comment]
This seems related to the well known Plasma session bugs on logout, and other desktops log out without problems.

**Comment by ohjames** [comment]
Don't think this is anything to do with sddm, KDE hangs on logout on the last three systems I've installed it on, both with and without sddm. This has been happening for about 3 years now. AFAICT KDE logout is just insanely buggy.

**Comment by taj0023** [comment]
This is a really annoying bug........I have this with kali linux KDE too

**Comment by aabacchus** [comment]
IIRC kde logout worked fine on ubuntu 20.04, but I have this bug in Fedora 32, and it has been noticed since 30 on bugzilla, and 28 here. Is anyone working on this?

**Comment by Pointedstick** [comment]
I believe this is https://bugs.kde.org/show_bug.cgi?id=359651, which is an upstream bug and not in SDDM.

It's being worked on for Plasma 5.21!

**Comment by KAMiKAZOW** [comment]
> 
> 
> This seems related to the well known Plasma session bugs on logout, and other desktops log out without problems.

Maybe close this report then?

**Comment by Pointedstick** [comment]
I would if I could, but I don't have those privileges in this repo.

**Comment by Pointedstick** [comment]
Oh look, now I do. :)
