### ISSUE TITLE
SDDM lets enter the desktop when user password expired

### ISSUE THREAD

**Issue by adocampo** [sddm/sddm#1037]
On a Windows domain I faced problems with users whose password were expired. Instead of warning them their password was expired and a way to let them to change it, it loaded the desktop but no kerberos ticket could be acquired (obviously) and no printer or folder mapping were working, no roaming profiles were loaded... 

I tried with those very same users and lightdm and I could see it takes care of everything, from the exiration notification to a simple form to change the password, and first of all, denying entering the desktop environment.

**Comment by hoehnth** [comment]
That looks like a PAM config problem. It should not allow login for user with expired password.
See [here](https://serverfault.com/questions/716556/freeipa-ldap-refuse-auth-for-users-with-expired-password) about the topic.
Changing expired password ist not yet supported in sddm but supported by [pending PR](https://github.com/sddm/sddm/pull/776).

**Comment by Vogtinator** [comment]
Yep, that's an issue with the PAM setup and not SDDM.
