### ISSUE TITLE
Starting graphical session targets

### ISSUE THREAD

**Issue by es20490446e** [sddm/sddm#1044]
The display manager should start SystemD's "graphical-session.target" and "graphical-session-pre.target", so graphical units are started too.

**Comment by Vogtinator** [comment]
Is that the displaymanager's job? I'd say that's entirely up to the systemd --user's default.target.

**Comment by plfiorini** [comment]
@Vogtinator Yes it is
@es20490446e We are already doing what's necessary with sddm. The system administrator enables sddm.service and that will make it start with the graphical target, then the system administrator configures the system to start the graphical.target instead of the multi-user.target.

Closing this issue as invalid.

**Comment by Vogtinator** [comment]
@plfiorini graphical.target != graphical-session.target!

The graphical-session.target is basically a replacement for the session .desktop file, managed by a systemd --user instance.

**Comment by plfiorini** [comment]
Ah didn't know that target, looks like the user session got less boring in recent years.
But what we have to do from the login manager?

**Comment by Vogtinator** [comment]
> But what we have to do from the login manager?

I assume the .desktop file would just call "systemctl --user start windowmanager.service" or so, but I'm not sure. If that is the case, sddm doesn't need to handle it specifically.

**Comment by plfiorini** [comment]
That way display managers that do not support systemd would still execute the Exec line program, those who support systemd and see the custom entry would execute `systemctl --user start session.server`.

**Comment by es20490446e** [comment]
I guessed it should be:
```
systemctl --user start graphical-session.target
systemctl --user start graphical-session-pre.target
```

But the targets have this line:
`RefuseManualStart=yes`

So it seems that it should be invoked as dependency of some other user unit, with something like:
```
Wants=graphical-session-pre.target
PartOf=graphical-session.target
```

**Comment by Vogtinator** [comment]
> So it seems that it should be invoked as dependency of some other user unit, with something like:

Yes, each wm has its own unit.

**Comment by davidedmundson** [comment]
Implementing this would break gnome and plasma's systemd usage. 

It also doesn't make sense to start graphical-session. It can only be included implicitly not started explicitly.

One create a new target and do the command above with that
