### ISSUE TITLE
SDDM freezes at boot when Nvidia KMS DRM is enabled and dual monitors

### ISSUE THREAD

**Issue by zjeffer** [sddm/sddm#1060]
I enabled Nvidia KMS DRM with nvidia.drm_modeset=1 in kernel parameters to stop tearing. Since I've done that, whenever I have my second monitor plugged in, every time I boot SDDM freezes for about 30 seconds. I can move my mouse but I can't click the password box.

I'm using an Optimus laptop a GTX 1050, Intel i7 7700HQ, a 128GB SSD and 8GB of RAM. Using Arch Linux and KDE Plasma. 

Here's a log from boot to desktop:
https://pastebin.com/fP5U5Hkz

And here's the same log but only from the sddm service: 
https://pastebin.com/dwHX8YrM

**Comment by cybik** [comment]
Yay, I'm not the only one with this issue!

Strangely enough, on earlier versions (and using Gentoo), I could use sddm over 3 screens.

**Comment by zjeffer** [comment]
@cybik Did you have nvidia.drm_modeset enabled then?

**Comment by cybik** [comment]
Surprisingly enough, modeset is disabled for me.

**Comment by zjeffer** [comment]
Can you move your mouse when this happens?

**Comment by cybik** [comment]
Yep

**Comment by zjeffer** [comment]
If you click the password box, can you try typing your password and then enter? For me, nothing happens visually but once I hit enter it actually logs me in, indicating that the problem is entirely visual.

**Comment by jamesremuscat** [comment]
I have a similar freeze on startup, except mine doesn't recover after 30 seconds; I have to log in to a TTY and `systemctl restart sddm`, at which point it works perfectly.

First try after boot: https://pastebin.com/JL6WfM5v
After restarting SDDM: https://pastebin.com/bRzCup7j

Note that in the former, `sddm-helper` exits "successfully" a few seconds after "Connect" is received from the greeter.

When it's frozen I can move the mouse, but can't change which UI element is apparently focused with Tab, nor can I click anything, type anything or log in.

My system (Ubuntu 18.04)
```
[    0.000000] Linux version 4.15.0-32-generic (buildd@lgw01-amd64-039) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 (Ubuntu 4.15.0-32.35-generic 4.15.18)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-32-generic root=UUID=95cabbd1-2741-4bbf-808c-9a5df758ded4 ro quiet splash vt.handoff=1
```

Dual-screen, nVidia GeForce GTX 1060 with proprietary binary drivers installed.

**Comment by zjeffer** [comment]
Do you also have nvidia drm modeset enabled?

**Comment by jamesremuscat** [comment]
No `nvidia.drm_modeset` for me.

**Comment by zjeffer** [comment]
I don't have this issue anymore.

**Comment by uncomfyhalomacro** [comment]
This issue is back again in openSUSE Tumbleweed
[journalctl-final-2.log](https://github.com/sddm/sddm/files/10927226/journalctl-final-2.log)

```
Mar 09 10:48:06 localhost.localdomain kernel: sddm-greeter[1667]: segfault at 10 ip 0000564d27511a30 sp 00007ffd4009f9a0 error 4 in sddm-greeter[564d274fa000+1d000] likely on CPU 5 (core 1, socket 0)
Mar 09 10:48:06 localhost.localdomain kernel: Code: 00 00 48 81 c4 a8 00 00 00 5b 5d 41 5c 41 5d 41 5e 41 5f c3 66 0f 1f 44 00 00 48 89 c7 49 89 c6 48 8d 5c 24 30 e8 80 8f fe ff <41> 0f b7 4e 10 45 0f b6 4e 13 48 89 c7 41 8b 46 08 45 0f b6 46 0f

```

**Comment by zjeffer** [comment]
Is that the same issue? You're getting a segfault while I don't think I ever had that.
