### ISSUE TITLE
SDDM desktop environment detection issues

### ISSUE THREAD

**Issue by ibroheem** [sddm/sddm#1065]
Sddm doesn't detect any desktop environment installed after sddm install. But it detects those installed before it.
For example I have: XFCE, Plasma, it detects those. Then I installed LxQt, Gnome Shell, it doesn't detect those.

**Comment by davidedmundson** [comment]
List your /usr/share/xsessions files

**Comment by ibroheem** [comment]
```
-rw-r--r--   1 root root   86 Aug  6  2011 lightdm-xsession.desktop
-rw-r--r--   1 root root 2.3K Jul  7 18:32 lxqt.desktop
-rw-r--r--   1 root root 2.3K Jun 30 12:52 plasma.desktop
-rw-r--r--   1 root root 5.4K Oct 21  2017 xfce.desktop

```

**Comment by davidedmundson** [comment]
Well, that explains why gnome shell isn't listed. 

As for lxqt, can you paste the contents, and confirm if the binary listed in TryExec= exists.

**Comment by ibroheem** [comment]
> Well, that explains why gnome shell isn't listed.
That was for another machine

It seem to work now, it turned out lxqt-session and related packages weren't installed
It works now. closing now. thanks
