### ISSUE TITLE
The "RememberLastUser" feature only works with local users. never with AD users'

### ISSUE THREAD

**Issue by lzaghdou** [sddm/sddm#1084]
SDDM login screen does not display last logged in user (active directory user)

We use KDE sddm display manager with an Opensuse Leap 15.0 distribution. Our desktop session is Plasma. 

STEPS TO REPRODUCE
1. We have one local user configured in our PC, and we try to log in an Active directory user, this works fine. 
2. Log out the AD user.
3. Then try to log in again the AD user (who was previously logged in).

EXPECTED RESULT
We expect SDDM login screen to display last logged in user, for instance our AD user, however, SDDM login screen always displays the local user. 
Note that we have set "RememberLastUser" value to true in /etc/sddm.conf file.

ADDITIONAL INFORMATION
The "RememberLastUser" feature only works with local users, never with AD users, why? Is it a SDDM restriction?
Please find attached the "/etc/sddm.conf" file (with a .txt extension for the attachment)
Regards,
Leila Z.

[sddm.conf.txt](https://github.com/sddm/sddm/files/2445613/sddm.conf.txt)

**Comment by JonSeverinsson** [comment]
Try adding the following systemd drop-in configuration file, to ensure that sddm.service starts _after_ AD users are resolvable. If that helps, go bug your distro to add the option to the service file they ship...

==> /etc/systemd/system/sddm.service.d/nss-user-lookup.conf <==
[Unit]
After=nss-user-lookup.target

**Comment by lzaghdou** [comment]
Thank you for your feedback but it still does not work for me.

**Comment by lzaghdou** [comment]
Thank you for your feedback, but it still does not work for me. :-(

**Comment by x09** [comment]
not work for me too
