### ISSUE TITLE
Clone displays in multi-screen environments

### ISSUE THREAD

**Issue by MayeulC** [sddm/sddm#1085]
Currently, sddm assumes an extended layout, with monitor placement often wrong, and primary monitor usually a weird choice.

This is even more confusing when the "primary" monitor is turned off (but not detected by the OS, my Hi-Fi amplifier does that), and the monitor placement is wrong.
So you either have to type in your password blindly (which would be fine as long as there is only one user), or move the mouse randomly until it appears on-screen. Both solutions are sub-par, and do not make for a nice user experience.

The advantage of the current approach is that each monitor is set to its native resolution.

I would like to offer an alternative approach, which I would like to see become the (configurable) default.

-----
"**Cloning**" displays would solve most aforementioned issues, at the cost of one drawback, which is that all monitors are modeset to the same resolution. But it would already be a nice usability improvement over the current state in most cases.

To go further (my apologies if I do not use the right terminology or make wrong assumptions, as I am not familiar with the stack), monitors could just show the **same viewport** at an adjusted scale factor, or sddm could just **keep the current** state of affairs, but:

- synchronizing elements: show the same element with the focused state on every screen,
- multiple mice: duplicate the mouse cursor to show it at the same position on the various screens (it would require a few tweaks to ensure it remains usable)
- add mouse boundaries on the screen, to avoid dragging it across screens.

The last solution would be my favourite approach, but I'll leave it to someone more familiar with the stack to decide and comment on this.

**Comment by MayeulC** [comment]
What about wayland? And I still think this would be a better approach.
Related: #976

**Comment by Roy-Orbison** [comment]
@davidedmundson Could this please be reopened? Understandably, forcing display modes is not the best solution, however the concept of having SDDM synchronise _the appearance of_ user selection, button states, password inputs, etc. would, I believe, eliminate most multi-monitor UX issues.

It would no longer matter which display was really focussed & receiving input, or whether it was even visible to the user. As long as any display was functional, it would be giving all the same visual feedback to the user. I opened a (philosophically) related [bug on KDE](https://bugs.kde.org/show_bug.cgi?id=484125).

**Comment by Vogtinator** [comment]
> @davidedmundson Could this please be reopened? Understandably, forcing display modes is not the best solution, however the concept of having SDDM synchronise the appearance of user selection, button states, password inputs, etc. would, I believe, eliminate most multi-monitor UX issues.

This is not possible to implement. If you mirror at a screen content level, different resolutions will just break. If you mirror at a QML input event level, you'll have hover events without a cursor.

**Comment by Roy-Orbison** [comment]
The QML level sounds like what I was thinking of. Personally, I'd prefer duplicated hover states over guessing which monitor is going to be used, but I understand that isn't for everyone.

**Comment by Vogtinator** [comment]
> The QML level sounds like what I was thinking of. Personally, I'd prefer duplicated hover states over guessing which monitor is going to be used, but I understand that isn't for everyone.

You'll still have to find your mouse cursor first, so you don't win anything...

**Comment by Roy-Orbison** [comment]
> You'll still have to find your mouse cursor first

Well I'm using my keyboard, so no, I don't. Like I said, I get that's not for everyone.
