### ISSUE TITLE
Pressing ENTER does not reveal hidden login module

### ISSUE THREAD

**Issue by tysontan** [sddm/sddm#1089]
On login screen, the login module disappears after a while without input. Pressing Enter does not reveal it, but actually submit the password. This is a small thing but a real nuisance.

My opinions:
1) People are used to input something only when they can see the input fields. They do not know whether they are inputting password without seeing the password field, and they don't know which user's password are being recorded. This is confusing.
2) People tend to click with mouse or press enter to reveal the input fields before they consider a valid input conversation. This is also how Windows 10 design its login screen. 
3) Although we can move mouse or input letters to reveal the login module, those actions are not the natural reactions from normal users. 
4) Note that clicking a mouse button does not always comes with mouse movement, and people tend to press only Enter before they see the input field.

My suggestions:
1) Do not submit password with ENTER when the login module is hidden.
2) Make ENTER the key to reveal login module with it is hidden.

**Comment by blhiggins** [comment]
If I might add: I have a habit of tapping a modifer key, e.g. the SHIFT key, to bring back hidden login fields. This works on KDE's lock screen, but doesn't seem to work on SDDM (0.18.0). It would be nice if SDDM behaved the same way, and revealed the login module when a modifier key is pressed.

**Comment by davidedmundson** [comment]
Is this with the (KDE) Breeze theme?

**Comment by blhiggins** [comment]
On Monday, 3 December 2018 12:40:10 PM EST davidedmundson wrote:
> Is this with the (KDE) Breeze theme?

It is. I assumed such behavior (reaction to modifier keys) was not determined 
by the theme, but forgive me if I'm wrong.

**Comment by tysontan** [comment]
> Is this with the (KDE) Breeze theme?

Yes, I was using Breeze theme for SDDM while reporting the bug.

**Comment by fredcwells** [comment]
I have exactly the same request.   This has been a real source of confusion for my multiple users.  It is not evident that they can begin to enter their login credentials without the dialog being displayed or that moving the mouse will expose the login screen.  To a person, they intuitively assume that pressing an idle key (shift/enter) on the keyboard (as wells as moving the mouse) should reveal the login screen.

**Comment by davidedmundson** [comment]
Then it's not an SDDM issue, sorry. Please report to KDE (product plasmashell, component lookandfeel)

**Comment by davidedmundson** [comment]
FWIW, (with my KDE hat on) I just fixed reveal on pressing a modifier key. I'd already done it for KDE's lockscreen so I just needed to move it over to their sddm theme.

**Comment by fredcwells** [comment]
Kindly explain how SDDM login screen issue is KDE plasma?

**Comment by plfiorini** [comment]
@fredcwells The Breeze theme is provided by KDE in order to provide a user experience that matches the one from Plasma.

**Comment by blhiggins** [comment]
On Saturday, January 5, 2019 1:50:54 PM EST davidedmundson wrote:
> FWIW, (with my KDE hat on) I just fixed reveal on pressing a modifier key.
> I'd already done it for KDE's lockscreen so I just needed to move it over
> to their sddm theme.

Great to hear! Sorry for the noise here - as in this case, it's sometimes hard 
as a user to know where the line is between program functionality and theme 
look and feel...

Peace,
Brendon

**Comment by tysontan** [comment]
> FWIW, (with my KDE hat on) I just fixed reveal on pressing a modifier key. I'd already done it for KDE's lockscreen so I just needed to move it over to their sddm theme.

Thank you for helping us with this issue, David!

To everyone: I have reported the issue to KDE/Plasmashell/lookandfeel
https://bugs.kde.org/show_bug.cgi?id=402957
