### ISSUE TITLE
sddm crash upon mouse click with dual screen display

### ISSUE THREAD

**Issue by anderlia** [sddm/sddm#1090]
SDDM used to work fine on my station (Thinkpad T400) for some while, in simple or dual screen configuration.

After the last KDE Neon upgrade, a regression appeared and now SDDM crashes in dual screen configuration.

I am running KDE Neon Bionic with KDE plasma version 5.14.1, KDE framework version 5.51.0 and Qt version 5.11.2 

The following packages were upgraded recently (October 19, 2018):
- kde-config-sddm:amd64 > from 4:5.14.0-0xneon+18.04+bionic+build15 to 4:5.14.1-0xneon+18.04+bionic+build16
- sddm-theme-breeze:amd64 > from 4:5.14.0-0xneon+18.04+bionic+build16 to 4:5.14.1-0xneon+18.04+bionic+build17

SDDM current version is sddm:amd64 0.17.0-2+18.04+bionic+build14.

Problem Description:  SDDM login screen is displayed on my external monitor after the Linux boot up process. My mouse is functional and mouse cursor is displayed on that login screen. When I click on the SDDM password entry box (so as to be able to enter my password as there is no focus initially on that box in dual screen configuration), then SDDM crashes and the SDDM login screen is turned into a blank screen. The problem is 100% reproducible. The problem also happens after logging out from an active KDE session, waiting for the SDDM login screen to be displayed, and then clicking anywhere on the SDDM login screen. The problem does not appear in single screen configuration (fortunately).

I am available for any further investigation.

**Comment by anderlia** [comment]
SDDM Breeze theme has been updated yesterday: sddm-theme-breeze:amd64 (from 4:5.14.1-0xneon+18.04+bionic+build17 to 4:5.14.1-0xneon+18.04+bionic+build18), and the problem disappeared after the upgrade. Seems the developers got aware of the regression and delivered an immediate fix.

So the issue can be closed. Thanks.

**Comment by baptx** [comment]
This problem happens for me with a single screen configuration since several months after switching from Xfce to LXQt on Ubuntu 18.04 LTS and Ubuntu 18.10.
Should we reopen this issue and changing the title or should I create a new issue? Any ideas about this problem are welcome, the SDDM login freezes every time I click somewhere on the screen. Hopefully the focus is on the password field by default so I don't have to click anywhere to log in.
