### ISSUE TITLE
Qt Quick Controls 2 Styles Support in Themes

### ISSUE THREAD

**Issue by MarianArlt** [sddm/sddm#1096]
Is there support for making a theme use one of the built-in styles of Qt Quick Controls 2?
The [documented ways](https://doc-snapshots.qt.io/qt5-5.11/qtquickcontrols2-styles.html#using-styles-in-qt-quick-controls-2) to make an application run with those styles include modifying the source of the application, which is not possible for theme creators, or running the application with a command line option (is this possible?).
Easiest would be to have the theme force the run-time option but I have never seen such an option documented for themes.
Then there's a Qt environment variable and a configuration file, but I doubt any of this is considered in the source code of SDDM.
Sadly the styles can not be activated from within QML, just adjusted.

The overall support in SDDM is provided, as I can successfully run `sddm-greeter -style material`. This is about a theme being able to access them.

**Comment by plfiorini** [comment]
Set `style` in `theme.conf`, see the Liri theme for SDDM: https://github.com/lirios/themes/blob/develop/sddm/theme.conf#L5

**Comment by MarianArlt** [comment]
Rad! Thanks for the pointer.
