### ISSUE TITLE
Pull booleans from theme.conf into themes QML as such

### ISSUE THREAD

**Issue by MarianArlt** [sddm/sddm#1097]
Right now if I pull a variable from a theme.conf that is designed as a boolean it is passed on as string rather than boolean. (True for INT as well or just any value actually)
Let's say there's a variable:
```
[General]
MakeBooleansBooleans=false
```
When I want to depend on this boolean in a theme I usually write the following:
```
QtStringVariable: config.MakeBooleansBooleans == "false" ? falsyString : trueString
```
This is apparently superfluous when it could just be:
```
QtStringVariable: !config.MakeBooleansBooleans ? falsyString : trueString
```
This does not work. Directly probing any variable will always return as string or undefined/null. So the last example will always return true if the variable has anything set in the config, either BOOL, INT or STRING or if nothing was set it will return as undefined/null.

What does work is just echo the variable as a direct value:
```
someQtBooleanVariable: config.MakeBooleansBooleans
```

Is there a way to force this behavior in SDDM? Or are there plans on making this work? Would this be possible at all? Is there some `config.bool.var` option I am not aware of?

This would make a lot of theme coding way faster and a lot cleaner (after all this is a simplified example).

**Comment by plfiorini** [comment]
That's weird and not suppose to happen.
Upon a quick glimpse of the code ThemeConfig is a QVariantMap which is available to QML as an object and its properties should be variants (http://doc.qt.io/qt-5/qtqml-cppintegration-data.html).
Perhaps the problem is when theme.conf is read but QSettings should recognize booleans.

**Comment by MarianArlt** [comment]
I'm not qualified enough to pinpoint this, I just see that in [ThemeConfig.cpp](https://github.com/sddm/sddm/blob/develop/src/common/ThemeConfig.cpp) the only conversion format used appears to be `QString` all throughout the file.
It's very easy to debug though, just put some variables in the theme.conf:
```
# theme.conf
DebugBool=true
DebugInt=0
```
and then in the corresponding Main.qml:
```
# Main.qml
Component.onCompleted: {
    console.log(config.DebugBool === true)
    console.log(config.DebugInt === 0)
}
```
This will print false in both cases to the console.

**Comment by Rokin05** [comment]
Hi, just for say i'm currently dev a theme and i have the same issue ;

- System : Arch
- sddm 0.18.1-1
- sddm-kcm 5.15.4-1
- qt5-base 5.12.2-2
- qt5-quickcontrols 5.12.2-1
- qt5-quickcontrols2 5.12.2-1


```
# theme.conf
MakeBooleansBooleans=false
```

```
# Main.qml
...

// This object is visible
Rectangle {
    width: 100 ; height: 100 ; color: "red"
    visible: config["MakeBooleansBooleans"]
}

// This object is NOT visible
Rectangle {
    width: 100 ; height: 100 ; color: "red"
    visible: config["MakeBooleansBooleans"] === "true"
}
...
```

I use a hook like this because i have a lot of settings but it's little sad :
```
# Main.qml
...

function conf(key) { 
    var val = config[key];
    if (val === "true")  return true
    if (val === "false") return false
    return val
}

Rectangle {
    width: 100 ; height: 100 ; color: "red"
    visible: conf("MakeBooleansBooleans")
}
...
```



A possible other (non vitale) issue example but with string ? :
(but in this case it's maybe my javascript code .. ;p)


```
# Main.qml
...

// Remove line comments :
function removeComment(key) { 
    var val = config[key];
    return val.replace(/ .*/,'')
    // return String(val.replace(/ .*/,''))  (do the same bad result)
    // return val.replace(/#.*/,'')  (do the same bad result)
    // return String(val.replace(/#.*/,''))  (do the same bad result)
}

Rectangle {
    width: 100 ; height: 100 
    color: removeComment("myColor")
}

// theme.conf:
// OK : myColor=red 
// NOK : myColor=red #My comment line
...
```
The javascript function removeComment("myColor") return only _red_ without the comment like expected but the rectangle color is not red (i have not found the solution).

**Comment by Vogtinator** [comment]
I suggest to handle this like the C++ code does: Expose methods like `QVariant::toBool` to QML on the `ThemeConfig` object, e.g.

```
bool ThemeConfig::boolValue(const QString &key) {
    return value(key).toBool();
}
```

That can then be used as

```
Item {
    visible: config.boolValue("showThisThingy")
}
```

which is explicit, consistent and backwards-compatible with older themes. Themes can also check whether SDDM exposes those methods for backwards-compatibility with older SDDM versions.

**Comment by Vogtinator** [comment]
Implemented in https://github.com/sddm/sddm/pull/1646
