### ISSUE TITLE
SDDM uses breeze cursor instead of set one

### ISSUE THREAD

**Issue by Izaic** [sddm/sddm#1100]
I have noticed recently that when i switch my cursor theme in the SDDM settings panel in Plasma, it does not change and SDDM continues to use Breeze instead.

I'm using KDE Neon Git Unstable, however i seem to have this same issue on Kubuntu and Manjaro.

**Comment by agaida** [comment]
Why should this be an issue?

**Comment by Vogtinator** [comment]
> Same for sddm. If you want to have a different cursor for sddm just set it in the sddm settings.

That's that @Izaic is doing:

> i switch my cursor theme in the SDDM settings panel in Plasma
