### ISSUE TITLE
Security issue : Lock screen bypass (sddm ubuntu)

### ISSUE THREAD

**Issue by Theadri1900** [sddm/sddm#1102]
Hi !
First issue i post on GitHub ever, sorry if it's not perfectly described.
I installed SDDM from "sudo apt-get install sddm" on Ubuntu 18.04
Using Wayland for Ubuntu.
When you want to lock your account (click on the locker), you go to the lock page, but if you change your tty you can find your Wayland session, still opened (so lock page useless because i just need to switch tty to find my session).
For me Lock page is on tty2 and Wayland session on tty3. (It changes sometimes).

Example :
1 - First login account
2 - "Lock" account with the locker (or super+L)
3 - Go to tty3 --> session still opened

Moreover, if i want to unlock my account with my password, it goes to black screen, and lock screen again... so impossible to unlock with normal way.

**Comment by davidedmundson** [comment]
That's not sddm.
