### ISSUE TITLE
Question about fingerprint login

### ISSUE THREAD

**Issue by Wangrong23** [sddm/sddm#1108]
I added "auth sufficient pam_fprintd.so" to the "/etc/pam.d/system-auth" file. Fingerprint authentication is preferred when logging in now. If you want to use password authentication, you must enter the password first, and then scan the wrong fingerprint several times to successfully log in.
If I want fingerprint authentication and password authentication to work at the same time, I can choose one when I log in. What should I do?
(translated by Google)

**Comment by mathieujobin** [comment]
lots of info on this thread #284 

in short, allowing both on the first try is tricky, but it comes down to pam config.
check the other issue, there are several examples you can try

**Comment by Pointedstick** [comment]
See information in https://github.com/sddm/sddm/issues/284.
