### ISSUE TITLE
support SVG and/or JPEG for face.icon files

### ISSUE THREAD

**Issue by lucasart** [sddm/sddm#1109]
For pictures JPEG makes more sense than PNG.

For vectorized graphics, PNG is fine, but SVG has the added advantage of scaling losslesly.

**Comment by Vogtinator** [comment]
That should work just fine. Make sure that the appropriate Qt image plugins are installed.

**Comment by wxl** [comment]
While [many image formats are supported by default](https://doc.qt.io/qt-5/qimage.html#reading-and-writing-image-files), SVG is not, nor does there seem to be a [plugin](https://doc.qt.io/qt-5/qtimageformats-index.html) for it. This would require SDDM using [Qt SVG](https://doc.qt.io/qt-5/svgrendering.html).

**Comment by davidedmundson** [comment]
Qt SVG contains said plugin. SDDM has to do nothing.
