### ISSUE TITLE
sddm-helper eats infinite memory in matter of seconds

### ISSUE THREAD

**Issue by szotsaki** [sddm/sddm#1110]
After some days of usage (usually when I'm working in Qt Creator) sddm-helper suddenly eats up all the memory available, then swap and hangs the whole system. Doing this so efficiently that even the mouse cursor is frozen at its last state and position.

[Here](https://mega.nz/#F!NZZ3kIKC!YGfnwiMObrr4m38Q13dQNw) you can find a heaptrack log (you can inspect it with `heaptrack_gui`). Unfortunately, this doesn't have debuginfo attached but I'm now running heaptrack with correct debuginfo packages installed. However, I suppose this will be helpful, too.

Versions:
openSUSE Tumbleweed, x64
sddm 0.18.0

**Comment by szotsaki** [comment]
I could reproduce it. There is something wrong with Qt Creator in that sense when I click on "Help" it starts using 100% CPU and from that moment on sddm-helper starts eating up memory.

However, when I stop Creator with GDB sddm-helper's memory consumption increase is stopped. No memory is freed, though.

I also extended the linked folder with some pictures showing that the issue originates from `HelperApp.cpp:353`.

**Comment by Vogtinator** [comment]
> According to the timestamping in one second it emits 226 644 lines of messages with 29 123 754 characters (and doing this in an infinite loop).

Ouch. That should be reported to Qt, there's nothing sddm can do here.
