### ISSUE TITLE
After suspend to ram, keyboard not working in sddm

### ISSUE THREAD

**Issue by mctdi** [sddm/sddm#1112]
i use suse tumbleweed
in wayland, after a suspend to ram keyboard not working to type password... but was able to go in console (Ctrl-Alt-F1)

**Comment by davidedmundson** [comment]
After you've already logged in?

**Comment by mctdi** [comment]
i connect to kde (wayland, sddm)....
i do a suspend to ram
i touch my keyboard to wake up
can't type anymore, only chose i have is to go in console mode or doing a ctrl-alt-delete

**Comment by davidedmundson** [comment]
That's not SDDM then. 

KDE's lockscreen looks like KDE's login theme, but it's a separate process
