### ISSUE TITLE
Feature Request: Ability to display Hostname on greeter

### ISSUE THREAD

**Issue by robark** [sddm/sddm#1122]
I need to display the hostname of the systems (in a computer lab setting) when they boot to the sddm-greeter. 

I have tried this code in Main.qml but it does not work

Text {
            color: "#ffffff"
            text: qsTr("Welcome to ") + sddm.hostname
             anchors.left: parent.left
            anchors.leftMargin: 14
            anchors.top: parent.top
            anchors.topMargin: 15
            font.pixelSize: 24
}

I also notice that the hostname is defined in 
https://api.kde.org/4.x-api/workspace-apidocs/plasma-workspace/html/classsddm.html

Any idea how to display the hostname? This would seem to be an obvious and popular query as most other display manager login screens show the hostname of the system.

**Comment by robark** [comment]
Solved the issue:

it was   sddm.hostName   with a capital 'N'. Problem solved.

Does that mean the online documentation (link in previous post) which shows it as a lower case 'hostname' is wrong? Or is there a different updated link of online documentation for sddm class?

**Comment by davidedmundson** [comment]
That documentation is for a different project. 

Glad you got it sorted.
