### ISSUE TITLE
Is it possible to set the desktop wallpaper as sddm background?

### ISSUE THREAD

**Issue by nixway** [sddm/sddm#1128]
Is it possible to set the desktop wallpaper as sddm background

**Comment by davidedmundson** [comment]
Manually, yes. 
Automatically, no.

**Comment by nixway** [comment]
Is such a function planned?

**Comment by davidedmundson** [comment]
No

**Comment by sezanzeb** [comment]
If you are using kde plasma, you can try something like

```bash
image=$(kreadconfig5 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group Wallpaper --group org.kde.image --group General --key Image)
image=${image/"file:\/\/"/""}
sudo cp "$image" /usr/share/wallpapers/user-wallpaper
sudo kwriteconfig5 --file /usr/share/sddm/themes/breeze/theme.conf.user --group General --key background /usr/share/wallpapers/user-wallpaper
```

If you are using a slideshow wallpaper, use `org.kde.slideshow` instead of `org.kde.image`.

But automating this might be tricky because of the required elevated privileges

**Comment by RokeJulianLockhart** [comment]
> https://github.com/sddm/sddm/issues/1128#issuecomment-1674345487

@sezanzeb, does that continue to apply for `cpe:/a:kde:plasma-workspace:6.3`? I ask per [`reddit.com/r/kde/comments/x8wgcl`](https://www.reddit.com/r/kde/comments/x8wgcl/dynamic_sddm_backgrounds/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button#:~:text=I%20want%20the%20sddm%20background%20to%20change%20constantly%20like%20how%20it's%20done%20on%20the%20lockscreen(make%20a%20slideshow).%20Is%20this%20possible?). Irrespective, it'd be great if you'd put that script in a repository, where I can direct people to contribute to it.

**Comment by sezanzeb** [comment]
I don't know, sorry, I ended up not using this script.
