### ISSUE TITLE
sddm-helper creates bizarre folder on login

### ISSUE THREAD

**Issue by brndd** [sddm/sddm#1131]
Originally reported this on [Red Hat's bugtracker](https://bugzilla.redhat.com/show_bug.cgi?id=1667171) but I reckon it might be an upstream issue, so reporting here as well.

Every time on boot/login, sddm-helper attempts to create a folder with a long nonsense hexadecimal name (eg. EFBFBDEFBFBD1356) and gets blocked by SELinux. Looking at journalctl suggests this happens when sddm-helper attempts to open xsession-errors:

```
Jan 17 17:22:36 kitakubu audit[1317]: AVC avc:  denied  { create } for  pid=1317 comm="sddm-helper" name=EFBFBDEFBFBD1356 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=system_u:object_r:user_home_t:s0 tclass=dir permissive=0
Jan 17 17:22:36 kitakubu sddm-helper[1317]: Could not open stderr to "��\u0013V/.cache/xsession-errors"
```

Because the hex string is different each time, I'm worried there could be something nasty like overflowing going on here.

The sealert output (see attachment on RH bugtracker) says this started occurring on 2018-12-23. It started happening spontaneously, presumably after an update. My installation is a relatively recent Fedora 29 system (upgraded from 28), which I made last summer. I'm running KDE with an i3 window manager on top (instead of KWin). I have not attempted to reproduce this on a fresh installation.

The Red Hat bugreport has another person confirming the issue, but they aren't using SELinux so the folders actually get created.

**Comment by davidedmundson** [comment]
My two RedHat friends who had this said it went away with updates.
Please reopen if there's still an issue.

**Comment by brndd** [comment]
It did not go away with updates, but I'll wait and see what the folks over at the Red Hat bugtracker say.

I tried running the code you provided, but it appears to provide no output... unless the output is directed to somewhere other than stdout!
