### ISSUE TITLE
Version 17.0 + commits since 20190101: setting a custom wallpaper breaks login; non-interactive black screen displayed instead of login screen or auto-login

### ISSUE THREAD

**Issue by Pointedstick** [sddm/sddm#1132]
In Neon dev unstable, I can reproduce the following issue with 100% success (failure?):

1. Use the distro package version of SDDM (`0.17.0+p18.04+git20190101.0023-0`)
2. Open System Settings > Startup and Shutdown > Login Screen (SDDM)
3. Set a custom background image; any path or image type will do
4. click Apply and authenticate
4. Reboot

The system reboots and the Plymouth splash screen is displayed, but instead of SDDM displaying the login screen or automatically logging in (for systems with auto-login enabled), instead a black screen is shown. The cursor is visible and movable, but there's nothing to click on.

**Comment by davidedmundson** [comment]
Can't reproduce. 

Please include your /etc/sddm config files

**Comment by davidedmundson** [comment]
and "journalctl -u sddm" output

**Comment by Pointedstick** [comment]
[Xsession.txt](https://github.com/sddm/sddm/files/2821968/Xsession.txt)

I just reproduced the problem and grabbed the journalctl log from a virtual terminal. Here's the full log, starting today: [journalctl_log.txt](https://github.com/sddm/sddm/files/2822045/journalctl_log.txt)

And here's the log for only SDDM: [journalctl_log_sddm.txt](https://github.com/sddm/sddm/files/2822050/journalctl_log_sddm.txt)

**Comment by Pointedstick** [comment]
More relevant information:

The SDDM KCM has somehow gotten itself configured to auto-login to OpenBox:
![screenshot_20190201_085930](https://user-images.githubusercontent.com/1097249/52133952-b419f900-25ff-11e9-828e-b61cbe97f200.png)

However this setting in the combobox is not actually reflected in SDDM's behavior. But when I change the wallpaper and click "Apply" it seems that this setting in the UI gets written to the config file and then suddenly I'm auto-logging-in to OpenBox, where this black screen is apparently expected (?).

So I guess the bug here is that the combobox's setting is out of sync with the config file, and displays the value that _will be_ written to the config file upon apply, rather than reading its current value.

Which means this likely isn't a problem with SDDM, but rather with the KCM, I guess?

**Comment by Pointedstick** [comment]
Not an SDDM issue (problem is in the Plasma KCM), and fixed by https://phabricator.kde.org/D18765
