### ISSUE TITLE
Autodetect DPI and scale the UI accordingly

### ISSUE THREAD

**Issue by Pointedstick** [sddm/sddm#1135]
We've got a lot of bugs about HiDPI. Can we have SDDM autodetect the screen's pixel density and do the appropriate scaling automatically? That would be really pleasant and user-friendly.

**Comment by plfiorini** [comment]
Qt does it already.

**Comment by davidedmundson** [comment]
Except Qt is then hit by: https://bugreports.qt.io/browse/QTBUG-67928
Unless youv'e got a DPI explicitly set in X which we can't control.

This is effectively a dupe of 1056.  
There is an option, it can't be on by default till it works.
