### ISSUE TITLE
Helper: access to memory that has already been freed.

### ISSUE THREAD

**Issue by ElenaZaretskaya** [sddm/sddm#1136]
When sessionLog is created (helper/UserSession::setupChildProcess()), access the field "pw_dir"
of passwd struct after the buffer has been freed.

https://github.com/sddm/sddm/blob/6c23c7e9adabdf2c3b22c75a83ed72f852701a64/src/helper/UserSession.cpp#L230-L240

I think, `free(buffer)` must be called after the initilialization of `sessionLog`

**Comment by davidedmundson** [comment]
Fixed
