### ISSUE TITLE
SDDM freezes when there is no input within minutes

### ISSUE THREAD

**Issue by hubitor** [sddm/sddm#1147]
I have this issue for some time now. Every time I boot my system and after the SDDM login screen appears if I don't enter my credentials immediately or within some minutes SDDM freezes and I cannot enter anything. When the freeze occurs I have to open a tty and restart the service with:
`$ sudo systemctl restart sddm`
and then I'm able to enter my credentials normally.
The issue is independent of kernel version or nvidia version. I don't know if it's related but I use 3-monitors.

OS: Arch Linux
DE: KDE Plasma 5

**Comment by chrisHRD** [comment]
@hubitor , I have the same issue across two of our production workstation.

Steps to reproduce: Power on workstation, let it reaches SDDM login screen, do nothing, wait screens power down to black, try to wake machine, inputs (mouse and keyboard) have no effect on SDDM, hard cycle or get to tty. 

OS: KDE Neon 18.04 fully patched.
DE: KDE Plasma 5
CPU: 4th Generation Intel i5
GPU: AMD RX480 (AMD RX550 in second machine)
GPU DRIVER: Mesa 18.2.2
Monitors: (3) 1080p on both test machine

**Comment by Pointedstick** [comment]
This was a bug in the Breeze theme which was fixed within the last year.
