### ISSUE TITLE
Can't switch virtual terminals

### ISSUE THREAD

**Issue by phaoost** [sddm/sddm#1149]
Hello,

I changed from KDM to SDDM and found I am unable to switch between virtual terminals with Ctrl-Alt-F[1-7] keys.
I am not finding how to enable it back other than switching back to KDM.

**Comment by adren** [comment]
I also noticed this problem of switch from one session to another (with the Ctrl+Alt+F8 for a second session and Ctrl+Alt+F7 to switch back to the original session)

One way that I found to "unlock" this was to press Ctrl+Shift keys altogether one or twice (repeatedly) before pressing yet another time the Ctrl-Alt-F8 which would eventually make it work.

The explanation goes beyond my understanding, but at least it worked!
