### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by jorti** [sddm/sddm#115]
I have reported this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1030065  thinking there were some problem starting the X server, but it was because sddm was only disaplayed in my HDMI output.

There should be a way to configure xrandr commands in sddm, or clone by default all the outputs.

**Comment by friedrico** [comment]
I have a similar problem.
Two screens (next to each other) but the second one (with the login form) is black.
This goes for sddm-0.12.0-2 and the current git-version.
With sddm-0.11.0-3 everything works fine. So at the moment I just downgraded. Maybe you could look into that.

**Comment by yaomtc** [comment]
I have two monitors, my primary connected via DisplayPort (which is the primary port of the graphics card, and the one the BIOS uses first) and another connected via HDMI. Why does it default to the HDMI monitor? Is there a way I can change this? Switching themes changes nothing.

**Comment by yaomtc** [comment]
This seems to be mostly fixed for me now. The focus and cursor is still on the HDMI monitor, though I guess that's a separate issue.

**Comment by lromor** [comment]
Issue still open here, I have an optimus laptop, when I connect via hdmi everything is fine
and in the monitor of the laptop sddm displays correctly.
By connecting via display port instead, (which is probably managed by the nvidia card) I see two sddm logins overlapped with different sizes.

**Comment by BobbyWibowo** [comment]
What's the situation with this? I have similar issue with @lromor. I've got an Optimus laptop,  a 1080p built-in screen and a 720p external monitor connected through HDMI. I'm seeing the 720p SDDM from the external monitor overlapping the 1080p SDDM on the built-in monitor.
![Photo](https://i.fiery.me/0tPm.jpg)
I can confirm the theme is irrelevant cause the same thing happens with Breeze theme as well.
```
sddm 0.17.0-2+18.04+bionic+build15
plasma-framework 5.56.1-0xneon+18.04+bionic+build31
```

**Comment by PrimordialHelios** [comment]
I have the same issue as @BobbyWibowo with a vanilla install on Fedora 29, breeze theme with sddm 0.18. My main monitor is connected through HDMI, secondary through DVI. The secondary monitor renders on top of the primary monitor.

**Comment by ghost** [comment]
Bug is still here. No proper multi-monitor support with SDDM. SSDM's handling of multiple monitors is completely unpredictable for the user, but it never displays it correctly. Even mirroring is broken because in that case no input field gets highlighted. So you could type your password until you're blue in the face and nothing would happen until you actually click on the password box.
