### ISSUE TITLE
SDDM can't find any Qt modules

### ISSUE THREAD

**Issue by android4682** [sddm/sddm#1151]
So I just installed a SDDM theme on my Debian 9 and it threw 
```
error module "QtQuick" version 2.11 is not installed
```
I've installed `qt5-default` via my package manager and also installed `qml` and `qml-module-qtquick-controls`
That didn't fix the issue so I removed it (kept `qtchooser`), installed **qt5.11.3** from source with *Desktop gcc 64-bit*, setting it up with `qtchooser` and setting the variable `QT_SELECT` in my `/etc/profile` and current terminal.

But I still got the same error.
I've asked around on the Qt forum and after some back and forth posting they concluded it's a SDDM issue.
I've installed SDDM from the Debian repository which is version **0.14.0-4+deb9u1**.
So my question is where does SDDM look for it's (qt) modules? Or am I running a wrong version of SDDM?
Any help would be appreciated, thanks!

If you need more info tell me and I'll post it.

**Comment by davidedmundson** [comment]
It won't be an SDDM issue, we don't mess with any paths. 
If libs aren't found it's a deployment issue. 

Probably this qt-chooser nonsense that Debian adds. 

Running with QML_IMPORT_TRACE=1 might help

Also 

cat /proc/`pidof sddm-greeter`/env | tr '\0' '\n'

to dump the env of sddm-greeter .

**Comment by android4682** [comment]
Thanks!
I've ran `cat /proc/<pid-of-sddm-greeter>/env | tr '\0' '\n'` and returned the following:
```
PWD=/var/lib/sddm
XDG_SESSION_TYPE=x11
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
USER=sddm
PATH=/bin:/usr/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/113/bus
DISPLAY=:0
XDG_SESSION_ID=1
XCURSOR_THEME=captitaine-cursors
XDG_RUNTIME_DIR=/run/user/113
LOGNAME=sddm
XAUTHORITY=/var/run/sddm/{c236d5b6-418f-493b-9cbb-3216cdbfad94}
XDG_VTNR=7
XDG_SESSION_CLASS=greeter
SHELL=/bin/false
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
KDE_DEBUG=1
LANGUAGE=en_US:en
LANG=en_US.UTF-8
HOME=/var/lib/sddm
```
I'm not sure but it looks like it's using `/var/lib/sddm` or nothing.
I tried running it with `QML_IMPORT_TRACE=1` but didn't get ANY response I have no idea how to pass variable to SDDM on boot so I tried `QML_IMPORT_TRACE=1 sddm-greeter --theme /path/to/theme`. The `error module "QtQuick" version 2.11 is not installed` was there but terminal didn't return anything.

Should I try it on different distro's? Or is there something else I can do?

**Comment by android4682** [comment]
I've tried Fedora and it worked instantly.
But how do I figure out where SDDM is pulling the Qt5 libraries from?

**Comment by davidedmundson** [comment]
It pulls QtQuick plugins from QML2_IMPORT_PATH

In a normal setup you don't need to meddle with this, I don't understand their qtchooser garbage they create.

Please report to Debian. Sorry.
