### ISSUE TITLE
sddm is filling up my /home partition

### ISSUE THREAD

**Issue by 2011** [sddm/sddm#1153]
When running certain programs (in particular, VLC), sddm is writing 8 MB per hour of the following three lines to be written over and over again to /home/user/.local/share/sddm/xorg-session.log.

```
[00007f947401ec80] vdpau_chroma filter error: video mixer attributes failure: An invalid handle value was provided. 
[00007f947401ec80] vdpau_chroma filter error: video mixer rendering failure: An invalid handle value was provided. 
[00007f947401ec80] vdpau_chroma filter error: video mixer features failure: An invalid handle value was provided.
```

This of course eventually fills up the partition making the machine unusable.

The filtering (no logging levels) and location (relative the the home directory? REALLY?) options for this file seem rather limited (I am so frustrated with this I would like to have this file written to /dev/null).

Is there any way of fixing this, or preventing these lines from being written (often programs will only log errors up to some parameter "n" times and discard further messages)?

**Comment by davidedmundson** [comment]
See sddm.conf

**Comment by 2011** [comment]
@davidedmundson I read all of that before posting.

There is absolutely nothing in /usr/share/man/man5/sddm.conf.5.bz2 that indicates any way of
1. changing the logging level
2. preventing the logging of excessive duplicate messages
3. eliminating the SessionLogFile or moving it outside of home directory

I would like to see ways to do **all** of these things, even if only one of them is possible now.

**Comment by davidedmundson** [comment]
[X11]
SessionLogFile=
