### ISSUE TITLE
SDDM does not show up on Linux 5.1

### ISSUE THREAD

**Issue by ranisalt** [sddm/sddm#1167]
Hello, since upgrading to Linux 5.1, SDDM does not show anymore, it just hogs after boot showing kernel logs on tty. Changing to second tty shows that computer is still responsive. Downgrading to Linux 5.0 Works, but that's not a long term option.

I also suffer from #1081 so I can't provide logs. Starting manually shows that SDDM stops after "Logind interface found"

**Comment by agaida** [comment]
Your problem has nothing to do with the kernel. I suggest to close the sddm issue or give a few facts more - like graphics, distribution and so on.

**Comment by mrjimenez** [comment]
I can't guarantee that this is the same issue, but since the last update in opensuse tumbleweed i have this issue. The logs are here.
[journalctl1.txt](https://github.com/sddm/sddm/files/3195606/journalctl1.txt)

**Comment by ranisalt** [comment]
> I suggest to close the sddm issue or give a few facts more

I'm sorry, but my computer was unusable because of that.

Here are the details:
Processor: i7-3517U
Graphics: Intel HD Graphics on Mesa 19.0.4 + modesetting
Distro: Arch Linux, running kernel 5.1.x (still working on 5.0.13)
Other software: Qt5 5.12.3, Xorg 1.20.4, SDDM 0.18.1 (tried latest from master, too).

Rolling back to Linux 5.0.13 solves the issue, as previously stated. SDDM is the only software that suffers from this upgrade.

@mrjimenez what command did you issue to get that log? I'd like to provide those too.

**Comment by ranisalt** [comment]
Ok, so lurking through journals (I used `journalctl -b -e`) I found that some error logs were warning about i915.fastboot kernel parameter, which I have enabled. The behavior of fastboot [has changed on kernel 5.1](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.1-DRM-Changes) and I guess that was affecting, removing this option has fixed and SDDM starts up again.

Considering @agaida is right and this issue is not SDDM-specific, I'm closing the issue.

**Comment by polarathene** [comment]
Should it be closed though if it's going to impact anyone using Intel with the affected processors that use Fastboot by default with 5.1+ Kernels?

**Comment by ranisalt** [comment]
> Should it be closed though if it's going to impact anyone using Intel with the affected processors that use Fastboot by default with 5.1+ Kernels?

I can't test it anytime soon, but I guess the issue would pop up again if anyone else has the same issue on a newer processor.

On older ones, enabling fastboot taints the kernel so it's unsupported. It might lead to faulty behavior, while newer hardware does not, and it's officially supported.
