### ISSUE TITLE
touchpad is not working at login screen

### ISSUE THREAD

**Issue by zdens** [sddm/sddm#1172]
hello!
I have MSI laptop with the such a system configuration installed:
Operating System: Kubuntu 19.04
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.0-15-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz

The problem is at login screen I cannot tap any buttons via touchpad, therefore it is very difficult to switch user, I can only type the password and press Enter on the keyborad.
I've read the issue https://github.com/sddm/sddm/issues/657, but there is no xorg.conf.d in b=my configuration and libinput is installed in the system.

**Comment by TKO-GLOBAL** [comment]
I'm not sure if you have solved this issue yet, but the solution is the same as issue #657, only the config file is located in `/usr/share/X11/xorg.conf.d/` in Kubuntu, and the file is `40-libinput.conf`. You can see all the possible config file locations for xorg by looking at `man xorg.conf`.

**Comment by zdens** [comment]
yes, the problem had been solved, unfortunately I don't remember what helped to solve it.
now the named config file has this section:
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
EndSection
and touchpad works fine
