### ISSUE TITLE
breeze theme password entry field is tiny even when font size is huge

### ISSUE THREAD

**Issue by MountainX** [sddm/sddm#1177]
I'm been using the beeze sddm theme on Arch Linux for several years. After an update a couple weeks ago, the password entry field became extremely small and impossible to read.

I made the following changes to /etc/sddm.conf
```
ServerArguments=-nolisten tcp -dpi 192
EnableHiDPI=true
```
After making these changes, the font for the time display and other elements is huge. But the password entry field is still tiny. It is not as tiny as before, but it is still impossible to use correctly for an average user.

I updated to all the latest packages today. Version is:
sddm 0.18.1-1
linux 5.1.14.arch1-1

I have tried a minimal config such as:

```
[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze
CursorTheme=Adwaita

[Users]
MaximumUid=60000
MinimumUid=1000
```

I have also tried tweaking any relevant sddm.conf config settings I could think to try, but nothing has any effect on this issue.

The problem is not present in other sddm themes. As a temp work-around I switched to the deepin theme. I would prefer to use breeze when the issue is fixed.

**Comment by MountainX** [comment]
If EnableAvatars is false, the username entry field suffers the same problem - it is too tiny to see, even with great eyesight.

**Comment by bugger11** [comment]
We are seeing this issue on all KDE systems.
sddm 0.18.1-1
plasmashell 5.16.5
Qt 5.13.1

**Comment by Pointedstick** [comment]
I suspect that this is a downstream issue: https://bugs.kde.org/show_bug.cgi?id=410810

**Comment by MountainX** [comment]
Thanks for looking into this. The issue you reference says, "With password visibility turned on it's ok." As I understand it, that means the problem is not present when you can view the actual characters. 

This issue, however, is present even when password visibility is turned on. 

I have seen the "not centered vertically" issue. When I first encountered that, the font size was normal. I'm not sure if I am still affected by that bug because with this super tiny font the character or symbols are so small they would not overlap the border.

**Comment by flipwise** [comment]
It's either a bug with the Breeze SDDM theme or with how it's packaged. Completely unrelated to SDDM itself so devs can feel free to close this and we can continue investigating here: https://bugs.kde.org/show_bug.cgi?id=416478

**Comment by Pointedstick** [comment]
Yes, it's https://bugs.kde.org/show_bug.cgi?id=410810 and/or https://bugs.kde.org/show_bug.cgi?id=416478.
