### ISSUE TITLE
Problem interaction sddm and keychain 

### ISSUE THREAD

**Issue by andreamtp** [sddm/sddm#118]
Hi, I'm experiencing a problem with sddm 0.2.0-0.16.20130914git50ca5b20.fc19 on Fedora19 x86-64 and keychain [ http://www.funtoo.org/Keychain | http://www.github.com/funtoo/keychain ].

As reported in the keychain doc I have in my ~/.bashrc the following expression: eval `keychain -q --eval id_rsa`.
In the past, when I was using kdm no problem at all: after the login, kde start loading and once the desktop appears then I was asked for my ssh passphrase via ksshaskpass.
Now that I switched to sddm with the same config, it got stuck.
Once inserted my login and pwd, the screen switch to black and the mouse cursor is the X of xorg, and stop, nothing happen. Doing pa `ps` on another terminal I can see that sddm is stuck on that keychain -q --eval...

Why sddm doesn't wait to ask me for the pwd when I'll be able to provide it?

thank you

**Comment by jleclanche** [comment]
Closing per last comment.

**Comment by ylabidi** [comment]
Although, it's still unclear to me why .bashrc is loaded even before a user has explicitly opened a terminal session, there is an easier workaround for this: making keychain execution contingent upon an attached terminal:
```bash
tty -s;
if [ "0" == "$?" ]; then
  # Terminal attached
  eval $(keychain --eval --agents ssh -Q --quiet `hostname`)
fi
```
