### ISSUE TITLE
all SDDM text is white, even on white backgrounds

### ISSUE THREAD

**Issue by NobodyIII** [sddm/sddm#1186]
For some reason, all of the text I see in SDDM is white, including the text that appears on white backgrounds. This happens regardless of which theme I use, and it makes it impossible to see what username I type, or the number of characters I've typed into the password box, unless I select the text, which makes its background light blue so I can see it.

This is on a relatively fresh install of Debian 10.0, with SDDM 0.18.0-1. I didn't have this problem at first, but now I do, and I'm not sure what caused it or how to fix it.

**Comment by Pointedstick** [comment]
Can you please provide a screenshot?

**Comment by KenwoodFox** [comment]
I'm also having this issue, the text box is white, but so are the password obfuscation circles.

it works fine, you just can't see how many characters or in what box you're typing. If you ctrl+a you can see the negative of the character circles surrounded by blue selection.

**Comment by hellojaccc** [comment]
https://user-images.githubusercontent.com/71537512/129033271-fb5d5cdc-9fe0-4e00-bed7-42cd109de38a.MOV

Sorry, i couldnt record screen

**Comment by Pointedstick** [comment]
Thanks. This is a bug in Plasma's greeter. Please report it at https://bugs.kde.org/enter_bug.cgi?product=plasmashell in the "Theme - Breeze" component.
