### ISSUE TITLE
0.18.0 (and 0.18.1) build sddm.conf missing?!

### ISSUE THREAD

**Issue by jmrcpn** [sddm/sddm#1187]
Building 0.17.0 generate an sddm.conf file
but sddm.conf seems NOT generated by  018.0 cmake/make.

within 0.17.0 Directory
 ..../build/src/daemon/CMakeFiles
contents include a directory named
generate_config_file.dir

This last one is missing altogether within 0.18.0 and
(obviously) smmd.conf is not created.

What  am I missing?
Is sddm.conf not needed anymore ???
An extra cmake -D option? (doesn't appear in the README.md)

Help will be very very welcome, I am really puzzled.

**Comment by rezso** [comment]
https://github.com/sddm/sddm/commit/b5748d7151a107ae7333c2ff8fa2fede781b82e0#diff-bd70b1b820a42ddb50607bfce360ce88

**Comment by Vogtinator** [comment]
> Is sddm.conf not needed anymore ???

It was never needed and just installed as an example. That's gone now.
