### ISSUE TITLE
Translations for desktop session names

### ISSUE THREAD

**Issue by Cistoge** [sddm/sddm#1194]
Hello,

maybe not the correct place to ask here, but I could not find a mailing list or a forum about sddm.

So, what do I have to do to make sddm show translated desktop session names, like they are listed in ${session}.desktop? Especially, what has to be changed in the breeze theme for that?

Regards
  Christoph

**Comment by Cistoge** [comment]
After checking the source code, I can answer this myself: sddm does not support localized desktopn session names at all, at least in version 0.18.0. At the moment, I helped myself out with function g_desktop_app_info_get_locale_string from the glib library. Experimenting with that gave that it needs entry Type=Application and an existing and executable file in the Exec= line. of the .desktop file to work correctly. Most .desktop files seem to follow this, but the X11 plasma session has Type=Xsession, the Wayland plasma session has Type undefined.

Here is the patch for localization:

[localization.txt](https://github.com/sddm/sddm/files/3616138/localization.txt)

**Comment by Cistoge** [comment]
I rewrote my patch so that it does not use glib functions anymore, but methods from qt. The new version is attached.
[localization.txt](https://github.com/sddm/sddm/files/7572768/localization.txt)

**Comment by aleixpol** [comment]
Would you please be able to provide the patch in a Pull Request?

**Comment by Cistoge** [comment]
Done: https://github.com/sddm/sddm/pull/1475
