### ISSUE TITLE
Starting wayland sessions uses up ttys

### ISSUE THREAD

**Issue by Cistoge** [sddm/sddm#1200]
Hello,

After ending a wayland session, the virtual terminal it used is not freed and it keeps being occupied. That way, it cannot be re-used for new wayland sessions, so that by time, if the computer is not rebooted or sddm restarted, all ttys can become unavailable. Furthermore, after ttys with number <= 12 have been blocked, the function keys cannot be used anymore to switch to the tty where the session runs.  

This is the output of lsof while the wayland session is running:

COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-l       471       root   26u   CHR    4,8         0t0 1076   /dev/tty8
sddm             621        root   27u   CHR    4,8        0t0 1076   /dev/tty8
dbus-run-    2154   cpleger    0u   CHR    4,8         0t0 1076   /dev/tty8
startplas      2157   cpleger    0u   CHR    4,8         0t0 1076   /dev/tty8
kwin_wayl   2187   cpleger    0u    CHR    4,8        0t0 1076   /dev/tty8

This is the output of lsof after ending the wayland session:

COMMAND    PID   USER    FD   TYPE  DEVICE SIZE/OFF NODE NAME
sddm              621   root      27u   CHR     4,8      0t0 1076     /dev/tty8
Xorg             2724   root      27u   CHR     4,8      0t0 1076     /dev/tty8
sddm-help    2740   root      27u   CHR     4,8      0t0 1076     /dev/tty8
sddm-gree    2743   sddm   27u   CHR     4,8      0t0 1076     /dev/tty8

So, while the session is running, there is only one process accessing the tty that does not depend on the session type, sddm. But after session end, also Xorg, sddm-helper and sddm-greeter keep the tty busy.

Regards
  Christoph

**Comment by codewiz** [comment]
This is where the VT for wayland is created:
https://github.com/sddm/sddm/blob/develop/src/daemon/Display.cpp#L319-L326

This is where SDDM switches to it:
https://github.com/sddm/sddm/blob/develop/src/daemon/Display.cpp#L372-L377

I don't see anywhere where this is being released.

The VT file descriptor is stored here:
https://github.com/sddm/sddm/blob/develop/src/common/Session.h#L72

Maybe the destructor of Session should just close(m_fd)?

**Comment by Vogtinator** [comment]
I fixed this in https://github.com/sddm/sddm/pull/1273, feel free to test

**Comment by Vogtinator** [comment]
Closing as dup of https://github.com/sddm/sddm/issues/1078
