### ISSUE TITLE
How should I configure SDDM fonts?

### ISSUE THREAD

**Issue by birdie-github** [sddm/sddm#1209]
By default it uses some font which looks extremely blurry and unpleasant for my eyes.

I have grepped the entire SDDM package and found very little about fonts - there are some QML files mentioning "font" but nothing specific.

It would be great to have an option right in /etc/sddm.conf to configure all fonts (unless a theme redefines them). Then maybe it would be great to have an option which overrides everything, "Just use the specified font and I don't care".

**Comment by flipwise** [comment]
It was added and will be available in 0.19: https://github.com/sddm/sddm/pull/1191

For now you have two options:
1) edit the theme and hardcode every label's `font.family` - clumsy

2) add a fonts replacement file in /var/lib/sddm/.config/fontconfig/conf.d/

The file looks like this:

[99-deepin.conf.zip](https://github.com/sddm/sddm/files/3912281/99-deepin.conf.zip)

Make sure the font is globally installed and to `chown sddm:sddm` the font replacement file so it's owned by sddm.
