### ISSUE TITLE
SDDM ignores PAM nodelay setting

### ISSUE THREAD

**Issue by raxod502** [sddm/sddm#1218]
Currently, when I type in a wrong password on my KDE login screen, there is a delay of three seconds before I can submit another password. I wish to reduce this delay below 100ms. To this end, I've configured `/etc/pam.d/system-auth` to add `nodelay` to the line:

```
auth      required  pam_unix.so     try_first_pass nullok nodelay
```

This has the consequence of removing the password entry delay for both tty logins and `sudo`, as desired. However, even after rebooting, SDDM ignores this configuration and continues to present a three-second delay. I tried further to configure `/etc/pam.d/sddm-greeter` by adding `nodelay` to the line:

```
session         required pam_unix.so nodelay
```

but to no avail. There are no other lines that feature `pam_unix.so` in any of the `/etc/pam.d` lines installed by the `sddm` package, so I am not sure how to proceed.

There are a number of complaints about this problem [on Reddit](https://www.reddit.com/r/kde/comments/911565/sddm_wrong_password_delay/), but I didn't find any working solutions there.

I run Manjaro Linux latest as of 2019-12-14 with KDE.

**Comment by kwshi** [comment]
I don't know much about KDE or PAM or SDDM, but based on some googling it looks like this *might* not be a SDDM-specific issue but an issue related to PAM in general--see:
- https://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password/2128#2128
- https://bbs.archlinux.org/viewtopic.php?id=197423
- https://unix.stackexchange.com/questions/40954/how-does-one-change-the-delay-that-occurs-after-entering-an-incorrect-password
- https://askubuntu.com/questions/877385/how-can-i-lower-the-delay-after-incorrectly-entered-login-and-sudo-passwords

I think this delay might be the same delay that occurs when you mistype a password in `sudo`, or `ssh`, etc.  To that end, it might be worth figuring out the following: does modifying those configurations (at least the `system-auth` one) or following instructions from some of the links above reduce the `sudo` delay time?  If not, maybe there is some more general issue where PAM is ignoring `nodelay` options in general, and that ignorance is propagating to SDDM.

**Comment by raxod502** [comment]
@kwshi As I mentioned in my original comment, modifying the PAM configuration (by adding `nodelay` to the relevant line in `system-auth`) eliminates the delay when using `sudo` etc., but the configuration is nevertheless ignored by SDDM.

**Comment by kwshi** [comment]
Oops, didn't notice that--sorry about that!

**Comment by raxod502** [comment]
Yes, it does seem that the problem is with kscreenlocker, and I can fix it by patching the source and reinstalling. On Arch/Manjaro, I follow this procedure:

    $ yay -G kscreenlocker
    $ cd kscreenlocker
    $ makepkg --nobuild

Now go into `src/` and find the line `m_graceLockTimer->setInterval(3000);`. Edit `3000` to be `0` instead.

    $ makepkg --noextract -si

Log out and back in -- voila!

I apologize for submitting a bug report against the wrong tracker. I have posted one against KDE: https://bugs.kde.org/show_bug.cgi?id=415443
