### ISSUE TITLE
Add Wayland compatibility to SDDM itself

### ISSUE THREAD

**Issue by opensource-assist** [sddm/sddm#1221]
SDDM itself can't run without an Xorg server.
I wanna totally remove all Xorg packages from the system but SDDM is stopping me to do so.
<hr>
Running on Debian Experimental

**Comment by tpgxyz** [comment]
Sounds like very related to https://github.com/sddm/sddm/issues/440

**Comment by PureTryOut** [comment]
Exactly the same as #440 even, I'd close this as a duplicate
