### ISSUE TITLE
multi GPU support

### ISSUE THREAD

**Issue by Zamundaaa** [sddm/sddm#1222]
So basically I have a monitor I can't connect to the dedicated AMD GPU (rx 5700 XT) because it doesn't have a DVI port. The solution to that problem for me is to enable "iGPU multi-monitor" in my BIOS which enables the internal GPU of my Intel i7 6700k, basically just as a video passthrough device in my case.
This works perfectly with KDE Plasma but sddm completely disables the monitor. Once I log in it gets enabled again and all sorts of resolution and state changes happen, making the login take a little longer and quite ugly to look at.
My request is basically that SDDM should also use monitors connected to a secondary GPU if available. It's pretty much just a visual change but it would be a very nice one for me.

**Comment by Zamundaaa** [comment]
The switching around of displays is now actually causing problems: Sometimes popups pop up in completely the wrong position. It's definitely a Qt or Plasma bug but could still be fixed by this.

**Comment by davidedmundson** [comment]
Sddm neither enables or disables monitors, it leaves them untouched from X.

To change X setup change your X config

**Comment by Zamundaaa** [comment]
Well, I don't have a X config at all... At least not that I know of.
Logging out definitely does turn off the monitor connected to the secondary GPU though, so there is at least _something_ changing things.
