### ISSUE TITLE
Question: is SDDM not being able to be installed during base system phase a bug?

### ISSUE THREAD

**Issue by hollowaykeanho** [sddm/sddm#1228]
Hi team, is SDDM expected not to be installed during base system installation phase?

I'm got some findings but I'm not sure whether is this expected behavior. The data is available at:
https://gitlab.com/zoralab/granatum/issues/13

Generally, SDDM installation is find after post base system installation.

**Comment by a17r** [comment]
Whatever *base system* you have is probably entirely a matter of your package manager?

**Comment by hollowaykeanho** [comment]
The base system I'm referring here is Debian 10 net installer ISO disc. The graphical installation is as follow:

The package manager should be strictly to `apt`.

![Screenshot_debian10_2020-01-17_10:05:05](https://user-images.githubusercontent.com/7259572/72578407-f6237400-3910-11ea-9da6-d6e97308d436.png)

The discovery was found when `simple-cdd` adds all the packages in the profiles into this phase of installation.

At this phase, so far all the software added via `simple-cdd` packages profiles are working fine apart of SDDM where it did not get installed despite being listed.

**Comment by a17r** [comment]
I guess what I was trying to say was, you are in the wrong issue tracker here.

**Comment by hollowaykeanho** [comment]
noted. In that case, I will close the question. Tracking the follow-up in debian-mentors mailing list here: https://lists.debian.org/debian-mentors/2020/01/msg00203.html
