### ISSUE TITLE
Redundant entry associated to Gnome on Wayland

### ISSUE THREAD

**Issue by Ricky-Tigg** [sddm/sddm#1238]
**Component**: sddm.x86_64  0.18.1-3.fc31; **OS**: Fedora

While SDDM was installed along with _KDE Plasma Desktop_, and after packages group Gnome was installed (`dnf -y install @gnome`) the greeter list two entries related to Wayland, ._Gnome_ and _Gnome (Wayland)_.

![sddm x86_64-0 18 1-environent-list](https://user-images.githubusercontent.com/26058215/76537420-6a4c4500-6486-11ea-99d3-6980fa5a90d1.png)

Selecting Gnome (Wayland) as login session, may or not open a dark environment. When login succeeds, logout is not operated properly; [journalctl_logins_wayland.txt](https://github.com/sddm/sddm/files/4325471/journalctl_logins_wayland.txt)

**Comment by jackhill** [comment]
I see duplicate GNOME entries on non-Fedora systems as well (in my case, [GNU Guix](https://guix.gnu.org)). For me this is duplicate Xog sessions because my gnome packages has installed two .desktop files in the xsessions directory.

@Ricky-Tigg What are the contents of your `/usr/share/xsessions` and `/usr/share/wayland-sessions`?

**Comment by Ricky-Tigg** [comment]
On my system:
```
$ ls /usr/share/{x,wayland-}sessions
/usr/share/wayland-sessions:
gnome.desktop

/usr/share/xsessions:
gnome-classic.desktop  gnome.desktop  gnome-xorg.desktop  plasma.desktop
```

**Comment by davidedmundson** [comment]
Then we're listing everything correctly, no?

**Comment by Ricky-Tigg** [comment]
Indeed, it has to be so.

**Comment by Ricky-Tigg** [comment]
Closing may have been a mistake. While GDM is set as greeter as consequence of `systemctl disable sddm && systemctl enable gdm && reboot`, in directory /usr/share, those very informations in directories wayland-sessions and xsessions, are handled correctly by GDM; It does not produce duplicates as illustrated here.

![GDM_entries](https://user-images.githubusercontent.com/26058215/89316229-7d092580-d684-11ea-9e9c-3a3c505ef779.png)
