### ISSUE TITLE
sddm.conf

### ISSUE THREAD

**Issue by Hermann12** [sddm/sddm#1240]
Why does the sddm.conf will be edited automatically to [Autologin] always. I use Lubuntu 19.10. I am new at Linux. I can‘t set this file read only after my edit. I tried delete Autologin for the user Lubuntu, but after restart the entry is there and automatic login runs. No password question pops up. Maybe not a bug of sddm, but unclear how I can handle this. Any hint? Thanks!

**Comment by iinc0gnit0** [comment]
try this in your config file:
```[Autologin]
Relogin=false```

**Comment by iinc0gnit0** [comment]
try this:
```\[Autologin\]
Relogin=false```

**Comment by iinc0gnit0** [comment]
Under [Autologin], put `Relogin=false`
