### ISSUE TITLE
SDDM not working if the password has special characters

### ISSUE THREAD

**Issue by amunozf** [sddm/sddm#1241]
When I try to login using a password with special characters like "KaseartLáser-028" (without the quotes) I always get the "login failed" message.

I can log in without a problem in the command line login screen, but not in SDDM. And yes, I'm typing my password correctly.

If I change the password for another one without special characters, it works, but I want to use safer passwords.

I'm using Kubuntu 19.10 and SDDM 0.18.0-1ubuntu2

**Comment by naterich2** [comment]
Have you tried setting your keyboard layout?

**Comment by amunozf** [comment]
My keyboard layout is correct. I just changed my password to make it work.

**Comment by Vogtinator** [comment]
Might be an issue with encoding. Do you use an `UTF-8` locale everywhere?
Does the password appear correctly in the username field?

**Comment by Pointedstick** [comment]
This is a bug somewhere in KDE Plasma, which is mirrored in the lock screen too. See https://bugs.kde.org/show_bug.cgi?id=380501.
