### ISSUE TITLE
Using zsh makes sddm unable to log in

### ISSUE THREAD

**Issue by SolarAquarion** [sddm/sddm#1250]
it gives me gkr issues

**Comment by varac** [comment]
Same here, I can't login when changing my login shell in `/etc/passwd` from `/bin/bash` to `/usr/sbin/zsh`.
@SolarAquarion did you fix it and how ?

**Comment by aleixpol** [comment]
This should have been fixed by bc5a18f34c0881929a6b2e5d3993971c4f692f4f.
