### ISSUE TITLE
Error in elarun theme

### ISSUE THREAD

**Issue by mvlvrd** [sddm/sddm#1272]
When running sddm with elarun in Debian I get the following (seemingly innocuous) error message:

file:///usr/share/sddm/themes/debian-theme/Main.qml:155: ReferenceError: session_button is not defined

The button in question was removed in #521 

I have removed the references in my local branch:
https://github.com/mvlvrd/sddm/commit/1283919944ef5806ac4c43111fdab226d38332ba
and run it without issue.

**Comment by Pointedstick** [comment]
Please feel free to submit a pull request. :)

**Comment by mvlvrd** [comment]
Done. Thanks!
