### ISSUE TITLE
SDDM segfaults at boot and at logout.

### ISSUE THREAD

**Issue by joder666** [sddm/sddm#1279]
SDDM has been slow for me for quite a while, i've been assuming is related to #1036 and did not pay much attention because of it. Recently it also started to segfault around the time i hit logging or as the loggin screen is shown, making the slow boot slower. 

If i log out from any session, since it segfaults again, i can't log in again to the same season i was using, eg, if i started an x11 season it gets stuck trying to log in, i have to crtl+backspace to kill X or switch to wayland session to avoid this.

I am running opensuse tumbleweed + kde desktop + kde unstable repos. 

Dmesg shows this : 

> 1568.577726] sddm-greeter[25987]: segfault at 2008 ip 00007f297ef81d67 sp 00007ffe0c267728 error 6 in libQt5Core.so.5.15.0[7f297ef44000+2fb000]
[ 1568.577735] Code: 06 b8 01 00 00 00 c3 48 83 f8 03 77 05 e9 71 fe ff ff 48 89 c7 e9 c9 00 00 00 90 0f 1f 84 00 00 00 00 00 31 c0 ba 01 00 00 00 <f0> 48 0f b1 17 75 01 c3 48 83 f8 03 77 05 e9 d6 fd ff ff 83 ce f

And this is a backtrace from coredump : 
[gdb.txt](https://github.com/sddm/sddm/files/4992721/gdb.txt)

**Comment by Vogtinator** [comment]
It's actually harmless, crashing during exit.

Unfortunately the backtrace is not that useful, because it doesn't give any indication which of the global objects crashed during destruction... You can probably work around this using a different theme.

**Comment by joder666** [comment]
Wow switching themes actually helped.
I tried elarun but with it i got the same problem.
So installed 2 new themes, PlasmaX and Sugar Candy, using either sddm is no longer dumping/seagfaulting at 1st login or after i logout and back in.
Also can log back into the previous session sucessfully although slow. Something wonky happens at this point since i get dumps from plasmashell, kactivitymanagerd, kgglobals but not from sddm.

**Comment by joder666** [comment]
Closing since its been a while since i stopped getting segfaults from sddm and the slow downs seem to be mostly gone as well.
