### ISSUE TITLE
ReuseSession=true is broken for multiple sessions

### ISSUE THREAD

**Issue by Vogtinator** [sddm/sddm#1281]
If sddm decides to reuse a session after successful authentication by unlocking and activating it, there are three processes competing for the VT switch:

1. `systemd-logind` is told to activate the target session
2. The `Xorg` display server for the greeter wants to restore the old VT on shutdown
3. When the greeter display is stopped, `sddm` tries to switch to the latest display

In the simplest (and the only one which currently works), all of those switch to the same VT. In other cases, especially when there is more than a single active session, it's more likely broken than working.

1 is the intended behaviour, nothing to fix there.
2 can be avoided by passing `-novtswitch`, but it appears like Xorg ignores this for some reason... It would be possible to do the reusing only after `Xorg` shut down, but that will cause flicker.
3 can be fixed by checking whether the stopped display was on the current VT and not doing anything otherwise.

**Comment by grahamperrin** [comment]
Also #917

**Comment by Pointedstick** [comment]
Is this fixed by https://github.com/sddm/sddm/pull/1690?

**Comment by Vogtinator** [comment]
In combination with #1460, #1644 and #1692, hopefully.
