### ISSUE TITLE
Help request: Field offset in SDDM

### ISSUE THREAD

**Issue by PH-KDX** [sddm/sddm#1287]
I've been looking for info on this all over the place and haven't found an answer anywhere.
I've downloaded a login theme for use with KDE, and I'd like to modify one of the fields in it; I'd like it to be offset from the top edge of the screen by a certain amount. How do I do this?

**Comment by Pointedstick** [comment]
You'd need to modify the QML code accordingly, and how you'd go about doing so depends how the theme is coded. I'm afraid such a question is rather out of scope for SDDM's bug tracker. :)
