### ISSUE TITLE
Can't change keyboard layout on "lock" / login screen in LXQT that used ssdm

### ISSUE THREAD

**Issue by AndNovAtor** [sddm/sddm#1288]
Maybe my issue is wrong or is on wrong place...
On Lubuntu 19/20, that "bundeled" with LXQT, that used ssdm, on login screen I can't change keyboard layout.

For example, if system configured with russian "system" locale (```/etc/default/locale``` contains only ```LANG="ru-RU.UTF.8"```) and English and Russian layouts added for console (with ```dpkg-reconfigure keyboard-configuration```) and for "user" in LXQT (it's separate "specific" configuration for LXQT). So, "default" keyboard layout is English (both for GUI and console).

When I logout from user with GUI (or reboot system without autologin), I can't login [back] to user, because only Russian layout works. Also, when no key pressed, layout icon-"indicator" shows that allegedly English layout is "selected", also the "indicator " dropdown shows ONLY English layout (allegedly, I can't change to Russian). When I press any key, the "indicator" icon changes to Russian layout, and the "indicator" dropdown NOW shows ONLY Russian layout. And, in reality, Russian layout is seleced, and ONLY Russian layout works. And if my password is on English, I need to reboot my system to login into GUI automatically (autologin is on). (facepalm)

Soo... What is the "official" way to work with multiple keyboard layouts? Or maybe I (or LXQT) doing something wrong?

I saw https://github.com/sddm/sddm/issues/703#issuecomment-280606920 and https://github.com/sddm/sddm/issues/202#issuecomment-531557766. Again, my ```/etc/default/locale``` contains only ```LANG="ru-RU.UTF.8"```, it must have this value (my system GUI should be on Russian). And ```/lib/systemd/system/sddm.service ``` contains ```EnvironmentFile=-/etc/default/locale```

Btw, I first created a ticket in Lubuntu tracker: https://discourse.lubuntu.me/t/cant-change-keyboard-locale-on-logon-screen-with-lxqt-lubuntu-19-04-19-10-and-20-04

![login_nokey_en](https://discourse.lubuntu.me/uploads/default/original/1X/55608bb753deb843aeab8d86106b3ce595da9f0c.jpeg)
![login_key_ru](https://discourse.lubuntu.me/uploads/default/original/1X/2331b36635dd8cd26921344c82dcb0a708f8aa47.png)

**Comment by johndoe71rus** [comment]
this is not sddm issue. This is lubuntu installer bug with non EN locales.

edit file /etc/X11/xorg.conf.d/00-keyboard.conf option 
Option "XkbLayout" "ru" change to "en"
or Option "XkbLayout" "us,ru(winkeys)"

**Comment by AndNovAtor** [comment]
Yes, of cource it's not a sddm bug itself. I already know it, thank you.
For the history: updated issue, direct link to comments with helpfull links:
https://discourse.lubuntu.me/t/cant-change-keyboard-locale-on-logon-screen-with-lxqt-lubuntu-19-04-19-10-and-20-04/1377/18
