### ISSUE TITLE
Cannot find module "QtQuick.VirtualKeyboard.Plugins"

### ISSUE THREAD

**Issue by Mc-Pain** [sddm/sddm#1290]
After booting I have the following warnings in syslog:
> авг 21 13:51:32 host-21 sddm-greeter[2436]: file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:22:1: Type InputPanel unavailable
> авг 21 13:51:32 host-21 sddm-greeter[2436]: qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:127:5: Type Keyboard unavailable
> авг 21 13:51:32 host-21 sddm-greeter[2436]: qrc:/QtQuick/VirtualKeyboard/content/components/Keyboard.qml:38:1: module "QtQuick.VirtualKeyboard.Plugins" is not installed

KDE Plasma: 5.19.4
KDE Frameworks: 5.73.0
Qt: 5.15.0
Kernel: 5.4.57-std-def-alt1

**Comment by Mc-Pain** [comment]
Could not reproduce in KDE Neon and Fedora.
Reproduced in Manjaro

**Comment by r-flash** [comment]
I have the exact same problem on Manjaro.

**Comment by davidosomething** [comment]
happens in arch

i have installed:
```
extra/qt5-virtualkeyboard 5.15.2-1 [0B 18.82MiB] [Installed] (qt qt5)
Virtual keyboard framework
```

which provides the virtual keyboard afaict
https://archlinux.org/packages/extra/x86_64/qt5-virtualkeyboard/files/

**Comment by ratijas** [comment]
I filed a bug report against Qt upstream, because in my opinion this is a bug in importing `QtQuick.VirtualKeyboard` module when `QT_IM_MODULE` environment variable is not set to "qtvirtualkeyboard".

https://bugreports.qt.io/browse/QTBUG-96291

**Comment by JRippy** [comment]
I could resolve this problem.
On the machine where i install the sofware, i download corresponding QT (example : 5.15.2) with QT Creator.
I link the Qml path with the sources on main.cpp :
```
qputenv("QML2_IMPORT_PATH", QString("/home/USER_NAME/Qt/5.15.2/gcc_64/qml").toLatin1());
```
and it's work.
You can move/export le qml folder to!

**Comment by DragonZV** [comment]
has this been fixed?

**Comment by MaKaNu** [comment]
Seems to be addressed in Qt6 and really difficult in Qt5 [QTBUG-96291/Comments](https://bugreports.qt.io/browse/QTBUG-96291?focusedCommentId=583267&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-583267)

**Comment by MaKaNu** [comment]
@ratijas Could you explain, where to handle this `QT_IM_MODULE`, if I am not able access the `cpp` files (or don't want to, because I updating a theme which uses VirtualKeyboard. As example dark sugar)?

**Comment by plfiorini** [comment]
SDDM sets QT_IM_MODULE when this option is set: https://man.archlinux.org/man/sddm.conf.5.en#InputMethod=
You probably have `InputMethod` set to `qtvirtualkeyboard`.

See https://github.com/sddm/sddm/blob/develop/src/greeter/GreeterApp.cpp#L354
