### ISSUE TITLE
Notifications on plasma lock screen

### ISSUE THREAD

**Issue by mohanboddu** [sddm/sddm#1291]
I recently moved to KDE from GNOME and one thing that I really miss from gnome is having notifications displayed on lock screen. I have read articles that it got disabled in plasma 5 for some security reasons, but is it possible to add it back? I dont want to see all the info about the notification, just what app and how many notifications from that app since I locked my computer.

Since KDE uses sddm, I am filing it here, if its a wrong place and its on KDE side, please let me know and I will file a ticket against plasma.

Thanks.

**Comment by Zamundaaa** [comment]
It is indeed wrong here. SDDM is what you see on login, the lock screen is something different. You can file a bug request for Plasma here: https://bugs.kde.org/
