### ISSUE TITLE
Switch user option is missing with systemd 246

### ISSUE THREAD

**Issue by ddmls** [sddm/sddm#1293]
When using systemd 246 the option to switch user is missing in plasma's menu and lockscreen.

This was apparently caused by commit 8f8cc84ba4612e74cd1e26898c6816e6e60fc4e9 of systemd.

Also reported and discussed in https://bugs.archlinux.org/task/67623

**Comment by davidedmundson** [comment]
I'm surprised that Arch bug report says that's confirmed as the cause. 

I was under the impression the breaking change is the getSessionByPid breaking.
Plasma calls that, it doesn't check SDDM's canMultiSeat property (SDDM does, but that's not relevant for Plasma's menu and lockscreen.)

I have a patch in plasma that avoids that call and the option is reappearing.

**Comment by ddmls** [comment]
Will your patch be included in the next version of plasma? Can we have it to use it in Arch?

**Comment by ddmls** [comment]
Since this is not a bug of SDDM it can be closed.

**Comment by jerith666** [comment]
I think perhaps https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/137 is the patch that @davidedmundson referred to?

**Comment by ddmls** [comment]
This is probably it, though I tried it and it didn't work for me.
