### ISSUE TITLE
SDDM login screen doesn't show that account is locked after 3 failed login attempts

### ISSUE THREAD

**Issue by unfa** [sddm/sddm#1294]
I've been cleaning my keyboard while on an SDDM log-in screen and when I tried to log-in my password was rejected 4 times in a row. Finally I enabled the "visible password" and verified that it is correct. Didn't pass though.

I've switched to a TTY instead and when I typed my user name I was immediately shown a message along these lines:

"This account is locked for 8 minutes due to 3 failed login attempts."

I've forcefully rebooted the machine and logged in at first attempt.

I think what happened is I've pressed <enter> at least 3 times while sweeping my keyboard to clean it, performing 3 failed login attempts, but SDDM didn't show me the warning about the next log-in attempts being locked behind a timeout - it just kept taking and refusing my password.

**Comment by Pointedstick** [comment]
This will require the theme itself to communicate that message to the user, and it affects not only the lock screen but also the login screen.

For the applicable downstream bug report for the Breeze theme, see https://bugs.kde.org/show_bug.cgi?id=428613.

**Comment by omichalek** [comment]
This "new issue" is still present, If I had not added ssh keys to a computer in question (it is running Manjaro) I would have had no clue whatsoever why I cannot login.
Frankly, this makes KDE completely unsuitable for my needs of a family computer.
