### ISSUE TITLE
Critical disk drive memory leak

### ISSUE THREAD

**Issue by sapphirepro** [sddm/sddm#1304]
Hello.

I want to report annoying problem with disk drive memory leak. It comes from ~/.local/share/sddm/xorg-session.log . It's simply rediculous that it can trash over 100 GB away in less then 1 day and resulting in all work loss and data loss due to disk out of space and apps unable to write their data, resulting in 0 byte files.

Please, please fix that nonsense.
1) Log file default size at most 10MB, not over 100GB
2) Delete logs on system startup
3) If log size per single boot excedeed - ignore all coming logs and WRITE NOTHING after exceeded size.

It's annoying that this bug can be a drive killer. Especially like me having SSD drive if any app generates error it's being filled till 100% full simply in no time.

NOTE!!! Once log limit exceeded DO NOT start to rewrite file immediatelly from start. No logs are worth of killing expensive SSD drives. Also I request feature to ignore logging at all, yeah just option for config file "write no logs".

Will be very appreciated if this long ago bug finally fixed.

Example of situation (file list from sddm logs directory):
`ls -la
total 118370260
drwxr-xr-x   2 root root           76 Sep  6 04:55 .
drwxr-xr-x 134 root root         8192 Oct 17 18:55 ..
-rw-------   1 root root           53 Jul 26  2018 .Xauthority
-rw-------   1 root root          769 Sep  6 04:57 wayland-session.log
-rw-------   1 root root 121210871808 Oct 17 19:22 xorg-session.log`

**Comment by sapphirepro** [comment]
Also please,follow Linux standards: /var/log. So that this can be separate partition that don't care of being full of even being tmpfs with close to 0MB size at all.

Current attempt to place absolute patch to system's root folders totally ignored and placed to user's home folder again

**Comment by Vogtinator** [comment]
This file is simply used for standard output and standard error of the session process. It is truncated on login already.

For some reason your DE or some application inside spams messages there. That is what needs to be fixed.

> Also please,follow Linux standards: /var/log.

All of this is user specific, so it has to be inside the users home directory.
