### ISSUE TITLE
Is there a way to use another virtual keyboard than the default qtvirtualkeyboard ?

### ISSUE THREAD

**Issue by Tuxman2** [sddm/sddm#1310]
Hi,

I would like to know if it is possible to define another virtual keyboard than the default qtvirtualkeyboard in SDDM.

I would like to use qtvkbd as my default virtual keyboard in SDDM. But I can't display the virtual keyboard button in the lower left corner with this one.

Can you help me to do that ?

Thanks.

**Comment by Pointedstick** [comment]
You need to set `QT_IM_MODULE=[whatever]` in the environment by the time SDDM runs.
