### ISSUE TITLE
Shipped PAM files do not work on Arch and other distros

### ISSUE THREAD

**Issue by ivangjxyz** [sddm/sddm#1313]
Operating System: Arch Linux
KDE Plasma Version: 5.20.2
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.9.3-arch1-1
OS Type: 64-bit

**Comment by rlokc** [comment]
+1 on this issue. Just came back from downgrading.
Issue seems to be with PAM, maybe a version mismatch in the dependencies?
Here's what I could gather through a quick-ish troubleshoot before throwing in the towel, because I don't know PAM in depth.

Here's the contents of the `/etc/pam.d/sddm-autologin` from 0.18.1-3:
```
#%PAM-1.0
auth        required    pam_env.so
auth        required    pam_faillock.so preauth
auth        required    pam_shells.so
auth        required    pam_nologin.so
auth        required    pam_permit.so
-auth       optional    pam_gnome_keyring.so
-auth       optional    pam_kwallet5.so
account     include     system-local-login
password    include     system-local-login
session     include     system-local-login
-session    optional    pam_gnome_keyring.so auto_start
-session    optional    pam_kwallet5.so auto_start
```

And here's what it got replaced by in 0.19 (for some reason didn't trigger a .pacnew replacement either)
```
#%PAM-1.0
auth        required    pam_env.so
auth        required    pam_tally2.so file=/var/log/tallylog onerr=succeed
auth        required    pam_shells.so
auth        required    pam_nologin.so
auth        required    pam_permit.so
-auth       optional    pam_gnome_keyring.so
-auth       optional    pam_kwallet5.so
account     include     system-local-login
password    include     system-local-login
session     include     system-local-login
-session    optional    pam_gnome_keyring.so auto_start
-session    optional    pam_kwallet5.so auto_start
```

Here are the logs from journalctl of my system trying to launch with 0.19:
```
ноя 04 10:34:39 GrumpLinux sddm[683]: Setting default cursor
ноя 04 10:34:39 GrumpLinux sddm[683]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
ноя 04 10:34:39 GrumpLinux sddm[683]: Display server started.
ноя 04 10:34:39 GrumpLinux sddm[683]: Reading from "/usr/share/xsessions/plasma.desktop"
ноя 04 10:34:39 GrumpLinux sddm[683]: Reading from "/usr/share/xsessions/plasma.desktop"
ноя 04 10:34:39 GrumpLinux sddm[683]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startplasma-x11"
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: PAM unable to dlopen(/usr/lib/security/pam_tally2.so): /usr/lib/security/pam_tally2.so: cannot open shared object file: No such file or directory
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: PAM adding faulty module: /usr/lib/security/pam_tally2.so
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] Starting...
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] Authenticating...
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: pam_kwallet5(sddm-autologin:auth): (null): pam_sm_authenticate
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: pam_kwallet5(sddm-autologin:auth): pam_kwallet5: Couldn't get password (it is empty)
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] Preparing to converse...
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] Conversation with 1 messages
ноя 04 10:34:39 GrumpLinux audit[753]: USER_AUTH pid=753 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=? acct="rlokc" exe="/usr/lib/sddm/sddm-helper" hostname=? add>
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] authenticate: Module is unknown
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] returning.
ноя 04 10:34:39 GrumpLinux sddm[683]: Authentication error: "Module is unknown"
ноя 04 10:34:39 GrumpLinux sddm-helper[753]: [PAM] Ended.
ноя 04 10:34:39 GrumpLinux sddm[683]: Auth: sddm-helper exited with 1
```
And then after that I just get a black screen with a cursor that I can move around. Thankfully can switch to a tty.

Noticed the line about pam_tally2.so. I indeed, do not have such a file at /usr/lib/security, nor is there a file that looks anywhere close to it.
Tried commenting out (I think - is commenting? Once again, that was just a cursory glance at things I have no idea about, so excuse me for my ignorance) the line with pam_tally2, but that only got rid of the "unable to dlopen" message, sadly it still all crashed with "Module is unknown" in the end

```
ноя 04 10:56:27 GrumpLinux sddm[687]: Setting default cursor
ноя 04 10:56:27 GrumpLinux sddm[687]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
ноя 04 10:56:27 GrumpLinux sddm[687]: Display server started.
ноя 04 10:56:27 GrumpLinux sddm[687]: Reading from "/usr/share/xsessions/plasma.desktop"
ноя 04 10:56:27 GrumpLinux sddm[687]: Reading from "/usr/share/xsessions/plasma.desktop"
ноя 04 10:56:27 GrumpLinux sddm[687]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startplasma-x11"
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] Starting...
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] Authenticating...
ноя 04 10:56:27 GrumpLinux audit[758]: USER_AUTH pid=758 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=? acct="rlokc" exe="/usr/lib/sddm/sddm-helper" hostname=? add>
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: pam_kwallet5(sddm-autologin:auth): (null): pam_sm_authenticate
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] Preparing to converse...
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: pam_kwallet5(sddm-autologin:auth): pam_kwallet5: Couldn't get password (it is empty)
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] Conversation with 1 messages
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] authenticate: Module is unknown
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] returning.
ноя 04 10:56:27 GrumpLinux sddm[687]: Authentication error: "Module is unknown"
ноя 04 10:56:27 GrumpLinux sddm-helper[758]: [PAM] Ended.
ноя 04 10:56:27 GrumpLinux sddm[687]: Auth: sddm-helper exited with 1
```

**Comment by alium** [comment]
archlinux's bug, because in archlinux's pam package exist no pam_tally2.so

**Comment by rlokc** [comment]
That's right, tyvm, forgot to peep in the Arch bug tracker, found [the ticket](https://bugs.archlinux.org/task/68520?string=sddm&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=) there.

**Comment by ivangjxyz** [comment]
Good, thank you!

**Comment by antonio-rojas** [comment]
From pam 1.4.0 release notes:

> Deprecated pam_tally and pam_tally2: these modules are no longer built
> by default and will be removed in the next release, use pam_faillock instead

so this needs fixing in sddm itself too.

**Comment by alium** [comment]
I'm sorry,  @antonio-rojas is right. In fact, it's probably more of an SDDM bug, they should reflect the latest released versions of pam (I know it's harder for compatibility, a lot of distro still use the old pam). 

ideally, SDDM should distinguish whether it is PAM 1.4 or older and modify the file according to the detected version

ideally... :-)

> From pam 1.4.0 release notes:
> 
> > Deprecated pam_tally and pam_tally2: these modules are no longer built
> > by default and will be removed in the next release, use pam_faillock instead
> 
> so this needs fixing in sddm itself too.

**Comment by Vogtinator** [comment]
PAM files are highly distribution specific, so IMO sddm should stop shipping them itself completely.

**Comment by wan-nyan-wan** [comment]
FYI, I froze the screen when I login after updated `0.19.0-1` to `0.19.0-2`. I fixed this by downgrading.

**Comment by jotoho** [comment]
Tuesday evening I got the issue where after autologin my screen was be black and only the cursor was visible `(0.19.0-1)` but I was still able to access other tty's and `0.19.0-2` **seemed** to fix it.
But when I tried to start my desktop-pc today, the display only turned completely black for a few seconds when the graphical user interface was supposed to appear before I was back on the text-only screen that was there before and I was even *unable to switch to a different TTY*.

I just spent the last two hours scanning the log files from the archlinux install disk and trying to get my pc to work again before eventually downgrading sddm back to the archive of version `0.19.0-1` I still had in the pacman cache, booting back up and using that version to access tty. Using the TTY I then downgraded back to `0.18.1-3` with `downgrader-git` from AUR and after a quick reboot everything was working again.

Until I get confirmation that the latest sddm is stable again I am putting it on the ignore-list and not touching 0.19.

**Comment by An7ar35** [comment]
+1 on this issue in Arch + KDE with sddm `0.19.0-1`. Had to downgrade back to `0.18.1-3` as well using tty to get back to a desktop.

Side note: I'm taking this opportunity to thank to all the maintainers. Your work is appreciated.

**Comment by davispuh** [comment]
This is not nice... I don't have autologin enabled and SDDM starts fine but as soon as I enter password it freezes, nothing happens and not able to login. Downgrading works but 0.19 is completely unusable...

**Comment by An7ar35** [comment]
Seems like it works now with the recent update of `pam 1.5.0-1` (`sddm 0.19.0-2` and `sddm-kcm 5.20.3-1`) on my setup. Auto-login is back to normal.

**Comment by antonio-rojas** [comment]
> Seems like it works now with the recent update of `pam 1.5.0-1` (`sddm 0.19.0-2` and `sddm-kcm 5.20.3-1`) on my setup. Auto-login is back to normal.

It works because sddm is patched.

**Comment by Pointedstick** [comment]
So should we just stop shipping these files?
