### ISSUE TITLE
Change of format of state.conf

### ISSUE THREAD

**Issue by norbusan** [sddm/sddm#1319]
Dear all,
it seems that with the bump from 0.18 to 0.19 the format of the `Session` entry has changed.

Up to 0.18.1:
```
Session=/usr/lib/xsessions/plasma.desktop
```
while on 0.19.0
```
Session=plasma.desktop
```

Is this a change on purpose? It requires that users select the correct session the first time after an upgrade from 0.18.

Thanks for your work

Norbert

**Comment by Vogtinator** [comment]
I can't reproduce the issue here with 0.19.0. The code is written in a way that the path used for reading the session `.desktop` file is also written into `state.conf`, so using a relative path would actually break that.

If you can reproduce this, the logs (system journal) would be helpful.

**Comment by Coucouf** [comment]
Hi,

yes I don’t really understand it either.

```
nov. 08 18:01:50 $hostname sddm[1172]: Greeter session started successfully
nov. 08 18:01:50 $hostname sddm[1172]: Message received from greeter: Connect
nov. 08 18:01:54 $hostname sddm[1172]: Message received from greeter: Login
nov. 08 18:01:54 $hostname sddm[1172]: Reading from "/usr/share/xsessions/plasma.desktop"
nov. 08 18:01:54 $hostname sddm[1172]: Reading from "/usr/share/xsessions/plasma.desktop"
nov. 08 18:01:54 $hostname sddm[1172]: Session "plasma.desktop" selected, command: "/usr/bin/startplasma-x11"
```
We get the full path from src/common/Session.cpp:238                                                                                                                       And then only the basename at src/daemon/Display.cpp:308
But I don’t see how any transformation can happen to the filename between the 2…

JFTR we have a couple of distro patches but nothing that I see having an impact on this issue :
https://salsa.debian.org/qt-kde-team/3rdparty/sddm/-/tree/master/debian/patches

**Comment by norbusan** [comment]
> I can't reproduce the issue here with 0.19.0. The code is written in a way that the path used for reading the session `.desktop` file is also written into `state.conf`, so using a relative path would actually break that.
> 
> If you can reproduce this, the logs (system journal) would be helpful.

Very strange. Here on Debian I see relative paths in the state.conf, and nothing else. As @Coucouf said, maybe this has to do with Debian's patches, but looking at them it sounds rather improbable. 

I will try to debug. Thanks for your comment!

**Comment by Vogtinator** [comment]
It's indeed caused by https://salsa.debian.org/qt-kde-team/3rdparty/sddm/-/blob/master/debian/patches/07_fix-desktop-session-env-var.diff.

**Comment by Coucouf** [comment]
Ah right I added that, trying to sync patches with Ubuntu. Sorry for the noise, we’ll fix that. :(

And thanks for your help.

**Comment by Vogtinator** [comment]
Try https://github.com/sddm/sddm/pull/1322 instead, that should work properly.
