### ISSUE TITLE
erresc: unknown str ESC]

### ISSUE THREAD

**Issue by ztoiax** [sddm/sddm#1337]
What does it mean to show this in `~/.local/share/sddm/xorg-session.log` file.
```sh
erresc: unknown str ESC]112ESC\
erresc: unknown str ESC]112ESC\
erresc: unknown csi ESC[22;0;0t
erresc: unknown csi ESC[23;0;0t
```

**Comment by plfiorini** [comment]
Probably a terminal or nvim error see https://www.reddit.com/r/suckless/comments/br93w5/st_emits_errors_when_nvim_is_started/
