### ISSUE TITLE
SDDM tries to start autologin X11 session with Wayland

### ISSUE THREAD

**Issue by DataDrake** [sddm/sddm#1348]
We recently ran into this issue in Solus while trying to upgrade from 0.18.1 to 0.19.0. We found that for our SDDM configuration and the Autologin configuration provided by Plasma, that SDDM would try to start the Autologin session with `scripts/wayland-session` instead of `scripts/Xsession`, even when provided with a `.desktop` for an xsession.

I've been doing some digging into this with the help of @kaktuspalme and it looks like the following is happening:

**Pre-conditions**
1. `Session` is empty or missing for `[Autologin]` in the SDDM `mainConfig`
2. `lib/sddm/state.conf` has been written out under 0.18.1 with an absolute path (ie. `Session=/usr/share/xsessions/plasma.desktop`)

**Autologin Process**

https://github.com/sddm/sddm/blob/46f08fb8c61bda7fa0e12fa022d058f54d351d3a/src/daemon/Display.cpp#L108-L121

1. `autologinSession` is found to be empty
2. `autologinSession` is overwritten with the last session from `lib/sddm/state.conf`
3. `findSessionEntry` is called to check for a valid Wayland session:

https://github.com/sddm/sddm/blob/46f08fb8c61bda7fa0e12fa022d058f54d351d3a/src/daemon/Display.cpp#L247-L256

4. `dir.exists()` is called with `/usr/share/xsessions/plasma.desktop` which has an absolute path.
5. Per [the docs](https://doc.qt.io/qt-5/qdir.html#exists) the absolute path will return true if it exists, even if it isn't in the path specified by the QDir.
6. The session type is switched to Wayland.
7. The session is run as Wayland with an Xsession `.desktop`.
8. Autologin fails.

Prior to [this commit](https://github.com/sddm/sddm/commit/c78da43cf44a1090d8aa1d5ed4a779a3ec42c504), X11 was being evaluated first to the opposite effect. The absolute path would override the relative check and the session would continue on without failing, being correctly set to X11 instead of Wayland.

**Possible Resolutions**

It seems to me that this could be fixed if one or both of these changes were made:
1. Absolute paths in `Session` from `var/lib/state.conf` should be treated differently than relative paths.
2. `var/lib/state.conf` should not be written out with an absolute path, possibly by also writing out a `SessionDir` field to preserve the full path.

I'm happy to provide any additional info you might need.

**Comment by Vogtinator** [comment]
> Prior to [this commit](https://github.com/sddm/sddm/commit/c78da43cf44a1090d8aa1d5ed4a779a3ec42c504), X11 was being evaluated first to the opposite effect.

I think you mean https://github.com/sddm/sddm/commit/994fa67b01ccfac1aaac08572302bbbea7842dc3?

(CC @Conan-Kudo as the author of the commit which "caused" this)

Session management is a bit messy, it handles relative paths, absolute paths and in some cases even just the base names of the session files. This is manageable only if there aren't any Wayland and X11 session files with the same name. However, the linked commit only makes a difference if a session exists in both...

Please try this:

```
diff --git a/src/daemon/Display.cpp b/src/daemon/Display.cpp
index b95f6e5..ab0f9b3 100644
--- a/src/daemon/Display.cpp
+++ b/src/daemon/Display.cpp
@@ -245,6 +245,11 @@ namespace SDDM {
     }
 
     bool Display::findSessionEntry(const QDir &dir, const QString &name) const {
+        // Given an absolute path: Check that it matches dir
+        const QFileInfo fileInfo(name);
+        if (fileInfo.isAbsolute() && fileInfo.absoluteFilePath() != dir.absolutePath())
+            return false;
+
         QString fileName = name;
 
         // append extension

```

**Comment by DataDrake** [comment]
Ah yeah, sorry, I must have copied the wrong URL. I think of it more as "revealing" than "causing" the problem.

> However, the linked commit only makes a difference if a session exists in both...
Uh, I'd have to say I don't thinks so. We don't have Wayland support for Plasma enabled and we only ship the X11 sessions. The directory for Wayland sessions doesn't even exist. Like I said, if the path is absolute, the prefix is ignored when calling `QDir::exists()` It's just that under the previous code it was failing to not fail the X11 check and that it just happened to be an X11 session that it was being asked to run. I'm pretty use if the session path in the `stateFile` was absolute with a Wayland session filepath that SDDM would have tried to run the Wayland session with X under the previous code.

I'll apply your patch later today and get some feedback from our testers.

**Comment by Vogtinator** [comment]
> Uh, I'd have to say I don't thinks so.

Right, by "only makes a difference" I meant "is only effective", i.e. the intended effect is only there if a session is both in the X11 and Wayland directories.

**Comment by DataDrake** [comment]
@Vogtinator Sorry, for the late reply. Based on the testing on our side that patch seems to work perfectly. The X11 session is started with the `/usr/share/xsessions/plasma.desktop` from the StateFile. Thank you!

Autologin itself still fails because of the missing `Session=plasma` on our side, but it at least gracefully fails to a normal login prompt now so that the user can log in and fix it without dropping to TTY. Once they toggle auto-login in the Plasma's System Settings the config is written correctly. But that's a problem for us to fix, not something SDDM needs to worry about.

**Comment by Vogtinator** [comment]
The diff was actually broken and should've used `absolutePath()` instead of `absoluteFilePath()´. Please try again with https://github.com/sddm/sddm/pull/1355 applied.

**Comment by Girtablulu** [comment]
Hi @Vogtinator 

I'm the Solus plasma Maintainer. I gave your new patch a test and it still fixes the autologin issue as our user described. It even  seems to solve the issue which @DataDrake mentioned above when the line `session=plasma` is missing now as well.

**Comment by Vogtinator** [comment]
Thanks for testing!
