### ISSUE TITLE
Flexible xsession-errors location

### ISSUE THREAD

**Issue by jleclanche** [sddm/sddm#135]
Recently gdm added the ability to view xsession-error using journalctl. This would be nice to have.

Failing that, though, the ability to set a different path than ~/.xsession-errors in the config would be nice. Same goes for ~/.Xauthority.

I recommend adding the following two sddm.conf values:

* **ClientLogFile**: Path to the log file. For example, "~/.cache/xsession-errors"
* **UserAuthFile**: Path to the Xauthority file. For example, "~/.x11/Xauthority"

**Comment by plfiorini** [comment]
Will be closed by #541

**Comment by plfiorini** [comment]
Fix merged

**Comment by cyring** [comment]
Built last release of SDDM on ArchLinux, "SessionLogFile" option works perfectly with a memory mounted file system.

THANK YOU
