### ISSUE TITLE
SDDM does not propagate user shell setting for Wayland

### ISSUE THREAD

**Issue by Conan-Kudo** [sddm/sddm#1351]
When setting my user's login shell to fish and logging out and logging back in, my Plasma Wayland session continues to use bash regardless of my shell setting. This behavior is only exhibited on Wayland. With X11, Plasma has the right settings in the session. This is exhibited by Konsole using bash on Wayland and fish on X11.

#### STEPS TO REPRODUCE
1. Login into Wayland session
2. Open Konsole
3. Run `chsh -s /bin/fish` after installing fish
4. Log out and log back in
5. Open Konsole

#### OBSERVED RESULT
Konsole opens with Bash prompt

#### EXPECTED RESULT
Konsole opens with Fish prompt

#### SOFTWARE/OS VERSIONS
Linux/KDE Plasma: Fedora 33 KDE Plasma
(available in About System)
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.2

#### ADDITIONAL INFORMATION
This was originally filed against Konsole as [kdebugs#423890](https://bugs.kde.org/show_bug.cgi?id=423890).

**Comment by aleixpol** [comment]
The `SHELL` environment variable should point to your shell when the wayland session starts. We need to see why it isn't being initialised properly.

Here we can see it's set to bash for some reason: https://bugsfiles.kde.org/attachment.cgi?id=131606
