### ISSUE TITLE
Multi-monitor: Make login field available on active monitor

### ISSUE THREAD

**Issue by ajyotirmay** [sddm/sddm#1356]
Hi,

So I usually have this issue where the password prompt is available on both monitors in a multi-monitor setup and I find myself looking at the wrong monitor while typing the password.

2 proposed solutions:
1. Make the prompt available only on the primary monitor (GDM's design can be referenced here)
2. show prompt on the active screen only (the screen with mouse pointer)

I believe solution 1 might be a good one.

**Comment by zeronote** [comment]
This really bothers me as well. Is it possible we are the only ones noticing it or perhaps there is already a change being implemented that addresses this?

I would be equally happy with both 1 and 2, although 2 seems more natural as usually the screen where the mouse pointer is rendered is also the last one you were looking at.

**Comment by ajyotirmay** [comment]
I'm not sure if this thing is being worked upon or if anyone has previously even noticed and marked this issue. But hopefully we'll get to hear from someone

**Comment by piotr-dobrogost** [comment]
From https://github.com/sddm/sddm/issues/514#issuecomment-149498505

> Whether showing the password prompt on all outputs or only on the primary one is up to the theme.

**Comment by zeronote** [comment]
Thanks @piotr-dobrogost.

@ajyotirmay I think we could close this and start looking at https://invent.kde.org/plasma/plasma-workspace/-/tree/master/sddm-theme

**Comment by ajyotirmay** [comment]
@zeronote yeah, right. That's the same theme I'm using. Let's see how it can be fixed.

@piotr-dobrogost thanks for helping out, I was unsure about where this issue lies. I'm closing it now, thanks again :)

**Comment by ajyotirmay** [comment]
@zeronote I've opened a bug report on KDE: https://bugs.kde.org/show_bug.cgi?id=432300

**Comment by aabacchus** [comment]
What themes does this *not* occur in?
