### ISSUE TITLE
ReuseSession set by default to false on Manjaro

### ISSUE THREAD

**Issue by medmedin2014** [sddm/sddm#1387]
`ReuseSession` causes some problems when you switch user, see https://bugs.kde.org/show_bug.cgi?id=434370
This problem was solved by changing `ReuseSession` to `true`.

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.105-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
```

**Comment by davidedmundson** [comment]
Our upstream default in the SDDM development branch is already set to true.
We've done all we can.
