### ISSUE TITLE
Black screen on nvidia-340xx and kernel-5.11

### ISSUE THREAD

**Issue by wojnilowicz** [sddm/sddm#1400]
Screen is black and no greeter is shown. Workaround is: switching to another TTY, login, type "startx" and Plasma starts.
The issue doesn't occur on kernel-5.10 and SDDM. The issue doesn't occur on lightdm, kdm, gdm display managers and kernel-5.11.

version: SDDM 0.19 on Plasma 5.21.4 on Fedora 34

**Comment by tpgxyz** [comment]
@wojnilowicz Please file a bug report to you distribution bugzilla.

**Comment by wojnilowicz** [comment]
> @wojnilowicz Please file a bug report to you distribution bugzilla.

It's not only my distribution issue. On Arch it is so as well, as can be read in the comments section at
https://aur.archlinux.org/packages/nvidia-340xx/

Why should I report it to my distribution?

**Comment by tpgxyz** [comment]
@wojnilowicz You should have to file issue for you distro devs, so they can be aware of such problem. Second this will help them to provide better testing before releasing anything to the public, to be sure things are not broken. Third if something is similar does not mean it the same matter.

**Comment by wojnilowicz** [comment]
Fixed.
