### ISSUE TITLE
Setting session-specific env vars

### ISSUE THREAD

**Issue by dbrgn** [sddm/sddm#1401]
I know that I can set user-specific environment variables with PAM, but I'd like to set some env vars only on some sessions but not on others.

Is there a way to specify an env var only per session (e.g. in /usr/share/wayland-sessions/)?

(A use case would be `MOZ_ENABLE_WAYLAND`, but there are others as well.)

**Comment by tpgxyz** [comment]
why don't you just edit your  /usr/share/wayland-sessions/*.desktop?
`Exec=env MOZ_ENABLE_WAYLAND=1 foo`

**Comment by dbrgn** [comment]
Ahhh, using the `env` binary as entry point is a great idea. Somehow that didn't occur to me 🙂 Thanks!
