### ISSUE TITLE
sddm wont boot after arch kernel update

### ISSUE THREAD

**Issue by tyler820201** [sddm/sddm#1404]
I have got the latest 0.19.0.6 sddm on my arch linux. After updating my system fully sddm wont boot anymore. Only tty login possible. I have got the latest 5.12.1 kernel.
 However with 5.10 lts kernel working properly.
 What i did so far:
reinstall the 5.12.1 kernel and headers and run mkinitcpio -P  ( i have nvidia 390 dkms)
reinstall sddm package
Still only the lts version able to boot sddm
Shall i downgrade to 5.11 or wait for kernel  update or is this a sddm bug???

[issue.txt](https://github.com/sddm/sddm/files/6437658/issue.txt)

**Comment by tpgxyz** [comment]
Sddm is not a culprit here. Please file bug report on your distribution.

**Comment by tyler820201** [comment]
Great. 
Thanks
