### ISSUE TITLE
Wayland session not started on tty1

### ISSUE THREAD

**Issue by zeertzjq** [sddm/sddm#1409]
After starting Plasma Wayland session, SDDM seems to remain on tty1, and Wayland session is started on another tty.

Operating System: Arch Linux
SDDM package version: 0.19.0-6

**Comment by tpgxyz** [comment]
That is not a bug. SDDM still uses X11 for greeter, which occupies in this case tty1.
This will change when wayland support will land for sddm-greeter. https://github.com/sddm/sddm/pull/1393
