### ISSUE TITLE
Adding on readme on what SDDM runs

### ISSUE THREAD

**Issue by bphd** [sddm/sddm#1410]
I know (I think) that SDDM runs actually on X11, but idk if in the future SDDM will run on Wayland or not. It's not the question here

What I suggest is to add in the readme, in description of what SDDM is, to add that it run on X11 (and if someday it'll run on Wayland, change it)

It's a useful information

Thanks

**Comment by plfiorini** [comment]
I will add it once #1393 is merged

**Comment by Marzal** [comment]
Hi, I see that Wayland is supported and announced in the README.

Shouldn't this issue be closed?
