### ISSUE TITLE
SDDM fails to start X11 session in Ubuntu hirsute 21.04

### ISSUE THREAD

**Issue by guss77** [sddm/sddm#1414]
When using the latest (0.19, or develop) SDDM with Ubuntu hirsute, the X11 session fails to start - the X server does not start and the greeter immediately shows again.

Looking at the user's journal, I see these errors:

```
-- Journal begins at Sat 2021-05-29 13:03:25 IDT. --
Jun 09 22:24:08 vesho sddm-helper[4972]: QDir::mkpath: Empty or null file name
Jun 09 22:24:08 vesho sddm-helper[4972]: Adding cookie to ""
Jun 09 22:24:08 vesho sddm-helper[4972]: QFSFileEngine::open: No file name specified
Jun 09 22:24:08 vesho sddm[4979]: /usr/bin/xauth:  file -q does not exist
Jun 09 22:24:08 vesho sddm[4979]: /usr/bin/xauth: (stdin):1:  bad "remove" command line
Jun 09 22:24:08 vesho sddm[4979]: /usr/bin/xauth: (stdin):2:  bad "add" command line
Jun 09 22:24:08 vesho sddm-helper[4972]: Xauthority path: "/run/user/1000/7f748bc4-5dfb-4f97-8f72-1bc5b341506e"
Jun 09 22:24:08 vesho sddm-helper[4972]: Running server: /usr/bin/X -nolisten tcp -background none -seat seat0 -noreset -keeptty -novtswitch -verbose 3 -auth /run/user/1000/7f748bc4-5dfb-4f97-8f72-1bc5b341506e -displayfd 8 vt3 -logfile /dev/null
Jun 09 22:24:08 vesho sddm[4980]: (EE)
Jun 09 22:24:08 vesho sddm[4980]: Fatal server error:
Jun 09 22:24:08 vesho sddm[4980]: (EE)
Jun 09 22:24:08 vesho sddm[4980]: Invalid argument -logfile with elevated privileges
Jun 09 22:24:08 vesho sddm[4980]: (EE)
Jun 09 22:24:08 vesho sddm[4980]: (EE)
Jun 09 22:24:08 vesho sddm[4980]: Please consult the The X.Org Foundation support
Jun 09 22:24:08 vesho sddm[4980]:          at http://wiki.x.org
Jun 09 22:24:08 vesho sddm[4980]:  for help.
Jun 09 22:24:08 vesho sddm[4980]: (EE)
Jun 09 22:24:08 vesho sddm-helper[4972]: Failed to read display number from pipe
Jun 09 22:24:08 vesho sddm-helper[4972]: [PAM] Ended.
Jun 09 22:24:08 vesho sddm-helper[4972]: QProcess: Destroyed while process ("/usr/bin/X") is still running.
```

When using the SDDM build that comes with hirsute - everything works fine.

I can workaround the problem and get an X11 session by commenting out this line: https://github.com/sddm/sddm/blob/develop/src/helper/xorguserhelper.cpp#L154 - without the "-logfile" option, it works.

**Comment by guss77** [comment]
Note that the man page for `xorg` says:

> *-logfile filename*
>    Use the file called filename as the Xorg server log file. The default log file is /var/log/Xorg.n.log on most platforms, where n is the display number of the Xorg server. The default may be in a different directory on some platforms. **This option is only available when the server is run as root** (i.e, with real-uid 0). 

So I'm not sure why `sddm-helper` that is always run as non-root uses the `-logfile` argument: it can never work.

**Comment by plfiorini** [comment]
Removing `-logfile` is not a valid fix.
Your problem is that Xorg is running with elevated privileges for some reason but it should be running as unprivileged user.

**Comment by guss77** [comment]
@plfiorini - my problem is that X11 is **not** running with elevated privileges while using `-logfile`. Please read the above quote from the man page.

**Comment by plfiorini** [comment]
Mmm it might be related to how privileges are dropped now in the helper.

**Comment by guss77** [comment]
@plfiorini If previously the helper was running Xorg as root, than that change would explain the change in behavior. I understand you don't think that removing the `-logfile` option is the correct response (PR #1415 ) - then would reverting the privilege change be a better way to handle the issue?

**Comment by plfiorini** [comment]
@guss77 The man page you are reading is outdated. Nowadays it says:

```
       -logfile filename
               Use the file called filename as the Xorg server log file.  The default log file when running as root is /var/log/Xorg.n.log and for non root it is $XDG_DATA_HOME/xorg/Xorg.n.log where n is the display number of
               the Xorg server.  The default may be in a different directory on some platforms.  This option is only available when the server is run as root (i.e, with real-uid 0).
```

Keep saying that it is available when the server is run as root but at the same time says where the log goes by default for non root.

To be honest I cannot reproduce this issue on Arch Linux.

Besides the message says `Invalid argument -logfile with elevated privileges` which is the opposite of what state previously, howerver `sddm-helper` drops the privileges before running the X server.
Looking at the xserver code in `bool PrivsElevated()` from `os/utils.c` it returns `true` if euid != uid and that might explain why you see that error.

The man page is confusing and I cannot reproduce the issue but we are safer by removing `-logfile`.

**Comment by guss77** [comment]
I think the man page uses the documentation for the "root only" `-logfile` option to explain what happens when you don't specify it. Weird, but I've seen worse. I also do not have an `$XDG_DATA_HOME/xorg` directory and have never seen user-mode log files :man_shrugging: 

My test system is Neon, where X definitely does not like you running it with `-logfile` as non-root and will print that message and exit when you just run it straight as a user - without any root privileges shenanigans, where I definitely do not have "elevated privileges" of any kind. I can investigate Xorg sources some more, but as you've merged the PR  that fixes the issue for me (thanks again :smile: ), then my itch has been scratched and I kind have no further incentive to do so...
