### ISSUE TITLE
Can't run with a full colour depth on Wayland

### ISSUE THREAD

**Issue by aleixpol** [sddm/sddm#1441]
Tested both on Weston and KWin, I don't really get all the colours on my display. It's possibly that my users didn't have some permission enabled but it's something that affects SDDM performance on wayland mode.

A picture, which says more than a thousand words:
![IMG_20210827_122953](https://user-images.githubusercontent.com/1282478/131114247-4644b478-d6c5-45fa-8182-6dd9c63f5800.jpg)

I really don't know what is wrong and neither kwin or weston's logs are very helpful there.

**Comment by plfiorini** [comment]
Please check with the embedded theme and other themes as well.

**Comment by aleixpol** [comment]
![IMG_20210830_185701](https://user-images.githubusercontent.com/1282478/131376279-43d8e1be-ae29-4d9a-b51b-e0d637f60d56.jpg)

**Comment by plfiorini** [comment]
That's weird, the greeter is just a normal Qt application, I doubt it can be a permission problem.
Do you also have any log of the compositor and the greeter?

**Comment by aleixpol** [comment]
Including a full system log just in case. 
https://paste.opensuse.org/19106528

**Comment by Vogtinator** [comment]
Is this still an issue?

If yes, does this affect started sessions as well or just the greeter?

**Comment by aleixpol** [comment]
Yes it is, just the greeter. My guess is that it might be the user/session that is lacking some hardware permission or access or something. I can't put the finger where.

**Comment by Vogtinator** [comment]
Maybe access to DRI (`/dev/dri/*`) nodes? As long as sddm has an active logind session that should work though and with kwin there should actually not be any output if that fails.

**Comment by Zamundaaa** [comment]
I checked and KWin in sddm is using full 10 bit color, no issues on that side. If I turn it down to use 8 bits like Xorg it still fails the same way too

**Comment by Vogtinator** [comment]
I can reproduce the issue in a VM. It occurs only with virgl (i.e. HW accel) enabled.

**Comment by Vogtinator** [comment]
According to debug logs, the greeter picks an RGB565 surface format. Running `eglinfo` in the same context prints that all formats are available though.

**Comment by Vogtinator** [comment]
Running the greeter with `EGL_LOG_LEVEL=debug` and looking at the Mesa code reveals the cause:

The default `QSurfaceFormat` has no RGBA buffer size set, which results in those getting passed as `0` to `eglChooseConfig`. That makes this section in https://registry.khronos.org/EGL/sdk/docs/man/html/eglChooseConfig.xhtml relevant:

> Special: by larger total number of color bits (for an RGB color buffer, this is the sum of EGL_RED_SIZE, EGL_GREEN_SIZE, EGL_BLUE_SIZE, and EGL_ALPHA_SIZE; for a luminance color buffer, the sum of EGL_LUMINANCE_SIZE and EGL_ALPHA_SIZE). If the requested number of bits in attrib_list is 0 or EGL_DONT_CARE for a particular color component, then the number of bits for that component is not considered.

i.e. all zeros means that the color depth is no longer a sort criteria. The chosen format is then ironically the smallest available one (due to `EGL_BUFFER_SIZE`)

When running `sddm-greeter` as a wayland application, the alpha buffer size is set to 8 by `QWaylandEglWindow` to support window decorations.

**Comment by Vogtinator** [comment]
The best work around I can think of is to set the default `QSurfaceFormat` in sddm-greeter explicitly to an RGB888 one.
FWICT this would then refuse RGB30 (10bpc/HDR) and RGB565 configs though. In any case, that's better than the current situation, so IMO acceptable in the wayland-egl case.

**Comment by aleixpol** [comment]
I'm confused though. Why is this needed for the greeter here but not elsewhere? The behaviour should be the same as when running as `sddm-greeter --test-mode` in a normal plasma session and in there it gets beautiful colours.

It would be interesting to know what is different when running it as sddm user... :thinking:

**Comment by Vogtinator** [comment]
> I'm confused though. Why is this needed for the greeter here but not elsewhere? The behaviour should be the same as when running as `sddm-greeter --test-mode` in a normal plasma session and in there it gets beautiful colours.
> 
> It would be interesting to know what is different when running it as sddm user... thinking

I explained that in https://github.com/sddm/sddm/issues/1441#issuecomment-1430478206

**Comment by aleixpol** [comment]
Of course :facepalm:
