### ISSUE TITLE
Permanent Systemd warning : 

### ISSUE THREAD

**Issue by j-c-dole** [sddm/sddm#1477]
Hello
I got always this warning:
`/usr/lib/systemd/system/plymouth-start.service:15: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for t
he service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.`
Anything to be done ?

**Comment by plfiorini** [comment]
It's not a SDDM issue, you should report it to the Plymouth developers.
