### ISSUE TITLE
SDDM restarting on shutdown

### ISSUE THREAD

**Issue by hasezoey** [sddm/sddm#1479]
## What is happening

Currently, most of the time i try powering down my system (or restarting), `sddm` restarts in the shutdown, i dont know why it happens, but my guess it is not really related to the kde (wayland) session

## System Information

My System is basically a `Manjaro 21.2(pre1)` with pulseaudio swapped for pipewire and also installed `plasma-wayland-session`

Main Session used: Wayland (plasma)

kernel: (`uname -a`) `Linux Meicoo-Manjaro 5.15.2-2-MANJARO #1 SMP PREEMPT Sat Nov 13 19:25:38 UTC 2021 x86_64 GNU/Linux`
sddm: (`pacman -Ss sddm`) `extra/sddm 0.19.0-7 [installed]`
sddm-kcm: (`pacman -Ss sddm`) `extra/sddm-kcm 5.23.3-1 (plasma) [installed]`
plasma-wayland-session: (`pacman -Ss plasma-wayland-session`)  `extra/plasma-wayland-session 5.23.3-1 [installed]`

in case it matters:
the system is on `btrfs`, with snapshots from `snapper` on a SSD

`inxi -b`:

```txt
System:    Host: Meicoo-Manjaro Kernel: 5.15.2-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.23.3
           Distro: Manjaro Linux
Machine:   Type: Desktop System: MSI product: MS-7972 v: 2.0 serial: <superuser required>
           Mobo: MSI model: B150M MORTAR (MS-7972) v: 2.0 serial: <superuser required> UEFI: American Megatrends
           v: C.90 date: 11/03/2016
Battery:   ID-1: hidpp_battery_0 charge: 81% condition: N/A
CPU:       Info: Quad Core Intel Core i7-7700K [MT MCP] speed: 1642 MHz min/max: 800/4500 MHz
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] driver: amdgpu
           v: kernel
           Display: wayland server: X.Org 1.21.1.3 driver: loaded: amdgpu,ati unloaded: modesetting resolution:
           1: 2560x1440~60Hz 2: 1920x1080~60Hz 3: 1920x1080~60Hz
           Message: Unable to show advanced data. Required tool glxinfo missing.
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
Drives:    Local Storage: total: 2.78 TiB used: 360.86 GiB (12.7%)
Info:      Processes: 352 Uptime: 1h 43m Memory: 31.3 GiB used: 4.78 GiB (15.3%) Shell: Zsh inxi: 3.3.09
```
Note: the `Battery` is probably from my Logitech wireless mouse

`journalctl /usr/bin/sddm -b-1`:

```txt
-- Journal begins at Sun 2021-09-05 20:48:28 CEST, ends at Tue 2021-11-30 17:04:26 CET. --
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Initializing...
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Starting...
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Logind interface found
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Adding new display on vt 1 ...
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Loading theme configuration from ""
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Display server starting...
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Adding cookie to "/var/run/sddm/{d985b51d-e391-4aa4-b564-b8e231a0fcd4}"
Nov 29 13:43:23 Meicoo-Manjaro sddm[591]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt1 -auth /var/run/sddm/{d985b51d-e391-4aa4-b564-b8e231a0fcd4} -noreset -displayfd 17
Nov 29 13:43:24 Meicoo-Manjaro sddm[591]: Setting default cursor
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Display server started.
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Socket server starting...
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Socket server started.
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Loading theme configuration from "/usr/share/sddm/themes/breath2/theme.conf"
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Greeter starting...
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Greeter session started successfully
Nov 29 13:43:25 Meicoo-Manjaro sddm[591]: Message received from greeter: Connect
Nov 29 13:43:30 Meicoo-Manjaro sddm[591]: Message received from greeter: Login
Nov 29 13:43:30 Meicoo-Manjaro sddm[591]: Reading from "/usr/share/wayland-sessions/plasmawayland.desktop"
Nov 29 13:43:30 Meicoo-Manjaro sddm[591]: Reading from "/usr/share/wayland-sessions/plasmawayland.desktop"
Nov 29 13:43:30 Meicoo-Manjaro sddm[591]: Session "/usr/share/wayland-sessions/plasmawayland.desktop" selected, command: "/usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland"
Nov 29 13:43:30 Meicoo-Manjaro sddm[591]: Authenticated successfully
Nov 29 13:43:31 Meicoo-Manjaro sddm[591]: Auth: sddm-helper exited successfully
Nov 29 13:43:31 Meicoo-Manjaro sddm[591]: Greeter stopped.
Nov 29 13:43:31 Meicoo-Manjaro sddm[591]: Session started
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Authentication error: "Process crashed"
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Auth: sddm-helper crashed (exit code 15)
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Authentication error: "Process crashed"
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Auth: sddm-helper exited with 15
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Socket server stopping...
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Socket server stopped.
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Display server stopping...
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Display server stopped.
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Removing display ":0" ...
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Adding new display on vt 1 ...
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Loading theme configuration from ""
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Display server starting...
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Adding cookie to "/var/run/sddm/{be50fe9f-729c-4541-8538-22dd381efe46}"
Nov 30 02:32:04 Meicoo-Manjaro sddm[591]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt1 -auth /var/run/sddm/{be50fe9f-729c-4541-8538-22dd381efe46} -noreset -displayfd 18
```

`journalctl -b-1`: [full.txt](https://github.com/sddm/sddm/files/7627141/full.txt)

(including the following, because i read that it causes some problems)
Theme(s): `Breath2 2021 Dark`, if not available, `Breeze` (like `Application Style`), and `Breath2` (like `Splash Screen`)
Login Screen (SDDM): `Breath2`

## Related

The following issues may be related, but are (from what i can tell) not my exact case:

- #610
- #1476

**Comment by brucethemoose** [comment]
I'm having this same issue on Arch Linux, with a wayland/kde config similar to @hasezoey :

My root filesystem is f2fs, nothing too fancy.

>  sudo inxi -b
> System:
>   Host: LinuxG14 Kernel: 5.15.6-xanmod1+clang-rog-1 x86_64 bits: 64
>   Console: pty pts/0 Distro: Arch Linux
> Machine:
>   Type: Laptop System: ASUSTeK product: ROG Zephyrus G14 GA401IV_GA401IV v: 1.0
>   serial: L7NRKD018443312
>   Mobo: ASUSTeK model: GA401IV v: 1.0 serial: UE07MC03EI UEFI: American Megatrends
>   v: GA401IV.219 date: 12/30/2020
> Battery:
>   ID-1: BAT0 charge: 22.7 Wh (31.2%) condition: 72.7/76.0 Wh (95.7%) volts: 15.8
>   min: 15.8
> CPU:
>   Info: 8-Core AMD Ryzen 9 4900HS with Radeon Graphics [MT MCP] speed: 1397 MHz
>   min/max: 1400/3000 MHz
> Graphics:
>   Device-1: AMD Renoir driver: amdgpu v: kernel
>   Display: server: X.org 1.21.1.1 driver: loaded: amdgpu unloaded: modesetting
>   resolution: <missing: xdpyinfo>
>   Message: Unable to show advanced data. Required tool glxinfo missing.
> Network:
>   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
> Drives:
>   Local Storage: total: 953.87 GiB used: 376.34 GiB (39.5%)
> Info:
>   Processes: 380 Uptime: 16m Memory: 15.12 GiB used: 3.17 GiB (21.0%) Shell: Bash
>   inxi: 3.3.07

> sudo journalctl -b -1 | grep sddm
> 
> Dec 10 11:58:07 LinuxG14 sddm[704]: Session started
> Dec 10 12:16:40 LinuxG14 sddm[704]: Authentication error: "Process crashed"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Auth: sddm-helper crashed (exit code 15)
> Dec 10 12:16:40 LinuxG14 sddm[704]: Authentication error: "Process crashed"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Auth: sddm-helper exited with 15
> Dec 10 12:16:40 LinuxG14 sddm[704]: Display server stopping...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Display server stopped.
> Dec 10 12:16:40 LinuxG14 sddm[704]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Removing display ":0" ...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Adding new display on vt 1 ...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Loading theme configuration from ""
> Dec 10 12:16:40 LinuxG14 sddm[704]: Display server starting...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Adding cookie to "/var/run/sddm/{212cead9-8200-4d4c-bdca-941eb4a7c027}"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt1 -auth /var/run/sddm/{212cead9-8200-4d4c-bdca-941eb4a7c027} -noreset -displayfd 17
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: State 'stop-sigterm' timed out. Killing.
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: Killing process 704 (sddm) with signal SIGKILL.
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: Killing process 5995 (Xorg) with signal SIGKILL.
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: Main process exited, code=killed, status=9/KILL
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: Failed with result 'timeout'.
> Dec 10 12:18:10 LinuxG14 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=sddm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
> Dec 10 12:18:10 LinuxG14 systemd[1]: sddm.service: Consumed 1.370s CPU time.
> Dec 10 12:18:10 LinuxG14 kernel: audit: type=1131 audit(1639160290.868:111): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=sddm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=?

> [alpha@LinuxG14 ~]$ sudo journalctl /usr/bin/sddm -b-1
> 
> -- Journal begins at Thu 2021-11-11 20:48:28 CST, ends at Fri 2021-12-10 12:35:34 CST. >
> Dec 10 11:58:04 LinuxG14 sddm[704]: Initializing...
> Dec 10 11:58:04 LinuxG14 sddm[704]: Starting...
> Dec 10 11:58:04 LinuxG14 sddm[704]: Logind interface found
> Dec 10 11:58:04 LinuxG14 sddm[704]: Adding new display on vt 1 ...
> Dec 10 11:58:04 LinuxG14 sddm[704]: Loading theme configuration from ""
> Dec 10 11:58:04 LinuxG14 sddm[704]: Display server starting...
> Dec 10 11:58:04 LinuxG14 sddm[704]: Adding cookie to "/var/run/sddm/{f73e85fc-c116->
> Dec 10 11:58:04 LinuxG14 sddm[704]: Running: /usr/bin/X -nolisten tcp -background n>
> Dec 10 11:58:06 LinuxG14 sddm[704]: Setting default cursor
> Dec 10 11:58:06 LinuxG14 sddm[704]: Running display setup script  "/usr/share/sddm/>
> Dec 10 11:58:06 LinuxG14 sddm[704]: Display server started.
> Dec 10 11:58:06 LinuxG14 sddm[704]: Reading from "/usr/share/wayland-sessions/plasm>
> Dec 10 11:58:06 LinuxG14 sddm[704]: Reading from "/usr/share/wayland-sessions/plasm>
> Dec 10 11:58:06 LinuxG14 sddm[704]: Session "/usr/share/wayland-sessions/plasmawayl>
> Dec 10 11:58:06 LinuxG14 sddm[704]: Authenticated successfully
> Dec 10 11:58:07 LinuxG14 sddm[704]: Session started
> Dec 10 12:16:40 LinuxG14 sddm[704]: Authentication error: "Process crashed"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Auth: sddm-helper crashed (exit code 15)
> Dec 10 12:16:40 LinuxG14 sddm[704]: Authentication error: "Process crashed"
> Dec 10 12:16:40 LinuxG14 sddm[704]: Auth: sddm-helper exited with 15
> Dec 10 12:16:40 LinuxG14 sddm[704]: Display server stopping...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Display server stopped.
> Dec 10 12:16:40 LinuxG14 sddm[704]: Running display stop script  "/usr/share/sddm/s>
> Dec 10 12:16:40 LinuxG14 sddm[704]: Removing display ":0" ...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Adding new display on vt 1 ...
> Dec 10 12:16:40 LinuxG14 sddm[704]: Loading theme configuration from ""
> 

> sudo pacman -Qs kde
> local/ark 21.12.0-1.1 (kde-applications kde-utilities)
>     Archiving Tool
> local/dolphin 21.12.0-1.1 (kde-applications kde-system)
>     KDE File Manager
> local/dolphin-plugins 21.12.0-1.1 (kde-applications kdesdk)
>     Extra Dolphin plugins
> local/filelight 21.12.0-1.1 (kde-applications kde-utilities)
>     View disk usage information
> local/frameworkintegration 5.88.0-1.1 (kf5)
>     Framework providing components to allow applications to integrate with a KDE
>     Workspace
> local/kaccounts-integration 21.12.0-1.1
>     Small system to administer web accounts for the sites and services across the KDE
>     desktop, including: Google, Facebook, Owncloud, IMAP, Jabber and others
> local/kactivities 5.88.0-1.1 (kf5)
>     Core components for KDE Activities
> local/kcontacts 1:5.88.0-1.1 (kf5)
>     Address book API for KDE
> local/kde-cli-tools 5.23.4-1.1 (plasma)
>     Tools based on KDE Frameworks 5 to better interact with the system
> local/kdeclarative 5.88.0-1.1 (kf5)
>     Provides integration of QML and KDE Frameworks
> local/kdecoration 5.23.4-1.1 (plasma)
>     Plugin based library to create window decorations
> local/kded 5.88.0-1.1 (kf5)
>     Extensible deamon for providing system level services
> local/kdelibs4support 5.88.0-1.1 (kf5-aids)
>     Porting aid from KDELibs4
> local/kdesu 5.88.0-1.1 (kf5)
>     Integration with su for elevated privileges
> local/kdialog 21.12.0-1.1 (kde-applications kde-utilities)
>     A utility for displaying dialog boxes from shell scripts
> local/khelpcenter 21.12.0-1.1 (kde-applications kde-system)
>     Application to show KDE Applications documentation
> local/kholidays 1:5.88.0-1.1 (kf5)
>     KDE library for regional holiday information
> local/kinit 5.88.0-1.1 (kf5)
>     Process launcher to speed up launching KDE applications
> local/kio-extras 21.08.3-1.1 (kde-applications kde-network)
>     Additional components to increase the functionality of KIO
> local/kmenuedit 5.23.4-1.1 (plasma)
>     KDE menu editor
> local/kompare 21.08.3-1.1 (kde-applications kdesdk)
>     Graphical file differences tool
> local/kscreen 5.23.4-1.1 (plasma)
>     KDE screen management software
> local/ksystemlog 21.08.3-1.1 (kde-applications kde-system)
>     System log viewer tool
> local/kwalletmanager 21.08.3-1.1 (kde-applications kde-utilities)
>     Wallet management tool
> local/kwayland-integration 5.23.4-1.1 (plasma)
>     Provides integration plugins for various KDE frameworks for the wayland windowing
>     system
> local/kwayland-server 5.23.4-1.1 (plasma)
>     Wayland server components built on KDE Frameworks
> local/lib32-libappindicator-gtk2 12.10.0-12
>     Allow applications to extend a menu via Ayatana indicators in Unity, KDE or Systray
>     (32-bit) (GTK+ 2 library)
> local/libblockdev 2.26-1.1
>     A library for manipulating block devices
> local/libkipi 21.08.3-1.1
>     An interface to use kipi-plugins from a KDE application
> local/libkleo 21.08.3-1.1
>     KDE PIM cryptographic library
> local/libkscreen 5.23.4-1.1 (plasma)
>     KDE screen management software
> local/partitionmanager 21.08.3-1.1 (kde-applications kde-system)
>     A KDE utility that allows you to manage disks, partitions, and file systems
> local/phonon-qt5 4.11.1-2.1
>     The multimedia framework by KDE
> local/plasma-desktop 5.23.4-1.1 (plasma)
>     KDE Plasma Desktop
> local/plasma-workspace 5.23.4-1.1 (plasma)
>     KDE Plasma Workspace
> local/polkit-kde-agent 5.23.4-1.1 (plasma)
>     Daemon providing a polkit authentication UI for KDE
> local/print-manager 21.08.3-1.1 (kde-applications kde-utilities)
>     A tool for managing print jobs and printers
> local/sddm-kcm 5.23.4-1.1 (plasma)
>     KDE Config Module for SDDM
> local/signon-kwallet-extension 21.08.3-1.1 (kde-applications kde-network)
>     KWallet integration for signon framework
> local/spectacle 21.08.3-1.1 (kde-applications kde-graphics)
>     KDE screenshot capture utility
> local/syndication 5.88.0-1.1 (kf5)
>     RSS/Atom parser library
> local/systemsettings 5.23.4-1.1 (plasma)
>     KDE system manager for hardware, software, and workspaces

**Comment by felagund** [comment]
This also seems to happen on Kubuntu (21.10 and current 22.04).

**Comment by RodJLinux** [comment]
I'm running Manjaro Qonos 21.2.6, KDE Plasma 5.24.5, kernel 5.15, X11 on three completely different systems and all have this bug since about May 2021. 

I have a workaround mitigation for those who are experiencing this bug:
Edit `/etc/systemd/system.conf` and change the line `#DefaultTimeoutStopSec=90s` to `DefaultTimeoutStopSec=5s`
This at least reduces the delay to a more acceptable and realistic five seconds. I have been using this with a delay of 10 seconds for at least nine months without any issues, but I can't absolutely guarantee it won't cause a problem (use at your own risk).

One commentator elsewhere recently said a process these days should not take more than a few ms to exit, 90 seconds is way too long IMHO.

**Comment by JacekJagosz** [comment]
I am also getting the same issue on Solus since I switched from Plasma X11 to Plasma Wayland. It might have been happening sometimes on X11, that would explain long shutdowns sometimes, but with Wayland it happens almost every time.
Errors related to sddm (in reverse order):
```
lip 08 16:27:30 malepudlo systemd[1]: sddm.service: Failed with result 'timeout'.
lip 08 16:27:30 malepudlo systemd[1]: sddm.service: Main process exited, code=killed, status=9/KILL
lip 08 16:27:30 malepudlo systemd[1]: sddm.service: Killing process 54501 (Xorg) with signal SIGKILL.
lip 08 16:27:30 malepudlo systemd[1]: sddm.service: Killing process 791 (sddm) with signal SIGKILL.
lip 08 16:27:30 malepudlo systemd[1]: sddm.service: State 'stop-sigterm' timed out. Killing.
lip 08 16:26:00 malepudlo sddm[791]: Running: /usr/bin/X -nolisten tcp -background none -seat seat0 vt7 -auth /var/run/sddm/{ea6bf22a-1bd5-4546-aa2b-72c30fdbd478} -noreset -displayfd 17
lip 08 16:26:00 malepudlo sddm[791]: Adding cookie to "/var/run/sddm/{ea6bf22a-1bd5-4546-aa2b-72c30fdbd478}"
lip 08 16:26:00 malepudlo sddm[791]: Display server starting...
lip 08 16:26:00 malepudlo sddm[791]: Loading theme configuration from ""
lip 08 16:26:00 malepudlo sddm[791]: Adding new display on vt 7 ...
lip 08 16:26:00 malepudlo sddm[791]: Removing display ":0" ...
lip 08 16:26:00 malepudlo sddm[791]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
lip 08 16:26:00 malepudlo sddm[791]: Display server stopped.
lip 08 16:26:00 malepudlo sddm[791]: Display server stopping...
lip 08 16:26:00 malepudlo sddm[791]: Auth: sddm-helper exited with 15
lip 08 16:26:00 malepudlo sddm[791]: Authentication error: "Process crashed"
lip 08 16:26:00 malepudlo sddm[791]: Auth: sddm-helper crashed (exit code 15)
lip 08 16:26:00 malepudlo sddm[791]: Authentication error: "Process crashed"
lip 08 16:26:00 malepudlo sddm[791]: Display server stopping...
lip 08 16:26:00 malepudlo sddm[791]: Auth: sddm-helper exited with 15
lip 08 16:26:00 malepudlo sddm[791]: Authentication error: "Process crashed"
lip 08 16:26:00 malepudlo sddm[791]: Auth: sddm-helper crashed (exit code 15)
lip 08 16:26:00 malepudlo sddm[791]: Authentication error: "Process crashed"
```

**Comment by mlazzarotto** [comment]
Happening also to me. I'm running sway v1.7

**Comment by brucethemoose** [comment]
For what its worth, the issue went away for me running sddm-git (from the CachyOS Arch repo).

**Comment by mlazzarotto** [comment]
> For what its worth, the issue went away for me running sddm-git (from the CachyOS Arch repo).

I'm not sure what you mean. Did you uninstall sddm package, downloaded the git repo and built sddm from source?

**Comment by brucethemoose** [comment]
> > For what its worth, the issue went away for me running sddm-git (from the CachyOS Arch repo).
> 
> I'm not sure what you mean. Did you uninstall sddm package, downloaded the git repo and built sddm from source?

The CachyOS Arch Linux repo has a prebuilt version of sddm git. I just installed it with pacman.

Maybe it has some other fixes applied? I'm not sure, I was simply told that would probably fix my sddm issue, and it did. 🤷 

There may be a similar package on the AUR.

**Comment by ghost** [comment]
Happening on EndeavourOS with Sway. Can confirm that sddm-git fixes it.

**Comment by EinfxchFinn** [comment]
This bug also occurs for me. But only with Wayland sessions (I'm using KDE Plasma) X11 sessions shut down normally.

**Comment by Vogtinator** [comment]
This was fixed by https://github.com/sddm/sddm/pull/1445.
