### ISSUE TITLE
sddm failure with NVIDIA proprietary driver (+ solution!)  [Add to wiki?]

### ISSUE THREAD

**Issue by fduncanh** [sddm/sddm#1493]
After an update of the NVIDIA driver to 470.94, sddm  failed leaving a black screen with just an arrow cursor.
Google show this is a common sddm problem, often solved by abandoning sddm.    It may have more than one cause,
but here is one solution.    A Wiki page devoted to NVIDIA issues that problem solvers could contribute to would be very useful.
**Some people seem to have spent days searching the internet for solutions.**

* symptom: boot to black screen with arrow cursor, after  sddm greeter quits.
startx x still works, as does lightdm.
ls -l /dev/nvidia* showed that 
```
crw-rw---- 1 root 33 195,   0 Jan 15 13:55 /dev/nvidia0
crw-rw---- 1 root 33 195, 255 Jan 15 13:55 /dev/nvidiactl
crw-rw---- 1 root 33 195, 254 Jan 15 13:55 /dev/nvidia-modeset
crw-rw---- 1 root video      239,   0 Jan 15 13:55 /dev/nvidia-uvm
crw-rw---- 1 root video      239,   1 Jan 15 13:55 /dev/nvidia-uvm-tools
crw------- 1 root root        10, 144 Jan 15 13:55 /dev/nvram
```
 * Clue:  (on OpenSUSE  15.3) with 
the new /etc/modprobe.d/50-nvidia-preempt.conf installed by the update starts with
```
options nvidia NVreg_DeviceFileUID=0 NVreg_DeviceFileGID=33 NVreg_DeviceFileMode=0660
```
The previous version had  DevideFileGID=483 (Group 483=video, which contained sddm as a user) 

 * Solution: create a new group  33  named (e.g. nvidia_sddm) and add sddm to it::
```
sudo groupadd -G 33 nvidia_sddm ; usermod -G nvidia_sddm sddm
```

**Comment by aleixpol** [comment]
Seems like something you should discuss with opensuse first, then we can address whatever needs addressing in SDDM.

 @antlarr @Vogtinator

**Comment by Vogtinator** [comment]
logind is supposed to grant SDDM access to those devices, see also https://bugzilla.opensuse.org/show_bug.cgi?id=1165987

Please open a (new) bug report.
