### ISSUE TITLE
SDDM crashes if it tries to autostart Plasma Wayland session

### ISSUE THREAD

**Issue by pasqui23** [sddm/sddm#1495]
I am on NixOS unstable and I have it discussed it downstream https://github.com/NixOS/nixpkgs/issues/152726
as a workaround I'm using lightdm

**Comment by aleixpol** [comment]
Can you maybe provide a backtrace if it's crashing?

**Comment by pasqui23** [comment]
On 18/01/22 02:59, Aleix Pol ***@***.***> wrote:
> Can you maybe provide a backtrace if it's crashing?
> 
How?

**Comment by aleixpol** [comment]
coredumpctl, maybe? It depends between distributions and I am unaware of the best practices for nixos.

As is, we cannot act on this issue.

**Comment by pasqui23** [comment]
ok I have the backtrace.Do I just put it on some file sharing service and put the link there?

**Comment by aleixpol** [comment]
You can paste it here.

**Comment by aleixpol** [comment]
Maybe a fix? https://github.com/sddm/sddm/pull/1496

**Comment by pasqui23** [comment]
Yes that does fix it
