### ISSUE TITLE
SDDM hangs when shutting down from KDE Plasma Wayland

### ISSUE THREAD

**Issue by MenacingPerson** [sddm/sddm#1513]
I've looked at a few issues but I can't find it reported, which is surprising because a lot of other people have it too.

So, switching to GDM or Xorg fixes it.

Not sure what logs I could attach here...

It's a blank screen, though it shuts down after a few minutes.

**Comment by aleixpol** [comment]
Should be the same as https://github.com/sddm/sddm/issues/1476.
