### ISSUE TITLE
SDDM always show this error message after locking 

### ISSUE THREAD

**Issue by Renarde-dev** [sddm/sddm#1529]
![IMG_20220309_153808](https://user-images.githubusercontent.com/91322598/157520229-a67e3947-4c3c-42c5-a0d8-89a356dbfe4d.jpg)

it suddenly happened after an update i think.
OS : KDE NEON community
sddm/focal,now 0.19.0-2+20.04

journalctl output :
https://pastebin.com/H3Neh2NB

**Comment by aleixpol** [comment]
What makes you think this is SDDM's fault?

**Comment by tpgxyz** [comment]
Definietly not a SDDM issue.

**Comment by Renarde-dev** [comment]
Sorry, I was away from github this weekend.
After some digging I found the culprit, kscreenlocker who broke after an update.

sorry for the issue.
