### ISSUE TITLE
Sometimes black screen after booting

### ISSUE THREAD

**Issue by des-b** [sddm/sddm#1531]
Sometimes I get a black screen during bootup. There is no cursor or anything else shown. If I reboot it usually works just fine. I compared the journal. This is what I see, when the error occurs:

```
sddm-greeter[857]: Adding view for ":0.0" QRect(0,0 3440x1440)
sddm-greeter[857]: QXcbConnection: XCB error: 148 (Unknown), sequence: 191, resource id: 0, major code: 140 (Unknown), minor code: 20
```

After reboot (and during successful boot) I see this:

```
sddm-greeter[842]: Adding view for "HDMI-1" QRect(0,0 3440x1440)
```

Any idea what this may cause or what I can do to avoid this?

**Comment by tpgxyz** [comment]
Please report such issues directly to you distribution support.

**Comment by des-b** [comment]
Okay. Sorry for the noise. I could not properly assess possible causes of the problem.

Just in case someone stumbles over this. It seems like this was a race condition during bootup. It seems loading Nvidia (🙈) driver modules in initramfs seems to work in my case. ([Arch Forums](https://bbs.archlinux.org/viewtopic.php?id=270564), [Arch Wiki](https://wiki.archlinux.org/title/NVIDIA#Early_loading))

Thanks for responding nevertheless.
