### ISSUE TITLE
Is this correct????            managerPath = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");

### ISSUE THREAD

**Issue by cheongi** [sddm/sddm#1540]
[sddm](https://github.com/sddm/sddm)/[src](https://github.com/sddm/sddm/tree/develop/src)/[daemon](https://github.com/sddm/sddm/tree/develop/src/daemon)/LogindDBusTypes.cpp

sddm is not talking to console kit properly and user switching is not functional.

Various sites suggest the display manager path is `/org/freedesktop/DisplayManager`

ck-list-sessions has too many blank fields and not what the sddm manual says:

```
Session16:
        unix-user = '1004'
        realname = 'test0'
        seat = 'Seat1'
        session-type = 'unspecified'
        session-class = 'user'
        session-state = 'online'
        active = FALSE
        x11-display = ':0'
        x11-display-device = '/dev/ttyv8'
        display-device = '/dev/   ?   '
        remote-host-name = ''
        is-local = TRUE
        on-since = '2022-04-12T20:03:56.252602Z'
        login-session-id = ''
        XDG_RUNTIME_DIR = '/var/run/user/1004'
        VTNr = '9'
```

**Comment by cheongi** [comment]
Have had a better look, 
   managerPath = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");

looks like it should be:
   managerPath = QStringLiteral("/org/freedesktop/ConsoleKit");

**Comment by cheongi** [comment]
Seems to behave better after fix. Still user switching issues.

**Comment by Vogtinator** [comment]
According to [the ConsoleKit documentation](https://www.freedesktop.org/software/ConsoleKit/doc/ConsoleKit.html#dbus-reference), `/org/freedesktop/ConsoleKit/Manager` is the correct path to use.

If the path was incorrect, SDDM would not start at all due to the lack of seats.

**Comment by cheongi** [comment]
Session reuse is not functional and sddm/ck is unstable for other FreeBSD users too. Sitting at a session marked "active = FALSE" is a bug somewhere.
[https://forums.freebsd.org/threads/consolekit-sddm-switch-user.84693/post-562516](url)


[https://github.com/sddm/sddm/blob/master/src/daemon/LogindDBusTypes.cpp](url)

```
if (QDBusConnection::systemBus().interface()->isServiceRegistered(QStringLiteral("org.freedesktop.login1"))) {
        qDebug() << "Logind interface found";
        available = true;
        serviceName = QStringLiteral("org.freedesktop.login1");
        managerPath = QStringLiteral("/org/freedesktop/login1");
        managerIfaceName = QStringLiteral("org.freedesktop.login1.Manager");
        seatIfaceName = QStringLiteral("org.freedesktop.login1.Seat");
        sessionIfaceName = QStringLiteral("org.freedesktop.login1.Session");
        userIfaceName = QStringLiteral("org.freedesktop.login1.User");
        return;
    }

  if (QDBusConnection::systemBus().interface()->isServiceRegistered(QStringLiteral("org.freedesktop.ConsoleKit"))) {
        qDebug() << "Console kit interface found";
        available = true;
        serviceName = QStringLiteral("org.freedesktop.ConsoleKit");
        managerPath = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");
        managerIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.Manager"); //note this doesn't match logind
        seatIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.Seat");
        sessionIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.Session");
        userIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.User");
        return;

```

**Comment by Vogtinator** [comment]
The issue looks like the ConsoleKit session isn't created on login. With logind, this is done by `pam_systemd`, no idea how it's meant to work with ConsoleKit.

**Comment by cheongi** [comment]
Paths expected by console-kit are reported in debug daemon log after a failure. The base path for Manager, Seat<nn>, and Session<nn> is `/org/freedesktop/ConsoleKit/`.

I presume that Manager, Seat<nn> and Session<nn> are all added to the base path.

```
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[10170]	DEBUG: CkManager: Unable to lookup cookie for caller - failing
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[10170]	DEBUG: manager: throwing error: Unable to find session for cookie
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[10170]	GLib-GObject-WARNING: instance of invalid non-instantiatable type '(null)'
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[10170]	GLib-GObject-CRITICAL: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed aborting...
2/5/22 8:19 AM	hpz2freebsd	dbus-daemon[23756]	[system] Activating service name='org.freedesktop.ConsoleKit' requested by ':1.9' (uid=565 pid=11293 comm="/usr/local/lib/polkit-1/polkitd --no-debug ") (using servicehelper)
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: Debugging enabled
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: initializing console-kit-daemon 1.2.2
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: bus_acquired org.freedesktop.ConsoleKit 
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: Creating thread for log writing
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: exported on /org/freedesktop/ConsoleKit/Manager
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: Creating seat /org/freedesktop/ConsoleKit/Seat1 with 0 devices
```
My system with path correction appears stable with bugs as opposed to unstable and crashing. Still chasing sddm/ck switching bug.

**Comment by davidedmundson** [comment]
>looks like it should be:
>managerPath = QStringLiteral("/org/freedesktop/ConsoleKit");

If you can find a source that'd be great. I know things were looked up at the time, but that was a long long time ago. CK could have changed.

**Comment by Vogtinator** [comment]
> I presume that Manager, Seat and Session are all added to the base path.

Yes, which makes `/org/freedesktop/ConsoleKit/Manager` the correct path to use.

The log you quoted says:

```
2/5/22 8:19 AM	hpz2freebsd	console-kit-daemon[57489]	DEBUG: exported on /org/freedesktop/ConsoleKit/Manager
```

And that's what SDDM uses.

**Comment by cheongi** [comment]
> According to [the ConsoleKit documentation](https://www.freedesktop.org/software/ConsoleKit/doc/ConsoleKit.html#dbus-reference),

I note that the ConsoleKit 0.4.1 Documentation by William Jon McCann probbaly describes the Sun version from 2008. Current systems appear to use consolekit2. https://consolekit2.github.io/ConsoleKit2/

**Comment by Vogtinator** [comment]
That also uses `/org/freedesktop/ConsoleKit/Manager` in the provided example code for the DBus API.

**Comment by Vogtinator** [comment]
It's actually rather simple to find out which of those paths is the correct one on your particular system. Just check which of those two commands works:

```
qdbus org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.GetCurrentSession
qdbus org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit org.freedesktop.ConsoleKit.Manager.GetCurrentSession
```

**Comment by cheongi** [comment]
It's more complex than I originally thought. Using sddm-0.19.0  from repository. Some paths are hard-coded. In reality using /org/freedesktop/DisplayManager/ , which ConsoleKit is apparently not using.

```
root@hpz2freebsd:/home/ian # echo $XDG_SEAT_PATH
/org/freedesktop/DisplayManager/Seat0
root@hpz2freebsd:/home/ian # echo $XDG_SESSION_PATH
/org/freedesktop/DisplayManager/Session3

root@hpz2freebsd:/usr/ports/x11/sddm/work/sddm-0.19.0/src # grep -inRsH "Manager"
./daemon/PowerManager.cpp:118:const QString LOGIN1_OBJECT = QStringLiteral("org.freedesktop.login1.Manager");
./daemon/PowerManager.cpp:121:const QString CK2_PATH = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");
./daemon/PowerManager.cpp:122:const QString CK2_OBJECT = QStringLiteral("org.freedesktop.ConsoleKit.Manager");

./daemon/DisplayManager.cpp:29:const QString DISPLAYMANAGER_SERVICE = QStringLiteral("org.freedesktop.DisplayManager");
./daemon/DisplayManager.cpp:30:const QString DISPLAYMANAGER_PATH = QStringLiteral("/org/freedesktop/DisplayManager");
./daemon/DisplayManager.cpp:31:const QString DISPLAYMANAGER_SEAT_PATH = QStringLiteral("/org/freedesktop/DisplayManager/Seat");
./daemon/DisplayManager.cpp:32:const QString DISPLAYMANAGER_SESSION_PATH = QStringLiteral("/org/freedesktop/DisplayManager/Session");
```

**Comment by Vogtinator** [comment]
That's the DBus object path SDDM is offering itself. It's unrelated to CK.

**Comment by cheongi** [comment]
So sddm and ConsoleKit don't communicate via dbus???

**Comment by cheongi** [comment]
```
# qdbus org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.GetCurrentSession
qdbus: Command not found.
# pkg inst qdbus
Updating FreeBSD repository catalogue...
Fetching packagesite.pkg: 100%    6 MiB   6.7MB/s    00:01    
Processing entries: 100%
FreeBSD repository update completed. 31192 packages processed.
All repositories are up to date.
pkg: No packages available to install matching 'qdbus' have been found in the repositories
# pkg inst qdbusviewer
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'qdbusviewer' have been found in the repositories
# pkg search qdbus
qt5-qdbus-5.15.2p17            Qt command-line interface to D-Bus (KDE patched)
qt5-qdbusviewer-5.15.2p17      Qt 5 graphical interface to D-Bus (KDE patched)
# pkg inst qt5-qdbus
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
# qt5-qdbus org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.GetCurrentSession
qt5-qdbus: Command not found.
# pkg inst qt5-qdbusviewer 
[...]
[1/1] Fetching qt5-qdbusviewer-5.15.2p17.pkg: 100%   45 KiB  46.0kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/1] Installing qt5-qdbusviewer-5.15.2p17...
[1/1] Extracting qt5-qdbusviewer-5.15.2p17: 100%
Building cache database of MIME types
# qt5-qdbusviewer org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.GetCurrentSession
qt5-qdbusviewer: Command not found.
```

Can't find how to look inside dbus with freebsd.

**Comment by Vogtinator** [comment]
> So sddm and ConsoleKit don't communicate via dbus???

Of course they do. But not through `org.freedesktop.DisplayManager`.

> Can't find how to look inside dbus with freebsd.

It could be called `qdbus-qt5` or be in a different directory.

**Comment by cheongi** [comment]
So the sddm daemon talks to itself via dbus???

**Comment by davidedmundson** [comment]
> So the sddm daemon talks to itself via dbus???

No. It talks to console kit. It serves org.freedesktop.displaymanager

**Comment by cheongi** [comment]
d-feet works. 

/org/freedesktop/ConsoleKit/Manager is the correct manager path. 

The problem has always been whether the path root labelled managerPath ends up being used as /org/freedesktop/ConsoleKit/Manager/Manager, /org/freedesktop/ConsoleKit/Manager/Seat<nn> and /org/freedesktop/ConsoleKit/Manager/Session<nn>. 

It appears that the real manager path is hard coded. I can't find that the managerPath variable is used at all with ConsoleKit; only logind.

```
root@hpz2freebsd:/usr/ports/x11/sddm/work/sddm-0.19.0/src # grep -inRsH "Manager"
./daemon/PowerManager.cpp:118:const QString LOGIN1_OBJECT = QStringLiteral("org.freedesktop.login1.Manager");
./daemon/PowerManager.cpp:121:const QString CK2_PATH = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");
./daemon/PowerManager.cpp:122:const QString CK2_OBJECT = QStringLiteral("org.freedesktop.ConsoleKit.Manager");
[...]
./daemon/DisplayManager.cpp:29:const QString DISPLAYMANAGER_SERVICE = QStringLiteral("org.freedesktop.DisplayManager");
./daemon/DisplayManager.cpp:30:const QString DISPLAYMANAGER_PATH = QStringLiteral("/org/freedesktop/DisplayManager");
./daemon/DisplayManager.cpp:31:const QString DISPLAYMANAGER_SEAT_PATH = QStringLiteral("/org/freedesktop/DisplayManager/Seat");
./daemon/DisplayManager.cpp:32:const QString DISPLAYMANAGER_SESSION_PATH = QStringLiteral("/org/freedesktop/DisplayManager/Session");
```
d-feet works. Still confused what DisplayManager is meant to be doing separate from ConsoleKit.

![Screenshot_20220508_061600](https://user-images.githubusercontent.com/43463113/167270600-aa093473-2e80-4fcd-8085-eb1176cdd13b.png)
![Screenshot_20220508_061951](https://user-images.githubusercontent.com/43463113/167270608-cc9c385d-6df2-4e0e-8a29-d0c2b2dcc395.png)
![Screenshot_20220508_061700](https://user-images.githubusercontent.com/43463113/167270603-a2533775-0c8b-46af-a2ad-8e3f8feb994a.png)
![Screenshot_20220508_061747](https://user-images.githubusercontent.com/43463113/167270605-e7546c2d-141f-4f86-805f-8406d46f68a1.png)
![Screenshot_20220508_061809](https://user-images.githubusercontent.com/43463113/167270607-64930cdd-77b7-4ea0-b57f-712cdba4c39d.png)

Looks like the bugs must be deeper in.

**Comment by arrowd** [comment]
Not sure why this is closed. The problem exists and I'm working on it.
