### ISSUE TITLE
Virtual keyboard should open automatically

### ISSUE THREAD

**Issue by plata** [sddm/sddm#1572]
On a device without physical keyboard attached or a convertible laptop in tablet mode:

While it's possible to use the virtual keyboard if the InputMethod is set, it would be nice if it would just open automatically if the password field receives focus.

**Comment by michaelk83** [comment]
Click the password field a 2nd time, and it opens (at least for me on SDDM 0.18.1 on Kubuntu 20.04). It would be an annoyance if it opens all the time by default. If no physical keyboard is detected, then that's another matter.

**Comment by plata** [comment]
This doesn't work for me. However, I realized that the issue is missing important context, so I will add that.

**Comment by plata** [comment]
Works fine on Wayland. This is sufficient for my use case.
