### ISSUE TITLE
user name is cut at the bottom on greeter when in background

### ISSUE THREAD

**Issue by superbonaci** [sddm/sddm#1576]
Capture of issue with sddm. Create 2 users and when you select one the other gets the text cut at the bottom. Running on Arch linux, packages:
````
sddm 0.19.0-8
sddm-kcm 5.25.4-1
````

![](https://i.imgur.com/HNQ9vyQ.png)

**Comment by superbonaci** [comment]
May be related to:
https://gitlab.manjaro.org/applications/manjaro-settings-manager/-/issues/188
https://gitlab.manjaro.org/applications/manjaro-settings-manager/-/issues/216

**Comment by tpgxyz** [comment]
Hi, this has nothing to do with sddm. Please fill the ticket to your distribution first, then fix your DPI.

**Comment by superbonaci** [comment]
I've changed the theme.
