### ISSUE TITLE
sddm-greeter "Invalid description '(empty)'" ; sddm-helper "gkr-pam: unable to locate daemon control file"

### ISSUE THREAD

**Issue by slrslr** [sddm/sddm#1584]
Hello, on stable version of the Debian (11, Bullseye) up to date, kernel 5.10.0-18-amd64, KDE desktop: 5.20.5, qt 5.15.2

during boot/login I have found some suspicious sddm messages that i have mentioned in the title of this issue.
I would like to get rid of so i am asking how and also if it is something that may be fixed for everyone to not cause confusion?
I have posted that short part of [journalctl output here please](https://bin.disroot.org/?4bc9414ee084012d#5iyoskxUqgHzMk8CZjZRbHzDnzqoEUNB9GDt3HSZnWT9).

Regarding control file issue, similar topics are:
https://github.com/canonical/lightdm/issues/70
https://discussion.fedoraproject.org/t/gkr-pam-unable-to-locate-daemon-control-file/18102
https://askubuntu.com/questions/1140913/gkr-pam-unable-to-locate-daemon-control-file

Debian issue similar: https://lists.debian.org/debian-qt-kde/2021/06/msg00011.html

Thank you

**Comment by tpgxyz** [comment]
Hi,
please fill ticket for you distro as in first place.
Second gkr-pam is not something that sddm uses at all.
