### ISSUE TITLE
User switching breaks

### ISSUE THREAD

**Issue by aleixpol** [sddm/sddm#1588]
We should look into whether we are switching ttys properly...

https://bugs.kde.org/show_bug.cgi?id=458169

**Comment by aleixpol** [comment]
I've been unable to reproduce this with DisplayServer different to wayland so far (tested with x11 and x11-user too).

Also couldn't reproduce under 0.19.0, hence setting the milestone to 0.20.

**Comment by davidedmundson** [comment]
I would suggest looking into whether logind thinks we're on the same tty we end up actually on. 

We use logind to perform switching most the time.

Relevant things are:
`        r = pam_get_item(handle, PAM_TTY, (const void**) &tty);`
`        cvtnr = getenv_harder(handle, "XDG_VTNR", NULL);`
