### ISSUE TITLE
Changing expired password

### ISSUE THREAD

**Issue by kobaltd** [sddm/sddm#1601]
When is this functionality implemented? Without it, it is not possible to use the system fully, especially in the corporate segment. This problem surfaced more than 4 years ago and has not yet been resolved.

**Comment by EXCV31** [comment]
@kobaltd https://github.com/sddm/sddm/pull/776/ - we're waiting for 6 years.

**Comment by kobaltd** [comment]
So this is the question. If you write about it "less", then for sure this problem will be solved "faster" :)

**Comment by Vogtinator** [comment]
Duplicate of #716
