### ISSUE TITLE
sddm block when logout that waiting for xorgdisplayserver pipe readline 

### ISSUE THREAD

**Issue by luojc123** [sddm/sddm#1618]
Get a black screen when logout from desktop session. 
cttl+alt+f* switch to the sddm's tty can continue the block that warting for xorgdisplayserver readline

**Comment by tpgxyz** [comment]
File a ticket for you distribution on the first place.

**Comment by luojc123** [comment]
@tpgxyz  I use createDisplay() at last event loop and fix this. Maybe the last Xorg process not exited completely
In Seat.cpp Seat::displayStopped()
        if (m_displays.isEmpty()) {
            QTimer::singleShot(100, this, [=] { createDisplay(); });
        }
