### ISSUE TITLE
dbus kcmsddm Permission denied

### ISSUE THREAD

**Issue by bphd** [sddm/sddm#1623]
I know it's not a bug from dBus or SDDM or something, just a misconfiguration of my system, but I just couldn't find what despite having found occurrence on internet

`dbus-daemon[]: [system] Activated service 'org.kde.kcontrol.kcmsddm' failed: Failed to execute program org.kde.kcontrol.kcmsddm: Permission denied`

Do you know what should be done for having permission to execute? I tried as root and it's the same, even with user execution permission

I ask here rather than on any Linux forum for the problem to be easily founded by future people

**Comment by aleixpol** [comment]
I'm not sure what you are trying to do, you didn't specify it in the bug report, but it looks a lot like a misconfiguration problem.

**Comment by bphd** [comment]
Trying to apply a theme

**Comment by aleixpol** [comment]
I see, that makes more sense.

This component lives in plasma-workspace. Please report here: https://bugs.kde.org/enter_bug.cgi?product=plasmashell

That said, it's probably a problem with your distro, reporting there first would make sense as the feature is working generally.
