### ISSUE TITLE
sddm and wayland: arch solution

### ISSUE THREAD

**Issue by slynobody** [sddm/sddm#1628]
what do you think of this solution a) in general and b) security-wise? 
https://wiki.archlinux.org/title/SDDM#Running_under_Wayland

and what would be the best solution to enter after '[Wayland] CompositorCommand='?
i fiddled around a bit and observed a few hickups here and there when using f.e. this:

CompositorCommand=kwin_wayland --no-lockscreen --no-kactivities --drm --lock

sometimes there seems to be a mouse-corner in the upper left and you sometimes could trigger something that reminds me of rudimentaries of a window-changer through alt-tab. to put it positive: could this be a first step to a solution to also integrate interfaces to audio, bluetooth, screen-backlight and even screensavers to sddm (like in gdm)?

**Comment by aleixpol** [comment]
Here it's described what we suggest from Plasma:
https://invent.kde.org/plasma/plasma-workspace/-/tree/master/sddm-wayland-session

Agreed, there's opportunity to do a bit more, like launching powerdevil which shouldn't be too hard.

**Comment by slynobody** [comment]
Thank you for your answer.

What do you think security-wise on the sketched solution? esp. in situations when you have to restart the sddm-service via root-shell because it crashed before (common since mesa 22.3 as well as mesa 23) ?

And  could you please explain in simple words what this will do (does not work here, needs another shell (is layer-shell old?)?
QT_WAYLAND_SHELL_INTEGRATION=layer-shell

what could be benefits of current alternatives:
-    ivi-shell
-    wl-shell
-    xdg-shell
-    fullscreen-shell-v1

in general: are there / what are the plans to 'do a bit more' from here on when it comes to power-devil- / sound- / background-lighting-integration?

**Comment by aleixpol** [comment]
`layer-shell` is not old, it's what we use for fullscreen shells. It's developed by wlroots and we implement it through https://invent.kde.org/plasma/layer-shell-qt.

The alternatives are all fairly old and unused. We considered using xdg-shell too which is what we use for most windows but managing fullscreen windows with xdg-shell has proven a challenge to us, thus the development and adoption of layer-shell-qt.

We should find a way to opt in the services that we think would be acceptable in the session. I've tested powerdevil before and it worked alright.

**Comment by slynobody** [comment]
is there any sddm development in the making / planning anymore? or do you really think the current state feature-wise is 'final'?
