### ISSUE TITLE
pure wayland with no xorg-server deps?

### ISSUE THREAD

**Issue by rezad1393** [sddm/sddm#1633]
is there a way to install this on archlinux with no xorg-server dependency?
is there any plan to remove this dependency?

**Comment by tpgxyz** [comment]
@rezad1393 please ask your archlinux people, maybe try their forums etc.

**Comment by rezad1393** [comment]
> @rezad1393 please ask your archlinux people, maybe try their forums etc.

are you telling me that sddm supports pure wayland with no xorg-server dependency right now, outside of archlinux?

**Comment by tpgxyz** [comment]
@rezad1393 i'm telling you to contact your distribution maintainers at the first place.

**Comment by rezad1393** [comment]
ok 
but my question is now "with no xorg-server dependency right now, **outside** of archlinux?"

**Comment by stanczew** [comment]
Why not try it yourself?
I'm running Arch with `sddm-git` on pure Wayland, with `xorg-*` dependencies removed. `xorg-server` is not even installed:
```
$ pacman -Q xorg-server
error: package 'xorg-server' was not found
```
So yes, there is a way, and it's quite trivial actually.

**Comment by rezad1393** [comment]
> Why not try it yourself? I'm running Arch with `sddm-git` on pure Wayland, with `xorg-*` dependencies removed. `xorg-server` is not even installed:
> 
> ```
> $ pacman -Q xorg-server
> error: package 'xorg-server' was not found
> ```
> 
> So yes, there is a way, and it's quite trivial actually.

how?
did you edit the git?
when I do that sddm doesnt start for me.

update:
never mind. it needed a config.

2nd update:
it seems that only autologin works.
if I disable autologin then I get blank screen with a stuck cursor on top left corner. I can ssh to the device.

**Comment by stanczew** [comment]
Works here, both with and without autologin.
I'm using `sddm-git` built from commit 0a54d3a, with `xorg-xauth` and `xorg-server` removed from `depends=()`.
My configuration file, taken from the Wiki (https://wiki.archlinux.org/title/SDDM#Running_under_Wayland):
```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen
```

**Comment by rezad1393** [comment]
> Works here, both with and without autologin. I'm using `sddm-git` built from commit [0a54d3a](https://github.com/sddm/sddm/commit/0a54d3abbb896d652bac7a495ed98b0617306a6c), with `xorg-xauth` and `xorg-server` removed from `depends=()`. My configuration file, taken from the Wiki (https://wiki.archlinux.org/title/SDDM#Running_under_Wayland):
> 
> ```
> [General]
> DisplayServer=wayland
> GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
> 
> [Wayland]
> CompositorCommand=kwin_wayland --no-lockscreen
> ```

thanks. I didnt see that sddm article part before. Is it new?
by the way, is that commit (snapshot?) the soonest sddm can run pure wayland or that was just you?
also the stable sddm doesnt support pure wayland or just archlinux using as a dep forces X?

**Comment by stanczew** [comment]
> is that commit (snapshot?) the soonest sddm can run pure wayland or that was just you?
No, it's just current top of the `develop` branch.

> also the stable sddm doesnt support pure wayland or just archlinux using as a dep forces X?

**Comment by stanczew** [comment]
> is that commit (snapshot?) the soonest sddm can run pure wayland or that was just you?

No, it's just current top of the `develop` branch.

> also the stable sddm doesnt support pure wayland or just archlinux using as a dep forces X?

From the Wiki:
"SDDM can run rootless under Wayland, but currently only when using the `sddm-git` package."

There is also no `DisplayServer` option in 0.19, so it's pretty safe to assume it doesn't support anything other than X:
https://man.archlinux.org/man/sddm.conf.5.en
