### ISSUE TITLE
SDDM login screen fails to render (black screen)

### ISSUE THREAD

**Issue by userse31** [sddm/sddm#1634]
SDDM's login screen fails to render under intel 82852/82855 integrated graphics.

Interestingly, when logged in, everything renders correctly.

**Comment by userse31** [comment]
Running "journalctl -b -0 | grep "sddm"" I get:

Dec 31 16:03:42 qwerty-700m sddm[432]: Initializing...
Dec 31 16:03:42 qwerty-700m sddm[432]: Starting...
Dec 31 16:03:42 qwerty-700m sddm[432]: Logind interface found
Dec 31 16:03:42 qwerty-700m sddm[432]: Adding new display on vt 7 ...
Dec 31 16:03:42 qwerty-700m sddm[432]: Loading theme configuration from ""
Dec 31 16:03:42 qwerty-700m sddm[432]: Display server starting...
Dec 31 16:03:42 qwerty-700m sddm[432]: Adding cookie to "/var/run/sddm/{a99f92a0-da2f-432f-b157-e3fcd3af90a6}"
Dec 31 16:03:42 qwerty-700m sddm[432]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{a99f92a0-da2f-432f-b157-e3fcd3af90a6} -background none -noreset -displayfd 17 -seat seat0 vt7
Dec 31 16:03:45 qwerty-700m sddm[432]: Setting default cursor
Dec 31 16:03:45 qwerty-700m sddm[432]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
Dec 31 16:03:45 qwerty-700m sddm[432]: Display server started.
Dec 31 16:03:45 qwerty-700m sddm[432]: Socket server starting...
Dec 31 16:03:45 qwerty-700m sddm[432]: Socket server started.
Dec 31 16:03:45 qwerty-700m sddm[432]: Loading theme configuration from "/usr/share/sddm/themes/debian-theme/theme.conf"
Dec 31 16:03:45 qwerty-700m sddm[432]: Greeter starting...
Dec 31 16:03:45 qwerty-700m sddm-helper[1002]: [PAM] Starting...
Dec 31 16:03:45 qwerty-700m sddm-helper[1002]: [PAM] Authenticating...
Dec 31 16:03:45 qwerty-700m sddm-helper[1002]: [PAM] returning.
Dec 31 16:03:45 qwerty-700m sddm-helper[1002]: pam_unix(sddm-greeter:session): session opened for user sddm(uid=114) by (uid=0)
Dec 31 16:03:45 qwerty-700m systemd-logind[406]: New session 1 of user sddm.
Dec 31 16:03:45 qwerty-700m systemd[1004]: pam_unix(systemd-user:session): session opened for user sddm(uid=114) by (uid=0)
Dec 31 16:03:45 qwerty-700m systemd[1]: Started Session 1 of user sddm.
Dec 31 16:03:45 qwerty-700m sddm[432]: Greeter session started successfully
Dec 31 16:03:46 qwerty-700m sddm-greeter[1021]: High-DPI autoscaling not Enabled
Dec 31 16:03:46 qwerty-700m sddm-greeter[1021]: Reading from "/usr/share/xsessions/lxqt.desktop"
Dec 31 16:03:46 qwerty-700m sddm-greeter[1021]: Loading theme configuration from "/usr/share/sddm/themes/debian-theme/theme.conf"
Dec 31 16:03:46 qwerty-700m sddm-greeter[1021]: Connected to the daemon.
Dec 31 16:03:46 qwerty-700m sddm-greeter[1021]: QFont::fromString: Invalid description '(empty)'
Dec 31 16:03:46 qwerty-700m sddm[432]: Message received from greeter: Connect
Dec 31 16:03:47 qwerty-700m sddm-greeter[1021]: Loading file:///usr/share/sddm/themes/debian-theme/Main.qml...
Dec 31 16:03:47 qwerty-700m sddm-greeter[1021]: file:///usr/lib/i386-linux-gnu/qt5/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: file:///usr/share/sddm/themes/debian-theme/Main.qml:40:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: file:///usr/share/sddm/themes/debian-theme/Main.qml:155: ReferenceError: session_button is not defined
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: file:///usr/share/sddm/themes/debian-theme/Main.qml:175: ReferenceError: session_button is not defined
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: Adding view for "LVDS1" QRect(0,0 1280x800)
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: QOpenGLShader: could not create shader
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: QOpenGLShader: could not create shader
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: QOpenGLShader: could not create shader
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: Message received from daemon: Capabilities
Dec 31 16:03:48 qwerty-700m sddm-greeter[1021]: Message received from daemon: HostName
Dec 31 16:03:58 qwerty-700m sddm-greeter[1021]: Reading from "/usr/share/xsessions/lxqt.desktop"
Dec 31 16:03:58 qwerty-700m sddm[432]: Message received from greeter: Login
Dec 31 16:03:58 qwerty-700m sddm[432]: Reading from "/usr/share/xsessions/lxqt.desktop"
Dec 31 16:03:58 qwerty-700m sddm[432]: Reading from "/usr/share/xsessions/lxqt.desktop"
Dec 31 16:03:58 qwerty-700m sddm[432]: Session "/usr/share/xsessions/lxqt.desktop" selected, command: "startlxqt"
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: [PAM] Starting...
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: [PAM] Authenticating...
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: [PAM] Preparing to converse...
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: [PAM] Conversation with 1 messages
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: pam_unix(sddm:auth): check pass; user unknown
Dec 31 16:03:58 qwerty-700m sddm-helper[1037]: pam_unix(sddm:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
Dec 31 16:04:00 qwerty-700m sddm-helper[1037]: [PAM] authenticate: Authentication failure
Dec 31 16:04:00 qwerty-700m sddm-helper[1037]: [PAM] returning.
Dec 31 16:04:00 qwerty-700m sddm-helper[1037]: [PAM] Ended.

>  sddm-greeter[1021]: QOpenGLShader: could not create shader

Now, im no scientist, but that seems bad.

**Comment by userse31** [comment]
So it appears this is an issue with the igpu in my computer not supporting opengl 2.0.

https://stackoverflow.com/questions/20530157/error-qopenglshader-could-not-create-shader-when-compiling-qtquick-applicati

Why in god's green earth someone thought "Ah yes, make it rely on opengl 2.0 and not have any sort of software rendering fallback!" needs a kick to the teeth.

Idiots...

**Comment by Pointedstick** [comment]
Ok, closing since it's a driver bug.

**Comment by userse31** [comment]
> Ok, closing since it's a driver bug.

Sounds good to me!
