### ISSUE TITLE
Logout from KDE session on Rawhide goes to a console/black screen, not SDDM (with SDDM wayland)

### ISSUE THREAD

**Issue by Conan-Kudo** [sddm/sddm#1636]
*(Reported originally downstream in Fedora as [rhbz#2110801](https://bugzilla.redhat.com/show_bug.cgi?id=2110801) by @AdamWill)*

If you do a clean install of current Fedora Rawhide KDE - e.g. from https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20230105.n.0/compose/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-Rawhide-20230105.n.0.iso - then boot the installed system, log in, and log out, you wind up at a console on tty2, not back at SDDM as you should.

As best I can tell, when the system boots, SDDM is running on tty1 and there are consoles on tty2 and tty3. After login, SDDM goes away and tty1 just shows a flashing cursor; KDE starts on tty3. tty2 still has a console. When logging out from KDE, the system puts you on tty2, with the console. tty1 still shows a flashing cursor. tty3 also now has a console again. SDDM doesn't seem to be present on any tty, though it's still *running* according to systemctl and ps.

Another user sees a variation of this problem where they get a black screen with just a flashing text cursor in the top left when logging out. That is, it doesn't switch to tty2, it just sticks to tty1 instead.

This problem shows up when using SDDM in Wayland mode. When using (root) X11, this doesn't occur.

Fedora KDE Rawhide nightlies can be found here: https://openqa.fedoraproject.org/nightlies.html

**Comment by Conan-Kudo** [comment]
For our sddm Wayland configuration, we use a package `sddm-wayland-plasma` that ships the sddm configuration snippet from plasma-workspace to configure SDDM to use kwin as the compositor.

cc: @aleixpol, @davidedmundson, @zzag, @Zamundaaa

**Comment by Conan-Kudo** [comment]
At this point in time, this is the sole blocker bug we have for eliminating X11 from our default hotpath entirely, per https://fedoraproject.org/wiki/Changes/WaylandByDefaultForSDDM

**Comment by Conan-Kudo** [comment]
This is reproducible with the current git master (3e486499b9300ce8f9c62bd102e5119b27a2fad1).

**Comment by Eckoa** [comment]
Just to confirm this issue isnt just Fedora Rawhide but on Arch linux also with sddm-git. SDDM runs on TTY1 and when Plasma starts SDDM closes and Plasma runs on TTY2. When you log out you drop to TTY2 and switching to TTY1 simply results in a black screen/flashing cursor

**Comment by aleixpol** [comment]
I've been unable to reproduce this on both my dev machines. I'll test with the latest rawhide as of today...

**Comment by AdamWill** [comment]
That's weird, it's 100% reproducible in openQA so far. Any time we go to an SDDM build that uses Wayland, we get the bug.

You won't be able to reproduce it on F37 vanilla as SDDM is built to use X there, but it should reproduce easily on Rawhide.

**Comment by aleixpol** [comment]
I tested it on https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20230125.n.0/compose/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-Rawhide-20230125.n.0.iso

**Comment by aleixpol** [comment]
I could finally reproduce it, now it also happens always, somehow I had to restart my system :shrug:
