### ISSUE TITLE
When is the next release of SDDM expected?

### ISSUE THREAD

**Issue by hphilm** [sddm/sddm#1639]
It is now more than 2 years since 0.19.0 got released. Also more and more issues in regard of **Wayland** pop up lately. So when is the next release of SDDM expected? See also: https://bugs.kde.org/show_bug.cgi?id=445449#c36

**Comment by ppolych** [comment]
This issue has been fixed in git version.

**Comment by herostrat** [comment]
Dublicate of #1471

**Comment by aleixpol** [comment]
Closing as it's indeed duplicate.
