### ISSUE TITLE
[Wayland] Latest commit causing SDDM to crash at boot 

### ISSUE THREAD

**Issue by Eckoa** [sddm/sddm#1648]
When running SDDM with this wayland configuration

```
[General] DisplayServer=wayland 

[Wayland] CompositorCommand=weston --shell=fullscreen-shell.so
```

This commit https://github.com/sddm/sddm/commit/9896dea10339ec478574f6ef7f9809854a0a8986 is causing SDDM to crash at boot. If you switch to another TTY and restart the SDDM service it works fine but at the initial boot it crashes and coredumps.

Rolling back to the Fix user switching https://github.com/sddm/sddm/commit/3ee57e99836fe051c97e0f301962120466d220f7 from yesterday resolves the issue

This is on Arch Linux with an  RX6800 on Mesa 22.3.4, let me know what other information you may require

**Comment by Vogtinator** [comment]
Can you get a backtrace? I have no idea how that change could cause a crash.

**Comment by Eckoa** [comment]
> Can you get a backtrace? I have no idea how that change could cause a crash.

I can no longer get it to do this, before it was repeatable across rebuilds and every reboot/startup but now i tried building with the latest commits and pinning to the one in question but it just doesnt happen now. Across multiple shutdowns/reboots it no longer crashes.

I guess this wasnt SDDMs fault but something else that just made it look like that commit was an issue. I did have some glibc, gcc, kernel, and rocm updates yesterday but im not sure in what way that would effect SDDM?

**Comment by Eckoa** [comment]
would it be helpful to roll back my updates and see if i can reproduce this?

**Comment by Vogtinator** [comment]
Probably not, I assume this was a false positive.
