### ISSUE TITLE
[Wayland] Blur Broken when running in wayland mode

### ISSUE THREAD

**Issue by Eckoa** [sddm/sddm#1649]
When running SDDM (as of yesterdays git) with either weston or Kwin blur is broken on themes that include it. This includes Breeze and any other theme with blur. 

![9319](https://user-images.githubusercontent.com/120538016/216444487-1492c9f0-62f8-4bb5-8bb3-80b066bce447.png)

wayland configs used

```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen --inputmethod maliit-keyboard
```

and 

```
[General]
DisplayServer=wayland

[Wayland]
CompositorCommand=weston --shell=fullscreen-shell.so
```

This is on Arch Linux with an  RX6800 on Mesa 22.3.4, let me know what other information you may require

**Comment by Zamundaaa** [comment]
can confirm

**Comment by Vogtinator** [comment]
Same as #1441?

**Comment by aleixpol** [comment]
Yes same.
