### ISSUE TITLE
[Enhancement] Support bluetooth devices.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [sddm/sddm#1652]
Currently, I am unable to easily access any options of the graphical interface of `sddm` with a fresh installation of OpenSUSE Tumbleweed because my mouse is connected via Bluetooth.

**Comment by tpgxyz** [comment]
@rokejulianlockhart Please file a bug report in OpenSUSE bug reporting platform.
I have bt keyboard and mouse and it works with sddm.

**Comment by RokeJulianLockhart** [comment]
@tpgxyz, thank you. Reported at [`bugzilla.suse.com/show_bug.cgi?id=1208157`](https://bugzilla.suse.com/show_bug.cgi?id=1208157).
