### ISSUE TITLE
How to prevent flash of white when sddm loads?

### ISSUE THREAD

**Issue by TheLastTeapot** [sddm/sddm#1668]
Every time sddm loads there is a bright white flash before it appears. Is this a bug or a problem on my end?

**Comment by tpgxyz** [comment]
@TheLastTeapot based on your description this is a problem at your end. Kindly please reach to your distribution bug reporting platform and file detailed eport there.

**Comment by TheLastTeapot** [comment]
This happens on multiple devices so it's not just one. Maybe a 'flash' isn't the best way to describe it, it's as if the default background is set to white and the actual background takes a couple milliseconds to load, but it's not just the background, it the whole screen, ui included. If this is just a matter of it loading slowly on my machines, ok.

**Comment by TheLastTeapot** [comment]
It was a problem with the Nordic theme specifically

**Comment by gorgiaxx** [comment]
Not only will a third-party theme cause screen flickering, but changing display settings such as resolution can also lead to this issue. I suspect that the GPU driver may not be compatible with Kwin. My GPU is AMD Radeon 680M.
