### ISSUE TITLE
sddm + wayland

### ISSUE THREAD

**Issue by slynobody** [sddm/sddm#1675]
In extension to #1628 – you did not answer the security-related questions there – to be more specific, one open question is:

(1) start a sddm-wayland-session (according to https://invent.kde.org/plasma/plasma-workspace/-/tree/master/sddm-wayland-session)
(2) you are aware that solution in accordance to (1) has opportunties to simply start other apps there (f.e. spectacle, f.e. to make screenshots of the password-field, the results of pressing alt-tab should trigger each ones interest), are you?!?
(3) should i do a noob-step-by-step-guide here to explicate this further (or even give further ideas what you can do in such a scenario?)? do you have any plans to deal with it?

**Comment by marcdeop** [comment]
What's the purpose of this ticket?

1 - very nice link so... what?
2 - that has been fixed (also additional patch for [kwin](https://invent.kde.org/plasma/kwin/-/commit/779005f1d2a1035aa4f711a748852f69ca61fc12)
3 - guide for what? you haven't said anything

**Comment by slynobody** [comment]
got it. please delete.

**Comment by marcdeop** [comment]
> got it. please delete.

Feel free to close the issue :-)
