### ISSUE TITLE
sddm get stucked at "Logind interface found"

### ISSUE THREAD

**Issue by Fmajor** [sddm/sddm#1698]
I make a new install for Gentoo, with kernel: 6.1.21-gentoo-x86_64
after reboot, the screen is on tty and X does not start
`systemctl status sddm` gives 
```
Apr 01 23:43:23 hostname sddm[3111]: Initializing...
Apr 01 23:43:23 hostname sddm[3111]: Starting...
Apr 01 23:43:23 hostname sddm[3111]: Logind interface found
```
There is no `/var/log/Xorg.0.log`, the X never try to start. I can start it with `startx` without problem

I have try to solve the `system entropy problem`(#1036) by setting `RANDOM_TRUST_CPU=y`, but with no luck

`sddm --test-mode` will exit will error `[1]    15646 IOT instruction (core dumped)  sddm --test-mode`, and with log
```
[00:02:03.728] (II) DAEMON: Initializing...
[00:02:03.736] (II) DAEMON: Starting...
[00:02:03.736] (II) DAEMON: Adding new display on vt 1 ...
[00:02:03.736] (II) DAEMON: Loading theme configuration from ""
[00:02:03.736] (II) DAEMON: Display server starting...
[00:02:03.736] (II) DAEMON: Adding cookie to "./{1ceaxxxx-xxxx-xxxx-xxxx-xxxx5a6f850d}"
[00:02:03.740] (EE) DAEMON: Failed to start display server process.
[00:02:03.740] (EE) DAEMON: Display server failed to start. Exiting
```

What's the reason that sddm get stucked at `Logind interface found`?

**Comment by Vogtinator** [comment]
What's the value of `CanGraphical` printed by `qdbus(-qt5) --system org.freedesktop.login1 /org/freedesktop/login1/seat/seat0 org.freedesktop.DBus.Properties.GetAll org.freedesktop.login1.Seat`?

**Comment by Fmajor** [comment]
```
$ qdbus --system org.freedesktop.login1 /org/freedesktop/login1/seat/seat0 org.freedesktop.DBus.Properties.GetAll org.freedesktop.login1.Seat                                           23-04-02 7:12:29
ActiveSession: qdbus: I don't know how to display an argument of type '(so)', run with --literal.
CanGraphical: false
CanTTY: true
Id: seat0
IdleHint: true
IdleSinceHint: 1680363864603342
IdleSinceHintMonotonic: 191394365
Sessions: qdbus: I don't know how to display an argument of type 'a(so)', run with --literal.

$ qdbus --literal --system org.freedesktop.login1 /org/freedesktop/login1/seat/seat0 org.freedesktop.DBus.Properties.GetAll org.freedesktop.login1.Seat                                 23-04-02 7:35:52
[Argument: a{sv} {"Id" = [Variant(QString): "seat0"], "ActiveSession" = [Variant: [Argument: (so) "", [ObjectPath: /]]], "CanTTY" = [Variant(bool): true], "CanGraphical" = [Variant(bool): false], "Sessions" = [Variant: [Argument: a(so) {[Argument: (so) "3", [ObjectPath: /org/freedesktop/login1/session/_33]]}]], "IdleHint" = [Variant(bool): true], "IdleSinceHint" = [Variant(qulonglong): 1680363864603342], "IdleSinceHintMonotonic" = [Variant(qulonglong): 191394365]}]
```

**Comment by Vogtinator** [comment]
> CanGraphical: false

So systemd doesn't see a graphics card, but sddm requires that to even attempt to start an Xserver.

That needs to be fixed in the system, either by adding udev rules or working around that some other way.

**Comment by Fmajor** [comment]
Problem solved by adding the right video modules in the kernel config
I use the ASPEED Graphics Family (BMC chip in Supermicro motherboard), then we should add `CONFIG_DRM_AST` into kernel config
