### ISSUE TITLE
sddm-wayland: Low quality graphics on login screen

### ISSUE THREAD

**Issue by agurenko** [sddm/sddm#1702]
After upgrade this morning in Fedora 38, that brought following changes:
```
Installing dependencies:
 sddm-wayland-plasma                        noarch          5.27.4.1-1.fc38           @commandline           16 k
     replacing  sddm-x11.noarch 0.19.0^git20230320.e07e805-2.fc38
```

The login screen now looks like this:
![2023-04-05 11-49-27](https://user-images.githubusercontent.com/6168150/230054411-5ddd721a-4bb1-4984-ae8f-a7cacd13f37c.jpeg)
Instead of this:
![2023-04-05 11-49-58](https://user-images.githubusercontent.com/6168150/230054449-05866a3c-0ae3-4b7d-b3b6-e4f23117421d.jpeg)

The theme is Breeze

**Comment by Vogtinator** [comment]
That's #1441, fixed in e6524335 already. Please reopen if it still occurs with a recent version.
