### ISSUE TITLE
How to auto run a script as root after login 

### ISSUE THREAD

**Issue by xux1217** [sddm/sddm#1705]
Hi,

  I am using the laptop-mode-tools to manage my laptop power, and in that docs, the dpms_standby of it have some issues when new X logon, can be fixed by configuring the display manager to run some shell scripts as root.

  In GDM, I can use the /etc/gdm/PostLogin to run these scripts as root.

  But in sddm, I try to use the /usr/share/sddm/scripts/Xsetup, but looks like it is executed before the login screen. And try to use the /usr/share/sddm/script/Xsession, but it is executed as user, not root, so have not enough privileges.

  I just want to execute `( sleep 60 ; /usr/sbin/laptop_mode force ) &` after user login successful, can anyone has some ideas by this?

**Comment by Vogtinator** [comment]
If you use systemd, you could create a custom unit which is required by `user@.service`.

**Comment by xux1217** [comment]
> If you use systemd, you could create a custom unit which is required by `user@.service`.

Can you please write a simple example? 
I don't know how to config the `installed` section.

I need execute these commands as root after every user login by SDDM. 
Include an user logout and then login again.

**Comment by Vogtinator** [comment]
The laptop-mode.conf man page says:

> CONTROL_DPMS_STANDBY
> When this option is enabled, laptop mode will control the DPMS standby timeout for all X displays on the machine that users have logged on to. In short, this allows laptop mode to control the time after which your screen is blanked.
> There is one limitation to this feature: the settings are not automatically applied to new X logons. This can be fixed by configuring the display manager. For the gdm display manager, configure a PostLogin directory [...]

That means this command probably needs access to the X11 display to do its stuff. However, that also means it does not need root.

**Comment by xux1217** [comment]
> The laptop-mode.conf man page says:
> 
> > CONTROL_DPMS_STANDBY
> > When this option is enabled, laptop mode will control the DPMS standby timeout for all X displays on the machine that users have logged on to. In short, this allows laptop mode to control the time after which your screen is blanked.
> > There is one limitation to this feature: the settings are not automatically applied to new X logons. This can be fixed by configuring the display manager. For the gdm display manager, configure a PostLogin directory [...]
> 
> That means this command probably needs access to the X11 display to do its stuff. However, that also means it does not need root.

but the `laptop_mode` require the root permission.

**Comment by xux1217** [comment]
I find a solution.

I use the systemd_path service to monitor the $HOME/.Xauthority file, when it has modified, call some commands.
