### ISSUE TITLE
SDDM never launches

### ISSUE THREAD

**Issue by User8395** [sddm/sddm#1712]
Basically the title. If SDDM is installed, the system will hang at a blinking cursor unless I reboot it manually.

The only way I can then remove SDDM is by booting into a LiveCD, chrooting into my OS, and removing it from there.

**Comment by Fulgurance** [comment]
I have the same problem. I am actually testing my software I am coding (a new package manager, it build everything from scratch), and my generated system under virtualbox can start plasma without sddm, but when I try to start sddm, nothing.

I installed the 0.19.0 version of SDDM.
I use Openrc as init system

**Comment by User8395** [comment]
So I reinstalled SDDM a bunch of times and then it fixed itself....somehow.

I'll still leave this issue open in case other people are having this problem.

**Comment by Vogtinator** [comment]
We definitely need some logs to provide any suggestions here.

**Comment by Sohail-XD** [comment]
It actually turns out there's a python 3.11 update, that broke this.
yay -S --rebuild --noconfirm $(yay -Qqo /usr/lib/python3.10/) fixed it for me.

**Comment by User8395** [comment]
@Vogtinator can I close this?

**Comment by Vogtinator** [comment]
Without any logs or other info from the ones still affected by this, there's no use in having it open.
