### ISSUE TITLE
race condition on sddm

### ISSUE THREAD

**Issue by rlarrosa1** [sddm/sddm#1713]
Hello,

After the last update of opensuse 15.4, sddm has stopped starting automatically with the error in the journalctl "could not start Display server on vt 7". 
All worked fine on opensuse 15.4 before the update.

Before the error, journalctl shows:

Adding new display on vt 7 ...
Loading theme configuration from ""
Display server starting...
Running: /usr/bin/X -nolisten tcp -auth /run/sddm/{dc1a0>

And three seconds latter:

sddm[1757]: Failed to read display number from pipe
sddm[1757]: Could not start Display server on vt 7

Doing:
systemctl restart display-manager.service

Worked fine, so it seems a race condition.

To solve it I have modified:
/usr/lib/X11/display-manager

To do:
        startproc -p $PIDFILE $DISPLAYMANAGER $XDMOPTIONS || rc_failed
        sleep 5
        killall sddm
        startproc -p $PIDFILE $DISPLAYMANAGER $XDMOPTIONS || rc_failed

And it works fine again.
It seems that X finishes after about 4 seconds.
Between one X and the other several nvidia modules are loaded, it seems to me that those must be loaded before X, but it is only my opinion. Perhaps another solution is loading the modules before starting X.

It seems to me that this is related to :
https://github.com/sddm/sddm/issues/1316

There someone said:

For me reverting https://github.com/sddm/sddm/commit/74394fd1cff26b0516af87539906a31bf2f49825 fixed it.

Thanks,

Rafael

**Comment by Vogtinator** [comment]
Yes, this sounds exactly like https://github.com/sddm/sddm/issues/1316.

Can you open a bug report downstream to get the fix applied?

I'll close this as a duplicate.
