### ISSUE TITLE
SDDM does not respect Numlock=on in Fedora 38

### ISSUE THREAD

**Issue by chandradeepdey** [sddm/sddm#1717]
Version e6524335a54ca469401ee9487adc4ae973860aad ([sddm-0.19.0^git20230404.e652433-1.fc38](https://koji.fedoraproject.org/koji/search?terms=sddm-0.19.0^git20230404.e652433-1.fc38&type=build&match=exact))
Wayland with KWin

**Comment by arenekosreal** [comment]
This also exists on AUR package [`sddm-git`](https://aur.archlinux.org/packages/sddm-git) on ArchLinux, the version is `0.19.0.218.g58a3517-1`

**Comment by CoelacanthusHex** [comment]
Arch Linux with sddm-git 0.19.0.218.g58a3517-1, with wayland and default weston.

**Comment by polnyjj** [comment]
Debian 12, KDE Wayland has also same problem. Numlock=on seems work but I need to click password bar everytime to write.

**Comment by Gigas002** [comment]
Still an issue on 0.20.0 release

**Comment by mateushonorato** [comment]
also happening to me in Nobara Linux 38

**Comment by REALERvolker1** [comment]
yep. I am using `sddm-wayland-generic.noarch` from the Fedora 38 repos, and num lock is not enabled on startup even after I turn it on in `/etc/sddm.conf`. `sddm-wayland-sway.noarch` won't even start for me but that is most likely not related to this issue, it's just relevant to mention that I have not been able to test num-lock on other sddm wayland backends.

**Comment by leodip** [comment]
Same issue here. Fedora 39 with KDE Plasma 5.27.8, Wayland.

**Comment by xofe** [comment]
I was having the same issue with SDDM 0.20 - for the Wayland mode, the “Numlock=on” option in “sddm.conf” had no effect.

I managed to get num lock working [using KWin‘s configuration](https://invent.kde.org/plasma/kwin/-/blob/Plasma/5.27/src/xkb.cpp#L330-L337) instead, by creating a file “.config/kcminputrc” in the SDDM home dir (“/var/lib/sddm”) with the content:
```
[Keyboard]
NumLock=0
```

**Comment by leodip** [comment]
@xofe  - thanks, I already have that.

It will activate numlock after login. But not in the login screen. I'm looking for a solution to the login screen numlock. Apparently there's no way to activate it. My BIOS already has numlock on (on boot), but when it gets to the login screen, it turns off.

**Comment by xofe** [comment]
@leodip Hmm, it works for me in the login screen, as long as KWin is set as the compositor (iirc, the default is Weston)

**Comment by chandradeepdey** [comment]
> I was having the same issue with SDDM 0.20 - for the Wayland mode, the “Numlock=on” option in “sddm.conf” had no effect.
> 
> I managed to get num lock working [using KWin‘s configuration](https://invent.kde.org/plasma/kwin/-/blob/Plasma/5.27/src/xkb.cpp#L330-L337) instead, by creating a file “.config/kcminputrc” in the SDDM home dir (“/var/lib/sddm”) with the content:
> 
> ```
> [Keyboard]
> NumLock=0
> ```

@xofe Thanks, this works for me as well. Should be fixed if [this](https://invent.kde.org/plasma/sddm-kcm/-/merge_requests/61) gets merged.

**Comment by chandradeepdey** [comment]
@Pointedstick could you check the MR please?

**Comment by chandradeepdey** [comment]
Thanks for merging so quickly @Pointedstick.

@leodip I would recommend you open a separate issue if this is not what you were experiencing. By the way, make sure you have the `NumLock` configuration in `/var/lib/sddm/.config/kcminputrc`, as @xofe said, and not just your home directory.

Same for the Weston people here. Please open a separate issue, since your fix will most definitely be different.  I am closing this one.

**Comment by leodip** [comment]
@chandradeepdey   thanks , I have opened a new issue : https://github.com/sddm/sddm/issues/1825

**Comment by REALERvolker1** [comment]
Why was this issue closed? This does not fix the bug.

**Comment by Everest10** [comment]
SDDM does not respect Numlock=on in Fedora 38, 39 and 40.
Several attempts to fix failed.

**Comment by Everest10** [comment]
> This also exists on AUR package [`sddm-git`](https://aur.archlinux.org/packages/sddm-git) on ArchLinux, the version is `0.19.0.218.g58a3517-1`

AUR ?? There is 50+ Linux distros. I use fedora.

**Comment by ezhan** [comment]
Fedora 40. SDDM does not respects the NumLock On settings in KDE.

**Comment by ghost** [comment]
Not sure why this is closed yet again when it is still an issue. Stop closing it until it is solved.

**Comment by ezhan** [comment]
Here is a bug for KDE and a solution, I have found how to enable NumLock:
https://bugs.kde.org/show_bug.cgi?id=487638

**Comment by coltEli** [comment]
Try holding alt key while typing first number, next numbers will type normally. Worked for me on debian 12  kde. From here: https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/2018203
