### ISSUE TITLE
Switch back x11 per default for launching plasma

### ISSUE THREAD

**Issue by TheIDarKIKnight** [sddm/sddm#1721]
Hi,

I've worked on a problem to put back x11 per default on the sddm-greater.

OS: AlmaLinux 8.8

I don't use autologin nor remember the last user connected so i didn't have the choice but to find sddm - state.conf which is poorly explained in the man for the moment.
And surprise this file is wipe out every time i start the machine physical or virtual alike so i made a script in the init.d to put it back
The state.conf file isn't created per default, is location is there -> /usr/share/xsessions/plasma.desktop
and it should look like this for exemple:

> [Last]
> Session=/usr/share/xsessions/plasma.desktop
> [User]
> Username=johndoe

For those who need this temporary fix here it is:

/etc/init.d/x11
`sed -i 's/Session=/Session\/usr\/share\/xsessions\/plasma.desktop/g`

I'm sorry if this issue has already been discuss but i didn't find it.

**Comment by a17r** [comment]
Downstream modification, not an upstream issue.

https://src.fedoraproject.org/rpms/plasma-workspace/blob/rawhide/f/plasma-workspace.spec#_505
