### ISSUE TITLE
SDDM shows other keyboard layouts but only uses us

### ISSUE THREAD

**Issue by Samuele1131** [sddm/sddm#1727]
I am pretty new to all this stuff. I installed Arch Linux with SDDM and KDE running under XWayland.

When I boot up, the greeter shows me different keyboard layouts, and though I'm unable to see them all (as the listbox doesn't scroll down for some reason), I can choose the one I want.

However, is that no matter which layout I pick, when I type my password it always uses the us layout, even though it shows another one.

I tried setting both X11 and Wayland to use the layout I want, and I followed the ArchWiki as best I could, but I haven't been able to solve this issue. Everything else, from the terminal to the actual desktop environment after login, works correctly.
What should I do?

**Comment by Vogtinator** [comment]
Anything in the journal?

**Comment by Vogtinator** [comment]
> SDDM and KDE running under XWayland.

That's not a thing. Do you use SDDM with wayland enabled?

**Comment by Samuele1131** [comment]
> > SDDM and KDE running under XWayland.
> 
> That's not a thing. Do you use SDDM with wayland enabled?

I think so? I run SDDM and start a  "Plasma (Wayland)" session

**Comment by Samuele1131** [comment]
> Anything in the journal?

I'm afraid I don't know what that is

**Comment by Vogtinator** [comment]
> > > SDDM and KDE running under XWayland.
> > 
> > 
> > That's not a thing. Do you use SDDM with wayland enabled?
> 
> I think so? I run SDDM and start a "Plasma (Wayland)" session

Unless you configured sddm manually, that still uses Xorg.



> > Anything in the journal?
> 
> I'm afraid I don't know what that is

Run `sudo journalctl -b` and look for messages from SDDM

**Comment by Samuele1131** [comment]
> > > > SDDM and KDE running under XWayland.
> > > 
> > > 
> > > That's not a thing. Do you use SDDM with wayland enabled?
> > 
> > 
> > I think so? I run SDDM and start a "Plasma (Wayland)" session
> 
> Unless you configured sddm manually, that still uses Xorg.
> 
> > > Anything in the journal?
> > 
> > 
> > I'm afraid I don't know what that is
> 
> Run `sudo journalctl -b` and look for messages from SDDM

I couldn't make much of what was in the journal, but here is what I found.

There are a bunch of files that SDDM could not open; mostly pngs, but there are two unrecognized keysyms.

Also, there are some messages saying there are malformed entries in different files (`/usr/share/wayland-sessions/plasmawayland.desktop` and `/usr/share/xsessions/plasma.desktop` are two examples), but in the end it looks like the session is opened correctly.

I placed a file with this in my `/etc/sddm.conf.d` directory to have SDDM start a Wayland session, or at least that was its purpose:

```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland
```

**Comment by Vogtinator** [comment]
> I placed a file with this in my /etc/sddm.conf.d directory to have SDDM start a Wayland session, or at least that was its purpose:

That's actually the manual config to make SDDM use wayland. This particular config you're using is invalid: It is missing important options, one of which is necessary for security and another which provides the keyboard layout option.

I highly recommend to delete that file and use whatever your distro provides instead. Currently the login screen can be completely bypassed if you keep using this.
