### ISSUE TITLE
sddm: Malformed entry in "/usr/share/xsessions/enlightenment.desktop" : ""

### ISSUE THREAD

**Issue by dania83** [sddm/sddm#1729]
I have found a lot off these errors in the journalctl 
juin 08 16:13:50 grat-os1 sddm[490]: Malformed entry in "/usr/share/wayland-sessions/enlightenment.desktop" : ""
juin 08 16:25:17 grat-os1 sddm-greeter[1751]: Malformed entry in "/usr/share/wayland-sessions/enlightenment.desktop" : ""
juin 08 16:25:17 grat-os1 sddm-greeter[1751]: Malformed entry in "/usr/share/xsessions/enlightenment.desktop" : ""
juin 08 16:25:28 grat-os1 sddm-greeter[1751]: Malformed entry in "/usr/share/xsessions/enlightenment.desktop" : ""
juin 08 16:25:28 grat-os1 sddm[490]: Malformed entry in "/usr/share/xsessions/enlightenment.desktop" : ""

the two desktop files are
antoine@grat-os1:/usr/share/xsessions$ cat enlightenment.desktop
[Desktop Entry]
Type=XSession
Name=Enlightenment
Name[ca]=Enlightenment
Name[de]=Enlightenment
Name[el]=Enlightenment
Name[eo]=Enlightenment
Name[fi]=Enlightenment
Name[fr]=Enlightenment
Name[gl]=Enlightenment
Name[ja]=Enlightenment
Name[ko]=Enlightenment
Name[ms]=Enlightenment
Name[pl]=Enlightenment
Name[ru]=Enlightenment
Name[sr]=Просвећење
Name[tr]=Enlightenment
Comment=Log in using Enlightenment (Version 0.25.99.1)
Comment[ca]=Iniciar sessió amb Enlightenment (Versió 0.25.99.1)
Comment[da]=Log ind med Enlightenment (Version 0.25.99.1)
Comment[de]=Anmelden und Enlightenment verwenden (Version 0.25.99.1)
Comment[el]=Είσοδος με το Enlightenment (Έκδοση 0.25.99.1)
Comment[eo]=Ensaluti pere de Enlightenment (Versio 0.25.99.1)
Comment[es]=Iniciar sesión usando Enlightenment (Versión 0.25.99.1)
Comment[fi]=Kirjaudu käyttäen Enlightenmentiä (versio 0.25.99.1)
Comment[fr]=Ouvrir une session Enlightenment (Version 0.25.99.1)
Comment[gl]=Iniciar sesión usando Enlightenment (Versión 0.25.99.1)
Comment[it]=Accedi con Enlightenment (Versione 0.25.99.1)
Comment[ko]=Enlightenment 로그인(버전 0.25.99.1)
Comment[ms]=Daftar masuk menggunakan Enligtenment (Versi 0.25.99.1)
Comment[pt]=Iniciar sessão no Enlightenment (Versão 0.25.99.1)
Comment[ru]=Войти используя Enlightenment (Версия 0.25.99.1)
Comment[sr]=Пријавите се за коришћење Просвећења (издања 0.25.99.1)
Comment[tr]=Enlightenment kullanarak giriş yaın (Version 0.25.99.1)
Icon=/usr/share/enlightenment/data/images/enlightenment.png
TryExec=/usr/bin/enlightenment_start
Exec=/usr/bin/enlightenment_start
DesktopNames=Enlightenment

antoine@grat-os1:/usr/share/wayland-sessions$ cat enlightenment.desktop
[Desktop Entry]
Type=Application
Name=Enlightenment (Wayland)
Name[ca]=Enlightenment (Wayland)
Name[de]=Enlightenment (Wayland)
Name[el]=Enlightenment (Wayland)
Name[eo]=Enlightenment (Wayland)
Name[fi]=Enlightenment (Wayland)
Name[fr]=Enlightenment (Wayland)
Name[gl]=Enlightenment (Wayland)
Name[ja]=Enlightenment (Wayland)
Name[ko]=Enlightenment (Wayland)
Name[ms]=Enlightenment (Wayland)
Name[pl]=Enlightenment (Wayland)
Name[ru]=Enlightenment (Wayland)
Name[sr]=Просвећење (Wayland)
Name[tr]=Enlightenment (Wayland)
Comment=Log in using Enlightenment (Version 0.25.99.1)
Comment[ca]=Iniciar sessió amb Enlightenment (Versió 0.25.99.1)
Comment[da]=Log ind med Enlightenment (Version 0.25.99.1)
Comment[de]=Anmelden und Enlightenment verwenden (Version 0.25.99.1)
Comment[el]=Είσοδος με το Enlightenment (Έκδοση 0.25.99.1)
Comment[eo]=Ensaluti pere de Enlightenment (Versio 0.25.99.1)
Comment[es]=Iniciar sesión usando Enlightenment (Versión 0.25.99.1)
Comment[fi]=Kirjaudu käyttäen Enlightenmentiä (versio 0.25.99.1)
Comment[fr]=Ouvrir une session Enlightenment (Version 0.25.99.1)
Comment[gl]=Iniciar sesión usando Enlightenment (Versión 0.25.99.1)
Comment[it]=Accedi con Enlightenment (Versione 0.25.99.1)
Comment[ko]=Enlightenment 로그인(버전 0.25.99.1)
Comment[ms]=Daftar masuk menggunakan Enligtenment (Versi 0.25.99.1)
Comment[pt]=Iniciar sessão no Enlightenment (Versão 0.25.99.1)
Comment[ru]=Войти используя Enlightenment (Версия 0.25.99.1)
Comment[sr]=Пријавите се за коришћење Просвећења (издања 0.25.99.1)
Comment[tr]=Enlightenment kullanarak giriş yaın (Version 0.25.99.1)
Icon=/usr/share/enlightenment/data/images/enlightenment.png
TryExec=/usr/bin/enlightenment_start
Exec=env E_WL_FORCE=drm E_COMP_ENGINE=gl /usr/bin/enlightenment_start
DesktopNames=Enlightenment

is it sddm that detects something wrong in the two files ?
I am not sure about the Type=XSession in /usr/share/xsessions/enlightenment.desktop and the command DesktopNames=Enlightenment on both files. The error seems to be a "" somewhere.

Best regards 

Daniel

**Comment by Vogtinator** [comment]
Fixed with https://github.com/sddm/sddm/pull/1731
