### ISSUE TITLE
"Qt shall use a UTF-8 locale" sddm compilation problem with qt6

### ISSUE THREAD

**Issue by dania83** [sddm/sddm#1755]
when I compile sddm with QT6 enable I get a lot of "Qt shall use a UTF-8 locale" warnings in the log. I compile in a chroot environnment, this sems not cause problem. There is no warning when sddm is compiled with QT5.
Is it related to QT6 or there is some change on sddm for the compilation with QT6.

Best regards 

Danie

HEAD is now at 07631f2 Ignore InputMethod=qtvirtualkeyboard on wayland
+ build
+ mkdir build
+ cd build
+ cmake ../sddm-0.20.0 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib/sddm -DDBUS_CONFIG_DIR=/usr/share/dbus-1/system.d -DDBUS_CONFIG_FILENAME=sddm_org.freedesktop.DisplayManager.conf -DBUILD_MAN_PAGES=ON -DBUILD_WITH_QT6=ON -DUID_MAX=60513
-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Release build
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Performing Test PAM_MESSAGE_CONST
-- Performing Test PAM_MESSAGE_CONST - Success
-- Found PAM: /usr/lib/libpam.so;/usr/lib/libdl.a
-- Checking for module 'xau'
--   Found xau, version 1.0.11
-- Checking for module 'xcb'
--   Found xcb, version 1.15
-- Found XCB: /usr/lib/libxcb.so
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.15
-- Found XKB: /usr/lib/libxcb-xkb.so
-- Building Qt 6 version
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found WrapVulkanHeaders: /usr/include
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
-- Checking for module 'systemd'
--   Found systemd, version 253
-- Checking for module 'libsystemd'
--   Found libsystemd, version 253
-- Autodetected UID_MIN=1000 from /etc/login.defs
-- The following features have been enabled:

 * systemd, systemd support
 * journald, journald support

-- The following OPTIONAL packages have been found:

 * Qt6CoreTools (required version >= 6.4.3)
 * Qt6Core (required version >= 5.15.0)
 * Qt6DBusTools (required version >= 6.4.3)
 * Qt6DBus (required version >= 5.15.0)
 * OpenGL
 * PkgConfig
 * Qt6GuiTools (required version >= 6.4.3)
 * Qt6Gui (required version >= 5.15.0)
 * Qt6QmlTools (required version >= 6.4.3)
 * Qt6Qml (required version >= 5.15.0)
 * WrapVulkanHeaders
 * Qt6Quick (required version >= 5.15.0)
 * Qt6LinguistTools (required version >= 5.15.0)
 * Qt6Test (required version >= 5.15.0)
 * Qt6QuickTest (required version >= 5.15.0)

-- The following REQUIRED packages have been found:

 * ECM (required version >= 1.4.0)
 * PAM
 * XCB
 * XKB (required version >= 0.5.0)
 * Qt6 (required version >= 5.15.0)

-- The following features have been disabled:

 * elogind, elogind support

-- Configuring done (1.1s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/work/src/build
+ make
[  0%] Generating sddm.1
[  1%] Generating sddm.conf.5
[  1%] Generating sddm-greeter.1
[  2%] Generating sddm-state.conf.5
[  2%] Built target man_sddm-state.conf.rst
[  2%] Built target man_sddm-greeter.rst
[  2%] Built target man_sddm.rst
[  3%] Automatic MOC for target sddm
[  3%] Built target man_sddm.conf.rst
[  3%] Generating ar.qm
[  3%] Built target themes-translation
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/ar.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[  4%] Automatic MOC for target sddm-helper
[  5%] Generating bn.qm
[  6%] Automatic MOC for target sddm-helper-start-wayland
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/bn.qm'...
    Generated 15 translation(s) (15 finished and 0 unfinished)
[  7%] Generating ca.qm
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/ca.qm'...
    Generated 15 translation(s) (15 finished and 0 unfinished)
[  7%] Generating cs.qm
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/cs.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[  8%] Generating da.qm
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/da.qm'...
    Generated 26 translation(s) (26 finished and 0 unfinished)
[  8%] Generating de.qm
Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
Updating '/tmp/work/src/build/data/translations/de.qm'...
    Generated 26 translation(s) (26 finished and 0 unfinished)
[  9%] Generating es.qm

When compiled with QT5

HEAD is now at 07631f2 Ignore InputMethod=qtvirtualkeyboard on wayland
+ build
+ mkdir build
+ cd build
+ cmake ../sddm-0.20.0 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib/sddm -DDBUS_CONFIG_DIR=/usr/share/dbus-1/system.d -DDBUS_CONFIG_FILENAME=sddm_org.freedesktop.DisplayManager.conf -DBUILD_MAN_PAGES=ON -DUID_MAX=60513
-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Release build
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Performing Test PAM_MESSAGE_CONST
-- Performing Test PAM_MESSAGE_CONST - Success
-- Found PAM: /usr/lib/libpam.so;/usr/lib/libdl.a
-- Checking for module 'xau'
--   Found xau, version 1.0.11
-- Checking for module 'xcb'
--   Found xcb, version 1.15
-- Found XCB: /usr/lib/libxcb.so
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.15
-- Found XKB: /usr/lib/libxcb-xkb.so
-- Building Qt 5 version
-- Checking for module 'systemd'
--   Found systemd, version 253
-- Checking for module 'libsystemd'
--   Found libsystemd, version 253
-- Autodetected UID_MIN=1000 from /etc/login.defs
-- The following features have been enabled:

 * systemd, systemd support
 * journald, journald support

-- The following OPTIONAL packages have been found:

 * PkgConfig

-- The following REQUIRED packages have been found:

 * ECM (required version >= 1.4.0)
 * PAM
 * XCB
 * XKB
 * Qt5Core
 * Qt5DBus
 * Qt5Gui
 * Qt5Network (required version >= 5.15.8)
 * Qt5Qml
 * Qt5QmlModels (required version >= 5.15.8)
 * Qt5Quick
 * Qt5LinguistTools
 * Qt5Test
 * Qt5Widgets (required version >= 5.15.8)
 * Qt5QuickTest
 * Qt5 (required version >= 5.15.0)

-- The following features have been disabled:

 * elogind, elogind support

-- Configuring done (0.9s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/work/src/build
+ make
[  0%] Generating sddm.1
[  1%] Generating sddm-state.conf.5
[  1%] Generating sddm-greeter.1
[  2%] Generating sddm.conf.5
[  2%] Built target man_sddm-state.conf.rst
[  3%] Automatic MOC for target sddm
[  3%] Built target man_sddm.conf.rst
[  3%] Built target man_sddm-greeter.rst
[  3%] Built target man_sddm.rst
[  3%] Generating ar.qm
Updating '/tmp/work/src/build/data/translations/ar.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[  3%] Built target themes-translation
[  4%] Automatic MOC for target sddm-helper
[  5%] Generating bn.qm
[  6%] Generating ca.qm
Updating '/tmp/work/src/build/data/translations/bn.qm'...
    Generated 15 translation(s) (15 finished and 0 unfinished)
Updating '/tmp/work/src/build/data/translations/ca.qm'...
    Generated 15 translation(s) (15 finished and 0 unfinished)
[  6%] Generating cs.qm
Updating '/tmp/work/src/build/data/translations/cs.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[  7%] Automatic MOC for target sddm-helper-start-wayland
[  8%] Generating da.qm
Updating '/tmp/work/src/build/data/translations/da.qm'...
    Generated 26 translation(s) (26 finished and 0 unfinished)
[  8%] Generating de.qm
Updating '/tmp/work/src/build/data/translations/de.qm'...
    Generated 26 translation(s) (26 finished and 0 unfinished)
[  9%] Generating es.qm
Updating '/tmp/work/src/build/data/translations/es.qm'...
    Generated 13 translation(s) (13 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[ 10%] Generating et.qm
Updating '/tmp/work/src/build/data/translations/et.qm'...
    Generated 15 translation(s) (15 finished and 0 unfinished)
[ 10%] Generating eu.qm

**Comment by Vogtinator** [comment]
This is because your build environment does not set a UTF-8 locale.

**Comment by dania83** [comment]
QT6 ask for UTF-8 not QT5  We have the same messages when we compile QT6 packages so I close this post

Best regards

Daniel
