### ISSUE TITLE
Should the PAM's default environment override the GreeterEnvironment option?

### ISSUE THREAD

**Issue by ilya-fedin** [sddm/sddm#1758]
pam_putEnv doesn't override PAM's environment loaded with pam_env.so so [this](https://github.com/sddm/sddm/blob/07631f2ef00a52d883d0fd47ff7d1e1a6bc6358f/src/daemon/Greeter.cpp#L183-L191) and [this](https://github.com/sddm/sddm/blob/07631f2ef00a52d883d0fd47ff7d1e1a6bc6358f/src/helper/HelperApp.cpp#L170-L181) gets overriden thanks to [this](https://github.com/sddm/sddm/blob/07631f2ef00a52d883d0fd47ff7d1e1a6bc6358f/src/helper/backend/PamBackend.cpp#L276). Is all that intended or should the imported environment variables from sddm process and/or GreeterEnvironment options take the precedence?

**Comment by Vogtinator** [comment]
Did you hit this in a specific scenario where it caused an issue?

It should be unlikely that there's a conflict for those specific variables that would lead to issues.

**Comment by ilya-fedin** [comment]
Yeah, NixOS has both XDG_DATA_DIRS and QT_PLUGIN_PATH in PAM environment. The right XDG_DATA_DIRS is in the PAM environment (systemd services don't have this variable set but the binary wrapper sets it to the package's closure what is not enough for icon and etc, PAM has profile dirs set for sessions that merge a lot of packages installed), the right QT_PLUGIN_PATH (with the path to layer-shell) is passed through GreeterEnvironment (as it's specific to config).

**Comment by ilya-fedin** [comment]
```
...
QT_PLUGIN_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/qt4/plugins:@{HOME}/.local/share/flatpak/exports/lib/kde4/plugins:/var/lib/flatpak/exports/lib/qt4/plugins:/var/lib/flatpak/exports/lib/kde4/plugins:@{HOME}/.nix-profile/lib/qt4/plugins:@{HOME}/.nix-profile/lib/kde4/plugins:/etc/profiles/per-user/@{PAM_USER}/lib/qt4/plugins:/etc/profiles/per-user/@{PAM_USER}/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins"
...
XDG_DATA_DIRS   DEFAULT="/nix/store/b7dczyw4m2hmlvsy92zp77psj22cv2n7-desktops/share:@{HOME}/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:@{HOME}/.nix-profile/share:/etc/profiles/per-user/@{PAM_USER}/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share"
...
```

**Comment by Vogtinator** [comment]
Hm, so the sddm service has different `$QT_PLUGIN_PATH` than sessions started by it? That's a strange setup.

The greeter uses a separate PAM config anyway, maybe `pam_env` should just be skipped there.

**Comment by ilya-fedin** [comment]
> Hm, so the sddm service has different `$QT_PLUGIN_PATH` than sessions started by it? That's a strange setup.

NixOS aims to be a pure distro, so every package has its own prefix and only required packages are specified in QT_PLUGIN_PATH for every package. In other words, literally each process has a different QT_PLUGIN_PATH.

> The greeter uses a separate PAM config anyway, maybe `pam_env` should just be skipped there.

It wouldn't have other variables then?

**Comment by Vogtinator** [comment]
> > Hm, so the sddm service has different `$QT_PLUGIN_PATH` than sessions started by it? That's a strange setup.
> 
> NixOS aims to be a pure distro, so every package has its own prefix and only required packages are specified in QT_PLUGIN_PATH for every package. In other words, literally each process has a different QT_PLUGIN_PATH.

What happens if a user opens a terminal and starts `sddm-greeter`?

> > The greeter uses a separate PAM config anyway, maybe `pam_env` should just be skipped there.
> 
> It wouldn't have other variables then?

Yeah, but it inherits from sddm itself, which might be enough. Might break certain setups though :-/

**Comment by ilya-fedin** [comment]
> Yeah, but it inherits from sddm itself, which might be enough. Might break certain setups though :-/

I don't think that's true. sddm passes only a hardcoded list of variables to the greeter and even if this wasn't the case, sddm itself doesn't have a PAM session and so doesn't have all those variables passed via pam_env. Here's the full content of the pam_env's conffile on my system:
```
CUPS_DATADIR   DEFAULT="/nix/store/j92n6mbrld3hgppy43m9yws2j7cnsj62-cups-progs/share/cups"
CUPS_SERVER   DEFAULT="rpi4"
EDITOR   DEFAULT="micro"
GDK_PIXBUF_MODULE_FILE   DEFAULT="/nix/store/imsms182qq0kmm9n4f3597sz5b72q4gs-gdk-pixbuf-loaders.cache"
GIO_EXTRA_MODULES   DEFAULT="/nix/store/ybx07k8g5kxclizhm3fskkgzv6rb0dwc-gvfs-1.50.4/lib/gio/modules"
GTK_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/gtk-2.0:@{HOME}/.local/share/flatpak/exports/lib/gtk-3.0:@{HOME}/.local/share/flatpak/exports/lib/gtk-4.0:/var/lib/flatpak/exports/lib/gtk-2.0:/var/lib/flatpak/exports/lib/gtk-3.0:/var/lib/flatpak/exports/lib/gtk-4.0:@{HOME}/.nix-profile/lib/gtk-2.0:@{HOME}/.nix-profile/lib/gtk-3.0:@{HOME}/.nix-profile/lib/gtk-4.0:/etc/profiles/per-user/@{PAM_USER}/lib/gtk-2.0:/etc/profiles/per-user/@{PAM_USER}/lib/gtk-3.0:/etc/profiles/per-user/@{PAM_USER}/lib/gtk-4.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/default/lib/gtk-3.0:/nix/var/nix/profiles/default/lib/gtk-4.0:/run/current-system/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0:/run/current-system/sw/lib/gtk-4.0"
GTK_USE_PORTAL   DEFAULT="1"
INFOPATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/info:@{HOME}/.local/share/flatpak/exports/share/info:/var/lib/flatpak/exports/info:/var/lib/flatpak/exports/share/info:@{HOME}/.nix-profile/info:@{HOME}/.nix-profile/share/info:/etc/profiles/per-user/@{PAM_USER}/info:/etc/profiles/per-user/@{PAM_USER}/share/info:/nix/var/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info"
KDEDIRS   DEFAULT="@{HOME}/.local/share/flatpak/exports:/var/lib/flatpak/exports:@{HOME}/.nix-profile:/etc/profiles/per-user/@{PAM_USER}:/nix/var/nix/profiles/default:/run/current-system/sw"
KPACKAGE_DEP_RESOLVERS_PATH   DEFAULT="/nix/store/q180pjbw0kwazcs2aw3l6sqm2lbq82a1-frameworkintegration-5.107.0/libexec/kf5/kpackagehandlers"
LANG   DEFAULT="ru_RU.UTF-8"
LD_LIBRARY_PATH   DEFAULT="/etc/sane-libs"
LIBEXEC_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/libexec:/var/lib/flatpak/exports/lib/libexec:@{HOME}/.nix-profile/lib/libexec:/etc/profiles/per-user/@{PAM_USER}/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec"
LOCALE_ARCHIVE   DEFAULT="/run/current-system/sw/lib/locale/locale-archive"
MOZ_DISABLE_CONTENT_SANDBOX   DEFAULT="1"
MOZ_PLUGIN_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/mozilla/plugins:/var/lib/flatpak/exports/lib/mozilla/plugins:@{HOME}/.nix-profile/lib/mozilla/plugins:/etc/profiles/per-user/@{PAM_USER}/lib/mozilla/plugins:/nix/var/nix/profiles/default/lib/mozilla/plugins:/run/current-system/sw/lib/mozilla/plugins"
NIXPKGS_ALLOW_UNFREE   DEFAULT="1"
NIX_PATH   DEFAULT="nixpkgs=/etc/static/nixpkgs:nixos-config=/etc/nixos/configuration.nix:nixpkgs-overlays=/etc/nixos/overlays-compat"
PATH   DEFAULT="/run/wrappers/bin:@{HOME}/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:@{HOME}/.nix-profile/bin:/etc/profiles/per-user/@{PAM_USER}/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
PLASMA_USE_QT_SCALING   DEFAULT="1"
QTWEBKIT_PLUGIN_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/mozilla/plugins/:/var/lib/flatpak/exports/lib/mozilla/plugins/:@{HOME}/.nix-profile/lib/mozilla/plugins/:/etc/profiles/per-user/@{PAM_USER}/lib/mozilla/plugins/:/nix/var/nix/profiles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/mozilla/plugins/"
QT_PLUGIN_PATH   DEFAULT="@{HOME}/.local/share/flatpak/exports/lib/qt4/plugins:@{HOME}/.local/share/flatpak/exports/lib/kde4/plugins:/var/lib/flatpak/exports/lib/qt4/plugins:/var/lib/flatpak/exports/lib/kde4/plugins:@{HOME}/.nix-profile/lib/qt4/plugins:@{HOME}/.nix-profile/lib/kde4/plugins:/etc/profiles/per-user/@{PAM_USER}/lib/qt4/plugins:/etc/profiles/per-user/@{PAM_USER}/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins"
SANE_CONFIG_DIR   DEFAULT="/etc/sane-config"
SYSTEMD_EDITOR   DEFAULT="micro"
TERMINFO_DIRS   DEFAULT="@{HOME}/.local/share/flatpak/exports/share/terminfo:/var/lib/flatpak/exports/share/terminfo:@{HOME}/.nix-profile/share/terminfo:/etc/profiles/per-user/@{PAM_USER}/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo"
TZDIR   DEFAULT="/etc/zoneinfo"
VISUAL   DEFAULT="micro"
XCURSOR_PATH   DEFAULT="@{HOME}/.icons:@{HOME}/.local/share/icons:@{HOME}/.local/share/flatpak/exports/share/icons:@{HOME}/.local/share/flatpak/exports/share/pixmaps:/var/lib/flatpak/exports/share/icons:/var/lib/flatpak/exports/share/pixmaps:@{HOME}/.nix-profile/share/icons:@{HOME}/.nix-profile/share/pixmaps:/etc/profiles/per-user/@{PAM_USER}/share/icons:/etc/profiles/per-user/@{PAM_USER}/share/pixmaps:/nix/var/nix/profiles/default/share/icons:/nix/var/nix/profiles/default/share/pixmaps:/run/current-system/sw/share/icons:/run/current-system/sw/share/pixmaps"
XDG_CONFIG_DIRS   DEFAULT="@{HOME}/.local/share/flatpak/exports/etc/xdg:/var/lib/flatpak/exports/etc/xdg:@{HOME}/.nix-profile/etc/xdg:/etc/profiles/per-user/@{PAM_USER}/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg"
XDG_DATA_DIRS   DEFAULT="/nix/store/b7dczyw4m2hmlvsy92zp77psj22cv2n7-desktops/share:@{HOME}/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:@{HOME}/.nix-profile/share:/etc/profiles/per-user/@{PAM_USER}/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share"
XDG_DESKTOP_PORTAL_DIR   DEFAULT="/nix/store/l38vgx0971hhlr3nmzm8w8490g84jci8-xdg-portals/share/xdg-desktop-portal/portals"
```

> What happens if a user opens a terminal and starts `sddm-greeter`?

That's what I get:
```
[23:49:23.054] (II) GREETER: High-DPI autoscaling Enabled
[23:49:23.297] (II) GREETER: Reading from "/nix/store/b7dczyw4m2hmlvsy92zp77psj22cv2n7-desktops/share/wayland-sessions/plasmawayland.desktop"
[23:49:23.298] (II) GREETER: Reading from "/nix/store/b7dczyw4m2hmlvsy92zp77psj22cv2n7-desktops/share/xsessions/plasma.desktop"
[23:49:23.298] (II) GREETER: Parsing xkb rules from "/nix/store/r9kk65vf0gjp03l8abv0yzfq34mz9vad-xkeyboard-config-2.33/share/X11/xkb/rules/evdev.xml"
[23:49:23.305] (II) GREETER: Loading theme configuration from "qrc:/theme/theme.conf"
[23:49:23.335] (EE) GREETER: Socket error:  "QLocalSocket::connectToServer: Invalid name"
[23:49:23.336] (EE) GREETER: Cannot connect to the daemon - is it running?
```

**Comment by Vogtinator** [comment]
Ok, that seems like `sddm-greeter` in that setup should just work with the variables set by the session, i.e. without `GreeterEnvironment` at all? To check whether icons etc. also work you can use `sddm-greeter --test-mode --theme (whatever the NixOS equivalent to /usr/share/sddm/themes/breeze is)`

IMO it's also fine to process `GreeterEnvironment` after any `pam_env` handling. I see you already prepared and tested a patch, can you open a PR?

**Comment by ilya-fedin** [comment]
In terms of variables, sddm-greeter won't have access to layer-shell-qt unless the invoker sets QT_PLUGIN_PATH in the combination with the QT_WAYLAND_SHELL_INTEGRATION (just like we want to do with GreeterEnvironment but the PAM logic gets in the way). XDG_DATA_DIRS would be ok as it's running in the session. sddm itself is not though so the PAM's override does a good thing in that case.

**Comment by Vogtinator** [comment]
So the Qt layer-shell plugin is only available to sddm-greeter but not to the session?

**Comment by ilya-fedin** [comment]
To the sddm-greeter via config (as sddm-greeter itself doesn't depend on it, it's a configured dependency by the means of QT_WAYLAND_SHELL_INTEGRATION) and to any other package that actually depends on layer-shell-qt in any environment (as it would be a build input, it will get hardcoded in the binary's wrapper which will always prepend all plugins in the build inputs to already set values in QT_PLUGIN_PATH)

**Comment by Vogtinator** [comment]
Apparently this is what you describe in https://github.com/NixOS/nixpkgs/pull/242009#issuecomment-1627391225, i.e. a flaw of the current design?

IMO that should be fixed on the NixOS side, but if it makes it easier then the way of changing the env var precedence should be fine too.

**Comment by ilya-fedin** [comment]
That's just my opinion and it's also seen that the other people in the community disagree with that. NixOS seem to prefer purity (every package gets access only to what it really needs) over global values...

**Comment by Vogtinator** [comment]
Very strange design, as plugins like this are meant to be generally available to all applications that can make use of it.

**Comment by ilya-fedin** [comment]
Yeah, I know, sadly NixOS doesn't work like that... It also is divided into Nix (the package manager) which could be used on any distro (and you can't set any global environment) and the distro itself on top of the Nix. And I'm not sure it's possible (with adequate performance at least?) to check every package's dependency in the store (that stores installed packages via different ways) to find all the installed plugins.

**Comment by ilya-fedin** [comment]
@K900 maybe you can explain better

**Comment by ilya-fedin** [comment]
> To check whether icons etc. also work you can use `sddm-greeter --test-mode --theme (whatever the NixOS equivalent to /usr/share/sddm/themes/breeze is)`

Yeah, they work

> IMO it's also fine to process `GreeterEnvironment` after any `pam_env` handling. I see you already prepared and tested a patch, can you open a PR?

#1759
