### ISSUE TITLE
Auth: sddm-helper exited with 11 after upgrading to v0.20.0-1

### ISSUE THREAD

**Issue by ragusa87** [sddm/sddm#1760]
Hello,

I just upgraded my system, and since then Sddm is not starting.
I am using KDE (wayland) on manjaro linux on a [framework](https://frame.work/) laptop (13th Gen Intel(R) Core(TM) i7-1360P)

> jui 10 13:44:10 laurent-framework systemd[1]: Started Simple Desktop Display Manager.
jui 10 13:44:10 laurent-framework sddm[1012]: Initializing...
jui 10 13:44:10 laurent-framework sddm[1012]: Starting...
jui 10 13:44:10 laurent-framework sddm[1012]: Logind interface found
jui 10 13:44:12 laurent-framework sddm[1012]: Adding new display...
jui 10 13:44:12 laurent-framework sddm[1012]: Loaded empty theme configuration
jui 10 13:44:12 laurent-framework sddm[1012]: Using VT 1
jui 10 13:44:12 laurent-framework sddm[1012]: Display server started.
jui 10 13:44:12 laurent-framework sddm[1012]: Socket server starting...
jui 10 13:44:12 laurent-framework sddm[1012]: Socket server started.
jui 10 13:44:12 laurent-framework sddm[1012]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
jui 10 13:44:12 laurent-framework sddm[1012]: Greeter starting...
jui 10 13:44:12 laurent-framework sddm-helper[1069]: [PAM] Starting...
jui 10 13:44:12 laurent-framework sddm-helper[1069]: [PAM] Authenticating...
jui 10 13:44:12 laurent-framework sddm-helper[1069]: pam_unix(sddm-greeter:session): session opened for user sddm(uid=964) by (uid=0)
jui 10 13:44:12 laurent-framework sddm-helper[1069]: [PAM] returning.
jui 10 13:44:12 laurent-framework sddm[1012]: Greeter session started successfully
jui 10 13:44:12 laurent-framework sddm-helper[1069]: [PAM] Closing session
jui 10 13:44:12 laurent-framework sddm-helper[1069]: pam_unix(sddm-greeter:session): session closed for user sddm
jui 10 13:44:12 laurent-framework sddm-helper[1069]: [PAM] Ended.
jui 10 13:44:12 laurent-framework sddm[1012]: Auth: sddm-helper exited with 11
jui 10 13:44:12 laurent-framework sddm[1012]: Greeter stopped. SDDM::Auth::HelperExitStatus(11)
jui 10 13:45:08 laurent-framework sddm[1012]: Signal received: SIGTERM

pacman -Qv sddm
> Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : sddm
sddm 0.20.0-1

> lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.0.0
Codename:       UltimaThule

I am not sure how I can report the error and what log I should provide, please let me know.

**Comment by Vogtinator** [comment]
`Auth: sddm-helper exited with 11`

11 is not any of the known codes of `sddm-helper` or `sddm-greeter`. However, `UserSession` ignores the exit status of the session process:

https://github.com/sddm/sddm/blob/07631f2ef00a52d883d0fd47ff7d1e1a6bc6358f/src/helper/UserSession.cpp#L50

So I suspect that `sddm-greeter` crashed with SIGSEGV (11) and the signal number ended up as exit code.

Do you have any process crash recorded?

**Comment by ragusa87** [comment]
I do:
> jui 10 13:44:12 laurent-framework sddm[1012]: Greeter session started successfully
jui 10 13:44:12 laurent-framework sddm-helper-start-wayland[1115]: Starting Wayland process "" "sddm"
jui 10 13:44:12 laurent-framework kernel: sddm-helper-sta[1115]: segfault at 4 ip 00007ff205a2bc37 sp 00007ffc10d09030 error 4 in libQt5Core.so.5.15.10[7ff20589f000+2dc000] likely on CPU 10 (core 18, socket 0)
jui 10 13:44:12 laurent-framework kernel: Code: 83 ec 20 48 8b 5f 08 64 48 8b 04 25 28 00 00 00 48 89 44 24 18 31 c0 44 8b 83 cc 00 00 00 45 85 c0 0f 85 b6 c7 e8 ff 48 8b 06 <8b> 78 04 85 ff 0f 84 7e 00 00 00 48 89 d5 41 89 cc 48 8d bb>
jui 10 13:44:12 laurent-framework systemd[1]: Created slice Slice /system/systemd-coredump.
jui 10 13:44:12 laurent-framework systemd[1]: Started Process Core Dump (PID 1116/UID 0).
jui 10 13:44:12 laurent-framework systemd-coredump[1117]: [🡕] Process 1115 (sddm-helper-sta) of user 964 dumped core.
                                                          
                                                          Stack trace of thread 1115:
                                                          #0  0x00007ff205a2bc37 _ZN8QProcess5startERK7QStringRK11QStringList6QFlagsIN9QIODevice12OpenModeFlagEE (libQt5Core.so.5 + 0x22bc37)
                                                          #1  0x000055756285225c n/a (sddm-helper-start-wayland + 0x525c)
                                                          #2  0x00007ff205239850 n/a (libc.so.6 + 0x23850)
                                                          #3  0x00007ff20523990a __libc_start_main (libc.so.6 + 0x2390a)
                                                          #4  0x0000557562852f05 n/a (sddm-helper-start-wayland + 0x5f05)
                                                          ELF object binary architecture: AMD x86-64

**Comment by ragusa87** [comment]
This one as well
> jui 10 13:44:47 laurent-framework dbus-daemon[1903]: [session uid=1000 pid=1903] Activating via systemd: service name='org.freedesktop.impl.portal.desktop.kde' unit='plasma-xdg-desktop-portal-kde.service' requested by ':1.3' (uid=1000 >
jui 10 13:44:47 laurent-framework systemd[1743]: Starting Xdg Desktop Portal For KDE...
jui 10 13:44:47 laurent-framework systemd-coredump[1923]: [🡕] Process 1904 (sddm-greeter) of user 1000 dumped core.
                                                          
                                                          Stack trace of thread 1904:
                                                          #0  0x00007f2c8f69f26c n/a (libc.so.6 + 0x8926c)
                                                          #1  0x00007f2c8f64fa08 raise (libc.so.6 + 0x39a08)
                                                          #2  0x00007f2c8f638538 abort (libc.so.6 + 0x22538)
                                                          #3  0x00007f2c8fca0098 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0xa0098)
                                                          #4  0x00007f2c9033f402 _ZN22QGuiApplicationPrivate25createPlatformIntegrationEv (libQt5Gui.so.5 + 0x13f402)
                                                          #5  0x00007f2c9033fa99 _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt5Gui.so.5 + 0x13fa99)
                                                          #6  0x00007f2c8fe9b215 _ZN23QCoreApplicationPrivate4initEv (libQt5Core.so.5 + 0x29b215)
                                                          #7  0x00007f2c9033fb46 _ZN22QGuiApplicationPrivate4initEv (libQt5Gui.so.5 + 0x13fb46)
                                                          #8  0x00007f2c9034087c _ZN15QGuiApplicationC1ERiPPci (libQt5Gui.so.5 + 0x14087c)
                                                          #9  0x000056383497d8d9 n/a (sddm-greeter + 0x118d9)
                                                          #10 0x00007f2c8f639850 n/a (libc.so.6 + 0x23850)
                                                          #11 0x00007f2c8f63990a __libc_start_main (libc.so.6 + 0x2390a)
                                                          #12 0x0000563834981655 n/a (sddm-greeter + 0x15655)
                                                          
                                                          Stack trace of thread 1905:
                                                          #0  0x00007f2c8f713c0f __poll (libc.so.6 + 0xfdc0f)
                                                          #1  0x00007f2c8e96cc2f n/a (libglib-2.0.so.0 + 0xb7c2f)
                                                          #2  0x00007f2c8e90d0e2 g_main_context_iteration (libglib-2.0.so.0 + 0x580e2)
                                                          #3  0x00007f2c8feea5cc _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea5cc)
                                                          #4  0x00007f2c8fe9a484 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x29a484)
                                                          #5  0x00007f2c8fcf72b6 _ZN7QThread4execEv (libQt5Core.so.5 + 0xf72b6)
                                                          #6  0x00007f2c8b861a9a n/a (libQt5DBus.so.5 + 0x18a9a)
                                                          #7  0x00007f2c8fcf34da n/a (libQt5Core.so.5 + 0xf34da)
                                                          #8  0x00007f2c8f69d44b n/a (libc.so.6 + 0x8744b)
                                                          #9  0x00007f2c8f720e40 n/a (libc.so.6 + 0x10ae40)
                                                          ELF object binary architecture: AMD x86-64
jui 10 13:44:47 laurent-framework systemd[1]: systemd-coredump@1-1906-0.service: Deactivated successfully.


As I tried to manually start the sddm service from terminal, I am not sure which dump are legit. Let me know on how I can help.

**Comment by Vogtinator** [comment]
> Starting Wayland process "" "sddm"

Apparently no wayland compositor is configured for SDDM?

**Comment by ragusa87** [comment]
I did a fresh reboot, I can confirm this is what I have in the log.

The configuration file /usr/lib/sddm/sddm.conf.d/default.conf is below:

```
[Autologin]
# Whether sddm should automatically log back into sessions when they exit
Relogin=false

# Name of session file for autologin session (if empty try last logged in)
Session=

# Username for autologin session
User=


[General]
# Which display server should be used.
# Valid values are: x11, x11-user, wayland. Wayland support is experimental
DisplayServer=x11

# Comma-separated list of environment variables to be set
GreeterEnvironment=

# Halt command
HaltCommand=/usr/bin/systemctl poweroff

# Input method module
InputMethod=

# Comma-separated list of Linux namespaces for user session to enter
Namespaces=

# Initial NumLock state. Can be on, off or none.
# If property is set to none, numlock won't be changed
# NOTE: Currently ignored if autologin is enabled.
Numlock=none

# Reboot command
RebootCommand=/usr/bin/systemctl reboot


[Theme]
# Current theme name
Current=

# Cursor size used in the greeter
CursorSize=

# Cursor theme used in the greeter
CursorTheme=

# Number of users to use as threshold
# above which avatars are disabled
# unless explicitly enabled with EnableAvatars
DisableAvatarsThreshold=7

# Enable display of custom user avatars
EnableAvatars=true

# Global directory for user avatars
# The files should be named <username>.face.icon
FacesDir=/usr/share/sddm/faces

# Font used in the greeter
Font=

# Theme directory path
ThemeDir=/usr/share/sddm/themes


[Users]
# Default $PATH for logged in users
DefaultPath=/usr/local/sbin:/usr/local/bin:/usr/bin

# Comma-separated list of shells.
# Users with these shells as their default won't be listed
HideShells=

# Comma-separated list of users that should not be listed
HideUsers=

# Maximum user id for displayed users
MaximumUid=60513

# Minimum user id for displayed users
MinimumUid=1000

# Remember the session of the last successfully logged in user
RememberLastSession=true

# Remember the last successfully logged in user
RememberLastUser=true

# When logging in as the same user twice, restore the original session, rather than create a new one
ReuseSession=true


[Wayland]
# Path of the Wayland compositor to execute when starting the greeter
CompositorCommand=weston --shell=fullscreen-shell.so

# Enable Qt's automatic high-DPI scaling
EnableHiDPI=true

# Path to a script to execute when starting the desktop session
SessionCommand=/usr/share/sddm/scripts/wayland-session

# Comma-separated list of directories containing available Wayland sessions
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions

# Path to the user session log file
SessionLogFile=.local/share/sddm/wayland-session.log


[X11]
# Path to a script to execute when starting the display server
DisplayCommand=/usr/share/sddm/scripts/Xsetup

# Path to a script to execute when stopping the display server
DisplayStopCommand=/usr/share/sddm/scripts/Xstop

# Enable Qt's automatic high-DPI scaling
EnableHiDPI=true

# Arguments passed to the X server invocation
ServerArguments=-nolisten tcp

# Path to X server binary
ServerPath=/usr/bin/X

# Path to a script to execute when starting the desktop session
SessionCommand=/usr/share/sddm/scripts/Xsession

# Comma-separated list of directories containing available X sessions
SessionDir=/usr/local/share/xsessions,/usr/share/xsessions

# Path to the user session log file
SessionLogFile=.local/share/sddm/xorg-session.log

# Path to Xephyr binary
XephyrPath=/usr/bin/Xephyr

```

**Comment by ragusa87** [comment]
Adding a specific configuration file such as the one below, fixed the issue. However, it feels odd that upgrading the package version breaks the whole setup. Having a black screen with no login prompt is quite a disturbing user experience. 

Thanks a lot for the help provided. I hope you can find a fix.


/etc/sddm.conf.d/10-wayland.conf
```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen --no-global-shortcuts
```

**Comment by Vogtinator** [comment]
The question is why it worked at all before the upgrade. What was the previous configuration?

It says `DisplayServer=x11` but that's obviously not true because `sddm-helper-start-wayland` is involved.

**Comment by ragusa87** [comment]
I don't have any backup so I can't tell what was the previous configuration. But the installation was made 2 weeks ago. So it's quite a fresh setup with probably the default configuration (I can't recall if I edited something)

My guess is that before, I was using sddm on x11, then booted up a kde-wayland session, and now the sddm session is directly booting using wayland. 

I see that the layout I was using before "fr_CH" is not selected or available, probably due to a switch from X11 to Wayland.. but that's another issue.

> ❯ localectl
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=fr_CH.UTF-8
               LC_TIME=fr_CH.UTF-8
               LC_MONETARY=fr_CH.UTF-8
               LC_PAPER=fr_CH.UTF-8
               LC_NAME=fr_CH.UTF-8
               LC_ADDRESS=fr_CH.UTF-8
               LC_TELEPHONE=fr_CH.UTF-8
               LC_MEASUREMENT=fr_CH.UTF-8
               LC_IDENTIFICATION=fr_CH.UTF-8
    VC Keymap: fr_CH
   X11 Layout: ch
  X11 Variant: fr

**Comment by Vogtinator** [comment]
> My guess is that before, I was using sddm on x11, then booted up a kde-wayland session, and now the sddm session is directly booting using wayland.

That's unlikely. X11 is the default in SDDM and Plasma can't change this.

Maybe there is some distro specific configuration or patch?

**Comment by ragusa87** [comment]
Maybe. 

All I can provide is the pacman.log, but I am not sure it helps.

cat pacman.log | grep -E "sdd|kde|way|plasma" | grep 2023-07

> [2023-07-10T13:23:11+0200] [ALPM] upgraded qt5-base (5.15.9+kde+r151-1 -> 5.15.10+kde+r130-1)
[2023-07-10T13:23:12+0200] [ALPM] upgraded libblockdev (2.28-2 -> 2.28-4)
[2023-07-10T13:23:12+0200] [ALPM] upgraded qt5-svg (5.15.9+kde+r8-1 -> 5.15.10+kde+r8-1)
[2023-07-10T13:23:12+0200] [ALPM] upgraded qt5-declarative (5.15.9+kde+r25-1 -> 5.15.10+kde+r26-1)
[2023-07-10T13:23:12+0200] [ALPM] upgraded qt5-wayland (5.15.9+kde+r55-1 -> 5.15.10+kde+r51-1)
[2023-07-10T13:23:13+0200] [ALPM] upgraded qt5-multimedia (5.15.9+kde+r3-1 -> 5.15.10+kde+r3-1)
[2023-07-10T13:23:13+0200] [ALPM] upgraded qt5-speech (5.15.9+kde+r1-1 -> 5.15.10+kde+r1-1)
[2023-07-10T13:23:13+0200] [ALPM] upgraded kded (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:14+0200] [ALPM] upgraded kdeclarative (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:16+0200] [ALPM] upgraded kdecoration (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:17+0200] [ALPM] upgraded qt5-quickcontrols2 (5.15.9+kde+r6-1 -> 5.15.10+kde+r6-1)
[2023-07-10T13:23:32+0200] [ALPM] upgraded qt5-webchannel (5.15.9+kde+r3-1 -> 5.15.10+kde+r3-1)
[2023-07-10T13:23:33+0200] [ALPM] upgraded qt5-location (5.15.9+kde+r4-1 -> 5.15.10+kde+r4-2)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kdesu (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kde-cli-tools (5.27.5.1-1 -> 5.27.6-1)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kde-gtk-config (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kdeconnect (23.04.1-1 -> 23.04.3-1)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kdegraphics-mobipocket (23.04.1-1 -> 23.04.3-1)
[2023-07-10T13:23:36+0200] [ALPM] upgraded kdegraphics-thumbnailers (23.04.1-1 -> 23.04.3-1)
[2023-07-10T13:23:37+0200] [ALPM] upgraded kdelibs4support (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:37+0200] [ALPM] upgraded kdenetwork-filesharing (23.04.1-1 -> 23.04.3-1)
[2023-07-10T13:23:38+0200] [ALPM] upgraded kwayland (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:38+0200] [ALPM] upgraded plasma-framework (5.106.0-1 -> 5.107.0-1)
[2023-07-10T13:23:38+0200] [ALPM] upgraded plasma-integration (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:38+0200] [ALPM] upgraded qt5-tools (5.15.9+kde+r1-1 -> 5.15.10+kde+r3-1)
[2023-07-10T13:23:39+0200] [ALPM] upgraded plasma-workspace (5.27.5-1 -> 5.27.6-2)
[2023-07-10T13:23:40+0200] [ALPM] upgraded kdeplasma-addons (5.27.5-1 -> 5.27.6-2)
[2023-07-10T13:23:41+0200] [ALPM] upgraded wayland-utils (1.1.0-1 -> 1.2.0-1)
[2023-07-10T13:23:41+0200] [ALPM] upgraded kwayland-integration (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:43+0200] [ALPM] upgraded xdg-desktop-portal-kde (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:54+0200] [ALPM] upgraded pamac-tray-icon-plasma (0.1.2-4 -> 0.1.2-5)
[2023-07-10T13:23:54+0200] [ALPM] upgraded plasma-browser-integration (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:54+0200] [ALPM] upgraded polkit-kde-agent (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-desktop (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-nm (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-pa (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-systemmonitor (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-thunderbolt (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded xorg-xwayland (23.1.1-1 -> 23.1.2-1)
[2023-07-10T13:23:55+0200] [ALPM] upgraded plasma-wayland-session (5.27.5-1 -> 5.27.6-2)
[2023-07-10T13:23:56+0200] [ALPM] upgraded plasma-workspace-wallpapers (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:23:58+0200] [ALPM] upgraded qt5-imageformats (5.15.9+kde+r9-1 -> 5.15.10+kde+r9-1)
[2023-07-10T13:23:59+0200] [ALPM] warning: /etc/pam.d/sddm installed as /etc/pam.d/sddm.pacnew
[2023-07-10T13:23:59+0200] [ALPM] upgraded sddm (0.19.0-9 -> 0.20.0-1)
[2023-07-10T13:23:59+0200] [ALPM] upgraded sddm-kcm (5.27.5-1 -> 5.27.6-1)
[2023-07-10T13:46:37+0200] [PACMAN] Running 'pacman -S sddm'
[2023-07-10T13:46:38+0200] [ALPM] reinstalled sddm (0.20.0-1)
[2023-07-10T13:47:09+0200] [PACMAN] Running 'pacman -U sddm'
[2023-07-10T13:50:01+0200] [PACMAN] Running 'pacman -R sddm'
[2023-07-10T13:50:06+0200] [PACMAN] Running 'pacman -R sddm-kcm'
[2023-07-10T13:50:08+0200] [ALPM] removed sddm-kcm (5.27.6-1)
[2023-07-10T13:50:10+0200] [PACMAN] Running 'pacman -R sddm'
[2023-07-10T13:50:11+0200] [ALPM] warning: /etc/pam.d/sddm saved as /etc/pam.d/sddm.pacsave
[2023-07-10T13:50:11+0200] [ALPM] removed sddm (0.20.0-1)
[2023-07-10T13:50:19+0200] [PACMAN] Running 'pacman -S sddm-kcm sddm'
[2023-07-10T13:50:20+0200] [ALPM] installed sddm (0.20.0-1)
[2023-07-10T13:50:20+0200] [ALPM] installed sddm-kcm (5.27.6-1)
```
Let me know if you need anything else.

**Comment by Vogtinator** [comment]
Can you restore the sddm factory configuration, i.e. undo all modifications and delete extra files?

**Comment by ragusa87** [comment]
Sorry, I have no idea on how to do that.
I checked the [plasma-workspace package v5.27.6](https://download.kde.org/stable/plasma/5.27.6/plasma-workspace-5.27.6.tar.xz.mirrorlist), I seems they change the default config from x11 to wayland by adding a configuration file (see `sddm-wayland-session/plasma-wayland.conf` from the archive). It could explains the switch.

They have something like that:
```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
InputMethod=

[Wayland]
CompositorCommand=kwin_wayland --no-global-shortcuts --no-lockscreen --inputmethod maliit-keyboard --locale1

```

My suggestion would be to close this issue, and see if you have another report that could be more specific to pinpoint the faulty configuration. I don't see myself re-configuring my setup and spend more time on this. Furthermore, I might be the only one having this issue. Let's see if there is more reports.

**Comment by Vogtinator** [comment]
The log output implies that `CompositorCommand` was empty, but there it's set, which should work.

> My suggestion would be to close this issue, and see if you have another report that could be more specific to pinpoint the faulty configuration. I don't see myself re-configuring my setup and spend more time on this. Furthermore, I might be the only one having this issue. Let's see if there is more reports.

Ok.

**Comment by turtley-turtle** [comment]
> Furthermore, I might be the only one having this issue. Let's see if there is more reports.

I am having this issue

**Comment by ragusa87** [comment]
Hello @turtley-turtle , this issue is closed. Feel free to open another one and report the logs in the new issue. Cheers.
