### ISSUE TITLE
Wayland multiseat

### ISSUE THREAD

**Issue by FinecoFinit** [sddm/sddm#1778]
Can't launch wayland on both seats, display just freezes and then I can't access main seat until I reboot

**Comment by MastroLindus** [comment]
hi @FinecoFinit , I had the same issue. As a temporary fix, I just used one session in wayland and one in X11.

However a recent update seems to have broken this setup as well: now no matter what session I use, the second user gets  black screen when it logins, so for me multiseat as a whole is broken (and it used to work completely fine until a few months ago, see also this: https://bbs.archlinux.org/viewtopic.php?id=287059 )

I think 0.20 might have broke it for me. Are you running 0.20 or earlier versions?

**Comment by FinecoFinit** [comment]
@MastroLindus I just switched to gdm

**Comment by Pointedstick** [comment]
Seems like a duplicate of https://github.com/sddm/sddm/issues/1762.
