### ISSUE TITLE
SDDM creates a session bus for itself.

### ISSUE THREAD

**Issue by arrowd** [sddm/sddm#1782]
After starting SDDM on FreeBSD and running `ps -axO user | grep dbus` I get:

```
15877 sddm        -  Ss     0:00.00 /usr/local/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
38254 messagebus  -  Ss     0:00.17 /usr/local/bin/dbus-daemon --system
15274 sddm        0  S      0:00.00 dbus-launch --autolaunch 20221029f46add6c6f6ff46add6c6f70 --binary-syntax --close-stderr
```

Looking around inside this bus using `qdbus-qt5` reveals than there is nothing on it except `org.freedesktop.DBus`. The whole bus seems unused, but I failed to figure what actually starts `dbus-launch`.

**Comment by Vogtinator** [comment]
It's running as `sddm` user, so it's most likely the greeter. It probably did some session call, maybe to fetch settings or something.

**Comment by arrowd** [comment]
Yes, `sddm-greeter` is the culprit. However, it is not linked to Qt5DBus nor to libdbus, so it doesn't seem to create the bus implicitly. However, I still can't find the code that creates it.

**Comment by Vogtinator** [comment]
You could run `dbus-monitor` and start `sddm-greeter` manually to see what DBus calls it tries.

**Comment by arrowd** [comment]
Something pulls in `QtDBus`, which contains `static QDBusConnectionManager` that starts a thread and spawns D-Bus session on the library load. I haven't figured what exactly causes `QtDBus` to be loaded, but at least there is an explanation for the `dbus-launch` process. Not a SDDM fault in any case.
