### ISSUE TITLE
X11 authorization over SSH (ffmpeg)

### ISSUE THREAD

**Issue by amakea** [sddm/sddm#1798]
Hi. I do a screen capture with FFmpeg (x11grab) on my one machine that I run over a SSH session on my local network. When I try to run it with 0.20.0 I am given an error regarding X11 authorization (MIT Magic Cookie) so I have rolled back to 0.19.0. Is their a correct way to deal with this in the latest version? Thank you.

**Comment by Vogtinator** [comment]
You'll have to set `XAUTHORITY` correctly. If you use systemd, you can use `systemd-run --user ffmpeg ...`

**Comment by amakea** [comment]
This will suffice, thank you. I can live without seeing the output stats from FFmpeg, but I will miss them. I could set FFmpeg to dump the information I want, but systemd journal would get majorly flooded. Open to different methods if they exist.

**Comment by Vogtinator** [comment]
> This will suffice, thank you. I can live without seeing the output stats from FFmpeg, but I will miss them. I could set FFmpeg to dump the information I want, but systemd journal would get majorly flooded. Open to different methods if they exist.

You can use the `-P` option for that, see `systemd-run --help`.
