### ISSUE TITLE
 Button "apply plasma settings" no longer works

### ISSUE THREAD

**Issue by es20490446e** [sddm/sddm#1801]
=== SYSTEM ===
- KDE Plasma 5.27.5
- KDE Frameworks 5.106.0
- Qt: 5.15.9
- SDDM 0.19.0
- Manjaro KDE

=== REPRODUCING ===
1. At "System Settings -> Display and Monitor -> Display Configuration" change "global scale".
2. At "System Settings -> Startup and Shutdown - > Login Screen (SDDM)", press the button "Apply Plasma Settings".

=== RESULT ===
- SDDM scale doesn't change

=== LINKS ===
- kde_settings.conf: https://pastebin.com/2PrsZzxp
- KDE Bug Tracker: https://bugs.kde.org/show_bug.cgi?id=471356

**Comment by Vogtinator** [comment]
Is this multi monitor?

Does it work if you add this?

```
[X11]
EnableHiDPI=false
```

What's in your `/etc/sddm.conf` and other SDDM config files?

**Comment by es20490446e** [comment]
- This is a laptop connected to an external monitor.
- Both monitors have the same max resolution.
- Keeping the laptop screen closed doesn't change behavior.
---
- EnablingHiDPI changes nothing.
- Using the default Plasma theme, Breeze, changes nothing.
- Reseting Breeze settings does nothing.
- The only things that change by applying plasma settings are the cursor style and size.
---
Files are:
- [sddm.conf.d/00_manjaro_settings.conf](https://pastebin.com/FsFQfesW)
- [sddm.conf.d/01_theme.conf](https://pastebin.com/8LzfWgzz)
- [sddm.conf.d/20-optimus-manager.conf](https://pastebin.com/pu0B255M)
- [sddm.conf.d/kde_settings.conf](https://pastebin.com/2PrsZzxp)
- [sddm.conf.d/virtualkeyboard.conf](https://pastebin.com/3TrjekL7)
- [sddm.conf](https://pastebin.com/aKSuidAK)

**Comment by Vogtinator** [comment]
I'm not sure what the behaviour of vanilla Qt with `-dpi` is. It might just get ignored (as it should be) in which case the approach that Plasma uses is broken.

Try

```
[General]
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=1.5;1.5
```

**Comment by es20490446e** [comment]
That scales certain UI elements, but not the fonts.

**Comment by es20490446e** [comment]
Changing the `font` parameter actually changes the font size.

**Comment by Vogtinator** [comment]
That sounds like some other script sets the `Xft.dpi` property, which essentially overrides the `-dpi` parameter.

SDDM does not do this, so please double-check your configuration and other maybe distro provided scripts.

**Comment by es20490446e** [comment]
Let me have a look 👀
