### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by Airmancooma** [sddm/sddm#1811]
Hi!

I would like to apply a blur to the password entry part but I just can't. I just want the background image to not be blurred only the part where the password part is.

I attach some examples:
This is opacity: 0.5 but that's not what I want
![image](https://github.com/sddm/sddm/assets/107194958/cefdadf4-3de2-4be5-af57-156215a088a7)
I want this: and this is blur but I dont know how can i make this in qml
![image](https://github.com/sddm/sddm/assets/107194958/527de96d-d67e-4ecd-98b5-6ae0230da143)

**Comment by Vogtinator** [comment]
You can try using QML `GraphicalEffects` `FastBlur` with a region from the background image (using `sourceClipRect`).

**Comment by Airmancooma** [comment]
> sourceClipRect

Okthx but how? Sorry I don't get the blurring so much and I couldn't find much on the internet how to do this (that's why I asked here)

**Comment by Vogtinator** [comment]
There's also a way using `ShaderEffectSource` to grab an area of the background:

```
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtGraphicalEffects 1.15

Item {
    width: 1024
    height: 768
    Image {
        id: background
        anchors.fill: parent
        source: "/usr/share/wallpapers/Next/contents/images/1024x768.png"
    }

    TextField {
        id: pwbox
        x: 450
        y: 420
        background: FastBlur {
            radius: 30
            source: ShaderEffectSource {
                sourceItem: background
                implicitWidth: 200
                sourceRect: pwbox.mapToItem(background, 0, 0, pwbox.width, pwbox.height)
            }
        }
    }
}
```

This is not SDDM specific though and belongs more on stackoverflow at this point, so I'll close this. See also https://stackoverflow.com/questions/28032329/qml-shader-effect-blur-behind-an-item.

**Comment by Airmancooma** [comment]
> There's also a way using `ShaderEffectSource` to grab an area of the background:
> 
> ```
> import QtQuick 2.15
> import QtQuick.Controls 2.15
> import QtGraphicalEffects 1.15
> 
> Item {
>     width: 1024
>     height: 768
>     Image {
>         id: background
>         anchors.fill: parent
>         source: "/usr/share/wallpapers/Next/contents/images/1024x768.png"
>     }
> 
>     TextField {
>         id: pwbox
>         x: 450
>         y: 420
>         background: FastBlur {
>             radius: 30
>             source: ShaderEffectSource {
>                 sourceItem: background
>                 implicitWidth: 200
>                 sourceRect: pwbox.mapToItem(background, 0, 0, pwbox.width, pwbox.height)
>             }
>         }
>     }
> }
> ```
> 
> This is not SDDM specific though and belongs more on stackoverflow at this point, so I'll close this. See also https://stackoverflow.com/questions/28032329/qml-shader-effect-blur-behind-an-item.

thx
