### ISSUE TITLE
disable blur

### ISSUE THREAD

**Issue by palonza** [sddm/sddm#1818]
it is posible disable blur on login screen?

**Comment by Ryder17z** [comment]
Not without implementing an override, because it seems like the property is forcibly applied by the theme Breeze and themes based on that.

**Comment by Vogtinator** [comment]
Yeah, needs to be implemented in the theme.

**Comment by Ryder17z** [comment]
> Yeah, needs to be implemented in the theme.

I'm gonna disagree with that tagging - it's not invalid, but should be marked as enhancement.

Because I can go into KDE settings and turn off all related effects such as blur but SDDM will still apply blur.

**Comment by Vogtinator** [comment]
That's something the theme resp. KDE Plasma has to implement, not SDDM. SDDM itself does not do anything with blur.

**Comment by palonza** [comment]
thank you all guys!

**Comment by Ryder17z** [comment]
Ah, thanks for the clarification.

**Comment by Ryder17z** [comment]
As a solution, i have replaced SDDM with LightDM

**Comment by Vogtinator** [comment]
You could also just select some other SDDM theme without blur...

**Comment by Ryder17z** [comment]
> You could also just select some other SDDM theme without blur...

I looked around for themes but i couldn't really find one that fit my wants:
* KDE6 support
* no background blur
* a style i like

LightDM with the Shikai theme on the other hand, I'm very happy with.
