### ISSUE TITLE
Two services allocated for the same bus name

### ISSUE THREAD

**Issue by lukedupost** [sddm/sddm#1823]
After un good login, to desktop SDDM kicks me back to login prompt. Configuration used is Manjaro Kde Plasma X11 or Wayland
This happened right after the last general update.

Here is the journactl 
 journalctl -b-1 -p err..alert | grep session                                                                                             0|1 ✘ 
nov. 08 16:34:01 manjaro-kde systemd[1587]: dde-session@x11.service: Two services allocated for the same bus name org.kde.KWin, refusing operation.
nov. 08 16:34:01 manjaro-kde systemd[1587]: dde-session@wayland.service: Two services allocated for the same bus name org.kde.KWinWrapper, refusing operation.
No more problem to continue with terminal and launch the session by startx.
Thanks for help.

**Comment by Vogtinator** [comment]
Not an SDDM issue. You installed incompatible packages on your system. dde-session can apparently not coexist with Plasma.
