### ISSUE TITLE
SDDM Unable to start Wayland session (Hyprland)

### ISSUE THREAD

**Issue by mxple** [sddm/sddm#1834]
```
/usr/share/wayland-sessions/hyprland.desktop 
[Desktop Entry]
Name=Hyprland
Comment=An intelligent dynamic tiling Wayland compositor
Exec=Hyprland
Type=Application```
```
```
.local/share/sddm/wayland-session.log 
Hyprland: error while loading shared libraries: libwlroots.so.12032: cannot open shared object file: No such file or directory
```
SDDM version: 0.20.0
Hyprland version: v0.32.3
Kernel: 6.6.2-arch1-1

Hyprland can be run without issue from a tty. SDDM allows me to authenticate, but then goes black and returns back to the greeter. SDDM journal logs don't show anything out of the ordinary, I believe the issue is described in `wayland-session.log`. I have `libwlroots.so.13032`, Hyprland is built requiring the correct version (13), so I'm not sure why SDDM is trying to use an older version of `libwlroots`.

Additionally, SDDM has no problems launching an X11 session.

**Comment by Vogtinator** [comment]
This points to some installation issue. Maybe you have some leftover libs in `/usr/local` or some leftover executables in `~/bin` or `~/local/bin`.

**Comment by mxple** [comment]
Thanks, the file `/usr/local/lib/libwlroots.so.12032` was present. After removing it, I still get the same error. I'm assuming I have to update my library paths?

**Comment by Vogtinator** [comment]
I suspect it's the other way around - that file was what actually made it work for you from a tty but not SDDM for some reason.

**Comment by mxple** [comment]
I found the issue, thanks for the hints. An old manual build of Hyprland was present at `/usr/local/bin`. Removing it fixed the issue.
