### ISSUE TITLE
SDDM screen only patially translated: english day, month Text for “restart”, "sleep¨, “shutdown” etc is in the “locale” language.

### ISSUE THREAD

**Issue by WillemHobers** [sddm/sddm#1836]
sddm screen shows day, month etc in English. Text for “restart”, "sleep¨, “shutdown” etc is in the “locale” language. (dutch)

Testing Qt6/Plasma6 on EndeavourOS.

Operating System: EndeavourOS 
KDE Plasma Version: 5.90.0
KDE Frameworks Version: 5.246.0
Qt Version: 6.6.1
Kernel Version: 6.6.3-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 3.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Acer
Product Name: Aspire A315-53
System Version: V2.02

**Comment by Vogtinator** [comment]
That's a bug in the Plasma theme and has to be fixed thee.

**Comment by WillemHobers** [comment]
Initially I had reported the problem over at KDE/Plasma. They said the issue needed to be resolved in SDDM, advised me to report here and closed the issue.
I have now reported the issue over at KDE.
