### ISSUE TITLE
Keyboard input does not work with kwin wayland from Plasma 6 Beta 1

### ISSUE THREAD

**Issue by jfroy** [sddm/sddm#1837]
I use sddm with kwin wayland for the greeter on my Arch Linux system. This works fine with the normal core+extra package repos. I just enabled the kde-unstable repo to test Plasma 6 beta 1, and I could no longer type my password at the sddm prompt or do anything with the keyboard. I could still switch to a different tty and type there, so the keyboard is working. But something between sddm and kwin wayland broke.

I followed the instructions on https://wiki.archlinux.org/title/SDDM#KDE_/_KWin to configure sddm.

**Comment by eternalevelyn** [comment]
Same here. I'm not entirely sure how it happens- but it seems to me that it's likely to do with the Plasma 6 beta.

**Comment by caderobinson** [comment]
https://bugs.kde.org/show_bug.cgi?id=477251
Fixed in beta2 (layer-shell-qt 5.91.0-1)

**Comment by jfroy** [comment]
I can confirm this is indeed fixed.
