### ISSUE TITLE
SDDM keyboard layout defaults to whatever is alphabetically first if using Wayland

### ISSUE THREAD

**Issue by CosmicHeron** [sddm/sddm#1843]
If changing the SDDM's config to use Wayland (using weston) it appears that SDDM will not pick up the appropriate keyboard layout but just default to whatever is listed first alphabetically which tends to be Albanian. However when changing the keyboard layout to the right one the setting does not persist and will switch back to Albanian on the next boot. I tried looking around but did not see any setting in `sddm.conf` for it. Layout settings set by localectl, in `vconsole.conf` or in KDE/fcitx5 seem to be completely ignored.

**Comment by Vogtinator** [comment]
Keyboard layout configuration with wayland is entirely up to the compositor. There's currently no way for SDDM to change it.

**Comment by Lunaphied** [comment]
Sorry to bump this up but can this be documented somewhere? I've been confused about why it's supposedly set to Albanian for awhile, despite it not actually affecting anything. 

Also if I'm understanding correctly SDDM runs under an existing compositor it doesn't run it's own or launch one directly?

**Comment by Vogtinator** [comment]
> Sorry to bump this up but can this be documented somewhere? I've been confused about why it's supposedly set to Albanian for awhile, despite it not actually affecting anything.

It's already addressed by https://github.com/sddm/sddm/commit/8c370d97c14836864e9a038975f7f4cca1418554, the keyboard selection won't be shown at all when using Wayland.

> Also if I'm understanding correctly SDDM runs under an existing compositor it doesn't run it's own or launch one directly?

It starts whatever compositor you configured in sddm.conf (`CompositorCommand`), by default it's Weston but distros with Plasma set it to kwin_wayland.
