### ISSUE TITLE
For some reason xauth files are now in tmp, with variable names, but I need a deterministic name for a wacom tablet udev rule...how do I do that?

### ISSUE THREAD

**Issue by Bracket-H** [sddm/sddm#1852]
Instead of raging about this change as I originally intended, I'll just ask this question for now.
Surely its possible, right?

**Comment by Vogtinator** [comment]
What exactly does that rule do? Accessing the user X11 display from udev is broken by design IMO.

You can use `su username -c "systemd-run --user <command>"` to run the command in the right context.

**Comment by Vogtinator** [comment]
> The rule sets up keyboard stuff (layouts, which for some reason get reset), sets up monitors with xrandr, sets up some wacom express remote keys, all with xsetwacom and some other x tools.

That's something that needs to be done in your session, not udev.

**Comment by Vogtinator** [comment]
Perform system level actions on device events (create /dev nodes, set permissions, ...). For device setup, whatever uses the device is responsible. X configuration (monitors, keyboard, tablet) is usually done by the DE.
