### ISSUE TITLE
Logging in takes alot of time 

### ISSUE THREAD

**Issue by Loup-Garou911XD** [sddm/sddm#1861]
Recently it started taking alot of time to login
I am running arch linux with gnome wayland
Also have installed a sddm theme
Happy to provide any other info needed for fixing the issue

[Journalctl](https://github.com/sddm/sddm/files/14088587/log.log)

**Comment by Vogtinator** [comment]
The delay is in gnome-shell for some reason:

```
Jan 30 00:26:54 laptop gnome-shell[803]: Running GNOME Shell (using mutter 45.3) as a Wayland display server
Jan 30 00:26:54 laptop gnome-shell[803]: Failed to make thread 'KMS thread' realtime scheduled: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.RealtimeKit1" does not exist
[...]
Jan 30 00:27:26 laptop gnome-shell[803]: Device '/dev/dri/card0' prefers shadow buffer
```

I doubt the RTkit error is related, but the almost 30s delay sounds like a DBus timeout.

BTW: GNOME requires GDM for some features like screen locking...

**Comment by Loup-Garou911XD** [comment]
> BTW: GNOME requires GDM for some features like screen locking...

Yeah I am aware of that, but this can't be causing it because as I said it started happening recently

**Comment by Loup-Garou911XD** [comment]
Any debugging tips that can help

**Comment by Vogtinator** [comment]
In another session (ideally through ssh from somewhere) run `dbus-monitor` and look for any timeouts.

**Comment by Vogtinator** [comment]
Alternatively you can also try to enable gnome-shell logging, but I have no idea how that's done.

**Comment by Loup-Garou911XD** [comment]
I also think I don't have drivers for my nvidia GPU if that could be the problem

**Comment by C0rn3j** [comment]
```bash
Jan 30 00:26:54 laptop systemd[716]: Starting GNOME Shell on Wayland...
Jan 30 00:27:27 laptop systemd[716]: Started GNOME Shell on Wayland.
Jan 30 00:27:27 laptop systemd[716]: Starting Portal service...
Jan 30 00:27:27 laptop systemd[716]: Starting Portal service (GNOME implementation)...
Jan 30 00:28:00 laptop systemd[716]: Started Portal service (GNOME implementation).
Jan 30 00:28:00 laptop systemd[716]: Started Portal service.
```

@Loup-Garou911XD Can you reproduce using a completely new linux user?

If not, what's the `env` in your old one and what's the `env` of your new one?

**Comment by Loup-Garou911XD** [comment]
env before login
```
PWD=/home/loup
XDG_SESSION_ID=2
XDG_VTNR=3
XDG_DATA_DIRS=/home/loup/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
SHELL=/usr/bin/fish
MAIL=/var/spool/mail/loup
XDG_SESSION_CLASS=user
MOTD_SHOWN=pam
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1000
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/system.slice/system-getty.slice/getty@tty3.service/memory.pressure
LANG=en_US.UTF-8
SHLVL=1
SYSTEMD_EXEC_PID=736
LOGNAME=loup
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
USER=loup
CREDENTIALS_DIRECTORY=/run/credentials/getty@tty3.service
INVOCATION_ID=a6f635a1219c4587bd7dafecfbe7fa66
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
TERM=linux
HOME=/home/loup
XDG_SESSION_TYPE=tty
```

env after login
```
SESSION_MANAGER=local/louptop:@/tmp/.ICE-unix/785,unix/louptop:/tmp/.ICE-unix/785
XDG_DATA_DIRS=/home/loup/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
SYSTEMD_EXEC_PID=996
SSH_AUTH_SOCK=/run/user/1000/gcr/ssh
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/b26bb2ce_6557_4300_9bb6_6b0016b171ca
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=GNOME
GNOME_SETUP_DISPLAY=:1
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
XDG_RUNTIME_DIR=/run/user/1000
GNOME_KEYRING_CONTROL=/run/user/1000/keyring
XDG_SESSION_CLASS=user
MAIL=/var/spool/mail/loup
LOGNAME=loup
VTE_VERSION=7402
HOME=/home/loup
XDG_SESSION_TYPE=wayland
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2
PWD=/home/loup
DESKTOP_SESSION=gnome-wayland
XDG_MENU_PREFIX=gnome-
USER=loup
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
TERM=xterm-256color
WAYLAND_DISPLAY=wayland-0
DISPLAY=:0
COLORTERM=truecolor
SHELL=/usr/bin/fish
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.H8Y9J2
MOTD_SHOWN=pam
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.SettingsDaemon.MediaKeys.service/memory.pressure
GNOME_TERMINAL_SERVICE=:1.84
SHLVL=1
XDG_SESSION_DESKTOP=GNOME
```

**Comment by Loup-Garou911XD** [comment]
> env before login
> ```
> PWD=/home/loup
> XDG_SESSION_ID=2
> XDG_VTNR=3
> XDG_DATA_DIRS=/home/loup/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
> SHELL=/usr/bin/fish
> MAIL=/var/spool/mail/loup
> XDG_SESSION_CLASS=user
> MOTD_SHOWN=pam
> XDG_SEAT=seat0
> XDG_RUNTIME_DIR=/run/user/1000
> MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
> MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/system.slice/system-getty.slice/getty@tty3.service/memory.pressure
> LANG=en_US.UTF-8
> SHLVL=1
> SYSTEMD_EXEC_PID=736
> LOGNAME=loup
> PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> USER=loup
> CREDENTIALS_DIRECTORY=/run/credentials/getty@tty3.service
> INVOCATION_ID=a6f635a1219c4587bd7dafecfbe7fa66
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> TERM=linux
> HOME=/home/loup
> XDG_SESSION_TYPE=tty
> ```
> 
> env after login
> ```
> SESSION_MANAGER=local/louptop:@/tmp/.ICE-unix/785,unix/louptop:/tmp/.ICE-unix/785
> XDG_DATA_DIRS=/home/loup/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
> SYSTEMD_EXEC_PID=996
> SSH_AUTH_SOCK=/run/user/1000/gcr/ssh
> GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/b26bb2ce_6557_4300_9bb6_6b0016b171ca
> LANG=en_US.UTF-8
> XDG_CURRENT_DESKTOP=GNOME
> GNOME_SETUP_DISPLAY=:1
> MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
> XDG_RUNTIME_DIR=/run/user/1000
> GNOME_KEYRING_CONTROL=/run/user/1000/keyring
> XDG_SESSION_CLASS=user
> MAIL=/var/spool/mail/loup
> LOGNAME=loup
> VTE_VERSION=7402
> HOME=/home/loup
> XDG_SESSION_TYPE=wayland
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2
> PWD=/home/loup
> DESKTOP_SESSION=gnome-wayland
> XDG_MENU_PREFIX=gnome-
> USER=loup
> PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
> DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
> TERM=xterm-256color
> WAYLAND_DISPLAY=wayland-0
> DISPLAY=:0
> COLORTERM=truecolor
> SHELL=/usr/bin/fish
> XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.H8Y9J2
> MOTD_SHOWN=pam
> MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.SettingsDaemon.MediaKeys.service/memory.pressure
> GNOME_TERMINAL_SERVICE=:1.84
> SHLVL=1
> XDG_SESSION_DESKTOP=GNOME
> ```

@C0rn3j

**Comment by C0rn3j** [comment]
@Loup-Garou911XD Which one is the new user?

**Comment by Loup-Garou911XD** [comment]
> @Loup-Garou911XD Which one is the new user?

Instructions were unclear, the env is of existing user,sry

**Comment by Loup-Garou911XD** [comment]
Will do it later today

**Comment by Loup-Garou911XD** [comment]
> @Loup-Garou911XD Which one is the new user?

env before login

```SHELL=/usr/bin/bash
CREDENTIALS_DIRECTORY=/run/credentials/getty@tty3.service
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
XDG_SEAT=seat0
PWD=/home/tempuser
LOGNAME=tempuser
XDG_SESSION_TYPE=tty
SYSTEMD_EXEC_PID=733
MOTD_SHOWN=pam
HOME=/home/tempuser
LANG=en_US.UTF-8
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/system.slice/system-getty.slice/getty@tty3.service/memory.pressure
INVOCATION_ID=28267a7d48cb42488d5a4c478ab1d94c
XDG_SESSION_CLASS=user
TERM=linux
USER=tempuser
SHLVL=1
XDG_VTNR=3
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1002
DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
XDG_DATA_DIRS=/home/tempuser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1002/bus
MAIL=/var/spool/mail/tempuser
_=/usr/bin/env
```

env after login
```SHELL=/usr/bin/bash
SESSION_MANAGER=local/louptop:@/tmp/.ICE-unix/829,unix/louptop:/tmp/.ICE-unix/829
COLORTERM=truecolor
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2
XDG_MENU_PREFIX=gnome-
SSH_AUTH_SOCK=/run/user/1002/gcr/ssh
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
DESKTOP_SESSION=gnome-wayland
PWD=/home/tempuser
LOGNAME=tempuser
XDG_SESSION_DESKTOP=GNOME
XDG_SESSION_TYPE=wayland
SYSTEMD_EXEC_PID=853
XAUTHORITY=/run/user/1002/.mutter-Xwaylandauth.C8U0J2
MOTD_SHOWN=pam
HOME=/home/tempuser
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=GNOME
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1002.slice/user@1002.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
VTE_VERSION=7402
WAYLAND_DISPLAY=wayland-0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/f92cda29_1793_409c_a86c_69f4d520a979
GNOME_SETUP_DISPLAY=:1
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=tempuser
GNOME_TERMINAL_SERVICE=:1.90
DISPLAY=:0
SHLVL=1
XDG_RUNTIME_DIR=/run/user/1002
DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
XDG_DATA_DIRS=/home/tempuser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1002/bus
MAIL=/var/spool/mail/tempuser
_=/usr/bin/env
```

**Comment by C0rn3j** [comment]
So it works fine on the new user?

**Comment by Loup-Garou911XD** [comment]
> So it works fine on the new user?

nope,same behaviour

**Comment by Loup-Garou911XD** [comment]
I didn't mention a few things that I should have
I am using a theme
The behaviour isn't consistent
- sometimes i can login immediately
- sometimes it logs me in after some time after entering password
- sometimes returns me to sddm screen after entering password and waiting on black screen for a while
