### ISSUE TITLE
sddm login with HideUsers in sddm.conf

### ISSUE THREAD

**Issue by Ouaille-Aime-Scier** [sddm/sddm#1864]
Hi sddm team,

In a plasma desktop environnment on KaOS distro, with an other SDDM theme than Breeze, when I put my user for HideUsers in sddm.conf file, SDDM don't give me access to my user for loging. Same behaviour on ArcoLinux.

See https://forum.kaosx.us/d/3123-sddm-login-with-hideusers-in-sddmconf.

Regards.

**Comment by Vogtinator** [comment]
That is exactly what HideUsers is for though?

> Comma-separated list of Users that shouldn't show up in the user list.

To log in as that user anyway you'll have to be able to type in the user name manually, which depends on the theme.

**Comment by Ouaille-Aime-Scier** [comment]
> That is exactly what HideUsers is for though?
> 
> > Comma-separated list of Users that shouldn't show up in the user list.
> 
> To log in as that user anyway you'll have to be able to type in the user name manually, which depends on the theme.

Hello @Vogtinator,

Yes I know that the HideUsers variable is hiding users list but it also hides the user and password input area, I am unable to seize my login name if SDDM theme is an other than Breeze.

**Comment by Vogtinator** [comment]
> Yes I know that the HideUsers variable is hiding users list but it also hides the user and password input area,

That's a bug in whatever theme you're using.

**Comment by Ouaille-Aime-Scier** [comment]
> > Yes I know that the HideUsers variable is hiding users list but it also hides the user and password input area,
> 
> That's a bug in whatever theme you're using.

Yes with all themes, including the default Maui and only Breeze theme give me access to manual user and password input areas.

**Comment by Vogtinator** [comment]
Well, themes can provide different behaviour and features which is intended. The `HideUsers` option also works as intended here. If a specific theme doesn't work for you, you can try to get that theme changed or switch to a different one.

**Comment by demmm** [comment]
Shouldn't the default theme shipped in SDDM not provide the correct behavior? When you mention `works as intended here` are you referring to Breeze or default SDDM?

**Comment by Vogtinator** [comment]
Both. It's fine for a theme not to offer login to users which are explicitly hidden. It's also fine for themes to allow manual entry of usernames to bypass that.

**Comment by Ouaille-Aime-Scier** [comment]
> Both. It's fine for a theme not to offer login to users which are explicitly hidden. It's also fine for themes to allow manual entry of usernames to bypass that.

The HideUsers parameter is made to hide the regular users list from those who would try to access the machine, it is not intended to prevent these authorized users to log.
