### ISSUE TITLE
[Feature Request] 24hour and 12hour settings

### ISSUE THREAD

**Issue by Firestar-Reimu** [sddm/sddm#1867]
[Feature Request] Add a settings for 24hour/12hour in the login screen, better sync settings from the digital clock.

**Comment by Vogtinator** [comment]
Which theme?

**Comment by Firestar-Reimu** [comment]
Plasma theme.

If I want to change it to 24h, I should change `/usr/share/sddm/themes/(theme_name)/Clock.qml` >> `Qt.formatTime`

from `text: Qt.formatTime(timeSource.data["Local"]["DateTime"])` to `text: Qt.formatTime(timeSource.data["Local"]["DateTime"], "H:mm:ss")`

**Comment by Vogtinator** [comment]
That's not something SDDM controls but entirely up to the theme. You'll need to file a feature request for the specific theme you're using.

**Comment by Vogtinator** [comment]
(There is an SDDM supplied Clock component, but at least Breeze doesn't use that as it uses Plasma supplied components instead.)
