### ISSUE TITLE
SDDM 0.20 breaks Multiseat.

### ISSUE THREAD

**Issue by meyerkc135** [sddm/sddm#1868]
Version 0,19 worked great, upgrading to 0.20 broke it (during a Fedora system update. Regressing multiseat back to 0.19 restores functionality. This is for multiseat functionality - 2 simultaneous users on one machine - 2 video cards, 2 sets of monitors, 2 USB hubs, etc...

seat0 worked flawlessly, seat-1 had multiple issues :
- user not shown as logged in, 
- no ability to get sound working (works perfectly - built-in (ASUS Z690) and/or USB/Bluetoth sound on seat0, AMD RX540 and/or USB Headset on seat-1. 
- commands such as dmesg were rejected
Amongst other issues.

Currently running Fedora39, issues started around the 36 update. Found where regressing to 0,19 was a potential solution - it is.

**Comment by Vogtinator** [comment]
Same as https://github.com/sddm/sddm/issues/1762?

**Comment by meyerkc135** [comment]
Yes, you're right - it appears so. 
I did a search for multiseat under SDDM and didn't find it - though I'm new to Github and trying to learn... If there's a way to delete this, great. If not, hopefully this will point others to the issue in work.
Thank you!

**Comment by n3rdopolis** [comment]
Should this be closed now?

**Comment by Vogtinator** [comment]
Yup, let's assume https://github.com/sddm/sddm/issues/1762 fixed it
