### ISSUE TITLE
Unable to switch DE after logging out

### ISSUE THREAD

**Issue by dietzcodes** [sddm/sddm#1869]
I am unable to switch to another desktop environment/window manager/compositor after logging out of KDE, and I instead am logged back into KDE after attempting to switch.

I have absolutely no idea if this is a KDE issue or an SDDM issue, but somebody on the KDE forums here suggested that it might be an SDDM issue: [https://discuss.kde.org/t/unable-to-switch-to-another-desktop-after-logging-out/10403](url)

As a result, I figured I would post this here, despite having no idea how to reproduce on another computer besides just logging out and attempting to switch desktop environments.

**Comment by Vogtinator** [comment]
Do you have the journal for the relevant timeframe?

**Comment by dietzcodes** [comment]
Huh, the issue must have been fixed at some point because I just tried switching sessions on my laptop and it worked fine, I guess the issue is resolved and something's just wrong with my current install on my desktop(I got the laptop after the issue was posted so I apologize for wasting your time).

**Comment by dietzcodes** [comment]
Huh, the issue must have been fixed at some point because I just tried switching sessions on my laptop and it worked fine, I guess the issue is resolved and something's just wrong with my current install on my desktop(I got the laptop after the issue was posted so I apologize for wasting your time).
