### ISSUE TITLE
sddm-greeter-qt6 is core dumping on 0.21

### ISSUE THREAD

**Issue by edt-xx** [sddm/sddm#1875]
On an up to date arch system on 6.7.6 with 0.21 (aur sddm-git) the greeter does not display and I find the following coredump in my logs.  I've reverted to 0.20 (from 19 Dec).  What else do you need?

```
Feb 26 21:08:04 grover sddm-greeter-qt6[1295]: No shell integration named "layer-shell" found
Feb 26 21:08:04 grover sddm-greeter-qt6[1295]: Loading shell integration failed.
Feb 26 21:08:04 grover sddm-greeter-qt6[1295]: Attempted to load the following shells QList("layer-shell")
Feb 26 21:08:04 grover sddm-greeter-qt6[1295]: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Feb 26 21:08:04 grover sddm-greeter-qt6[1295]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
                                               
                                               Available platform plugins are: wayland-egl, wayland, eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.
Feb 26 21:08:04 grover systemd[1]: Started Process Core Dump (PID 1345/UID 0).
Feb 26 21:08:04 grover kernel: razermouse: Command timed out. status: 04 transaction_id.id: ff remaining_packets: 00 protocol_type: 00 data_size: 16, command_class: 00, command_id.id: 8>
Feb 26 21:08:04 grover systemd-coredump[1348]: [🡕] Process 1295 (sddm-greeter-qt) of user 991 dumped core.
                                               
                                               Stack trace of thread 1295:
                                               #0  0x00007f4bcceab32c n/a (libc.so.6 + 0x8d32c)
                                               #1  0x00007f4bcce5a6c8 raise (libc.so.6 + 0x3c6c8)
                                               #2  0x00007f4bcce424b8 abort (libc.so.6 + 0x244b8)
                                               #3  0x00007f4bcd48a924 n/a (libQt6Core.so.6 + 0x8a924)
                                               #4  0x00007f4bcd48b135 _ZNK14QMessageLogger5fatalEPKcz (libQt6Core.so.6 + 0x8b135)
                                               #5  0x00007f4bcdad9be9 n/a (libQt6Gui.so.6 + 0xd9be9)
                                               #6  0x00007f4bcdb74a18 _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt6Gui.so.6 + 0x174a18)
                                               #7  0x00007f4bcd53db15 _ZN23QCoreApplicationPrivate4initEv (libQt6Core.so.6 + 0x13db15)
                                               #8  0x00007f4bcdb74ac1 _ZN22QGuiApplicationPrivate4initEv (libQt6Gui.so.6 + 0x174ac1)
                                               #9  0x00007f4bcdb6c4fb _ZN15QGuiApplicationC2ERiPPci (libQt6Gui.so.6 + 0x16c4fb)
                                               #10 0x00005563f81780a6 n/a (sddm-greeter-qt6 + 0x120a6)
                                               #11 0x00007f4bcce43cd0 n/a (libc.so.6 + 0x25cd0)
                                               #12 0x00007f4bcce43d8a __libc_start_main (libc.so.6 + 0x25d8a)
                                               #13 0x00005563f8178a25 n/a (sddm-greeter-qt6 + 0x12a25)
                                               ELF object binary architecture: AMD x86-64
Feb 26 21:08:04 grover systemd[1]: systemd-coredump@1-1345-0.service: Deactivated successfully.
```

**Comment by Vogtinator** [comment]
`No shell integration named "layer-shell" found`

Your config forces the greeter to use layer-shell but layer-shell isn't installed for Qt 6.

**Comment by edt-xx** [comment]
That comes from:

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen
with the breeze theme selected.  Any idea what installs layer-shell on Arch?  Alternately what should I be using for qt6 with wayland?

**Comment by Vogtinator** [comment]
> with the breeze theme selected. Any idea what installs layer-shell on Arch? Alternately what should I be using for qt6 with wayland?

Plasma 6 ships a layer-shell plugin. No idea how the package is called on Arch.

**Comment by edt-xx** [comment]
its in kde-unstable called layer-shell-qt.  Installing it does not fix the issue.  Still dumps.  How do I tell sddm to use qt5?  At least till Arch switches to plasma 6?

**Comment by Vogtinator** [comment]
You'll have to use a Qt 5 theme and make sure you ahve the Qt 5 greeter installed.

**Comment by edt-xx** [comment]
How do I do that?  Alternately it looks like there is a greeter for wayland using weston.  What would I need to specify in:

GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

to select the weston greeter?  I'll update the Arch aur package comments once this is working here - faq for wayland will have many arch users using the directive above...

**Comment by Vogtinator** [comment]
I have absolutely no idea about arch, but this is invalid configuration.

If you use `GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell` with a Qt 6 theme, layer-shell for Qt 6 must be installed.

**Comment by edt-xx** [comment]
What else can I use?  I've been looking for docs but not finding much.   Looks like most of the packages needed for qt6 / plasma6 support in Arch are in the kde-unstable repository (which I'd avoid till plasma6 is released).  Also installing layer-shell for qt6 (from kde-unstable) just leads to another coredump with other missing packages.  So I need to either stick to 0.20 till plasma6 is released or change the greeter to use something else (I'd rather avoid X).

**Comment by Vogtinator** [comment]
Or just use a Qt 5 theme like before. That's the only difference to 0.20.

**Comment by edt-xx** [comment]
I did not change my theme.  0.20 uses breeze, same config in 0.21 and it has problems.  What theme will work with:
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=xdg-shell

[Wayland]
CompositorCommand=weston --shell=kiosk

with breeze set I find:
Feb 27 10:11:09 grover sddm[6151]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
Feb 27 10:11:09 grover sddm[6151]: The theme at "/usr/share/sddm/themes/breeze" requires missing "/usr/bin/sddm-greeter" . Using fallback theme.
Feb 27 10:11:09 grover sddm[6151]: Loaded empty theme configuration

and get a blank screen but no coredumps

**Comment by Vogtinator** [comment]
The issue is that your sddm 0.21 supports only Qt 6 themes but your breeze is Qt 5 only.

You'll either have to install a Qt 5 sddm 0.21 or Breeze 6.

**Comment by edt-xx** [comment]
building with -DBUILD_WITH_QT6=OFF produces a version that works.  

Thanks for the help.
