### ISSUE TITLE
SDDM themes not loading

### ISSUE THREAD

**Issue by Krys87** [sddm/sddm#1890]
Since upgrading to Plasma 6 no themes are loading anymore:

```sh
[krys@archlinux ~]$ journalctl | grep "org.kde.plasma.private.sessions"
Mar 10 03:34:11 archlinux sddm-greeter[516]: file:///usr/share/sddm/themes/Breeze-Noir-Dark/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed 
                                                  import org.kde.plasma.private.sessions 2.0 
Mar 10 03:34:11 archlinux sddm-greeter[516]: file:///usr/share/sddm/themes/Breeze-Noir-Dark/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed 
                                                  import org.kde.plasma.private.sessions 2.0 
Mar 10 03:39:58 archlinux sddm-greeter[509]: file:///usr/share/sddm/themes/monochrome/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed 
                                                  import org.kde.plasma.private.sessions 2.0 
Mar 10 03:39:58 archlinux sddm-greeter[509]: file:///usr/share/sddm/themes/monochrome/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed 
                                                  import org.kde.plasma.private.sessions 2.0 
Mar 10 04:54:03 archlinux sddm-greeter[516]: file:///usr/share/sddm/themes/Breeze-Noir-Dark/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed 
                                                  import org.kde.plasma.private.sessions 2.0 
Mar 10 04:54:03 archlinux sddm-greeter[516]: file:///usr/share/sddm/themes/Breeze-Noir-Dark/components/WallpaperFader.qml:28:1: module "org.kde.plasma.private.sessions" is not installed
```

This is the `WallpaperFader.qml`

```sh
import org.kde.plasma.private.sessions 2.0
import "../components"
```

I know other users have the same issue where no theme is loading anymore

The log message is clear, the qml has the import statement but the `org.kde.plasma.private.sessions` seems missing - but missing from where? 

Any ideas whats wrong here?

**Comment by Vogtinator** [comment]
Your SDDM theme requires Plasma 5.

**Comment by kjkent** [comment]
Unsure if SDDM is an official part of Plasma, but, if so, it might be worth considering back-compatibility as it seems a significant proportion of the SDDM themes available via the KDE System Settings menu ("Get New...") are now unusable.

**Comment by Vogtinator** [comment]
> Unsure if SDDM is an official part of Plasma, but, if so, it might be worth considering back-compatibility as it seems a significant proportion of the SDDM themes available via the KDE System Settings menu ("Get New...") are now unusable.

SDDM is fully backwards compatible there, but Plasma is not. Themes which require Plasma 5 won't work with Plasma 6 and vice versa.

**Comment by Krys87** [comment]
The plasma 5 themes should be removed from the menu when using plasma 6 and
vice versa.. But this must be filed at the plasma front. Its nothing
critical but its annoying

**Comment by kjkent** [comment]
Makes sense; it'll naturally improve over time and I guess there's more pressing things. Searching for Plasma 6 in the "Get New..." dialogue does bring up a few!

Thanks for the info and your (and the other contributors') hard work on SDDM 🙏

**Comment by adogecheems** [comment]
You can install a package to get compatibility with plasma5 if necessary using the following command:
`sudo pacman -S plasma-framework5`

**Comment by iaceene** [comment]
The issue was that `/usr/bin/sddm-greeter` was missing.

Your system has the Qt6 version (`sddm-greeter-qt6`) but the Sweet theme was looking for the generic `sddm-greeter` binary. By creating the symlink:

```bash
sudo ln -s /usr/bin/sddm-greeter-qt6 /usr/bin/sddm-greeter
```
SDDM could now find and launch the greeter with your Sweet theme. The theme apparently works fine with the Qt6 greeter despite being designed for Qt5.
