### ISSUE TITLE
Test mode cannot locate plasma components

### ISSUE THREAD

**Issue by es20490446e** [sddm/sddm#1892]
Running on Plasma 6, if you do:
```
sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze | grep "(WW)"
```
It compains that library import requires a version.

If you remove the non versioned lines on `/usr/share/sddm/themes/breeze/Main.qml`, then it complains that plasma modules are not installed.

But if you just use Breeze on the login screen, it works. So test mode and actual SDDM behave differently.

**Comment by es20490446e** [comment]
Installing plasma-framework5 work-arounds the problem.

**Comment by es20490446e** [comment]
- [Report on KDE](https://bugs.kde.org/show_bug.cgi?id=483433)

**Comment by Vogtinator** [comment]
You need to run `sddm-greeter-qt6`.
