### ISSUE TITLE
SDDM Wayland does not go into monitor powersave

### ISSUE THREAD

**Issue by mcloaked** [sddm/sddm#1897]
Running Arch Linux with Plasma 6 ( 6.0.2-4 ) under a Wayland session but with SDDM ( 0.21.0-4 ) all fully updated to latest versions runs fine with SDDM running as default under X11.  If SDDM is made to run in Wayland by adding in the file /etc/sddm.conf.d/10-wayland.conf with contents:

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell,XKB_DEFAULT_LAYOUT=gb

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1

allows SDDM to run in Wayland, with the correct locale.  

However if no user logs in then the monitor remains powered on indefinitely, whereas when running under X11 it will timeout and put the monitor into powersave after the timeout period.

This timeout should also be honoured when running under Wayland in order to conserve energy and the monitor should go into powersave mode after the timeout period until a user moves the mouse or presses a keyboard key and then logs in.

Also if the computer is a server then when detecting IdleMonitor suspend would not be appropriate, even though monitor powersave would be very valuable.

**Comment by Vogtinator** [comment]
Same as https://github.com/sddm/sddm/issues/1710.

It's not clear what's responsible for DPMS. IMO kwin, so should be filed at bugs.kde.org.

**Comment by mcloaked** [comment]
Posted bug report at https://bugs.kde.org/show_bug.cgi?id=484015

**Comment by ryanmusante** [comment]
Seeing this issue as well on my KDE setup, no movement on bug fix?
