### ISSUE TITLE
Return to login form by pressing escape key?

### ISSUE THREAD

**Issue by geos-github** [sddm/sddm#1915]
When the sddm login screen is left idle for a few moments, the login form disappears (and the background image is no longer blurred). One can return to the login form by typing a letter or a number.
Would it be possible to have sddm go back to/evoke the login form also when the escape key is pressed?

**Comment by Vogtinator** [comment]
That's specific to the Plasma SDDM (and lockscreen) theme, SDDM has no influence there.

IIRC the escape key actually hides the main block explicitly.

**Comment by geos-github** [comment]
So this behavior is specific to the theme used and could be configured/programmed in the individual theme?
BTW, I did my test with the breeze theme.

**Comment by Vogtinator** [comment]
> So this behavior is specific to the theme used and could be configured/programmed in the individual theme?

Yes.

**Comment by geos-github** [comment]
Thanks for clarifying.
