### ISSUE TITLE
Sddm and OLD PC (2007 produced).

### ISSUE THREAD

**Issue by alexzk1** [sddm/sddm#1926]
PC was off for a year. Today I turned it on, updated to kernel 6.8.9 and current SDDM never pops up.
I tried to install rngd. 
`# rngd -f` shows that there are no hardware random sources.
Eventually I replaced SDDM by another DM and all is working again.

I think this is not good at all when simple login screens just do not work because of missing randomness silently. It could print out something in console at least, some watchdog on it, with hints.

CPU is Athlon Dual-Core QL-60 there.

**Comment by Vogtinator** [comment]
Please provide a backtrace so we can tell what's actually doing a blocking wait for randomness there. Maybe it's the xauth cookie generation, maybe it's something completely out of our control.

**Comment by alexzk1** [comment]
Not sure what trace do you need, in log it has "SDDM starting". In console it is "reaching graphical target" from the systemd.
It's old machine. I had to solve many problems at once, like 10 years old nvidia driver on new kernel, sddm, and so on. 
I found article in arch-wiki that in can be missing entropy. I tried rngd which said "no random device". So I just replaced SDDM.
Also, I recall 2 years ago on Atom N4555 processor fresh arch linux (at that moment) stopped to load because of the entropy too.

No more additional information, it does not generate errors or anything like that. SDDM just stays forever doing nothing after printing "starting". I could stop and  restart service too from another console.

**Comment by Vogtinator** [comment]
> SDDM just stays forever doing nothing after printing "starting".

At that point please attach gdb and get a backtrace with `gdb -p $(pidof sddm) -ex 'thread apply all bt' -ex q`

**Comment by alexzk1** [comment]
[sddm.log](https://github.com/sddm/sddm/files/15245474/sddm.log)

Command was:
`gdb -p $(pidof sddm) -ex 'thread apply all bt' -ex q |& tee sddm.log`

Greeter didn't show up. Console screen is black as usual with startup messages.

**Comment by Vogtinator** [comment]
It's not stuck. I guess it's a different issue and unrelated to randomness.

Check the value of `CanGraphical` using `qdbus(-qt5,6) --system org.freedesktop.login1 /org/freedesktop/login1/seat/seat0 org.freedesktop.DBus.Properties.GetAll org.freedesktop.login1.Seat`. If it's `false`, it's a systemd or kernel bug that they don't see a DRM capable GPU.

**Comment by alexzk1** [comment]
Yes, it is `false` for 5/6. Well, that old nvidia driver does not have `nvidia_drm`. Instead it has `nvidia_uvm`.

**Comment by Vogtinator** [comment]
CanGraphical must be true to be able to use sddm, so this is a Nvidia and/or systemd bug. 

As a workaround you can use `nomodeset`.
