### ISSUE TITLE
Unable to write username with lower case

### ISSUE THREAD

**Issue by jgrocha** [sddm/sddm#1930]
I'm not able to write my login name with just lowercase letters.

If I enter: 
`jgr` → the username will be `Jgr`.
`Jjgr` and then delete the first letter, the second is changed to uppercase and I get `Jgr` again.

The first letter is always changed to uppercase.

Does anyone know a workaround?

![image](https://github.com/sddm/sddm/assets/163681/0e72a4d9-9f41-4753-9832-277299e25d0d)

I'm using:
```
ii  sddm                                           0.19.0-2ubuntu2.3                            amd64        modern display manager for X11
ii  sddm-theme-debian-maui                         0.19.0-2ubuntu2.3                            all          'Debian Maui' theme for SDDM X11 display manager
```
Can it be a theme problem and not an sddm issue?

Current theme:
```
cat /etc/sddm.conf
[Theme]
Current=sugar-candy
```

**Comment by Vogtinator** [comment]
That does indeed sound like a theme issue.

Does login still work? If so, it's a display problem and not an input problem and might in fact be intentional, e.g. using the `Font.Capitalize` option for `TextEdit`.

**Comment by jgrocha** [comment]
> That does indeed sound like a theme issue.
> 
> Does login still work? If so, it's a display problem and not an input problem and might in fact be intentional, e.g. using the `Font.Capitalize` option for `TextEdit`.

Thanks @Vogtinator for the feedback.

It is a theme issue. A simple `grep -r Capitalize *` returns:

```
jgr@dragon:/usr/share/sddm/themes/sugar-candy$ grep -r Capitalize *
Components/Input.qml:                    font.capitalization: Font.Capitalize
Components/Input.qml:            font.capitalization: config.AllowBadUsernames == "false" ? Font.Capitalize : Font.MixedCase
Components/UserList.qml:                font.capitalization: Font.Capitalize
Components/UserList.qml:        font.capitalization: Font.Capitalize
```
