### ISSUE TITLE
SDDM rejects first password attempt after system wakes from sleep. 

### ISSUE THREAD

**Issue by leehead5150** [sddm/sddm#1941]
every time i wake my system from sleep, it rejects the first password attempt. i know i've typed it correctly as verified by the show password function on the login screen. i'm able to log in on the second attempt. this only happens when its coming out of sleep. i am able to login on the first attempt from boot, lock screen, logout, etc 

my system...

OS: Fedora Linux 40 (KDE Plasma) x86_64
Host: HP EliteBook x360 1030 G3 (SBKPF)
Kernel: Linux 6.8.10-300.fc40.x86_64
Shell: bash 5.2.26
Display (CMN1380): 1920x1080 @ 60Hz (as 960x540) [Built-in]
DE: KDE Plasma 6.0.5
WM: KWin (Wayland)
WM Theme: Vivid-Blur-Dark-Aurorae-6
Theme: Fusion (VividCyanDarkColorscheme) [QT], Breeze [GTK3/4]
Icons: Colorful-Dark-Icons [QT], Colorful-Dark-Icons [GTK3/4]
Font: Noto Sans (10pt) [QT], Noto Sans (10pt) [GTK3/4]
Cursor: Future-cyan (24px)
Terminal: konsole 24.2.2
CPU: Intel(R) Core(TM) i5-8350U (8) @ 3.60 GHz
GPU: Intel UHD Graphics 620 @ 1.10 GHz [Integrated]
Memory: 4.25 GiB / 7.60 GiB (56%)
Swap: 1.07 GiB / 7.60 GiB (14%)
Disk (/): 52.85 GiB / 193.31 GiB (27%) - btrfs
Disk (/mnt/Windows): 162.25 GiB / 280.99 GiB (58%) - fuseblk
Local IP (wlp108s0):
Battery: 78% [Discharging]
Locale: en_US.UTF-8

**Comment by Vogtinator** [comment]
Full journal please.

I guess something trips up pam_nologin (through `/run/nologin`) or maybe pam_systemd.

**Comment by leehead5150** [comment]
i replied to your email. I haven't heard any more requests for information or log format. so i started wondering if you had ever received the log file. i attached it here just in case. 
[full_journal.log.gz](https://github.com/user-attachments/files/15751042/full_journal.log.gz)

**Comment by Just4pLeisure** [comment]
I too have what I believe to be the same issue Lee and see timestamped messages coinciding with the rejected password like those in your log. e.g. :

`Jun 08 12:16:25 HPEBX3601030G3 kscreenlocker_greet[22273]: pam_unix(kde:auth): auth could not identify password for [lhead]
Jun 08 12:16:25 HPEBX3601030G3 kscreenlocker_greet[22273]: pam_unix(kde:auth): conversation failed
Jun 08 12:16:25 HPEBX3601030G3 kscreenlocker_greet[22273]: pam_unix(kde:auth): unexpected response from failed conversation function`

I think it is a PAM problem too, but have no idea how to debug or resolve. I'd like to help and get this small but somewhat frustrating issue resolved. The only other tidbit I can add is that I _think_ this started when I upgraded from Fedora 39 to 40...

**Comment by Vogtinator** [comment]
If it's `kscreenlocker_greet` it's actually the Plasma screenlocker that's failing here and unrelated to SDDM. Please report that on https://bugs.kde.org and link that here.

If I interpret the lock correctly, what happens is actually:
1. You lock the screen
2. You click on the "suspend button"
3. This somehow triggers a broken PAM conversation
4. The system suspends
5. When the system wakes back up, it's still somehow influenced by the broken PAM session before suspend.

The cause for that is probably 3. I think I've seen that here on my system as well, but didn't have any problems with unlocking later.

**Comment by Just4pLeisure** [comment]
Thank you for your analysis Fabian, I have reported it as you asked: 
https://bugs.kde.org/show_bug.cgi?id=490924
