### ISSUE TITLE
SDDM doesn't respect keyboard layout and defaults to us

### ISSUE THREAD

**Issue by izdener** [sddm/sddm#1942]
/etc/locale.conf has: LANG="hu_HU.UTF-8"

localectl output:
System Locale: LANG=hu_HU.UTF-8
VC Keymap: hu
X11 Layout: hu
X11 Model: pc105
---
how can I set SDDM to respect system locale?

I use a custom ublue-os with hyprland.

**Comment by Vogtinator** [comment]
SDDM respects that. Due to a bug it always shows `us` as layout on startup though. Is that the case for you?

**Comment by izdener** [comment]
No, the system locale is set to my native language Hungarian, but SDDM sets itself to US. (In wayland session).

**Comment by Vogtinator** [comment]
> No, the system locale is set to my native language Hungarian, but SDDM sets itself to US. (In wayland session).

What do you mean by "sets itself"? SDDM does not set the keyboard layout on startup at all, it only displays it.

**Comment by izdener** [comment]
I mean everything else is in my language, but SDDM. So I assume, it doesn't pick up the locales from the system.

`localectl:
System Locale: LANG=hu_HU.UTF-8
    VC Keymap: hu
   X11 Layout: hu
    X11 Model: pc105
  X11 Options: terminate:ctrl_alt_bksp`

**Comment by Vogtinator** [comment]
> I mean everything else is in my language, but SDDM.

So it's about translations, not the keyboard layout?
