### ISSUE TITLE
how does a display manager work?

### ISSUE THREAD

**Issue by natesworksold** [sddm/sddm#1944]
Im trying to use startx to start my display manager it starts but i cant see it

Works if i ran from another de tho then the display manager is pointless

Sorry for offtopic idk where to post this

**Comment by ibra-kdbra** [comment]
Ask this in arch community..
[Reddit](https://www.reddit.com/r/archlinux/)
Or ask on in linux community:
[Reddit](https://www.reddit.com/r/linux/)

**Comment by natesworksold** [comment]
> Ask this in arch community..
> [Reddit](https://www.reddit.com/r/archlinux/)
> Or ask on in linux community:
> [Reddit](https://www.reddit.com/r/linux/)

Thanks
