### ISSUE TITLE
sddm doesn't displays theme like how it displays with sddm-greeter-qt6 --test-mode command.

### ISSUE THREAD

**Issue by syrupderg** [sddm/sddm#1946]
I'm using Arch linux with KDE plasma. I'm trying to make a custom theme but when I check my theme with sddm-greeter-qt6 --test-mode command it looks like this:

![](https://github.com/sddm/sddm/assets/67545942/1e0de8c0-38a6-453e-acb3-bfdac0d52ff4)
![](https://github.com/sddm/sddm/assets/67545942/6ad892bd-0500-4a4b-8c9d-f0ef3bb7eda3)
![](https://github.com/sddm/sddm/assets/67545942/54140d37-dd53-4c33-9c8d-d8c757aa30c3)
![](https://github.com/sddm/sddm/assets/67545942/a3f625af-23ab-4d25-af71-8d616f0efbc3)

But when I apply my theme from kde system settings it looks like this:

![IMG_20240602_232509](https://github.com/sddm/sddm/assets/67545942/7e763f96-cd2d-4a3d-bc01-8728a5a36b0d)
![IMG_20240602_232518](https://github.com/sddm/sddm/assets/67545942/70a93803-9a47-450f-881e-53b177ba5fd7)
![IMG_20240602_232526](https://github.com/sddm/sddm/assets/67545942/987449a0-5d36-48ad-83b4-54b04af0df98)
![IMG_20240602_232534](https://github.com/sddm/sddm/assets/67545942/808979fd-4cbf-448f-9961-9fc9dd9120dc)

Icons are bigger than they should, font sizes are not right and some of the sizings are different (password bar)
i tried changing qt versions from metadata.desktop file but it didnt made a difference, i checked with journalctl and it was showing that sddm greeter is loading this in qt 6 version if i set it to 6 in metadata file. source files of my theme are here: https://github.com/birbkeks/win-sddm

**Comment by Vogtinator** [comment]
The Plasma environment has some Plasma plugins which can alter behavior and appearance.

You can try using `env -i HOME=$HOME DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/breeze-openSUSE/` to get an environment which is a bit closer.

**Comment by syrupderg** [comment]
> The Plasma environment has some Plasma plugins which can alter behavior and appearance.
> 
> You can try using `env -i HOME=$HOME DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/breeze-openSUSE/` to get an environment which is a bit closer.

with that command i get the same theme display when i use it. how can i fix this problem? i want it to be exactly like the first image but i dont know what exactly causes the problem.

**Comment by Vogtinator** [comment]
TBH I don't see any differences there.

It might be using the org.kde.breeze Qt Quick Controls 2 style.

**Comment by syrupderg** [comment]
where can i find sytle locations?

**Comment by Vogtinator** [comment]
Depends on the distro. Not sure how you could override that from an SDDM theme though, you'd need some C++ code or environment variables...

**Comment by syrupderg** [comment]
> TBH I don't see any differences there.
> 
> It might be using the org.kde.breeze Qt Quick Controls 2 style.

i found out that if i dont run env with "-i" option it displays like how it should. also i dont get an error releated to locale.
![image](https://github.com/sddm/sddm/assets/67545942/935275f9-24d4-492d-9a8a-251f246b5617)

**Comment by Vogtinator** [comment]
Yes, the `-i` is the important part...

**Comment by syrupderg** [comment]
> Yes, the `-i` is the important part...

i managed to fix most of the stuff by rewriting my code but i still couldnt manage to fix icons, no matter what i do, they look much more worse than how they should even though im using svg files. i cant match the same size and even if i do they look very bad.

bad one:
![image](https://github.com/sddm/sddm/assets/67545942/8f420e56-8dd6-422c-9df6-ee1cbe92347a)

how it should be displayed:
![image](https://github.com/sddm/sddm/assets/67545942/46b422a3-a998-4280-bb8b-15c0f637015a)

**Comment by Vogtinator** [comment]
Looks like something might be offset by a fraction of a pixel. You could try rounding some sizes and positions.

**Comment by syrupderg** [comment]
> Looks like something might be offset by a fraction of a pixel. You could try rounding some sizes and positions.

i tried that but it doesnt work. it still looks bad and blurry. also i noticed that icon problem also happens on maui theme too somehow, it doesnt shows combobox (session) icon, layout box arrow icon, power and reboot icon.

**Comment by syrupderg** [comment]
i found out that "sddm-greeter-qt6 --test-mode command" doesnt care about width, height, color or any values i change for icon and it looks better but the command that starts with "env -i" does care about values i changed, tho not typing any width or height values doesnt changes a thing unlike the buttons in the power popup panel :/

**Comment by syrupderg** [comment]
i made it look bigger to show how different they look. this is the letter T as an example, this sort of thing happens to icons too. 

with "sddm-greeter-qt6 --test-mode --theme" command:
![image](https://github.com/sddm/sddm/assets/67545942/5013d84e-7421-4232-9c23-6ead7b5c9498)

with "env -i HOME=$HOME DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sddm-greeter-qt6 --test-mode --theme" command:
![image](https://github.com/sddm/sddm/assets/67545942/649ecc22-9bca-46b9-a74e-aa605adffe00)

**Comment by syrupderg** [comment]
@Vogtinator lol i found a way to fix this, literally the same thing as microsoft does, using a custom font for icons with renderType: Text.QtRendering works really well. from my testings this happens on every sddm theme, even on breeze. only downside is this takes a little bit more time but the results are worth it. i also noticed that maui theme is very old and needs to be updated.
