### ISSUE TITLE
Screen flashes if ESC is hit at login screen, when the screen is off

### ISSUE THREAD

**Issue by fishBone000** [sddm/sddm#1947]
At login screen, hitting ESC turns the screen off. But if the screen is already off, the screen will turn on, then off in a short time.  
I think sddm wakes up the screen when it detects the keystroke, but turns it off once it finds it's ESC key.  
Sounds kind of dumb, perhaps change this behavior? And if it's Xorg or sth else instead of sddm that wakes up the screen, is it possible to prevent it on sddm's side?

Also try holding ESC when the screen is off.

**Comment by Vogtinator** [comment]
That sounds weird. SDDM does not handle Esc, nor does Xorg.

Which theme do you use? Maybe that causes an entirely black screen when hitting Esc, triggering some monitor standby...

**Comment by fishBone000** [comment]
Breeze, configured via KDE System Settings  
I will try to change themes and see if it helps, later today

**Comment by fishBone000** [comment]
I did some tests.  
It seems that it would be no problem if it's the first spawned login screen, the one after I boot up my laptop, that is. Let's call it the system login screen, for convenience. (I don't know how you call it internally)
But if it's the login screen that shows up after I hit CTRL-L in KDE, then hitting ESC will cause the flashing screen. Let's call it the user login screen. 

I tried to change the themes in the config files, and it does change the theme of the system login screen. But the theme of user login screen is unaffected, it seems to be controlled by KDE.  
I will try to change the user login screen via KDE's settings panel later.

**Comment by Vogtinator** [comment]
> But if it's the login screen that shows up after I hit CTRL-L in KDE, then hitting ESC will cause the flashing screen. Let's call it the user login screen.

That's the lockscreen and it's actually unrelated to SDDM. You can report this to KDE.
