### ISSUE TITLE
Wrong cursor icon style 

### ISSUE THREAD

**Issue by syrupderg** [sddm/sddm#1954]
SDDM doesn't shows the right cursor icon style when i startup my system. Even if I delete that cursor icon style 
SDDM still uses the wrong cursor icon style. I think SDDM itself uses adwaita cursor icon style or kde classic cursor icon theme by default but removing them doesn't changes a thing. This issue happens on all SDDM themes. This bug doesn't happens on test mode. I'm on Arch Linux, Plasma 6.1

**Comment by Firestar-Reimu** [comment]
See #1894?

**Comment by syrupderg** [comment]
> See #1894?

https://github.com/sddm/sddm/issues/1894#issuecomment-2041232191 sddm uses cursors from /usr/share/icons/default/ directory and doesnt care /etc/sddm.conf nor /etc/sddm.conf.d/kde_settings.conf. workaround is creating a link or copying to the default folder and changing "inherits" from index.theme.
