### ISSUE TITLE
SDDM says invalid password if the user has no password (session unlocking)

### ISSUE THREAD

**Issue by bug-fix0r** [sddm/sddm#1963]
If the user has no password SDDM will always say wrong password making it impossible to unlock a session. I am talking about unlocking a session and not logging in.

On the Kubuntu live ISO the default user named **kubuntu** has no password. When you leave the password field empty and hit enter in SDDM it will say "Unlocking failed". That's why many people can't unlock their session after Kubuntu locked it automatically. 

I have only tried Kubuntu but I suppose it affects SDDM in general.

https://www.reddit.com/r/Ubuntu/comments/zwjxwk/ubuntu_studio_2210_live_session_user_password/

https://www.kubuntuforums.net/forum/archives/eol-releases/-15-10/pre-installation-an/63352-kubuntu-15-10-asks-for-password-for-live-session

**Comment by Vogtinator** [comment]
Works fine here on the openSUSE live iso. Make sure PAM allows login with empty password.

**Comment by ohyeaah** [comment]
@Vogtinator When I login in a tty (Ctrl + Alt + F...) I can login using the empty password. That's why I thought it's an SDDM issue. However I'm not an expert.

**Comment by grahamperrin** [comment]
Historical (fixed in 2022): 

- KDE bug [440055 – Can't unlock the screen if the user has an empty password](https://bugs.kde.org/show_bug.cgi?id=440055)

**Comment by bug-fix0r** [comment]
From what I know it's a problem with kscreenlocker and not sddm. That's why I closed the issue.
