### ISSUE TITLE
How to return to my desktop after testing the theme

### ISSUE THREAD

**Issue by ffs-akl** [sddm/sddm#1965]
After this command( sddm-greeter-qt6 --test-mode  --theme /path/to/your/themes)  was ran, it  is  a full screen program,  and there seems to be no way to return to the desktop normally, only to restart or switch to another tty and kill sddm-greeter
I didn't believe it's going to be so stupid, there must be a shortcut keys hidden out of` sddm-greeter-qt6  --help-all`  
Maybe it's common sense for many people that doesn't need to be explained, but it does bother me for a long time.
Could someone help to take a look at this issue?

**Comment by Vogtinator** [comment]
You should be able to alt-tab and ctrl-c.

IIRC it was also possible at some point to just trigger a login attempt and it would close, but FWICT that's not the case (anymore?).

**Comment by ffs-akl** [comment]
Thank you very much!
