### ISSUE TITLE
Black screen after sddm startup

### ISSUE THREAD

**Issue by fxzxmicah** [sddm/sddm#1967]
In an openSUSE virtual machine with KVM/QEMU, sddm in Wayland mode will only display normally when the kernel parameter includes `console=ttyS1`, otherwise it will only show a black screen.
Normal in X11 mode of sddm.

In addition, setting the `console=ttyS1` kernel parameter will cause the `systemd-vconsole-setup` service to fail. I don't know if there is any relationship between the two.
https://github.com/systemd/systemd/issues/30501

sddm version: 0.21.0

**Comment by SalahAdDin** [comment]
I have the same issue with Manjaro KDE in an ASUS ROG!

**Comment by Vogtinator** [comment]
That's https://github.com/sddm/sddm/issues/1844
