### ISSUE TITLE
SDDM login is glitched

### ISSUE THREAD

**Issue by JadenJSJ** [sddm/sddm#1971]
Guys so I just installed Arch Linux today on my laptop with wayland, sddm, and plasma
I enabled sddm.service

After I reboot sddm has many lines on it, and I cant see anything
I blindly typed my password and spammed enter and I logged in to Plasma no problems, currently typing this on the system.
# How can I fix SDDM login screen?

## Steps I've tried to fix this
Reboot, install `xf86-video-amdgpu,intel, xorg (installed all group packages), xrandr`, applying plasma settings to SDDM, making the script below
I have a hunch my laptop display can only display in its native resolution, but connecting a external display didn't help

```
# /usr/local/share/sddm/scripts/Xsetup
#!/bin/sh
xrandr -s 1920x1080
```
Default Login after install

![IMG_20240720_153843](https://github.com/user-attachments/assets/ace43357-d5a5-448a-8620-874fada5cac1)

Plasma Loads just fine
![IMG_20240720_161937](https://github.com/user-attachments/assets/838caf0e-2c72-4dd9-9363-783a2895575a)

After applying plasma settings
![IMG_20240720_162431](https://github.com/user-attachments/assets/8e1b79cb-f5f4-40a9-be44-2ed703a9a997)

**Comment by Vogtinator** [comment]
I don't think sddm is the cause of that, it's likely X or Mesa.

Try without `xf86-video-amdgpu` and `xf86-video-intel`, they're both obsolete and the latter is known broken.

**Comment by JadenJSJ** [comment]
Thanks alot that worked.
Uninstalling `xf86-video-amdgpu` and `xf86-video-intel` fixed it!
