### ISSUE TITLE
Using Breeze in KDE Plasma 6 defaults to old version and has errors

### ISSUE THREAD

**Issue by exup** [sddm/sddm#1975]
Since upgrading to plasma 6 my SDDM theme is using Breeze but is throwing the following error.

"The current theme cannot be loaded due to the following errors, please select another theme"
"/usr/share/sddm/themes/breeze/Main.qml: Library import requires a version"
"/usr/share/sddm/themes/breeze/Main.qml:13:52: Library import requires a version"
"/usr/share/sddm/themes/breeze/Main.qml: Library import requires a version"

I am running QT6 and breeze 6.1.3-1

I cant run sddm-greeter-qt6 as it says its not found. I can run sddm-greeter so I assume I am missing QT6 components? 
Ive unistalled breeze, reinstalled it but no luck.

I am a little lost as what to do next. Its not a deal breaker, as I get the old SDDM blue login screen along with the red errors above, it would be nice to fix it and use different wallpaper.

Operating System: Arch Linux 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.3-arch1-2 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 PRO 6650U with Radeon Graphics
Memory: 30.1 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 21CGS0VT0B
System Version: ThinkPad T14 Gen 3

**Comment by Vogtinator** [comment]
> I cant run sddm-greeter-qt6 as it says its not found. I can run sddm-greeter so I assume I am missing QT6 components?

Yup. The error messages also fit - it's using sddm-greeter(-qt5) to show a Qt 6 theme which won't work.

If you installed SDDM from distro packages, that's what you have to look at.

**Comment by exup** [comment]
ok user error, for some reason back in 2022 I installed sddm-git as an AUR package. Seems this was not updated... so removed it and using the default package SDDM which has the QT6 components. All good, problem is I cant remember why I installed the AUR package over the default, but hey it works.

So not a bug but user error - resolved.
