### ISSUE TITLE
Before the first login, SDDM keeps the system and the monitor always on

### ISSUE THREAD

**Issue by sbadux** [sddm/sddm#1980]
Hello,
after booting the system and before the first login, SDDM keeps the system and the monitor always-on.

How to reproduce (I tested it on Fedora KDE and KaOS)
1) Boot the system
2) Wait for the screen to stanby (it never happens)

The standby works fine after the first login, I guess because it uses the user's power settings, but if you don't login the monitor and the system will never go in standby.

I think SDDM should let the monitor at least for the monitor go in standby. A default 10-minutes standby will help to preserve the hardware and reduce the power consumption.
Moreover, the users with offline-updates enabled have to check the end of the updates and login, otherwise the system will stay on "forever"

**Comment by Vogtinator** [comment]
That's entirely up to the compositor, which in your case is most likely kwin.

**Comment by sbadux** [comment]
Hello, thanks for your reply. I reported it on KDE Bugs.
