### ISSUE TITLE
How to get sddm-greeter installed in Lubuntu Oracular??

### ISSUE THREAD

**Issue by esteelpaz** [sddm/sddm#1993]
Had some issues with Lubuntu's sddm log in applets, not providing "suspend function" . . . even after putting the debian-elarun theme in the sddm-config directory . . . still did not have suspend function.  Got this post from Humpty on the Lubuntu forum . . . no "greeter" . . . I ran his suggested symlink command and on log out I got a white screen background, but showing the elarun theme options for suspend.  

Any way to get this part of the regular config package in sddm???

> In the live iso of 24.10, there is a ‘suspend’ button at the top right hand corner of the default ‘lubuntu’ theme, and it works. It also works for 24.04, so a fresh install of something more stable is one solution.

But if you try to install the elarun theme (for 24.10) e.g
sudo apt install sddm-theme-elarun
Then the theme installs, and you can even run sddm-conf which does it’s job, by updating the /etc/sddm.conf.

So it should work right? No. The new config file is not accepted.

You hinted a good question which was ‘has anything changed in 24.10?’
The error message I found was that the theme needs the command ‘sddm-greeter’.
But in 24.10, sddm uses ‘sddm-greeter-qt6’.

So a short term solution is to symlink the old command to the new command.
sudo ln -s /usr/bin/sddm-greeter-qt6 /usr/bin/sddm-greeter
The long term solution is to [convince somebody](https://u45635552.ct.sendgrid.net/ls/click?upn=u001.Lj-2BtmSeWxX9Hcmxm2-2Fazpnlc5rpTKZ5Xiocrrbbs9fA2P6ZsGMqJbNB9LBelPOk-2FdofH_SnxfZBKDy6zUDpWz3CRtsAjcJWybv2FIfkwsAoEv6GUb-2Frpn8yvRzURQa5jzq3EA1JrHXSz9a98Yhhp4B5OlTXSCtyfTmC3bCqufJL65r78MY90pALUd9I8YJN6Ai1SeQVqHTnbqNkhddhxbh7FY-2BQNyuzgzqDFzLKhQXBbY2sAT6nWjs1L-2BGUX7ELecWRnUSppLDoZRwPkBWkRnZeeatQ-3D-3D) that something is wrong.

>

**Comment by esteelpaz** [comment]
<bump> . . . still would be hoping that this issue would be fixed upstream from where it occurred . . . .

**Comment by Vogtinator** [comment]
> The error message I found was that the theme needs the command ‘sddm-greeter’.
But in 24.10, sddm uses ‘sddm-greeter-qt6’.

Already fixed with #1876.

**Comment by esteelpaz** [comment]
Thanks for the reply and the fix . . . .
