### ISSUE TITLE
Interactivity and AI chats in lock/login/greeter screen (enhancement)

### ISSUE THREAD

**Issue by osering** [sddm/sddm#1994]
More and more interactivity and gamification is used in different products.
Right now sddm lock-screen is quite static. If you do not know password, there is not much you can do.
My proposal is to follow Android development in this area and give some interactivity to this screen, which is user configurable.
Like, give possibility to run some predefined program (programs) - small/big game e.t.c.
Moreover, like Android let temporary (non-authorized) user to use this piece in SOS situations (send some message or make contact) as well as in case of lost laptop, way to show owners/users credentials/contacts or make contact (in some messenger) with owner. Run browser-kiosk mode. Why not?
As well as  configurable notifications - which can be shown on this screen, and also possibility to show conky-like information if owner wishes (contain some dash board elements if someone needs/wants).
Finally, possibility (chat window or speech to text) to talk to some local AI (meta/mistral model, which runs quite well on laptop CPU as well), if configured (for SOS situations or others).

**Comment by Vogtinator** [comment]
Feel free to implement anything you want in a theme.

I don't see anything concerning SDDM itself in this issue, so I'm going to close this.

**Comment by osering** [comment]
Did not know, that **opensource projects** (as R.Stallman visioned) **just accept enhancements** (and maybe - issues/bugs) **which original project authors' were planning**, but just did not put their plans on the table for some reason :)

Isn't it in FOSS projects' interest to give some examples how to be most efficient in this ecosystem? Give people some most sophisticated and rich theme examples which to full extent demonstrates sddms' technical peak possibilities, which then can be followed. Was not the concept/standard (ISO or not) of themes coming from sddn project authors? Or theme authors just hacked this project to inject their themes behind the backs of project leeds?
I checked central WIKI (https://github.com/sddm/sddm/wiki), but there is nothing about how project leads even remotely see such a rich implementations (video and other app windows or layer on greeting screen), nor documented standard to which proposed "theme.conf.user" as one of two theme config files should adhere. Which is essential elements, which - optional, what syntax to use, etc?

Could you please show the development vector (and elaborate where well documented "theme standard" with config files can be found)  to people more distant to project, to be able without pasting some inadequate (not relevant to project) ideas here and bothering project leads, just based on documented standard and/or SDK, to make individually their themes for usage with sddn.
