### ISSUE TITLE
XorgDisplayServer::start() fails to find Xsetup script

### ISSUE THREAD

**Issue by rparkins999** [sddm/sddm#1995]
The problem is that the macro DATA_INSTALL_DIR is used for two different directories.

In the top level CMakeLists.txt DATA_INSTALL_DIR is defined as "/usr/share/sddm".

In src/common/Consants.h.in DATA_INSTALL_DIR is defined as "/usr/share/sddm/themes".

The second definition is the one which gets into build/src/common/constants.h and is used in Configuration.h to define X11.DisplayCommand as "/usr/share/sddm/themes/scripts/Xsetup", but the RPM has installed Xsetup in /usr/share/sddm/scripts, so XorgDisplayServer::start() looks in the wrong place for Xsetup and fails to find it.

I can't find any usage of DATA_INSTALL_DIR where is should be "/usr/share/sddm/themes", so I think that the second definition is just plain wrong and should be removed.

**Comment by rparkins999** [comment]
The second definition is in src/common/Constants.h.in, not src/common/Constants.h.

Fixing the definition in src/common/Constants.h.in also fixes another problem that I had encountered where it couldn't find the login theme defined in System Settings., Previously I had worked around that by setting my preferred theme as the default in the code.

**Comment by Vogtinator** [comment]
I don't see that, it's defined as CMake variable in CMakeLists.txt and as C macro in src/common/Constants.h.in. That looks fine to me.

Are you using some patched version?

**Comment by rparkins999** [comment]
Yes, I patched some definitions because I was having trouble building with the original macro definitions. I did do a git diff which didn't show Constants.h.in as having changed, but I didn't do it against the original commit that I had cloned. So the bad definition was my fault - my apologies.
