### ISSUE TITLE
Passwordless?

### ISSUE THREAD

**Issue by ghost** [sddm/sddm#2]
Thanks for the gift. Passwordless login is not the job of display managers, is it? (Would be a fine convenience for a Qt-only environment.)

**Comment by sorenweber** [comment]
I would like this feature. I would like for my kids to be able to log on without entering passwords. I could do this in KDM (on Kubuntu 14.04.4) and after upgrading and switching to SDDM I (they) really miss this feature.

Basically, I would like to be able to define a list in sddm.conf (like HideUsers), e.g. PasswordlessUsers, with users that can log in without entering their password. Only administrators should be able to define this list.
