### ISSUE TITLE
Login not working on multi-monitor setup

### ISSUE THREAD

**Issue by max06** [sddm/sddm#2006]
Hello there!

Starting with Plasma 6.2 I'm experiencing issues logging in. One of the 2 login forms just does nothing on login, while the second one works as expected.

Monitor setup:
- Scenario 1, at my desk: Primary Monitor (5120\*1440) left of secondary (1920\*1080, unused, for hdmi audio)
- Scenario 2, at my couch: Primary Monitor (1920\*1080,  secondary in scenario 1)

(To clarify: Scenario 1 always has 2 active monitors, with the second one being unused by me)

After reboot (in scenario 1) I'm greeted with sddm on both screens. I use the password form on my primary monitor. After pressing enter, the form input as well as the button get disabled, but nothing else happens. 

Workaround: I have to turn on the second monitor (a projector) to be able to see the second login form on the secondary display. Entering my password there and pressing enter works as expected. 

Besides being very annoying (it forces me to get up, switch rooms, turning on the projector and getting the second keyboard), it's also not very healthy for my projectors light source. 

---

System information: NixOS unstable (x86_64, Kernel 6.6.58), with NVidia RTX 2060 Super/560.35.03. Plasma 6.2.2 on wayland. 
Happy to provide any requested information.

My `sddm.conf`: 

```ini
[General]
DefaultSession=plasma.desktop
DisplayServer=x11
HaltCommand=/run/current-system/systemd/bin/systemctl poweroff
Numlock=none
RebootCommand=/run/current-system/systemd/bin/systemctl reboot

[Theme]
Current=breeze
CursorSize=24
CursorTheme=breeze_cursors
FacesDir=/run/current-system/sw/share/sddm/faces
ThemeDir=/run/current-system/sw/share/sddm/themes

[Users]
HideShells=/run/current-system/sw/bin/nologin
HideUsers=nixbld1,nixbld10,nixbld11,nixbld12,nixbld13,nixbld14,nixbld15,nixbld16,nixbld17,nixbld18,nixbld19,nixbld2,nixbld20,nixbld21,nixbld22,nixbld23,nixbld24,nixbld25,nixbld26,nixbld27,nixbld28,nixbld29,nixbld3,nixbld30,nixbld31,nixbld32,nixbld4,nixbld5,nixbld6,nixbld7,nixbld8,nixbld9
MaximumUid=30000

[Wayland]
CompositorCommand=
EnableHiDPI=true
SessionDir=/nix/store/bj7ykivkbqj47isky7rbxnmnxpzs9ghk-desktops/share/wayland-sessions

[X11]
DisplayCommand=/nix/store/sy5bnvq4sx6g8w9q3hz4fw6734iclz1b-Xsetup
DisplayStopCommand=/nix/store/qynp0fxx9lr45ic9cfqlbjw7i5ickrk5-Xstop
EnableHiDPI=true
MinimumVT=7
ServerPath=/nix/store/zvjmbmgz5jhd416h2vv7af473ql2bb7w-xserver-wrapper
SessionCommand=/nix/store/shyqcfj9hla4jix5mdzc018r560a0krv-xsession-wrapper
SessionDir=/nix/store/bj7ykivkbqj47isky7rbxnmnxpzs9ghk-desktops/share/xsessions
XauthPath=/nix/store/b8kdiq7qhx5r3fazga3ajls5ksxrf7jm-xauth-1.1.3/bin/xauth
XephyrPath=/nix/store/mfafsw7bv00dkrqr69v78zf1bwggf5br-xorg-server-21.1.13/bin/Xephyr
```

**Comment by Vogtinator** [comment]
That's https://bugs.kde.org/show_bug.cgi?id=494804 resp. https://bugreports.qt.io/browse/QTBUG-130767

**Comment by max06** [comment]
Thanks a lot!
