### ISSUE TITLE
Showing the virtual keyboard breaks the top layout

### ISSUE THREAD

**Issue by medmedin2014** [sddm/sddm#2013]
When I click on Virtual Keyboard button in SDDM, it squeezes the time and users components

Screen resolution: 1366*768
Scaling: 100%

```
sddm: 0.21.0
Operating System: Manjaro Linux rolling
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.12.1-2-MANJARO (64-bit)
Graphics Platform: Wayland
```

![2024-11-23 20 25 00](https://github.com/user-attachments/assets/18bc7511-c5ea-4060-b9d2-380c88d1103b)

**Comment by Vogtinator** [comment]
That's an issue with the theme you're using.

**Comment by Vogtinator** [comment]
Looks like Breeze, you can file a report at https://bugs.kde.org.
