### ISSUE TITLE
Unable to set a new  SDDM on Ubuntu 24.10, KDE Plasma

### ISSUE THREAD

**Issue by Foxof7207** [sddm/sddm#2018]
I'm unable to set a new SDDM on the KDE Plasma, it does ask for my password but it doesn't change anything.

I'm the root user.

**Comment by Vogtinator** [comment]
That would be a bug in KDE Plasma, not SDDM. Please report that to Ubuntu.

**Comment by Vogtinator** [comment]
> I'm the root user.

That sounds very wrong, you must not run Plasma as root.

**Comment by Foxof7207** [comment]
Okay, thx.

I will report that to ubuntu
