### ISSUE TITLE
How to skip "Unlock" button

### ISSUE THREAD

**Issue by MrQubo** [sddm/sddm#2023]
I've upgraded from plasma5 to plasma6 today. I'm using fprintd to login, and after that upgrade when I touch fingerprint reader the desktop doesn't login immediately like before, but I have to click "Unlock" button at the middle or hit Enter.

No idea why this change happened and I weren't able to find any info.

**Comment by Vogtinator** [comment]
If there's an "Unlock" button that's the Plasma lockscreen and not SDDM. There are currently various reports on https://bugs.kde.org about this, there's probably one that matches your observations best.
