### ISSUE TITLE
Blank screen when startup

### ISSUE THREAD

**Issue by panda-z** [sddm/sddm#216]
Hello, I got a white blank screen with a cursor when I start `sddm` via `systemd`.

OS: Archlinux + systemd
Package version: sddm-qt5-git 654.87e2a5d-1

If you need any further information or log, please let me know.

**Comment by tyduptyler13** [comment]
I am having this issue currently with the sddm included in kubuntu.

I have also tried building my own sddm with the latest (stable) qt and still have the same issues.

Any suggestions would be great.

**Comment by tyduptyler13** [comment]
Some details that might help you:

I am running:
* sddm 0.11.0
* qt 5.4.1
* fglrx drivers (build with the kubuntu packages) (2:15.200-0ubuntu4)

**Comment by LeonardKoenig** [comment]
Same thing here, running on nVidia Optimus. Log is the same, it ends with message received from greeter.
ArchLinux here
