### ISSUE TITLE
SDDM refuses to acknowledge sddm.conf

### ISSUE THREAD

**Issue by tghe-retford** [sddm/sddm#236]
After installing SDDM (either sddm-qt5-git or sddm-qt5) on Arch Linux and enabling it with systemd, I found that after creating /etc/sddm.conf either manually from the instructions in the sddm.conf manual or with the SDDM configuration module for KDE 4, SDDM simply refuses to acknowledge the sddm.conf file and revert to a default unconfigured install, only acknowledging the last user and session selected from state.conf.

For your information, this is my sddm.conf file. All but the CurrentTheme line was generated with the SDDM KCM module for KDE 4:

[General]
AutoRelogin=false
AutoUser=sonic
CurrentTheme=breeze
CursorTheme=breeze_cursors
HaltCommand=
MaximumUid=65000
MinimumUid=1000
Numlock=on
RebootCommand=

**Comment by FirewallDaProtogen** [comment]
still having this issue nowadays
even tried directly making the file under /usr/lib/sddm/sddm.conf.d/default.conf and no results
