### ISSUE TITLE
Problem with autologin

### ISSUE THREAD

**Issue by Esclapion** [sddm/sddm#264]
When autologin is activated, policykit and logout don't work.

**Comment by jleclanche** [comment]
@Esclapion i think this was fixed a while back, closing. let me know if it still happens in 0.10

**Comment by Esclapion** [comment]
Sorry, I answer late. For me, the problem is not solved. I use kernel 3.16, sddm 0.11, systemd 218.

When autologin is active, if I do a logout, it breaks in VBox. Installed or not. 
Without, it works.

With lightdm, it works. So, for the moment...
