### ISSUE TITLE
Slow to display the greeter screen

### ISSUE THREAD

**Issue by opoplawski** [sddm/sddm#281]
sddm takes about 15 seconds to start up, mainly in starting the greeter

between:

Greeter session started successfully

and

Message received from greeter: Connect

I at first thought sddm should not try to enumerate all users' face icons at startup, but I'm not sure that that is the hangup.

For comparison, kdm seems to take about 2 seconds to startup.

**Comment by jleclanche** [comment]
@opoplawski So this is #274 then? Can you try that see if it helps?

**Comment by loimu** [comment]
I can confirm.
```
$ apt-cache policy sddm
sddm:
  Installed: 0.11.0-0ubuntu10
  Candidate: 0.11.0-0ubuntu10
```
