### ISSUE TITLE
pam_gnome_keyring.so freezes session logout

### ISSUE THREAD

**Issue by MartinBriza** [sddm/sddm#286]
Don't know what to do about it. Is it our problem? Or their? Seems like ours as there's nobody else mentioning this problem with other DMs.

Details: I guess QProcess doesn't catch the SIGCHLD signal from the session to be able to properly reap it.

**Comment by kkofler** [comment]
Can't the signal handlers be saved and restored somehow, to override PAM modules messing with them?

**Comment by rdieter** [comment]
ping, it's been over a year, will anyone be looking into this soon?

**Comment by davidedmundson** [comment]
It was fixed in GNOME keyring ages ago

**Comment by rdieter** [comment]
So... a dup of #385 ?

**Comment by plfiorini** [comment]
looks like duplicate, anyway it should be fixed now.
