### ISSUE TITLE
sddm-helper exited with 127

### ISSUE THREAD

**Issue by ArthurBorsboom** [sddm/sddm#291]
In my journal is see this at every login attempt:

sddm[205]: Auth: sddm-helper exited with 127

What does this mean?
Do you know how to prevent this?

**Comment by mathieujobin** [comment]
have you had any better luck since last October?
have you tried a more recent release? 

should you be willing to compile your own sddm, I have a troubleshooting branch on my fork, which includes the most recent master and will output more messages. that could help troubleshooting your issue.

https://github.com/mathieujobin/sddm/tree/troubleshooting

**Comment by ArthurBorsboom** [comment]
Hi Mathieu,

I need to lookup if the issue still exists.
On the two of my three workstations the issue does not exist (anymore).
I still have to check the third one.

To be continued.

On 6 April 2015 at 00:55, Mathieu Jobin <notifications@github.com> wrote:

> have you had any better luck since last October?
> have you tried a more recent release?
>
> should you be willing to compile your own sddm, I have a troubleshooting
> branch on my fork, which includes the most recent master and will output
> more messages. that could help troubleshooting your issue.
>
> https://github.com/mathieujobin/sddm/tree/troubleshooting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sddm/sddm/issues/291#issuecomment-89867686>.
>



-- 
Arthur Borsboom
Lieven de Keystraat 77
3067 KG, Rotterdam
The Netherlands
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>

**Comment by ArthurBorsboom** [comment]
Hi Mathieu,

I checked again.
I dont have the error message anymore.

Thanks for your thoughtfulness.

Regards,
Arthur.

On 6 April 2015 at 00:55, Mathieu Jobin <notifications@github.com> wrote:

> have you had any better luck since last October?
> have you tried a more recent release?
>
> should you be willing to compile your own sddm, I have a troubleshooting
> branch on my fork, which includes the most recent master and will output
> more messages. that could help troubleshooting your issue.
>
> https://github.com/mathieujobin/sddm/tree/troubleshooting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sddm/sddm/issues/291#issuecomment-89867686>.
>



-- 
Arthur Borsboom
Lieven de Keystraat 77
3067 KG, Rotterdam
The Netherlands
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>
