### ISSUE TITLE
second monitor can not be interacted with

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#292]
I'm using SDDM 0.10.0 in Kubuntu 14.10 pre-release with the Breeze theme.  I have two monitors.  When I want to use SDDM to unlock the screen it nicely shows the SDDM theme on both screens complete with users and widgets on each screen.  Interfacting with widgets works fine using my built in monitor but on the secondary monitor it does not work, I can't select the text entry box and clicking on the users or the reboot button etc does nothing.

**Comment by plfiorini** [comment]
Can you verify with master?

**Comment by plfiorini** [comment]
Given the recent work with multiple screen support it's likely to be fixed on master.
Please reopen if you still have problems.
