### ISSUE TITLE
Option for locked KDE autologin

### ISSUE THREAD

**Issue by facorread** [sddm/sddm#306]
Hello, thank you very much for your development efforts.

As KDM has been dropped from Plasma 5, and SDDM has been [recommended](http://blog.davidedmundson.co.uk/blog/display_managers_finale) as the display manager for Plasma 5, I hereby request the implementation of KDM Auto-Login's convenience-security 'Lock session' option into SDDM.

If nobody expresses interest, I'd like to have an opportunity to contribute to this feature.

Thanks for considering this request.

**Comment by majewsky** [comment]
For all the users having the same problem, here's a workaround that I found from reading into the startkde script. Put the following into a file called `~/.config/plasma-workspace/env/autolock.sh`:

```
dl=1
```

As of Plasma 5.2, this will cause ksmserver to be launched with the `--lockscreen` option, which is what we want. With this in place, you can then enable the Autologin option of SDDM.

**Comment by facorread** [comment]
Hi Stefan, thanks for your research. I am using Fedora 21 and tried your suggestion. It didn't work at either `~/.config/plasma-workspace/env/autolock.sh` or ` ~/.kde4/env/autolock.sh`, but I added `export DESKTOP_LOCKED=yes` at ~/.profile and it worked with the same mechanism you presented. Hope this helps.

**Comment by wadoo** [comment]
Thx for the info but i'm under kde-plasma 4.14.4 and your trick is not working for me. 
But in the same way, even if i'm not on kde plasma 5, i don't have this option anymore.
I think is an big miss this option was so useful for me...
anyway i solved this by adding a shell scrit to the startup of kde.
(/home/wadoo/.kde/Autostart/lockscreen.sh)
it contains: 
qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
Hope it can help someone.
I'm on Fedora 21.

**Comment by wadoo** [comment]
facorread  another solution in the same time ;)

i will try yours to know because with mine the screen is locked after all is loaded so you can interat for some seconds.

Thx for info

**Comment by facorread** [comment]
Yeah, good thinking, cheers and thanks to all of you :)

**Comment by plfiorini** [comment]
Closing, DE specific features should be dealt by the DE.

**Comment by int-ua** [comment]
Can anyone confirm this: https://bugs.kde.org/show_bug.cgi?id=346714 ?

**Comment by davidedmundson** [comment]
Repllied there

**Comment by majewsky** [comment]
I would argue that this is not desktop-specific (even if it is only implemented by one desktop at the moment). It's a protocol established by another display manager (KDM) which is not KDE-specific in any way that would prevent it from being implemented in other desktops.

**Comment by plfiorini** [comment]
@majewsky I really don't know how Plasma works regarding this feature, I see dl=1 and DESKTOP_LOCKED=yes env vars being mentioned. While the former seems very ksmserver specific I would rather standardize on DESKTOP_LOCKED.

Indeed this feature could be implemented by other desktops so maybe DESKTOP_LOCKED should be standardized as XDG_DESKTOP_LOCKED and we can add a setting to sddm to lock the desktop on autologins telling users that it will work only on some desktops.

@jleclanche Since you are a far better xdg expert, what are your thoughts?

**Comment by jleclanche** [comment]
The concept of an env variable for desktop locking seems incompatible with multihead setups no?

**Comment by plfiorini** [comment]
multihead or multiseat?

**Comment by plfiorini** [comment]
multihead -> that's up to the desktop to show the lock screen on all the screens or only on the primary screen.
multiseat -> guess that each seat runs its desktop session which is a different process hence it can have diffrent env vars

**Comment by jleclanche** [comment]
multiseat sorry.

**Comment by int-ua** [comment]
Can we somehow set `DESKTOP_LOCKED=yes` only on autologin?

**Comment by nazar2sfive** [comment]
yes please add this feature. i also would love to have locked sddm autologin.

**Comment by winiciuscota** [comment]
The ```dl=1 ```stopped working for me after the last update on Manjaro(with kde 5.17.4).
Is there any other workaround?

**Comment by ddnomad** [comment]
This would be lovely indeed!
