### ISSUE TITLE
maldives theme is non-free

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#315]
The maldives theme is non-free because the background image has a restrictive licence.  This means it can not go into any mainstream Linux distribution.

**Comment by plfiorini** [comment]
Fine by me.
Do we all agree?

I summon @davidedmundson @jleclanche @MartinBriza @nslqqq

**Comment by jleclanche** [comment]
I don't do theming ;)

**Comment by plfiorini** [comment]
The question was: do you guys like it?

**Comment by jleclanche** [comment]
I haven't seen the maldives theme, I can't really compare.

**Comment by nslqqq** [comment]
lgtm
