### ISSUE TITLE
Licences Incomplete and Inconsistent

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#318]
SDDM licences are incomplete and inconsistent

This patch can be applied straight away, it adds the full text of CC-BY-3.0 and CC-BY-SA-3.0 (not necessary but preferred by linux distributions) and it adds the licence used by the cmake modules (which is necessary)
http://starsky.19inch.net/~jr/tmp/sddm.diff

This patch changes use of CC-BY-3.0 to CC-BY-SA-3.0 for consistency (the circles theme claims both licences) and makes the licence versions explicit, it needs the agreement of the author Abdurrahman AVCI
http://starsky.19inch.net/~jr/tmp/sddm2.diff

**Comment by plfiorini** [comment]
@jriddell please send PRs instead of diffs next time.
