### ISSUE TITLE
greeter: purge password box on submitting wrong input

### ISSUE THREAD

**Issue by pmattern** [sddm/sddm#320]
Just some minor usability issue:

I think it would be much better if the password box got cleaned after a wrong password was submitted.
Right now the wrong content has to be deleted manually which isn't exactly convenient, imho.

**Comment by ArchangeGabriel** [comment]
+1

**Comment by flyingDavid** [comment]
I would prefer it the password would be selected, so if you just start typing, the old password gets purged, but if you wan't to change e.g. only the last character, you can do this though. Take a look at the KDE Breeze theme to try it out.

**Comment by jleclanche** [comment]
No, that's horrible UX. Passwords are not user-visible so we shouldn't give them the occasion to correct what they don't know is wrong.

**Comment by flyingDavid** [comment]
Sometimes, when I type in the password quickly, I hit two keys instead of one at the end. If the password is selected, I can correct this fault.
I agree that there only a limited use for this, though it doesn't have drawbacks IMHO. (But I'm no UI expert, just my opinion...)

**Comment by plfiorini** [comment]
I haven't tested it but off the top of my head:

https://github.com/sddm/sddm/blob/master/data/themes/maui/Main.qml#L48

this line is wrong, the password property from PictureBox is a string that points to the "text" property of the line edit.

line 48 should be:

listView.currentItem.password = ""

I can fix it tonight.

**Comment by jleclanche** [comment]
@plfiorini I'll take care of it.

**Comment by plfiorini** [comment]
Ok thanks, keep in mind that the same mistake might have been carried around in the other themes.

**Comment by plfiorini** [comment]
Looks like it was fixed, closing the issue

**Comment by pmattern** [comment]
Confirming the problem is fixed in all themes currently shipped by SDDM itself.

78e1d9a on Arch Linux.
