### ISSUE TITLE
Create proper release tarballs

### ISSUE THREAD

**Issue by elkrejzi** [sddm/sddm#321]
Hello,

I am working with Beyond Linux From Scratch, a book that contains instructions on how to build different packages on top of Linux From Scratch. I need to ask you to provide a proper release tarball, ie "sddm-0.11.tar.xz", if possible, so we could properly reference it from our book.

It seems that github supports that. See qupzilla releases page - it contains a proper tarball along the standard github generated ones.

https://github.com/QupZilla/qupzilla/releases

Thanks in advance.

**Comment by jleclanche** [comment]
Why can't you use `https://github.com/sddm/sddm/archive/v0.11.0.tar.gz`?

**Comment by elkrejzi** [comment]
We are book maintainers, we provide references to the upstream tarball and instructions on what's needed and how to build it. If several of those are downloaded in one place (using the default github tarballs or any similar download scheme), it would create a confusion which tarball corresponds to which package. Not to mention that if there are two packages that coincidentaly have the same version (not very likely) and use the same naming scheme, they would collide with each other. Any naming scheme that corresponds to the more or less official $pkgname-$pkgver.tar.??? would be fine (or any that includes the package name).

I suppose you could go and create the "sddm-0.11.0" tag, instead of the "v0.11.0" (0.11.0 used as an example version here), which hopefully will then include the package name in the default github tarballs, with a rather small anoyance of renamed extracted dir, which would then include the pkgname twice ($repository-$tag -> sddm-sddm-0.11.0), which is something we could live with.

See:

https://github.com/LibVNC/libvncserver/releases or
https://github.com/Mindwerks/wildmidi/releases

**Comment by jleclanche** [comment]
So the problem is the naming on your filesystem? If you're telling people to wget stuff, you can just give it an -O sddm-0.11.tar.gz or something... this is a problem on your side, to be honest, and I don't see what can be done here that isn't already being done.

**Comment by elkrejzi** [comment]
Not really. I'm just providing a link to the tarball. It's up to user to choose whatever way of downloading they want. See

http://www.linuxfromscratch.org/~krejzi/kde5/kde5/sddm.html

The reference to a tarball you see is the renamed github tarball.

**Comment by bdubbs** [comment]
It's difficult to create a wget list when the file name has to be changed.  If no one on github created the properly named tarballs, we would have:

https://github.com/libical/libical/releases/download/v1.0.1/v1.0.1.tar.gz
https://github.com/i-rinat/libvdpau-va-gl/releases/download/v0.3.4/v0.3.4.tar.gz
https://github.com/TigerVNC/tigervnc/archive/v1.4.2.tar.gz
https://github.com/libass/libass/releases/download/0.12.1/0.12.1.tar.xz
https://github.com/taglib/taglib/releases/download/v1.9.1/v1.9.1.tar.gz

That download would be virtually useless.
Fortunately, most github devs are very cooperative,

**Comment by eliasp** [comment]
Well, I don't see how the shortcomings of one distributions installation process should justify additional efforts for every upstream package used by this distribution.
What about providing a small wrapper script instead for your users where instead of a plain wget-list a file like this is provided:
```
https://github.com/libical/libical/releases/download/v1.0.1/v1.0.1.tar.gz -> libical-1.0.1.tar.gz
https://github.com/i-rinat/libvdpau-va-gl/releases/download/v0.3.4/v0.3.4.tar.gz -> libvdpau-va-gl-0.3.4.tar.gz
https://github.com/TigerVNC/tigervnc/archive/v1.4.2.tar.gz -> tigervnc-1.4.2.tar.gz
https://github.com/libass/libass/releases/download/0.12.1/0.12.1.tar.xz -> libass-0.12.1.tar.xz
https://github.com/taglib/taglib/releases/download/v1.9.1/v1.9.1.tar.gz -> taglib-1.9.1.tar.gz
```
The wrapper script could simply parse these lines and use the name in the last column as argument for `wget -O`.
Many years ago, Gentoo was facing the same issue (causing collisions/checksum errors in the download directory) and [simply added support for named downloads](https://dev.gentoo.org/~zmedico/portage/doc/ch06s03s03.html#package-ebuild-eapi-2-metadata-src-uri-output-file-name-customization) in  `EAPI=0` which allowed now to do this:
```bash
SRC_URI="https://github.com/taglib/${PN}/releases/download/v${PV}/v${PV}.tar.gz -> ${P}.tar.gz"
```

**Comment by bdubbs** [comment]
The wget list is generated from xml.  It's a text file, not a script. 

I'm not really that familiar with github.  Is it really not possible to just create a symbolic link for a release tarball?

**Comment by eliasp** [comment]
> The wget list is generated from xml. It's a text file, not a script.
This makes everything even more easy.

So instead of simply dumping the source URLs into the file, create a file containing this instead:
```bash
#!/bin/bash
DOWNLOAD_DIR=/tmp/foo/bar
mkdir -p ${DOWNLOAD_DIR}
wget https://github.com/libass/libass/releases/download/0.12.1/0.12.1.tar.xz -O ${DOWNLOAD_DIR}/libass-0.12.1.tar.xz
wget https://github.com/taglib/taglib/releases/download/v1.9.1/v1.9.1.tar.gz  -O ${DOWNLOAD_DIR}/taglib-1.9.1.tar.gz
[…]
```
Then make the file executable and give this to your users instead of a plain wget-list containing only URLs.

Problem solved!

**Comment by bdubbs** [comment]
Never mind.  We'll just distribute the properly named package on our web site and use that url.  We prefer the original developer's site, but  can do that for the very few non-conforming exceptions.

We prefer to just have a text file for 'wget -i file-list.txt', not a script. 

The fact that github does not facilitate a simple 'wget url' or 'curl url' that fetches the proper filename without customization just makes it inconvenient for those you are trying to help with the project.  If we had to do that for the 800 or so packages that we support, then it would make our whole project much more difficult.

**Comment by elkrejzi** [comment]
Wait, why invalid? Doesn't f2411926d997633e1b931dc136d232350f85a067 fix the problem, according to the commit message?

**Comment by plfiorini** [comment]
https://github.com/sddm/sddm/commit/f2411926d997633e1b931dc136d232350f85a067 allows us to create tarballs that we can later upload to github on the release page.

I think that should work out for you @elkrejzi

**Comment by elkrejzi** [comment]
@plfiorini which is exactly what I originally asked for. Thanks.

**Comment by jleclanche** [comment]
@elkrejzi I misunderstood the issue, sorry.
