### ISSUE TITLE
Wishlist: session-setup- and session-cleanup-script like lightdm

### ISSUE THREAD

**Issue by agaida** [sddm/sddm#322]
session-setup-script = Script to run when starting a user session (runs as root)
session-cleanup-script = Script to run when quitting a user session (runs as root)

--

ok, one can use /etc/(x)profile or $HOME/.(x)profile - shellagnostic or the respective shell-files to do setup things - but there is nothing the other way around.

Thats bad for user-mounts, that should be cleaned up at logout or similar tasks.

**Comment by jleclanche** [comment]
Without a solid reason behind this, it won't get done.

**Comment by agaida** [comment]
This issue is not so important in the moment - maybe i look at sddm again in a year or two. Until then - good luck.
