### ISSUE TITLE
Login screen is sometimes missing characters

### ISSUE THREAD

**Issue by mgolden** [sddm/sddm#324]
I am running kubuntu the 14.10 plasma 5 test ISO.  I occasionally see a very odd behavior on the login screen: it's missing characters.  I have not yet determined what I do that causes it - it never seems to happen from a fresh boot.

![img_20141122_190957](https://cloud.githubusercontent.com/assets/64071/5242175/2ed57d2e-78fb-11e4-9d32-bec27c29e45d.jpg)
![img_20141125_204706](https://cloud.githubusercontent.com/assets/64071/5242184/5395bd9a-78fb-11e4-8a3e-2367b543adb0.jpg)

**Comment by plfiorini** [comment]
Does this happen with the other themes or just with breeze (which is not shipped by SDDM)?

**Comment by mgolden** [comment]
I have never tried any other themes.  Can you tell me how to change it?

**Comment by jleclanche** [comment]
Closing; there's been no other report of this, it's likely an issue outside of our control.

**Comment by mgolden** [comment]
I still see this occasionally on the Kubuntu 15.04 release.  It doesn't affect only the login screen but also some of the hover states of the nav bar.

**Comment by FirefighterBlu3** [comment]
i and my friends use Arch Linux with kf5 and login with sddm. we all see this on three PCs and 5 laptops

**Comment by mgolden** [comment]
Do you also have nvidia cards?  I wonder if that's somehow related.

**Comment by FirefighterBlu3** [comment]
yes, they're all nvidia

**Comment by zzottel** [comment]
Same here, also Arch, also nvidia.

**Comment by zzottel** [comment]
Just to mention that: Using nouveau instead of nvidia drivers, the problem vanished.
