### ISSUE TITLE
Cloned with 2 monitors

### ISSUE THREAD

**Issue by valsoray17** [sddm/sddm#328]
in Fedora 21 sddm both monitors display cloned login screen. Is it possible to configure sddm to leave the secondary monitor screen with default wallpaper instead?

Thanks.

**Comment by jerome2** [comment]
Same problem, never find answer or solution (search 2 months). Thganks for any help or answer.

**Comment by iBeliever** [comment]
I'm having this issue as well and am also on Arch Linux. My laptop's screen (including the cursor) is mirrored to the external monitor. This is definitely a bug as my theme is set to just display the wallpaper on secondary monitors.

**Comment by plfiorini** [comment]
Some setups mirror by default with Xorg (don't ask my why).
You should change that with xrandr calls from the Xsetup script.
Besides we've got more multiple screens fixes in the last couple of releases, so I'm closing the issue.
