### ISSUE TITLE
xrandr settings ignored in multi-monitor setup

### ISSUE THREAD

**Issue by github-cygwin** [sddm/sddm#335]
Hi,

I just installed Fedora 21 the other day, and due to sudden display problems with KDM
(https://bugzilla.redhat.com/show_bug.cgi?id=1176352) I decided to try SDDM.  I'm
encountering problems very similar to the KDM problem
(https://bugzilla.redhat.com/show_bug.cgi?id=1176992).  Most annoying is the inability
to exactly define the output settings so the login dialog shows up on the desired output. 

In /usr/share/sddm/scripts/Xsetup I'm setting up my dual-monitor setup like this:

    xrandr --output DP1 --auto --pos 1600x0
    xrandr --output HDMI2 --primary --auto --pos 0x100
    xrandr > /tmp/xrandr.out

Despite the HDMI2 output defined as primary output, which is confirmed by the subsequent
call to xrandr logging to the file in /tmp, the login dialog always shows up on the monitor
connected to DP1, independently of the theme used in /etc/sddm.conf.  For further testing
I defined my own theme, copied from the "circles" screen.

theme.conf:

    [General]
    background=pic-left.jpg
    background2=pic-right.jpg

In Main.qml I changed

    Rectangle {
        width: 640
        height: 480

to

    Rectangle {
        width: 4160
        height: 1440

The Repeater block I exchanged with

    Rectangle {
        x: 0
        y: 100
        width: 1600
        height:1200
        Repeater {
            x: geometry.x; y: geometry.y; width: geometry.width; height: geometry.height
            model: screenModel
            Background {
                source: config.background
                fillMode: Image.Scale
                onStatusChanged: {
                    if (status == Image.Error && source != config.defaultBackground) {
                        source = config.defaultBackground
                    }
                }
            }
        }
    }
    
    Rectangle {
        x: 1600
        y: 0
        width: 2560
        height:1440
        Repeater {
            model: screenModel
            Background {
                x: geometry.x; y: geometry.y; width: geometry.width; height: geometry.height
                source: config.background2
                fillMode: Image.Scale
                onStatusChanged: {
                    if (status == Image.Error && source != config.defaultBackground) {
                        source = config.defaultBackground
                    }
                }
            }
        }
    }

The result is... weird, to say the least. 

Desired output would have been background=pic-left.jpg on the left monitor at HDMI2,
background2=pic-right.jpg on the right monitor at DP1, login dialog on the primary monitor
HDMI2, the left one.

Actual output is a white canvas on the left monitor, the left 2/3rd of the right monitor showing
pic-left.jpg, scaled to 1600x1200, the right 1/3rd of the right monitor showing the left snippet
of pic-right.jpg scaled to 2560x1440, login dialog on the right monitor, DP1.

As an extra surprise, the cursor changes when moving it between the outputs.  On the right
monitor it's the typical arrow cursor, on the left monitor with just the white background it
becomes the default X cursor, the X-shape.

It's really strange that none of these problems exist inside a running KDE session, despite using
identical xrandr settings.

Hope this is fixable.

Thanks,
Corinna

**Comment by plfiorini** [comment]
This is likely to be fixed with 0.13.0, feel free to reopen if it's not the case

**Comment by github-cygwin** [comment]
This is broken again with sddm 0.14.

My xrandr settings are still

`xrandr --output DP1 --auto --pos 1600x0
xrandr --output HDMI2 --primary --auto --pos 0x100
xrandr > /tmp/xrandr.out`

My theme settings are 

`[...]
    Background {
        property variant geometry: screenModel.geometry(screenModel.primary)
        x: geometry.x; y: geometry.y; width: geometry.width; height: geometry.height
        source: config.background
        fillMode: Image.Stretch
        onStatusChanged: {
            if (status == Image.Error && source != config.defaultBackground) {
                source = config.defaultBackground
            }
        }
    }

    Background {
        property variant geometry: screenModel.geometry(screenModel.primary + 1)
        x: geometry.x; y: geometry.y; width: geometry.width; height: geometry.height
        visible: primaryScreen
        source: config.background2
        fillMode: Image.Stretch
        onStatusChanged: {
            if (status == Image.Error && source != config.defaultBackground) {
                source = config.defaultBackground
            }
        }
    }

    Rectangle {
        property variant geometry: screenModel.geometry(screenModel.primary + 1)
        x: geometry.x; y: geometry.y; width: geometry.width; height: geometry.height
        color: "transparent"
        visible: primaryScreen
        [...]
    }`

The last Rectangle constitutes the login box.  The backgrounds are exchanged and the login box shows up on the non-primary screen.  I can exchange the backgrounds, but I can not place the rectangle on the real primary screen since changing

`visible: primaryScreen`

to

`visible: primaryScreen + 1`

does not move the login box, but duplicates it on both screens instead.


Corinna
