### ISSUE TITLE
systemctl stop sddm doesn't (always) kill sddm-greeter

### ISSUE THREAD

**Issue by github-cygwin** [sddm/sddm#336]
Hi,

while testing my local sddm theme as in issue #335, I noticed that

    init 3

or

    systemctl stop display-manager

or

    systemctl stop sddm

more often than not fails to kill the child sddm-greeter.  If you do this a few times during update,
maintainance, or testing, the machine ends up collecting disfunctional sddm-greeter processes.

This is on Fedora 21 with systemd-216-12 only running a local X session on display :0.  I checked
the sddm.service file and the Fedora file is created from the upstream sddm.service.in with just
@CMAKE_INSTALL_FULL_BINDIR@ set to /usr/bin.

I may be wrong, but AFAICS stopping the sddm process should always stop sddm-greeters as well.
Or am I missing something?

Thanks,
Corinna

**Comment by jleclanche** [comment]
I've never seen this.

**Comment by github-cygwin** [comment]
On Feb 20 07:46, Jerome Leclanche wrote:
> I've never seen this.

I can reproduce it basically at will on my Fedora 21:

$ uname -sr
Linux 3.18.6-200.fc21.x86_64
$ ps -ef | grep sddm
root      1086     1  0 10:45 ?        00:00:00 /usr/bin/sddm
sddm      1100     1  0 10:45 ?        00:00:00 /usr/lib/systemd/systemd --user
sddm      1102  1100  0 10:45 ?        00:00:00 (sd-pam)
root      1740  1100  0 10:47 tty1     00:00:00 /usr/libexec/Xorg.bin :0 -auth /var/run/sddm/:0 -nolisten tcp -background none -noreset vt1
root      1747  1086  0 10:47 ?        00:00:00 /usr/libexec/sddm-helper --socket /tmp/Auth1086.1424511951 --id 4 --start /usr/bin/sddm-greeter --socket /tmp/sddm-:0-YTWEoP --theme /home/corinna/Pictures/sddm/themes/corinna --user sddm --greeter
sddm      1750     1  0 10:47 ?        00:00:00 /usr/bin/sddm-greeter --socket /tmp/sddm-:0-YTWEoP --theme /home/corinna/Pictures/sddm/themes/corinna
sddm      1756     1  0 10:47 ?        00:00:00 /bin/dbus-launch --autolaunch be3c8516fe60406380c4ebef174e12c8 --binary-syntax --close-stderr
sddm      1757     1  0 10:47 ?        00:00:00 /bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
corinna   1799  1768  0 10:48 tty2     00:00:00 grep --color=auto sddm
$ sudo systemctl stop sddm
$ ps -ef | grep sddm
sddm      1100     1  0 10:45 ?        00:00:00 /usr/lib/systemd/systemd --user
sddm      1102  1100  0 10:45 ?        00:00:00 (sd-pam)
sddm      1750     1  0 10:47 ?        00:00:00 /usr/bin/sddm-greeter --socket /tmp/sddm-:0-YTWEoP --theme /home/corinna/Pictures/sddm/themes/corinna
corinna   1804  1768  0 10:49 tty2     00:00:00 grep --color=auto sddm


Corinna

**Comment by jleclanche** [comment]
Can you paste the output of `journalctl -u sddm`?

**Comment by github-cygwin** [comment]
On Feb 21 05:47, Jerome Leclanche wrote:
> Can you paste the output of `journalctl -u sddm`?

Nothing of interest in there, unfortunately:

$ sudo journalctl -b -u sddm
-- Logs begin at Sun 2013-12-22 13:43:49 CET, end at Sat 2015-02-21 17:56:17 CET. --
Feb 21 10:45:52 foo.example.com sddm-helper[1099]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Feb 21 10:47:40 foo.example.com sddm-helper[1747]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Feb 21 11:03:00 foo.example.com sddm-helper[1904]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)

10:45 and 10:47 correspond with the timestamps in the ps output I pasted
into my previous reply.  11:03 corresponds with me starting sddm again
after creating the output for you.  Nothing else from sddm is in the
logs from earlier startups, just what you see above for today.


Sorry,
Corinna

**Comment by jleclanche** [comment]
Closing this by lack of information and reproducibility.
