### ISSUE TITLE
Not possible to override systemd unit file install location

### ISSUE THREAD

**Issue by martenjj** [sddm/sddm#343]
Some developers may want to relocate all of the installation, either for local testing or as part of packaging.  It is possible to override all of the normal install locations by setting CMake variables, but SYSTEMD_SYSTEM_UNIT_DIR is always read from pkg-config even if it is set already.  It should be possible to override this in the same way as any other variable.

Suggested patch:
<pre>
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4d6e0a9..61230a4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -109,8 +109,11 @@ if(SYSTEMD_FOUND)
         endif()
     endif()

-    execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=systemdsystemunitdir systemd OUTPUT_VARIABLE SYSTEMD_SYSTEM_UNIT_DIR)
-    string(REGEX REPLACE "[ \t\n]+" "" SYSTEMD_SYSTEM_UNIT_DIR ${SYSTEMD_SYSTEM_UNIT_DIR})
+    if (NOT DEFINED SYSTEMD_SYSTEM_UNIT_DIR)
+        execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=systemdsystemunitdir systemd OUTPUT_VARIABLE SYSTEMD_SYSTEM_UNIT_DIR)
+        string(REGEX REPLACE "[ \t\n]+" "" SYSTEMD_SYSTEM_UNIT_DIR ${SYSTEMD_SYSTEM_UNIT_DIR})
+    endif()
+
     set(MINIMUM_VT 1)
     set(HALT_COMMAND "/usr/bin/systemctl poweroff")
     set(REBOOT_COMMAND "/usr/bin/systemctl reboot")
</pre>

**Comment by plfiorini** [comment]
Please send a pull request so your contribution gets properly in with your name

**Comment by plfiorini** [comment]
Fix merged
