### ISSUE TITLE
Only considers one battery when showing the charge level on the greeter

### ISSUE THREAD

**Issue by Yofel** [sddm/sddm#347]
In Kubuntu 15.04 sddm tells me at login that my battery is 98% charged, which is not the full truth:

Battery 0: Discharging, 47%, 02:20:37 remaining
Battery 0: design capacity 4363 mAh, last full capacity 4222 mAh = 96%
Battery 1: Unknown, 98%
Battery 1: design capacity 1890 mAh, last full capacity 1626 mAh = 86%

running sddm 0.11.0-0ubuntu3

**Comment by jleclanche** [comment]
Sounds to me like we should be displaying all batteries.

**Comment by MartinBriza** [comment]
We do expose battery percentage? I thought this was a feature of the Plasma theme(s).

**Comment by plfiorini** [comment]
SDDM is a login manager it doesn't display battery information.
It's rather theme responsibility to do that, in this particular case (Kubuntu) I assume you are using the default breeze theme from Plasma.  This report should be submitted to KDE.
