### ISSUE TITLE
Kded5 process launched from greeter is not killed after login.

### ISSUE THREAD

**Issue by konqoro** [sddm/sddm#348]
I got 2 kded5 process running on my system. One runs as user sddm and the other as my user.

Also see KDE bug https://bugs.kde.org/show_bug.cgi?id=337674

**Comment by plfiorini** [comment]
Are you using the Breeze theme?

**Comment by konqoro** [comment]
Yes breeze, sddm theme

**Comment by plfiorini** [comment]
Breeze is a KDE theme for Plasma and uses KDE stuff including kded5.
This seems pretty normal given the circumstance.
SDDM doesn't employ directly any KDE dependency, this should be reported to the KDE bug tracker.
