### ISSUE TITLE
SDDM doesn't display Caps Lock key active message

### ISSUE THREAD

**Issue by lnxslck** [sddm/sddm#349]
When on SDDM, if you press Caps Lock, SDDM doesn't display any warning that Caps Lock is active.

**Comment by eliasp** [comment]
This depends on the theme, whether it implements such a warning or not.

What theme are you using?

**Comment by lnxslck** [comment]
@eliasp I'm using the default theme

**Comment by plfiorini** [comment]
It does now with the PasswordBox component.
