### ISSUE TITLE
FreeBSD : 0.11.0 doesn't compile fine

### ISSUE THREAD

**Issue by nadstaky** [sddm/sddm#353]
I'm new to FreeBSD, I made a port.  It fails here :1234: 
[35m[1mScanning dependencies of target sddm-helper
[0m[ 83%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/__/common/Configuration.cpp.o
[0m[ 84%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/__/common/ConfigReader.cpp.o
[0m[ 85%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/__/common/SafeDataStream.cpp.o
[0m[ 87%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/Backend.cpp.o
[0m[ 88%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/HelperApp.cpp.o
[0m[ 90%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/UserSession.cpp.o
[0m[ 91%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/backend/PamHandle.cpp.o
[0m[ 92%] [32mBuilding CXX object src/helper/CMakeFiles/sddm-helper.dir/backend/PamBackend.cpp.o
[0m[1m/usr/home/bioman/0FreeBSD/MyPorts/sddm/work/sddm-0.11.0/src/helper/backend/PamBackend.cpp:254:28: [0m[0;1;31merror: [0m[1m
      use of undeclared identifier 'PAM_XDISPLAY'[0m
            m_pam->setItem(PAM_XDISPLAY, qPrintable(display));
[0;1;32m                           ^
[0m1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /usr/home/bioman/0FreeBSD/MyPorts/sddm/work/sddm-0.11.0
*** Error code 1

Stop.
make[2]: stopped in /usr/home/bioman/0FreeBSD/MyPorts/sddm/work/sddm-0.11.0
*** Error code 1

Stop.
make[1]: stopped in /usr/home/bioman/0FreeBSD/MyPorts/sddm/work/sddm-0.11.0
*** Error code 1

Stop.
make: stopped in /usr/home/bioman/0FreeBSD/MyPorts/sddm

I've been asked to grep in /usr/include for PAX_XDISPLAY, don't have it.

here are the full build log :
http://pastebin.com/icXpweWM

**Comment by nadstaky** [comment]
It's isn't PAX_XDISPLAY but PAM_XDISPLAY. In /usr/include I have many PAM_foo but not this one.

**Comment by plfiorini** [comment]
Looks like lightdm fixed it with an ifdef: https://bugs.launchpad.net/lightdm/+bug/999709
These are in fact Linux-PAM specific.
