### ISSUE TITLE
Shutdown timer passes zero into negative numbers

### ISSUE THREAD

**Issue by Skaendo** [sddm/sddm#355]
In Slackware64-current/KDE 5.2 (unofficial alien build), when logging out and pressing shutdown, the timer continues past zero on into negative numbers.

The only way that I can turn off PC is to press the power button at that point.

**Comment by plfiorini** [comment]
I don't understand, what timer?

**Comment by Skaendo** [comment]
After I log out of KDE and return to the sddm login screen, I click on the power icon in the lower right hand corner it gives me two choices; Cancel or Shutdown, and starts a 30 second countdown. Clicking the Shutdown button does nothing, and the countdown timer continues into negative numbers. After that I have to press the hardware power button in order to turn off my PC.

**Comment by plfiorini** [comment]
Which theme are you using?

**Comment by Skaendo** [comment]
Default theme.

I don't have KDE 5 installed on any machine at this moment. I am going to set up a PC right now with Slackware-current and install KDE 5 so I can give you better answers, and a screenshot.

**Comment by plfiorini** [comment]
We need to figure out whether the issue happens with the default theme or breeze (the Plasma 5 theme). If it happens with breeze then the bug should be reported to the Plasma developers.
However I don't think we have a timer like that with the default theme.

**Comment by Skaendo** [comment]
Some possibly irrelevant info;

I did a full install of Slackware-current (3.18.11 kernel) with KDE 4.14.3. Set it up to desktop with a regular user then dropped to runlevel 3, removed KDE 4 and installed KDE 5. There have been new builds that Eric has made since I first posted, but the problem persists.

Here is the build announcement for KDE 5 that I am using on Slackware-current: http://alien.slackbook.org/blog/kde-5_15-07-july-release-for-slackware-current/

And I am following the instructions here: http://taper.alienbase.nl/mirrors/alien-kde/current/testing/README

I am setting up PC right now, and at the point of removing KDE 4. Should only take about another half hour or so to finish.

**Comment by Skaendo** [comment]
Here is a "screenshot" (lol)

![dsc08268](https://cloud.githubusercontent.com/assets/10820150/8732555/e64a6002-2bc3-11e5-81ed-aece748b46af.JPG)

**Comment by plfiorini** [comment]
Are you using systemd?
Did you set a RebootCommand and HaltCommand on /etc/sddm.conf? If you don't have systemd you should try editing /etc/sddm.conf and add:

```
[General]
HaltCommand=/usr/sbin/halt
RebootCommand=/usr/sbin/reboot
```

Beware paths may change on your distro.

**Comment by Skaendo** [comment]
No, Slackware does not use systemd.

I tried playing with the halt and reboot commands to no avail. (/sbin/halt & /sbin/reboot)
As they are packaged by AlienBob sddm.conf is set to:
HaltCommand=/sbin/shutdown -h -P now
RebootCommand=/sbin/shutdown -r now.

I can change the theme and it seems like no matter what theme is used the shutdown and reboot commands are not being executed. What I am assuming is the default theme (maui) I see no shutdown or reboot options.

I found that some people are having similar issues here: https://github.com/sddm/sddm/issues/236 including Alien Bob. He is a Slackware developer.

**Comment by jleclanche** [comment]
@Skaendo does this happen in .13?

**Comment by Skaendo** [comment]
I plan on setting up another test install in a little while.
I did have a install set up about a week ago, and it seemed to be better, the only thing that I noticed is that it took a second or two to register that I clicked shutdown but it did work.
I will update in a little while after I have set up another test run.

**Comment by Skaendo** [comment]
As far as I can tell, I have no more issues with sddm. The only time that I am having issues with it now is when the Plasma theme is applied. This was not the case before, as I was having issues with any applied theme, including the default one.

Just for reference, currently I am using sddm .12. I will build .13 and test if you want me to.

**Comment by jleclanche** [comment]
Should be fine then.
