### ISSUE TITLE
Desktop doesn't load if $HOME containts non-ASCII character(s)

### ISSUE THREAD

**Issue by davispuh** [sddm/sddm#364]
If I've a user with `$HOME` like `/home/Dāvis/` then after typing password I get black screen with visible cursor but without desktop - it doesn't load.

```
sddm-helper[1253]: Starting: "/usr/share/sddm/scripts/Xsession" "/usr/bin/startkde"
sddm-helper[1258]: Could not open stderr to .xsession-errors file
sddm-helper[1258]: Adding cookie to "/home/D?vis/.Xauthority"
sddm[1223]: Session started
sddm-helper[1253]: [PAM] Ended.
sddm[1223]: Auth: sddm-helper exited with 1
systemd-logind[324]: Removed session c15.
```

It works fine with KDM.

**Comment by mathieujobin** [comment]
this could be very much caused by Qt toLocal8Bit() being used in helper/UserSession.cpp
https://github.com/sddm/sddm/blob/master/src/helper/UserSession.cpp#L65

**Comment by mathieujobin** [comment]
@davispuh note that my system gives a warning when I create an accout with your username

```
mathieu@mathieu-MSI-X6:~$ sudo adduser Dāvis
[sudo] password for mathieu: 
adduser: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
mathieu@mathieu-MSI-X6:~$ 


```

**Comment by davispuh** [comment]
That's not surprising, for me on Arch Linux it complains only about capital letters, `dāvis` don't give any warnings while `Davis` does.
Anyway to be POSIX compliant username should match`^[a-z][-a-z0-9]*$` but technically there aren't any reason why couldn't use any other characters/format. Main reason is for compatibility with other applications which could break with unexpected usernames. I'm intentionality creating it such as just personal preference and have been using it for years without any problems until now SDDM :D For regular home users I don't think anyone really cares about POSIX compliance (I don't) so I would recommend to try work with non-compliant usernames whenever it's possible.

**Comment by davispuh** [comment]
hmm, I think using  `toLocal8Bit()` might be correct way because internally it uses `QTextCodec::codecForLocale`, but for #365, more suspicious are `QString(const char *)` casts at [/src/helper/backend/PamBackend.cpp#273](/sddm/sddm/blob/master/src/helper/backend/PamBackend.cpp#L273)  and at some other places too.

**Comment by plfiorini** [comment]
@davispuh Could you please try applying #464? Maybe it will fix this issue too.

**Comment by davispuh** [comment]
It didn't fix this either.
```
systemd[1]: Started User Manager for UID 1339.
sddm-helper[11427]: Starting: "/usr/share/sddm/scripts/Xsession" "/usr/bin/startkde"
sddm-helper[11432]: Adding cookie to "/home/D\u0101vis/.Xauthority"
sddm[11399]: Session started
sddm-helper[11427]: [PAM] Ended.
sddm[11399]: Auth: sddm-helper exited with 1
sddm-helper[11408]: [PAM] Ended.
sddm[11399]: Auth: sddm-helper exited successfully
sddm[11399]: Greeter stopped.
```
