### ISSUE TITLE
Can't login if username contains non-ASCII characters(s)

### ISSUE THREAD

**Issue by davispuh** [sddm/sddm#365]
Username such as `dāvis` can't login. After typing password it shows `Login failed`.
```
sddm-helper[13097]: [PAM] Starting...
sddm-helper[13097]: [PAM] Authenticating...
sddm-helper[13097]: [PAM] Preparing to converse...
sddm-helper[13097]: [PAM] Conversation with 1 messages
sddm-helper[13097]: pam_tally(sddm:auth): pam_get_uid; no such user
sddm-helper[13097]: pam_unix(sddm:auth): check pass; user unknown
sddm-helper[13097]: pam_unix(sddm:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
sddm-helper[13097]: [PAM] authenticate: Authentication failure
sddm-helper[13097]: [PAM] returning.
sddm[13078]: Authentication error: "Authentication failure"
sddm-greeter[13087]: Message received from daemon: LoginFailed
sddm-helper[13097]: [PAM] Ended.
sddm[13078]: Auth: sddm-helper exited with 1
```

works with KDM.

**Comment by jleclanche** [comment]
you already filed #364

**Comment by davispuh** [comment]
those are different issues :P but might be fixed with same change, don't know.

**Comment by plfiorini** [comment]
@davispuh Could you please try applying #464?

**Comment by davispuh** [comment]
Nope :( it didn't fixed this, nothing changed, but I'll look into it now myself, was planing doing it anyway.

**Comment by davispuh** [comment]
I think you'll need to revert it, because qPrintable is correct way to go, it uses toLocal8Bit which uses codecForLocale to convert to system locale as you probably can't assume it will be UTF-8.

Problem is that sddm is first process which starts and no one have set locale's environment variables. So Qt uses "C" as locale because there aren't LANG/LC and that's why nothing will work outside of ASCII.

I'm pretty sure implementing #460 should fix these issues.
