### ISSUE TITLE
sddm integration with the Plasma 5 desktop

### ISSUE THREAD

**Issue by acerspyro** [sddm/sddm#366]
There's a few things that could be done to help SDDM integrate with the Plasma 5 environment, including:
- Animations
- Fitting the selected user's color theme and background
- A settings GUI
- Compositing
Thanks!

**Comment by eliasp** [comment]
>There's a few things that could be done to help SDDM integrate with the Plasma 5 environment, including:

Generally, that's something which should be reported at [bugs.kde.org](https://bugs.kde.org) as the theme is shipped as part of plasma-workspace.

>   * Animations

What kind of animations?

>   * Fitting the selected user's color theme and background

This would result in a flickery firework of color/theme switches whenever one selects another user. Besides that, this won't work for users whose $HOME will only become available after PAM auth (e.g home on NFS).

>   * A settings GUI

[Already available](http://quickgit.kde.org/?p=sddm-kcm.git)

>   * Compositing Thanks!

This would need a full-blown compositor to be run. And then: what would the profits be for sddm? As it's UI is relatively trivial, I don't see any real reasons to do so.

**Comment by davidedmundson** [comment]
Responded on Bugzilla
