### ISSUE TITLE
Create new session does nothing with Breeze theme

### ISSUE THREAD

**Issue by juhamust** [sddm/sddm#369]
The `Create new session` button provided in login view does nothing when clicked. The expected behavior is to ask for auth info and create a session.

This is not the only issue I've encountered with the SDDM+Breeze theme (other themes do not seem to have those/same features). But is this the correct issue tracker to report Breeze related issues in the first place?

**Comment by jonmast** [comment]
Do you mean on the lock screen? If so check out https://bugs.kde.org/show_bug.cgi?id=343416

**Comment by juhamust** [comment]
Thanks, seems very much the same issue. Let's see how version 5.2.1 will turn up.

Therefore, assuming the issue is not SDDM related after all, thus closing this for now.
