### ISSUE TITLE
keyboard and mouse input freeze with SDDM

### ISSUE THREAD

**Issue by scpkyy** [sddm/sddm#370]
Description of problem:
When using SDDM in either KDE4 or KDE5 there are random input freezes of keyboard and mouse. Furthermore the machine cannot be ssh'd to from another machine in this state or rebooted as it is unresponsive. The only solution is to hard reboot. After disabling SDDM and enabling KDM the lockups do not recur. The problem first appeared when I enabled SDDM in FC20. Upgraded to FC21 and still the same problem. Did a bios upgrade - that did not resolve it. Installed KDE5 Plasma (very nice) - but that has not resolved the problem. Cannot find anything specific in the logs. Have used different keyboards and mouse to no avail. Also noticed on the last crash that Cap Lock was on in SDDM but not on the keyboard. Had to ssh to the machine and enable KDM and reboot. 

Version-Release number of selected component (if applicable):
SDDM version 0.10.0-3.fc21

How reproducible: Random
Steps to Reproduce: 1. Use SDDM 
2. Move mouse (?) 
3. Random lockup 

Actual Results: Lockup of computer. Fan still running (at higher speed perhaps indicating increased CPU access).

Expected Results: SDDM should not cause input lockup

**Comment by damianb** [comment]
likely related to #323
