### ISSUE TITLE
SDDM and polkit issue (no shutdown, reboot, sleep and suspend)

### ISSUE THREAD

**Issue by SPROgster** [sddm/sddm#379]
Clean installed Calculate Linux 14.12.1 (OpenRC). All kde-base/* packages removed. Installed @kde-plasma-5.2 from kde overlay. Consolekit installed.

Where is no shutdown, reboot, suspend and sleep buttons in KickOff.
Default values in /usr/share/polkit-1/actions/org.freedesktop.consolekit.policy and /usr/share/polkit-1/actions/org.freedesktop.upower.policy on this items (action id="org.freedesktop.upower.suspend" and all others) something like: 
```
<allow_inactive>no</allow_inactive>
<allow_active>yes</allow_active>
```
After changing to 
```
<allow_any>yes</allow_any> 
```
items appers.

If add yes to allow_inactive, items appers only after manual /etc/init.d/xdm start

/etc/conf.d/xdm:
```
#------------------------------------------------------------------------------
# Modified Calculate-core 3.3.0.13
# Processed template files:
# /var/lib/layman/calculate/profiles/templates/3.3/3_ac_install_live/1-merge/x11-base/xorg-server/conf.d/xdm
# For modify this file, create /etc/conf.d/xdm.clt template.
#------------------------------------------------------------------------------

CHECKVT=7
XUSER=sprog
DISPLAYMANAGER="sddm"
START_STOP_ARGS="--background -- /usr/bin/xautologin $XUSER $CHECKVT"
```

PS Sorry if it's not a sddm bug

**Comment by davidedmundson** [comment]
Do you have logind?

**Comment by SPROgster** [comment]
No, I have not. No systemd at all

**Comment by davidedmundson** [comment]
I've seen this problem before in setup issues where we weren't going through PAM correctly to tell logind which the active session is, this must be some consolekit equivalent.

Check your pam files make sure it's going through console kit connector properly.
Also I think there's meant to be some console kit thing in /etc/X11/Xsession that wraps the session.
