### ISSUE TITLE
SDDM using wrong font

### ISSUE THREAD

**Issue by zatherz** [sddm/sddm#383]
So, starting from version 0.9, SDDM should use the Oxygen font. The problem is that, for me, it doesn't. It uses a different font, as shown in the image:
![image](https://cloud.githubusercontent.com/assets/4568670/6651682/8dd8433c-ca46-11e4-9660-8a3461ab0512.png)

I'd like it to use Oxygen-Sans for the interface. Is there any way to make it so?

**Comment by plfiorini** [comment]
Does it happen with the maui theme as well?

**Comment by zatherz** [comment]
This issue seems to be gone, either after a reinstallation of SDDM, Plasma or a different update.

**Comment by ellisistfroh** [comment]
Please close this bug-report as KDE bakes its own breeeze-login screen, So this was fixed from the KDE-devs.
