### ISSUE TITLE
Incorrect date localization

### ISSUE THREAD

**Issue by anntzer** [sddm/sddm#384]
With a French locale, the date shows up as (e.g., today) "dimanche, mars 15", which is the English order, but this is absolutely incorrect as this should be written as "dimanche 15 mars".

**Comment by aspotashev** [comment]
Same problem for Russian locale.

**Comment by anntzer** [comment]
Actually the fix is trivial: the call to `Qt.formatDate(container.dateTime, "dddd, MMM dd")` in Clock.qml should use the `Qt.DefaultLocaleLongDate` (or `ShortDate`, depending on your preference) format instead of "dddd, MMM dd".
