### ISSUE TITLE
After KDE logout, log in screen never loads - Stalls on sddm-helper

### ISSUE THREAD

**Issue by magicmyth** [sddm/sddm#385]
This is a forward of Launchpad bug 1407152
https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1407152

On an up to date Kubuntu Vivid, loging out leaves a black screen with cursor permently untill sddm-helper is killed.

**Comment by Thik** [comment]
same here on openSUSE

**Comment by davidedmundson** [comment]
Confirmed something is wrong. 

openbox also fails to log out, and KDE works fine with xdm.

Will fix.

**Comment by davidedmundson** [comment]
I'll write up my findings in case someone can come up with an idea.

sddm-helper invokes the session (say, openbox) via QProcess
it then connects and waits on that QProcess finishing, when that happens it exits itself.

That signal is never emitted

When openbox is killed it goes into defunct state, meaning the kernel is waiting for the parent process to read it's return status.  

According to /proc openbox's parent is sddm-helper

a breakpoint on qt_sa_sigchld_sigaction in qprocess_unix shows that sddm-helper never receives that signal.

Replacing the qprocess connections in sddm-helper by
waitpid(m_session->pid(), 0, 0); exit(0):  works

(though I don't want to push that as it doesn't solve the root problem)

I've tried the following with no luck:
 - removing the signal handler in the sddm daemon
 - getting rid of the xsession scripts, and invoking the main session app directly
 - getting rid of consolekit wrapping the session

Interestingly (and confusingly) on my Arch box logout seems to work.

**Comment by davidedmundson** [comment]
Found it (in Kubuntu at least)
They packaged it so the sddm PAM file included pam_gnome_keyring.
common_password already included pam_gnome_keyring.
sddm's pam file includes common_password.

The end result is session pam_gnome_keyring is included twice.

The first one sets up a signal handler, starts gnome-keyring and all is well.
The second one sets up a signal handler, does nothing, then intercepts all of my SIGCHLD signals that I need in sddm-helper to know when our session ends.

Our QProcess object never gets told the child exited so never wakes up and the session (startkde, openbox whatever) is in a defunct state waiting for us to read the exit state.

I'll talk to Kubuntu people, @thik can you notify the relevant SuSE people and point them to me.

**Comment by mathieujobin** [comment]
good job figuring this one out @davidedmundson 

I'm not sure if that's related, but I have another PAM issue with sddm,

/etc/pam.d/sddm includes a /etc/pam.d/system-login 
which does not exist on my system.
it might be a legacy file that has been removed on the recent switch to systemd ?

I replace that reference to be systemd-user and sddm works fine again.

hope this can helps someone else.

**Comment by davidedmundson** [comment]
Can you state your distro.
PAM files tend to end up distro specific

**Comment by mathieujobin** [comment]
Kubuntu 15.04 vivid

**Comment by jriddell** [comment]
uploaded gnome-keyring 3.16.0 to ubuntu vivid now, building away now
