### ISSUE TITLE
password filed vertical align and invisible content

### ISSUE THREAD

**Issue by MauroMombelli** [sddm/sddm#391]
on my Laptop the password field act very strange, "text" is not vertically aligned and when it reach the right border it just disappear (it's still here as i can delete and select it)

here some "circles" theme, on breeze is even more visible. The only thing i can think of is that i changed the default font size in Plasma. Other than Theme and CursorTheme no changes to default configuration.

![img_20150325_192644](https://cloud.githubusercontent.com/assets/6372561/6837348/8c671740-d34b-11e4-97ac-34e1b8c00659.jpg)

**Comment by simonsmiley** [comment]
have the same issue. running archlinux with latest updates

**Comment by MauroMombelli** [comment]
@flyingDavid you are right!

can you lease point where i can send this bug to QT?

![image](https://cloud.githubusercontent.com/assets/6372561/6998380/a25ab4dc-dbe1-11e4-8275-7bb152661dae.png)

**Comment by flyingDavid** [comment]
I did some more investigations and filed this bug report:
https://bugreports.qt.io/browse/QTBUG-45412

**Comment by jleclanche** [comment]
Flagging as wontfix as it's been upstreamed. Follow up on QTBUG-45412.

**Comment by MauroMombelli** [comment]
Can confirm has been fixed
