### ISSUE TITLE
Stopping sddm gives a blank tty

### ISSUE THREAD

**Issue by siddharthasahu** [sddm/sddm#392]
Hi,

If I stop the sddm service (systemctl stop sddm), tty1 goes blank with a blinking cursor instead of showing the user login.

**Comment by eliasp** [comment]
Please provide some context:
- which sddm version?
- which distribution?
- which initsystem?
- etc.

**Comment by siddharthasahu** [comment]
Oh sorry completely forgot. I am on Arch Linux using systemd 218 and sddm 0.11.0

**Comment by plfiorini** [comment]
That's because getty was not started which is normal considering you enabled the sddm service.

**Comment by siddharthasahu** [comment]
Hey, thanks for the input.

I can see now that the display manager service has a 'Conflicts=getty@tty1.service' line, so starting the DM service stops tty1. Seems like a weird decision. Will ask in my distro channel.

Cheers!

**Comment by plfiorini** [comment]
Login managers start on tty1 so there shouldn't be a getty there when sddm starts.

**Comment by siddharthasahu** [comment]
Ah ok. Can you please explain why that is a necessity? Security issues I am guessing?
1) How about when I choose minimumVT=7? It stills stops tty1.
2) Is there a way to start the getty service again when sddm service is stopped?

**Comment by plfiorini** [comment]
It's a systemd convention login managers are on vt1
