### ISSUE TITLE
nvidia-prime support at login

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#393]
Nvidia Prime is a funky setup for users who feel the need for both NVidia and Intel GPUs on their computer.  This needs a program to be run as root at login and logout.  Here's a patch I'm using in Kubuntu to run the program at login.

This would be more elegant with cascading config support as requested in https://github.com/sddm/sddm/issues/217 then the nvidia-prime package could just set a config value like lightdm has:
"display-setup-script is run after the X server starts but before the user session / greeter is run. "

**Comment by jriddell** [comment]
Index: sddm-0.11.0/data/scripts/Xsetup
===================================================================
--- sddm-0.11.0.orig/data/scripts/Xsetup
+++ sddm-0.11.0/data/scripts/Xsetup
@@ -1,3 +1,7 @@
 #!/bin/sh
 # Xsetup - run as root before the login dialog appears
 
+if [ -e /sbin/prime-offload ]; then
+    echo running NVIDIA Prime setup /sbin/prime-offload, you will need to manually run /sbin/prime-switch to shut down
+    /sbin/prime-offload
+fi

**Comment by tseliot** [comment]
We have "display-setup-script" (which seems to be the same as the "DisplayCommand" entry in sddm), and "display-stopped-script" to execute a script immediately after X is stopped. I've just written some code that should add the latter (it's more of a copy and paste).

**Comment by plfiorini** [comment]
Maybe this is something that we would add by default.

@jriddell Is there any change between distros on how NVIDIA Prime is handled?
