### ISSUE TITLE
display-stopped-script config value for nvidia-prime

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#394]
Nvidia Prime is a funky setup for users who feel the need for both NVidia and Intel GPUs on their computer.  It needs to run a script on shutdown to keep these users happy.

This is implemented in lightdm as a config value "display-stopped-script is run after an X server exits. It is run as root. " and the nvidia-prime package in ubuntu sets this to run /sbin/prime-switch

**Comment by plfiorini** [comment]
We have https://github.com/sddm/sddm/blob/master/data/scripts/Xstop now, shall we close this issue?

**Comment by jleclanche** [comment]
Yes
