### ISSUE TITLE
Graphical corruption when Suspended with compositor

### ISSUE THREAD

**Issue by lavacano** [sddm/sddm#398]
99kb http://i.imgur.com/gmrqPe0.jpg

might be related to my bug report here https://bugs.kde.org/show_bug.cgi?id=346024

**Comment by mathieujobin** [comment]
I got this issue this morning.

I am using Kubuntu 15.04

I created a new session, which open on tty9, existing desktop was tty8,
when I switch back with ctrl-alt-f8, my desktop was flickering with triangle going in circle and pictures of my open apps and sddm login

I probably could have `service sddm restart` but chose to reboot.

**Comment by lavacano** [comment]
@mathieujobin right out of sleep password field has focus and last user is selected, you can enter your password press enter then suspend kwin compositing (default leftalt+shift+F12) and poof corruption vanishes.  Can you confirm here https://bugs.kde.org/show_bug.cgi?id=346024 ?

**Comment by the100rabh** [comment]
I too am facing a similar issue, once the system wakes up from sleep, the display gets corrupted. 
service sddm restart works to get display back to nomal mode, but it does not help that all apps open are closed defeating the very purpose of putting system to sleep. 
I am Dell Inspiron 15, 3000series.

**Comment by plfiorini** [comment]
This seems a Plasma bug not related to sddm.
When the user session is started the sddm greeter is long gone.
Closing the issue.
