### ISSUE TITLE
Add screen lock for autologin

### ISSUE THREAD

**Issue by HinzundKunz** [sddm/sddm#401]
It would be great if you could set the screen to lock after autologin. It would reduce the felt boot time even further.

**Comment by int-ua** [comment]
Duplicate, check https://github.com/sddm/sddm/issues/306#issuecomment-76474868 for a workaround.

**Comment by int-ua** [comment]
What DEs can do that? I know only about KDE.

**Comment by plfiorini** [comment]
Close as being duplicate of #306
