### ISSUE TITLE
Add an option to set DPI value

### ISSUE THREAD

**Issue by Jiehong** [sddm/sddm#402]
Hello,

Currently, SDDM does not offer any option to set a DPI value. It seems that the value used may be 96 DPI, perhaps hard-coded somewhere.

On "retina"-like  screen (Apple products, but also some Lenovo, Dells, etc.), the size of everything is way too small, but would appear just right with a DPI value of 192.

Would it be possible to have the possibility to set the DPI value in sddm.conf?

**Comment by jleclanche** [comment]
I dont think we should provide an option but we should do a better job of figuring out the dpi.

**Comment by int-ua** [comment]
There are some cases where we still need to set DPI manually. For example users with weak eyesight.

**Comment by jleclanche** [comment]
@int-ua yes, but sddm should not be the place where you set it, we should get it from global settings. If you want high dpi on sddm, you generally want high dpi on your desktop too.

**Comment by int-ua** [comment]
A reasonable argument, yes, but what if there are multiple users (both Unix and IRL) and only one needs high DPI on desktop?

**Comment by jleclanche** [comment]
Then we'd still pull in from global settings. Those will just have to be set according to your preference. This is something we want to figure out, but it should be transparent to both us and the users.

**Comment by WeiHan3** [comment]
My workaround is "ServerArguments=-nolisten tcp -dpi 192" in sddm.conf. 

It works in Gentoo and version 0.13.0.

**Comment by plfiorini** [comment]
I'd rather add @WeiHan3 suggestion to the documentation in the troubleshooting section rather than adding an option somewhere.
