### ISSUE TITLE
Add native ConsoleKit2 support 

### ISSUE THREAD

**Issue by stalkerg** [sddm/sddm#404]
ConsoleKit2 is not deprecated and supported:
https://github.com/ConsoleKit2/ConsoleKit2

Last commit Apr 7, 2015:
https://github.com/ConsoleKit2/ConsoleKit2/commits/master

Please don't close bug. Maybe in the future, but you implement support.

**Comment by plfiorini** [comment]
As far as I know none of the sddm developers is willing to maintain another backend.
There is not enough man power to do that, besides another backend might introduce complexity.
