### ISSUE TITLE
A simple username field entry.

### ISSUE THREAD

**Issue by shrinidhi666** [sddm/sddm#406]
Is there any simple way to just type the username rather than select from a list of 100+ usernames in a workplace?!. Its really annoying to go through all the names in the list everytime and also there is no easy way to scroll , at least in the latest version of kubuntu 15.04 testing.

**Comment by flyingDavid** [comment]
You should report this bug to kde (package: plasmashell, component: look and feel), as the breeze greeter, which you are appearently using, is part of kde, not of sddm. A workaround would be to choose another greeter in the kde system settings (in the startup section, but I'm not sure if other greeters are installed by default in kubuntu).

**Comment by shrinidhi666** [comment]
Thanks . I changed the greeter theme to archlinux , which I installed from their repo and it worked .

**Comment by plfiorini** [comment]
So shall I close it now?

**Comment by flyingDavid** [comment]
I don't know much about sddm and qml, but wouldn't it be a good idea to have a config option whether to use a user list or a username field? So every greeter could have a user list or a username field, depending on the option. A username prompt is definitely needed in big environments, but in small environments, a user list is better. In my opinion it's bad if we have to change this by changing the theme, and not by changing the config. Of course a theme could also ignore this option for simplicity..

**Comment by shrinidhi666** [comment]
@plfiorini I dont mind if this issue is closed as long as there is a proper documentation of how to get it done. I had to ask here and kubuntu community in G+ just to know that its a theme based option. The better solution is what @flyingDavid suggested.

**Comment by mathieujobin** [comment]
from a UI stand point, it would be interesting if you could focus on the user selection and type in your username on the graphical selection, without the standard text input field. right now, on the breeze theme, the focus is locked up on the password field. which works for most users.

the people I met with low troubleshooting skills usually installs a different distro when they don't like something.

and people who manage systems with hundreds of users should know how their login manager works. sddm's flexible theme infrastructure is one of its killer feature.

my two cents,

**Comment by flyingDavid** [comment]
Interesting idea, but I think only few people would use this feature because most people wouldn't know it exists.
There should also be a feedback what the user typed in (like a little textfield, in case the user misstypes), so there would be almost no difference to a username field with autocompletion (Btw: does autocompletion in themes with usernamename filed exists?).

I agree that people managing hundreds of  systems should know how the loginmanager works, but they shouldn't need to use another the theme to accomplish the username selection, or change the source code, so I think a config option is still needed.

**Comment by hussamT** [comment]
For some, exposing the usernames of the people on the machine may be considered a security issue. I would rather manually type in my username and password and not even expose the last-logged-in user.

**Comment by Skavenger0** [comment]
Does anyone have a workaround for this. Not being able to type my user name is stopping me logging in using domain based authentication.

**Comment by jleclanche** [comment]
This isn't a matter of configuration, we should provide some way of typing in the username. @plfiorini @davidedmundson I'd suggest that typing in letters would pop up a feedback text box and hide the non-matching users from the user list, kinda like what the gtk file picker does.

**Comment by flyingDavid** [comment]
@Skavenger0 did you try the workaround mentioned above, (using another theme) until the issue is fixed?
@jleclanche do you think users would realize that this feature exists as there would be no textbox initially? I'm still in doubt about this. Or do you intend to display a small hint about it?

**Comment by jleclanche** [comment]
A UX hint of sorts is possible. For now I'd focus on actually building the feature and see how it fares.

**Comment by plfiorini** [comment]
This should be implemented on the themes:
1. Provide a link or button that opens a popup asking username and password
2. Send those information to the daemon the usual way

**Comment by Skavenger0** [comment]
@jleclanche yes I did try to change the theme but my installation wouldn't accept it for some reason. 
The issue is really hitting me as my organisation uses Active Directory for authentication, providing single login credentials for any computer in the company. Without the ability to type the U/N sddm just shows a list of over 1000 users to scroll through.

Can anyone give me a high level guide on what I should be doing to change the theme please?

**Comment by marcelrc** [comment]
@Skavenger0 On Kubuntu 15.04 install the packages "sddm-theme-circles", "sddm-theme-elarun" or "sddm-theme-maldives". Then go to the system settings -> startup and shutdown -> auth screen (SDDM) and choose another theme.

**Comment by Skavenger0** [comment]
@marcelrc Thanks, sorted

**Comment by dirteat** [comment]
Hi there,
I just would like to stress that such a feature is a must. All sysadmins do not want a list of all usernames displayed on the greeter. I think sddm should have a simple configuration option taking precedence over any kde themes that would remove such a list. I hope it could be implemented as this would be a added value compared to other dm (it is a pain to do it on gdm, lxdm, lightdm...).

Keep up the good work!

cheers.

**Comment by bluej100** [comment]
I switched to the maldives theme as a workaround.

**Comment by doktor5000** [comment]
@jleclanche You might also want to consider that not everybody might appreciate, that login manager shows hints about existing usernames, as this might be considered a security issue. We also switched to a custom theme as our default theme for Mageia (based on maldives theme but with other graphics).

**Comment by jleclanche** [comment]
@doktor5000 Usernames are not hidden information. If you really want this you can always use HideUsers; themes should take those into account.

**Comment by rivaldi8** [comment]
In my opinion, SDDM should automatically switch from the user list to user name and password fields when the user count surpasses a certain threshold.

**Comment by shmerl** [comment]
I have the same problem when trying to authenticate using active directory user. Breeze theme for sddm leaves no option for such log in, so it's actually a bug for it. Should it be filed in KDE bug tracker?

**Comment by devurandom** [comment]
See-Also: https://bugs.kde.org/show_bug.cgi?id=364139

**Comment by CyberKiller40** [comment]
Just hit this at my workplace too, we have ~10k users in ldap and saying the Breeze theme is unusable with this number is a bit of an understatement ;-). Luckily other themes allow manual username entry.

**Comment by davidedmundson** [comment]
Plasma 5.7 Breeze now also has a text input field.

**Comment by CyberKiller40** [comment]
Awesome :-)

**Comment by orclex** [comment]
The login screen  "Different User" with text input field is good but it would be great to have an option to see that login screen as default. In large companies it is one unnecessary click if you always need to login using a text input field.

**Comment by hoehnth** [comment]
Maybe its better to show only users which already logged in, see [#479](https://github.com/sddm/sddm/issues/479). Would be an additional config option. We patched sddm to have that reasonable small user list shown in greeter. Provided as PR but needs some finishing work.

**Comment by Pointedstick** [comment]
This is a theme issue because the greeter theme has total control over how to present users. Also, the Breeze SDDM theme now has this feature. You can optionally enter username entry mode and type a username if the list of users is overwhelmingly long.
