### ISSUE TITLE
monitor does not shut on sddm screen anymore

### ISSUE THREAD

**Issue by mathieujobin** [sddm/sddm#407]
my monitor used to go on low power saving when I stop using my computer for several minutes.

but sddm seems to be keeping it up.

any idea if this is a setting somewhere?

**Comment by mathieujobin** [comment]
just to confirm and logged out, and my screen goes to sleep when I on the login screen (AKA no active session)

but does not on lock screen.

this could be a problem with kscreenlocker, right?

**Comment by plfiorini** [comment]
Lock screen is not sddm, so this issue seems not related to sddm.

**Comment by mathieujobin** [comment]
thanks
