### ISSUE TITLE
nvidia propietary driver causing blank screen

### ISSUE THREAD

**Issue by pgquiles** [sddm/sddm#409]
I am having trouble with a laptop with hybrid graphics (Intel 4600 + Nvidia GeForce 840M).

When I select nvidia with nvidia-prime, I get a blank screen at next boot.

I am using a fully-updated Kubuntu Vivid amd64, Nvidia proprietary drivers 349.16-0ubuntu0~xedgers15.04.1 (from the X-edgers PPA) and nvidia-prime 0.8.1

Selecting intel with nvidia-prime works fine but it's the Intel graphics card, not Nvidia.

prime-switch reports the usual "/etc/modprobe.d is not a file" and "no alternatives":

pgquiles@envy:~$ sudo prime-switch
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
update-alternatives: error: no alternatives for x86_64-linux-gnu_gfxcore_conf

No Intel graphics installer on the system, there never was (some people say removing it solved the problem: https://bugs.launchpad.net/ubuntu/+source/upstart/+bug/1369216 )

**Comment by jleclanche** [comment]
Try the previous major driver version, the 349.16 line is giving me a lot of segfaults as well.

**Comment by pgquiles** [comment]
Tried 346.59-0ubuntu1, same problem

**Comment by kirby33** [comment]
Hello everybody.

If you don't know which driver to use, I suggest to go to the NVIDIA website: http://www.nvidia.fr/Download/index.aspx?lang=en select your graphic card (and Linux) and push the search button.
For me, I have a GTX880M and I get the driver "Version: 346.72".
Therefore I use the driver nvidia-346 coming from the ppa xorg-edgers

For a good starting point:
   sudo apt-get install ppa-purge
   sudo apt-get remove --purge nvidia-*
   sudo ppa-purge ppa:xorg-edgers/ppa

And now (of course replace the number 346 with the number you get from the NVIDIA website):
   sudo add-apt-repository ppa:xorg-edgers/ppa 
   sudo apt-get update
   sudo apt-get install nvidia-346 nvidia-346-uvm nvidia-settings nvidia-prime

About the black-screen issue:
Using the the root privilege edit the file /sbin/prime-offload:
   sudo gedit /sbin/prime-offload

And just replace the first line #!/bin/sh by #!/bin/bash and save.

Now, you can use the command: sudo prime-select nvidia (or intel) and reboot your laptop.

If you want to use the prime-indicator widget:
   sudo add-apt-repository ppa:nilarimogard/webupd8
   sudo apt-get update
   sudo apt-get install prime-indicator

I use lightdm as login manager, and for me, prime-indicator doesn't work properly. I have fix the issue with this workaround:

With the root privilege edit the files /usr/lib/primeindicator/igpuon and /usr/lib/primeindicator/dgpuon and just before "sync" insert this line:   service lightdm restart

So you get this for the file igpuon:
   prime-select intel
   service lightdm restart
   sync

And you get this for the file dgpuon:
   prime-select nvidia
   service lightdm restart
   sync

I hope that this feed-back will be helpful to other people.
++ Kirby

**Comment by plfiorini** [comment]
Closing for no reply for 2 months besides this should be dealt with custom configurations.
We have the Xsetup script now, mentioned on README.md
