### ISSUE TITLE
Kerberos/LDAP; how to respect /etc/security/group.conf ?

### ISSUE THREAD

**Issue by tkleindienst** [sddm/sddm#414]
Question:
What has to be adjusted to make SDDM respect /etc/security/group.conf?

Using Kerberos/LDAP on a Kubuntu install: Login in via SDDM seems to ignore the /etc/security/group.conf file. Local groups (like "audio", "cdrom") need to be added on-the-fly when logging-in.

Does SDDM support this?

**Comment by jleclanche** [comment]
According to #416 this is an invalid issue.
