### ISSUE TITLE
sddm boot up unresponsive black screen

### ISSUE THREAD

**Issue by TheodoreT** [sddm/sddm#415]
I am running an archlinux x86_64 system. Updating **llvm-libs-svn, llvm-svn clang-svn, clang-analyzer-svn, xf86-video-ati-git** packages to their latest version causes an unresponsive black screen during the booting procedure. Downgrading to the **llvm-libs-svn-235384-1, llvm-svn-235384-1, clang-svn-235384-1, clang-analyzer-svn-235384-1, xf86-video-ati-git-3206.5921ba4-1** revisions makes things work again.

**Comment by pkonecny** [comment]
Hi Theodore, 
I can confirm this issue.
This is the output of journalctl -b 0 grepped for sddm (could only get to this via ssh as Ctrl+Alt+FX does not work)
Aug 02 12:58:16 elitebook sddm[260]: Initializing...
Aug 02 12:58:16 elitebook sddm[260]: Starting...
Aug 02 12:58:16 elitebook sddm[260]: Adding new display 0 on vt 1 ...
Aug 02 12:58:16 elitebook sddm[260]: Adding cookie to "/var/run/sddm/:0"
Aug 02 12:58:16 elitebook sddm[260]: Display server starting...
Aug 02 12:58:16 elitebook sddm[260]: Running: /usr/bin/X :0 -auth /var/run/sddm/:0 -nolisten tcp -background none -noreset vt1
Aug 02 12:58:20 elitebook sddm[260]: Display server stopped.

One question: Are you using a laptop with hybrid graphics? If so I believe this to be the roo of the issue.

**Comment by pkonecny** [comment]
A workaround for this is to restart sddm via ssh (systemctl restart sddm.service)
After that this is my journalctl

Aug 01 23:29:37 elitebook sddm[279]: Initializing...
Aug 01 23:29:37 elitebook sddm[279]: Starting...
Aug 01 23:29:37 elitebook sddm[279]: Adding new display 0 on vt 1 ...
Aug 01 23:29:37 elitebook sddm[279]: Adding cookie to "/var/run/sddm/:0"
Aug 01 23:29:37 elitebook sddm[279]: Display server starting...
Aug 01 23:29:37 elitebook sddm[279]: Running: /usr/bin/X :0 -auth /var/run/sddm/:0 -nolisten tcp -background none -noreset vt1
Aug 01 23:29:39 elitebook sddm[279]: Signal received: SIGUSR1
Aug 01 23:29:39 elitebook sddm[279]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
Aug 01 23:29:39 elitebook sddm[279]: Display server started.
Aug 01 23:29:39 elitebook sddm[279]: Socket server starting...
Aug 01 23:29:39 elitebook sddm[279]: Socket server started.
Aug 01 23:29:39 elitebook sddm[279]: Greeter starting...
Aug 01 23:29:39 elitebook sddm-helper[439]: [PAM] Starting...
Aug 01 23:29:39 elitebook sddm-helper[439]: [PAM] Authenticating...
Aug 01 23:29:39 elitebook sddm-helper[439]: [PAM] returning.
Aug 01 23:29:39 elitebook sddm-helper[439]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Aug 01 23:29:39 elitebook systemd-logind[276]: New session c1 of user sddm.
Aug 01 23:29:39 elitebook systemd[1]: Started Session c1 of user sddm.
Aug 01 23:29:39 elitebook systemd[441]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
Aug 01 23:29:39 elitebook sddm[279]: Greeter session started successfully
Aug 01 23:29:40 elitebook sddm-greeter[445]: Connected to the daemon.
Aug 01 23:29:40 elitebook sddm[279]: Message received from greeter: Connect
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 23:29:40 elitebook sddm-greeter[445]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Aug 01 23:29:41 elitebook sddm-greeter[445]: QDBusConnection: name 'org.freedesktop.UDisks2' had owner '' but we thought it was ':1.13'
Aug 01 23:29:41 elitebook sddm-greeter[445]: Message received from daemon: Capabilities
Aug 01 23:29:41 elitebook sddm-greeter[445]: Message received from daemon: HostName
Aug 01 23:31:10 elitebook sddm[279]: Message received from greeter: Login
Aug 01 23:31:10 elitebook sddm[279]: Reading from "plasma.desktop"
Aug 01 23:31:10 elitebook sddm-helper[578]: [PAM] Starting...
Aug 01 23:31:10 elitebook sddm-helper[578]: [PAM] Authenticating...
Aug 01 23:31:10 elitebook sddm-helper[578]: [PAM] Preparing to converse...
Aug 01 23:31:10 elitebook sddm-helper[578]: [PAM] Conversation with 1 messages
Aug 01 23:31:11 elitebook sddm-helper[578]: [PAM] returning.
Aug 01 23:31:11 elitebook sddm[279]: Authenticated successfully
Aug 01 23:31:11 elitebook sddm-helper[578]: pam_unix(sddm:session): session opened for user paul by (uid=0)
Aug 01 23:31:11 elitebook sddm-greeter[445]: Message received from daemon: LoginSucceeded
Aug 01 23:31:11 elitebook sddm-helper[439]: [PAM] Ended.
Aug 01 23:31:11 elitebook sddm-helper[578]: Starting: "/usr/share/sddm/scripts/Xsession" "/usr/bin/startkde"
Aug 01 23:31:11 elitebook sddm[279]: Auth: sddm-helper exited successfully
Aug 01 23:31:11 elitebook sddm[279]: Greeter stopped.
Aug 01 23:31:11 elitebook sddm-helper[583]: Adding cookie to "/home/paul/.Xauthority"
Aug 01 23:31:13 elitebook sddm[279]: Session started
Aug 02 00:58:44 elitebook systemd[1]: Stopped Session c1 of user sddm.
Aug 02 00:58:44 elitebook systemd[442]: pam_unix(systemd-user:session): session closed for user sddm
Aug 02 00:58:44 elitebook sddm[279]: Signal received: SIGTERM
Aug 02 00:58:44 elitebook sddm[279]: Socket server stopping...
Aug 02 00:58:44 elitebook sddm[279]: Socket server stopped.
Aug 02 00:58:44 elitebook sddm[279]: Display server stopping...
Aug 02 00:58:46 elitebook sddm[279]: Display server stopped.
Aug 02 00:58:46 elitebook sddm[279]: QProcess: Destroyed while process ("/usr/lib/sddm/sddm-helper") is still running.

**Comment by pkonecny** [comment]
It also happens on openSuSE Leap 42.1
OpenSuse handles it more gracefully than Arch though. I can change to another vt where as in arch I can only use ssh to get something out of the system. 
This is the initial boot up on openSuSE 42:

Aug 01 14:30:42 linux-eflx sddm[1032]: Starting...
Aug 01 14:30:42 linux-eflx sddm[1032]: Adding cookie to "/run/sddm/:0"
Aug 01 14:30:42 linux-eflx sddm[1032]: Display server starting...
Aug 01 14:30:42 linux-eflx sddm[1032]: Running: /usr/bin/X :0 -auth /run/sddm/:0 -nolisten tcp -background none -noreset vt7
Aug 01 14:30:42 linux-eflx.site display-manager[912]: Starting service sddm..done
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Running display setup script  "/etc/X11/xdm/Xsetup"
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Display server started.
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Socket server starting...
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Socket server started.
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Greeter starting...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] Starting...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] Authenticating...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] returning.
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Aug 01 14:30:42 linux-eflx.site systemd[1432]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
Aug 01 14:30:43 linux-eflx.site sddm-greeter[1435]: QXcbConnection: Could not connect to display :0
Aug 01 14:30:43 linux-eflx.site sddm-helper[1427]: [PAM] Ended.
Aug 01 14:30:43 linux-eflx.site sddm[1032]: Auth: sddm-helper exited successfully
Aug 01 14:30:43 linux-eflx.site sddm[1032]: Greeter stopped.
Aug 01 14:30:43 linux-eflx.site systemd[1433]: pam_unix(systemd-user:session): session closed for user sddm


After restarting sddm i get this: 

Aug 01 14:30:42 linux-eflx sddm[1032]: Starting...
Aug 01 14:30:42 linux-eflx sddm[1032]: Adding cookie to "/run/sddm/:0"
Aug 01 14:30:42 linux-eflx sddm[1032]: Display server starting...
Aug 01 14:30:42 linux-eflx sddm[1032]: Running: /usr/bin/X :0 -auth /run/sddm/:0 -nolisten tcp -background none -noreset vt7
Aug 01 14:30:42 linux-eflx.site display-manager[912]: Starting service sddm..done
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Running display setup script  "/etc/X11/xdm/Xsetup"
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Display server started.
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Socket server starting...
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Socket server started.
Aug 01 14:30:42 linux-eflx.site sddm[1032]: Greeter starting...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] Starting...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] Authenticating...
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: [PAM] returning.
Aug 01 14:30:42 linux-eflx.site sddm-helper[1427]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Aug 01 14:30:42 linux-eflx.site systemd[1432]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
Aug 01 14:30:43 linux-eflx.site sddm-greeter[1435]: QXcbConnection: Could not connect to display :0
Aug 01 14:30:43 linux-eflx.site sddm-helper[1427]: [PAM] Ended.
Aug 01 14:30:43 linux-eflx.site sddm[1032]: Auth: sddm-helper exited successfully
Aug 01 14:30:43 linux-eflx.site sddm[1032]: Greeter stopped.
Aug 01 14:30:43 linux-eflx.site systemd[1433]: pam_unix(systemd-user:session): session closed for user sddm
Aug 01 14:42:48 linux-eflx.site sddm[1924]: Starting...
Aug 01 14:42:48 linux-eflx.site sddm[1924]: Adding new display 1 on vt 7 ...
Aug 01 14:42:48 linux-eflx.site sddm[1924]: Adding cookie to "/run/sddm/:1"
Aug 01 14:42:48 linux-eflx.site sddm[1924]: Display server starting...
Aug 01 14:42:48 linux-eflx.site sddm[1924]: Running: /usr/bin/X :1 -auth /run/sddm/:1 -nolisten tcp -background none -noreset vt7
Aug 01 14:42:50 linux-eflx.site sddm[1924]: Running display setup script  "/etc/X11/xdm/Xsetup"
Aug 01 14:42:50 linux-eflx.site sddm[1924]: Socket server starting...
Aug 01 14:42:50 linux-eflx.site sddm[1924]: Socket server started.
Aug 01 14:42:50 linux-eflx.site sddm[1924]: Greeter starting...
Aug 01 14:42:50 linux-eflx.site sddm-helper[1934]: [PAM] Starting...
Aug 01 14:42:50 linux-eflx.site sddm-helper[1934]: [PAM] Authenticating...
Aug 01 14:42:50 linux-eflx.site sddm-helper[1934]: [PAM] returning.
Aug 01 14:42:50 linux-eflx.site sddm-helper[1934]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Aug 01 14:42:50 linux-eflx.site systemd[1938]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
Aug 01 14:42:50 linux-eflx.site sddm[1924]: Greeter session started successfully
Aug 01 14:42:50 linux-eflx.site sddm-greeter[1942]: Connected to the daemon.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject: Cannot create children for a parent that is in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: Message received from daemon: Capabilities
Aug 01 14:42:51 linux-eflx.site sddm-greeter[1942]: Message received from daemon: HostName
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Display server stopped.
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Socket server stopping...
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Socket server stopped.
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Removing display 0 ...
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Adding new display 0 on vt 7 ...
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Adding cookie to "/run/sddm/:0"
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Display server starting...
Aug 01 14:42:53 linux-eflx.site sddm[1032]: Running: /usr/bin/X :0 -auth /run/sddm/:0 -nolisten tcp -background none -noreset vt7
Aug 01 14:42:55 linux-eflx.site sddm[1032]: Display server stopped.
Aug 01 14:43:00 linux-eflx.site sddm[1924]: Reading from "plasma5.desktop"
Aug 01 14:43:00 linux-eflx.site sddm-helper[2003]: [PAM] Authenticating...
Aug 01 14:43:00 linux-eflx.site sddm-helper[2003]: [PAM] Preparing to converse...
Aug 01 14:43:00 linux-eflx.site sddm-helper[2003]: [PAM] Conversation with 1 messages
Aug 01 14:43:00 linux-eflx.site sddm-helper[2003]: [PAM] returning.
Aug 01 14:43:00 linux-eflx.site sddm[1924]: Authenticated successfully
Aug 01 14:43:00 linux-eflx.site sddm-greeter[1942]: Message received from daemon: LoginSucceeded
Aug 01 14:43:00 linux-eflx.site sddm-helper[2003]: pam_unix(sddm:session): session opened for user paul by (uid=0)
Aug 01 14:43:00 linux-eflx.site sddm-helper[2005]: Adding cookie to "/home/paul/.Xauthority"
Aug 01 14:43:00 linux-eflx.site sddm[1924]: Session started
Aug 01 14:43:00 linux-eflx.site sddm-helper[1934]: [PAM] Ended.
Aug 01 14:43:00 linux-eflx.site sddm[1924]: Auth: sddm-helper exited successfully
Aug 01 14:43:00 linux-eflx.site sddm[1924]: Greeter stopped.

**Comment by hgraeber** [comment]
I have to laptops affected by this bug. After backporting commit 7ed4ab1 to the openSUSE Tumbleweed sddm package the resulting sddm starts as expected.

**Comment by AdamKnube** [comment]
I can confirm this issue on 3 more machine setups it does not only affect laptops/hybrids but any combination of cards. First two machines are Intel/nvidia hybrid laptops similar to the above comments. However I can also add to this list an AMD (desktop) motherboard with built in (AMD) graphics that are disabled, but Nvidia PCI card being used as the default video output. This setup also hangs the SDDM on boot as described.

In my case however I do think the graphics similarites are just coincidence as I am finding in the logs [PAM] errors and sddm fails to authenticate. So in my case at least I doubt its graphical.

# journalctl -u sddm
Sep 18 15:29:19 thebomb sddm-helper[13196]: [PAM] Starting...
Sep 18 15:29:19 thebomb sddm-helper[13196]: [PAM] Authenticating...
Sep 18 15:29:19 thebomb sddm-helper[13196]: [PAM] Preparing to converse...
Sep 18 15:29:19 thebomb sddm-helper[13196]: [PAM] Conversation with 1 messages
Sep 18 15:29:19 thebomb sddm-helper[13196]: pam_unix(sddm:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rh
Sep 18 15:29:21 thebomb sddm-helper[13196]: [PAM] authenticate: Authentication failure
Sep 18 15:29:21 thebomb sddm-helper[13196]: [PAM] returning.
Sep 18 15:29:21 thebomb sddm[13171]: Authentication error: "Authentication failure"
Sep 18 15:29:21 thebomb sddm-helper[13196]: [PAM] Ended.
Sep 18 15:29:21 thebomb sddm[13171]: Auth: sddm-helper exited with 1

If after this I wait for a minute or so and then do:
# systemctl restart sddm
Then when I switch back to TTY1 I have my login screen. Seems to be a timing issue.
Running bleeding edge Arch Linux [core] not [testing].

**Comment by jleclanche** [comment]
Try in 0.13 please.

**Comment by pkonecny** [comment]
Tried 0.13 both on my desktop and my notebook. Seems to work, at least for me. 
Thanks for fixing!
