### ISSUE TITLE
groups and id command don't work properly when login with SDDM

### ISSUE THREAD

**Issue by Pulfer** [sddm/sddm#416]
"groups" and "id" command don't work properly when login with SDDM. They display only main user group (=username). But if I run "groups username" or "su username" (then "groups"), all groups are properly listed.

In case you need to check how SDDM is built, see:
https://abf.rosalinux.ru/import/sddm/tree/rosa2014.1

**Comment by tkleindienst** [comment]
The root of this problem is the same as with my issue #414 
It seems sddm can not deal with some pam modules, esp.  pam_group
After looking for hours through /etc/pam.d/ I finally gave up. I have not found a solution yet.

**Comment by tkleindienst** [comment]
Further remark: If you do "su username" pam does not utilize /etc/pam.d/sddm
Most likely /etc/pam.d/login will be used. That's why the group assignment works.

**Comment by jleclanche** [comment]
@plfiorini @davidedmundson thoughts?

**Comment by Pulfer** [comment]
Sorry, this bug is invalid. The issue was in kinit from KDE Frameworks 5, not in SDDM.

**Comment by hslabbert** [comment]
@Pulfer please elaborate how an issue in kinit, which relates to kerberos, results in logins through sddm failing to honor pam_group.so / /etc/security/group.conf on a system configured through sssd for ldap authentication with no kerberos being used, and what config if any would allow sddm to honour pam_group.so / /etc/security/group.conf in such a setup.

**Comment by Pulfer** [comment]
@hslabbert It was kinit from KDE Frameworks 5 ( https://quickgit.kde.org/?p=kinit.git ), not from kerberos. Setting start_kdeinit permissions to 4755 as defined in CMakeLists.txt ( https://quickgit.kde.org/?p=kinit.git&a=blob&h=46d6cb35454727e40f0d1fa066209045511b970e&hb=ae0e855c6b6b87d000988cc71e054f734109ec06&f=src%2Fstart_kdeinit%2FCMakeLists.txt#l21 ) leads to wrong group and id results.

**Comment by hslabbert** [comment]
@Pulfer appreciate the clarification; thanks. I was stuck in kinit = MIT "kerberos init" with this being related to auth.  Yay for namespace collisions...
Apologies for the noise.
