### ISSUE TITLE
security: SDDM resume from suspend, hibernate shows desktop

### ISSUE THREAD

**Issue by gaelsano** [sddm/sddm#417]
When I resume from hibernate or suspend, SDDM  (kframeworks 5.2, plasma 5.2, consolekit/eudev/open-rc on x86-32, manjaro) takes some time to start the screen locker. In the meantime my desktop is displayed for all to see. This does not happen with resume from screen blanking.

Sorry if this has already been posted or fixed in a future version. I searched the issue list for "resume" and couldn't find a similar bug

**Comment by plfiorini** [comment]
The screen locker is done by Plasma not SDDM.
