### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by jerome2** [sddm/sddm#421]
i update a theme and add video in the main.qml file. the compilation works with qtcreator, but on real use (after boot time, when display manager sddm open), only the logo i added is view, the video (white screen instead).
My OS is archlinux, i follow the instruction on the so minimalist documentation (sddm user and group on /var/lib/sddm, user sddm added to group video), and graphic chipset is intel weon (no problem of use).
Also, i have dual monitor and the same view is duplicate on the two monitors.
Thanks for tell the users who want to add videos what to do for show them if this is not a bug (and also, if this is not a bug, sorry for post it here... but on the doc there is no information about how to ask question or something more, i hope because of this lake and lot of time to search a solution without any success, you could understand).

**Comment by plfiorini** [comment]
Could you post to pastebin.com the theme qml file and any error related to sddm from the journal?

**Comment by plfiorini** [comment]
Closing because I haven't heard since Aug.
Please reopen when you can provide the QML file of your theme, we need it to better understand the issue.
