### ISSUE TITLE
Starting SDDM renders VTs/TTYs inaccessible

### ISSUE THREAD

**Issue by mueslo** [sddm/sddm#425]
If I start my system while having no display manager enabled or with KDM, I get all the usual ttys from 1-6. If I start SDDM (via systemctl), when I switch to them, the screen is black.

SDDM 0.11, Arch Linux

**Comment by plfiorini** [comment]
that seems normal, getty is not loaded by default on the graphical target.

**Comment by mueslo** [comment]
Mh, doesn't seem normal to me. And while getty is of course not running on VT1 where SDDM is,  it should still be active on the other ones, no?

```
● getty@tty1.service - Getty on tty1
   Loaded: loaded (/usr/lib/systemd/system/getty@.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mo 2015-06-15 01:05:08 CEST; 11h ago


● getty@tty2.service - Getty on tty2
   Loaded: loaded (/usr/lib/systemd/system/getty@.service; enabled; vendor preset: enabled)
   Active: active (running) since Mo 2015-06-15 01:04:42 CEST; 11h ago
```

When something runs amok and blocks X/KWin, I really would like to be able to still have access to a terminal, and it's also not normal in the sense that this is not how it's been previously and with other display managers.

**Comment by jleclanche** [comment]
I'm not getting that issue. on arch.

**Comment by plfiorini** [comment]
Got it once with the Hawaii images but can't reproduce it anymore, now I understand the issue better.
This was also reported to me by the OpenMandriva guys.
However since I cannot reproduce this every time I'm having a hard time to figure out what's going on.
It could be a systemd issue though.

**Comment by davispuh** [comment]
For me on Arch Linux all TTYs from 1 to 6 work fine and they're started by systemd's getty.target. When sddm is started then systemd will stop `getty@tty1.service` as per sddm.service `Conflicts=`. Then if sddm is stopped `getty@tty1.service` won't be started again, but you can start it manually with
```sh
systemctl start getty@tty1.service
```

**Comment by mueslo** [comment]
It seems this is an AMD catalyst issue on my end, so I'm closing the issue.
