### ISSUE TITLE
Wayland phase 3 (Greeter)

### ISSUE THREAD

**Issue by plfiorini** [sddm/sddm#440]
Phase 1: https://github.com/sddm/sddm/issues/419
Phase 2: https://github.com/sddm/sddm/issues/426
- [x] Greeter: KeyboardBackend moved to its separate .cpp/.h files
- [x] Greeter: Wayland keyboard backend
- [x] Non X11 greeter requires Qt >= 5.5
- [x] Greeter: Make sure combo boxes do not create new windows
- [x] Greeter: Use QPA for the first iteration and in the next iteration use Green Island
- [x] Xorg user session

**Comment by genodeftest** [comment]
As long as this issue is not closed, can you please clarify the short description of SDDM? It currently reads `QML based X11 and Wayland display manager`, but it should probably be more like `QML based display manager for X11 and Wayland sessions`

**Comment by plfiorini** [comment]
Wait for #616

**Comment by woutermont** [comment]
Can I just ask if there is any progress on a wayland-backed greeter?

**Comment by sandersr** [comment]
What's the ETA on this issue? It seems it's been open for a very long time and it's almost done.

**Comment by mispp** [comment]
There wasn't any activity recently here, is this still planned or?

**Comment by majkrzak** [comment]
It seems that #673 and #616 just have to be merged

**Comment by sandy-8925** [comment]
So, I looked into https://github.com/sddm/sddm/pull/616 - that work uses the GreenIsland compositor. However, the GreenIsland compositor seems to be deprecated and doesn't work with newer Qt versions in it's present form.

I propose using wlroots instead - @plfiorini  , @davidedmundson - do you guys think it's a good approach? I want to get sddm running on Wayland, so I'd like to take this up.

**Comment by majkrzak** [comment]
@plfiorini what's the current status? Are you alive?

**Comment by plfiorini** [comment]
Let's see if I can continue working on it during Xmas vacations.

**Comment by kanyck** [comment]
Was there any progress on that?

**Comment by ReK2Fernandez** [comment]
Whats the progress on this?

**Comment by raneon** [comment]
This issue seems abandoned. Will this be followed up eventually?

**Comment by majkrzak** [comment]
2 years ago it was matter of merging existing PR-s, AFAIK 😅

**Comment by major-mayer** [comment]
Great to see some progress here ❤️
This lines up with the increased Wayland effort in this year for the rest of the KDE ecosystem.

**Comment by Koli0842** [comment]
It indeed is so awesome to see some movement in this topic. I've been checking back on this topic for some years now.
Thank you so much everyone who contributed to this!

**Comment by shmerl** [comment]
Are there any plans to release a new version of sddm? It would be nice for distros to pick this feature of running sddm itself in Wayland mode.

**Comment by JJRcop** [comment]
> Are there any plans to release a new version of sddm?

There indeed appear to be plans! Take a look at the 0.20 milestone https://github.com/sddm/sddm/milestone/13
