### ISSUE TITLE
Problems with 1440p display

### ISSUE THREAD

**Issue by somniumAeternam** [sddm/sddm#443]
I have a problem with sddm and an 1440p display. The display is from Samsung (SyncMaster SA850). I attached a screenshot which shows the overlay I have. The top layer shows the sddm manager with the resolution 1080p. The error happens at startup and shutdown, as well as with a locked screen.

<img width="1280" alt="bildschirmfoto1" src="https://cloud.githubusercontent.com/assets/9334916/8763363/7d5ea66c-2d98-11e5-8c83-4500df93f8ef.png">

EDIT: I run sddm version 0.11.0-1 on Arch Linux.

**Comment by plfiorini** [comment]
What happens on the lock screen is Plasma's responsibility, what happens on the login screen instead is sddm's responsibility hence the bug should probably be reported to the Plasma developers too.

Do you by any chance have another screen?
Could you try master?

**Comment by somniumAeternam** [comment]
This is actually happening at the login screen and the lock screen, though on the lock screen it looks a bit different. It is working on an 1080p screen, but on the 1440p screen shows the bug

**Comment by plfiorini** [comment]
Please try with: https://github.com/sddm/sddm/pull/511

**Comment by plfiorini** [comment]
Should be fixed with #511, feel free to reopen if it doesn't.
