### ISSUE TITLE
SDDM starts a new session for an already logged in user

### ISSUE THREAD

**Issue by City-busz** [sddm/sddm#447]
Steps to reproduce:
1. SDDM starts at system startup. Log in as usual.
2. Switch user with `dm-tool switch-to-greeter`.
3. Try to log in with the same user.
The expected result is to get back the already opened session. Instead of that, a new user session is started for the same user causing various problems. In the same case, GDM, LightDM and LXDM switch back to the already opened session properly.

**Comment by jleclanche** [comment]
On top of this we need visual feedback somehow that the session is open.

**Comment by xiangzhai** [comment]
logout and login several times, then ```loginctl``` show as below:

```
loginctl 
   SESSION        UID USER             SEAT            
       c27        989 sddm             seat0           
         3       1000 zhaixiang        seat0           
         2       1000 zhaixiang        seat0           

3 sessions listed.
```

it is often N sessions listed depend on the relogin times.

**Comment by cyberesprit** [comment]
There is no continuation at this bug? This problem still exists today ...

**Comment by jleclanche** [comment]
PRs welcome if you wish to work on it.

**Comment by tpgxyz** [comment]
On daily use this is quite annoying, and each logout existing session is not shut down, which leads to have many processes that lives over not used sessions.

**Comment by plfiorini** [comment]
i don't have time to do it, @davidedmundson do you have time to help out?

**Comment by cyberesprit** [comment]
Sorry, but this problem still exists today :-(

**Comment by mxttie** [comment]
see PR #730

**Comment by Anagastes** [comment]
This issue still exist in version 0.19.0-4 on arch.

I have already set this config, unfortunately without success.
ReuseSession=true

As soon as I lock the pc, change the user and then log back into the 1st user, a new session is started instead of using the old one.

![image](https://user-images.githubusercontent.com/17494592/112611497-30927600-8e1e-11eb-964a-724a833861e8.png)

**Comment by mx1up** [comment]
when this feature finally came available in my distro, I also encountered some problems with it, but it has been a while.. I thought I did something wrong. I will try it out over the weekend

**Comment by LaserHydra** [comment]
I am using SDDM 0.19.0-7 on Artix, and I can confirm I am still experiencing the same issue, despite having ReuseSession=true

I'll gladly provide more information if I can, though I am not certain which other information may be useful in this case.

**Comment by UMU618** [comment]
Can't reproduce on Debian 11, sddm 0.19.0-3.

**Comment by enkeyz** [comment]
Same problem with latest Manjaro, sddm 0.19.0-8, `ReuseSession=true`

1. Switch user
2. Log back into the same account with SDDM
3. Black screen with cursor

**Comment by City-busz** [comment]
I confirm that the original issue that I reported was fixed (probably by https://github.com/sddm/sddm/pull/730 and https://github.com/sddm/sddm/pull/1216 ). I tested it with sddm 0.19.0. I still experience issues with wayland sessions (switching to wrong VT), but it's another issue.

**Comment by osirisgothra** [comment]
Is there a way to work around this, in case of emergencies? 
 0.20.0-2ubuntu4, xfce4 4.18/gtk 3.22.41(amd64) - Tried moving the vt and then terminating sddm, but all that did was orphan all the running X applications and start a new copy of xfce4.
