### ISSUE TITLE
sddm doesn't source $HOME/.profile

### ISSUE THREAD

**Issue by shmerl** [sddm/sddm#448]
I just switched to KDE Plasma 5 (Debian testing) which uses sddm instead of kdm. And it looks like $HOME/.profile isn't sourced anymore. I'm not sure if it's sddm or it's Plasma 5 problem. Is it supposed to be sourced or not?

**Comment by PlutoniumHeart** [comment]
Same problem, same environment.

**Comment by davidedmundson** [comment]
> Is it supposed to be sourced or not?

No it is not.

.xsessionrc is sourced though

**Comment by shmerl** [comment]
What's sourced in case of Wayland usage then? And why it shouldn't source .profile?

**Comment by davidedmundson** [comment]
turning that around, why should it?

**Comment by shmerl** [comment]
Because purpose of .profile is to apply to the whole session. I'm aware that some display managers include it, others don't and in general it's a major mess.

**Comment by jleclanche** [comment]
The display manager shouldn't source `.profile`, it's meant for the shell.

**Comment by shmerl** [comment]
Is it also supposed not to include /etc/profile?

**Comment by jleclanche** [comment]
No.

**Comment by shmerl** [comment]
OK, I'll a file some related Debian bugs. Is there some recommended place which **is** sourced by sddm? .xessionrc doesn't sound right at least for Wayland.

**Comment by jleclanche** [comment]
We should probably figure that out for wayland, but generally speaking sourcing things from your display manager is not recommended.

**Comment by davidedmundson** [comment]
For wayland onwards systemd user units will probably be the way to go.

**Comment by davidedmundson** [comment]
BTW, what's the bug with Debian that you need to file? Link it here when you do, and maybe we can help comment on how to fix it.

**Comment by shmerl** [comment]
Sure. The bug is related to some packages relying on /etc/profile being sourced. For instance, in Debian /etc/profile adds /usr/games to the PATH (as well as bunch of other stuff like /usr/local/bin and etc.). Some Debian packaged games like minetest, supertuxkart and others rely on /usr/games being in the PATH. That's just what I discovered, there can be more things that are affected.

I'll post the bug here once I'll file it.

**Comment by davidedmundson** [comment]
Thanks. 
In *Buntu path is sourced from /etc/environment.

There is a pam module pam_env which reads this and sets that for the session.

**Comment by shmerl** [comment]
I filed the bug here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794419

**Comment by shmerl** [comment]
sddm has [this Xession file](https://github.com/sddm/sddm/blob/master/data/scripts/Xsession) which includes profiles. Is it supposed to be used?
