### ISSUE TITLE
Release 0.12.0 doesn't exist as per release annoucement

### ISSUE THREAD

**Issue by sudhirkhanger** [sddm/sddm#451]
Release 0.12.0 doesn't exist as per release announcement [1].

[1] https://github.com/sddm/sddm/wiki/0.12.0-Release-Announcement

**Comment by jleclanche** [comment]
That's because it hasn't been released.

**Comment by sudhirkhanger** [comment]
Thanks. It would be great if the drafts of announcements say that it is a DRAFT.
