### ISSUE TITLE
root xauth cookies are not created as the default ~/.Xauthority

### ISSUE THREAD

**Issue by tuzonice** [sddm/sddm#452]
While the xauth cookies for users are perfectly valid, this seems not to be true for root. They are created as non-standard file names such as .xauthSyw1Eq which will confuse applications expecting it to be ~/.Xauthority.
The application, for which I reproduced that, was the emacs server started as root.

I link the corresponding gentoo bug report and the emacs mailing list thread.

Gentoo Bug:
https://bugs.gentoo.org/show_bug.cgi?id=555346
Emacs mailing list:
https://lists.gnu.org/archive/html/emacs-devel/2015-08/msg00372.html

**Comment by plfiorini** [comment]
Let's see if #541 fixes this

**Comment by tuzonice** [comment]
Reported the fix back to the Gentoo devs. Thank you very much for your time.
