### ISSUE TITLE
 SDDM ignores auto-login after logout

### ISSUE THREAD

**Issue by omega3** [sddm/sddm#470]
In Plasma 5 (on Kubuntu 15.10 wily) sddm auto-login only when system starts from boot. When I have two users and logout from one account and want to auto-login to another account (that has auto-login set in system setting) sddm can't do that. 

Please, make it work for Plasma 5. As a reference: in kdm this feature works. It is enough to click twice or press enter and auto-login works (even if system doesn't start but user was only logged out).

**Comment by jleclanche** [comment]
You need to set Autologin.Relogin to true if you want autologin to work after the first logout.

**Comment by omega3** [comment]
I don't understand your reply.

I use Kubuntu 15.10. The only option there is auto login and I have it checked. 
http://imgur.com/bkpa5lr

But this doesn't let me auto login after logout but only after system restart.

There is another option: Relogin after quit 
http://imgur.com/5JPDS7E
but this has no sense at all because it doesn't allow me chose another user but automatically autologin to the same user. 

When I have two users: one user account and administrative account I want to be able to logout from user account login to administrative account by typing password than logout from administrative account and auto-login to user account.

Can you be more specific with your explanation and give me steps what to do, please?

"Relogin to true" - what do you mean by "true"?

**Comment by jleclanche** [comment]
I was talking about `/etc/sddm.conf`, this is a gui for it. I don't understand what you're asking for in logging out of an account and auto-logging into another. Autologin doesn't skip authentication, it skips the greeter altogether. You'll have to delete the user's password if you want to log in without a password (although Im not sure we support that correctly right now)

**Comment by omega3** [comment]
"I don't understand what you're asking for in logging out of an account and auto-logging into another. "

By the above I mean exactly this:
When I have two users: one user account and administrative account I want to be able to logout from user account login to administrative account by typing password than logout from administrative account and auto-login to user account.

In KDM it is possible. 
When I log out of administrative account and want to log in to user account I don't need to type password. I just choose user and when mouse cursor is in password field it is enough to press enter and it auto-login me to user account (no need to type password).
