### ISSUE TITLE
PasswdBackend compilation errors

### ISSUE THREAD

**Issue by alienbob** [sddm/sddm#477]
Hi!

When compiling the latest sddm git snapshot on Slackware-current in order to check out the status of ConsoleKit2 support, I find that the compilation fails.
The PasswdBackend.cpp file generates the following errors:

[ 58%] Building CXX object src/greeter/CMakeFiles/sddm-greeter.dir/__/common/Soc
ketWriter.cpp.o
In file included from /usr/include/qt5/QtCore/qobject.h:41:0,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/h
elper/backend/../Backend.h:24,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/h
elper/backend/PasswdBackend.h:24,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/h
elper/backend/PasswdBackend.cpp:21:
/usr/include/qt5/QtCore/qstring.h: In member function 'virtual bool SDDM::PasswdBackend::authenticate()':
/usr/include/qt5/QtCore/qstring.h:771:5: error: 'QString::QString(const char*)' is private
     QString(const char *ch);
     ^
/tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/helper/backend/PasswdBackend.cpp:41:23: error: within this context
         if (m_user == "sddm") {
                       ^
In file included from /usr/include/qt5/QtCore/qobject.h:41:0,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/helper/backend/../Backend.h:24,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/helper/backend/PasswdBackend.h:24,
                 from /tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/helper/backend/PasswdBackend.cpp:21:
/usr/include/qt5/QtCore/qstring.h:771:5: error: 'QString::QString(const char*)' is private
     QString(const char *ch);
     ^
/tmp/kde-build/plasma-extra/sddm-d42700a_20150822git/src/helper/backend/PasswdBackend.cpp:52:71: error: within this context
             r.prompts << Prompt(AuthPrompt::LOGIN_USER, "Login", false);
                                                                       ^
.... and several more that are analogous. The full log can be found here: http://sprunge.us/NWPE

I am not a C++ programmer, I tried to understand the flow of the code but failed miserably. What I can do however, is test your changes to the code.
Can you please have a look at this? I realize that none of you are using the passwd backend but Slackware does, and will do so for a long time to come. I would like to co-operate in whatever way possible to get this fixed.

Thanks, Eric Hameleers

**Comment by xiangzhai** [comment]
Hi @alienbob 

Try my patch https://github.com/AOSC-Dev/sddm/commit/c6be72636f43a28f1b6aebff9d682d0182dd7a1e

sddm enabled ***-DQT_NO_CAST_FROM_ASCII*** so QString(const char *) is private!

Regards,
Leslie Zhai

**Comment by alienbob** [comment]
Hi @xiangzhai 

Your patch needed a small tweak because it was not based on the official master, but after applying it, I was able to compile sddm master snapshot without errors on Slackware. Thanks for the patch.
Tonight I shall see how sddm works in cooperation with ConsoleKit2.

Regards, Eric Hameleers

**Comment by xiangzhai** [comment]
Hi @alienbob 

Yes, it is [sddm forked](https://github.com/AOSC-Dev/sddm/) and try to implement:

- [ ] plymouth smooth transition https://github.com/AOSC-Dev/sddm/commit/79d86cfe3bf771c6017855e7487616e34c1f4ba8
- [ ] AccountsService faceIcon https://github.com/sddm/sddm/pull/439

Regards,
Leslie Zhai

**Comment by majewsky** [comment]
That's interesting. I just rebuilt the current master branch from scratch, and it builds without errors or warnings. Using Qt 5.5.0 on Arch Linux w/ all updates.

**Comment by majewsky** [comment]
Also, there is `QString::fromUtf8` in there. Is that correct, or should it be `QString::fromLocal8Bit`? (I can't really see where these bytearrays are coming from, so I'm just mentioning it here to make sure someone double-checks it.)

**Comment by plfiorini** [comment]
@majewsky passwd backend is not built when pam is found. this is also the reason why CI didn't notice the error.
