### ISSUE TITLE
pam backend loginFailed

### ISSUE THREAD

**Issue by xiangzhai** [sddm/sddm#478]
Hi sddm developers,

I git fetch upstream today, recompile it, daemon-reload, then loginFailed! it was able to work in Aug 12th, and I noticed that there are a lot of commits recently, waiting for code reviewing ;-)

I just disable pam, instead to use (shadow && crypt) PasswordBackend https://github.com/AOSC-Dev/sddm/commit/c6be72636f43a28f1b6aebff9d682d0182dd7a1e

Please someone double check the pam backend, or give me some advice, why it failed to work in my box, thanks a lot!

Regards,
Leslie Zhai

**Comment by xiangzhai** [comment]
sometimes we need a customized pam file:

```
auth        substack      password-auth
-auth        optional      pam_kwallet.so
auth        include       postlogin

account     required      pam_nologin.so
account     include       password-auth

password    include       password-auth

session     required      pam_loginuid.so
session     optional      pam_console.so
session     optional      pam_systemd.so
-session    optional    pam_ck_connector.so
session     optional      pam_keyinit.so force revoke
session     required      pam_namespace.so
session     include       password-auth
-session     optional      pam_kwallet.so
session     include       postlogin
```

**Comment by plfiorini** [comment]
Out of curiosity: which distro are you running?
Every distro implements PAM its way hence every distro need a different PAM config.

**Comment by xiangzhai** [comment]
LFS ;-)
