### ISSUE TITLE
add ability to use SDDM as locker

### ISSUE THREAD

**Issue by vkravets** [sddm/sddm#48]
A lot of DM is not supporting the same UI as lock screen. Will be greate if SDDM will have such mechanizm.

E.g. run sddm --lock and it use the same theme but show locker screen.

Any ideas how it can be implemented?

Thanks,
Vladimir

**Comment by plfiorini** [comment]
The lock screen as a separate process has security concerns (it would be very easy to kill it) and certainly require some cooperation between the lock screen and the desktop.
It also requires more changes to make the greeter appear again when summoned or never close the greeter process.  I'm against on making SDDM a lock screen and nobody actually wrote code in so much time, so I will just close the issue.

**Comment by ArijanJ** [comment]
10-year necro! I found https://github.com/mstoeckl/swaylock-plugin, which lets you run any background-generating program as your lockscreen. Combining this with `windowtolayer` lets you use SDDM's --test-mode in a sort of rube goldberg machine to let you have your beautiful SDDM theme as your lock screen (but only visually, the login is handled by swaylock). Hope this helps someone in the future.
