### ISSUE TITLE
remember last session per user

### ISSUE THREAD

**Issue by robin92** [sddm/sddm#481]
As a user I would like to have my last session remembered on per user basis. Consider the following usecase:
1. **Alice** logins with _Gnome_ desktop and after a while logs out.
2. **Bob** logins with _Plasma_ desktop and after a while powers off.
3. **Alice** logins but doesn't need to change session to _Gnome_ since it has been remembered. After a while log out.
4. **Bob** logins but doesn't need to change session to _Plasma_ since it has been remembered.

**Comment by jleclanche** [comment]
Closing in favour of #510
