### ISSUE TITLE
Add an option for changing the keyboard layout

### ISSUE THREAD

**Issue by Tratoschek** [sddm/sddm#482]
It would be nice, if sddm provides an ability to change the keyboard layout at startup.

Usecase: Consider a multiuser system, where some user prefer normal qwerty and another something like dvorak. Then the user(s), whose keyboard layout is not the default in sddm, has to learn to type his password in two layouts.

**Comment by MayeulC** [comment]
Well, since it has been posted here, I cross-reference this bug report : 
https://bugs.kde.org/show_bug.cgi?id=343427
That's really something that's bugging me everyday, even though I learned how to type ma password with a different keyboard layout :)

**Comment by mruessler** [comment]
Is this a KDE issue, then? Can it be closed here?

**Comment by jleclanche** [comment]
We should get that in the basic theme, too, so this can stay open.

**Comment by jleclanche** [comment]
We have a layout selector in the default theme actually, so this can be closed now.
