### ISSUE TITLE
SDDM is freezing when trying to login with user without a home directory

### ISSUE THREAD

**Issue by Wenzel** [sddm/sddm#487]
Steps to reproduce:
1. create a new user "foobar"
2. remove "/home/foobar"
3. try to login "foobar" with SDDM
4. SDDM is frozen.

Also, trying to restart the service with `systemctl restart sddm` in another tty ends with no display on the screen.

**Comment by plfiorini** [comment]
Do you see something from journalctl -b ?

**Comment by Wenzel** [comment]
these are some messages that i found:
~~~
sept. 08 07:35:31 localhost.localdomain sddm-helper[7031]: Couldn't create directory: /home/foobar because: 13-Permission denied
sept. 08 07:35:31 localhost.localdomain audit[7031]: <audit-1400> avc:  denied  { write } for  pid=7031 comm="sddm-helper" name="/" dev="dm-1" ino=2 scontext=system_u:sys
sept. 08 07:35:31 localhost.localdomain sddm-helper[7031]: Couldn't open file: /home/foobar/.kde/share/apps/kwallet/kdewallet.salt because: 2-No such file or directory
sept. 08 07:35:31 localhost.localdomain sddm-helper[7031]: kwalletd: Couldn't create or read the salt file
sept. 08 07:35:31 localhost.localdomain sddm-helper[7031]: pam_kwallet(sddm:auth): pam_kwallet: Fail into creating the hash
~~~

**Comment by plfiorini** [comment]
This is the kwallet PAM plugin that needs to create a file but it can't do that because the home directory was removed.  Doesn't look like a bug, rather a misconfigured system.

**Comment by Wenzel** [comment]
although there are some lines related to kwalletd, this line
~~~
sddm-helper[7031]: Couldn't create directory: /home/foobar because: 13-Permission denied
~~~
is related to SDDM.
Also, even if the system is misconfigured, SDDM should allow the user to login again, and not froze the display.
