### ISSUE TITLE
Breeze theme items not shown on login screen

### ISSUE THREAD

**Issue by jam3z** [sddm/sddm#491]
I am trying to use Breeze theme from KF5.  I have installed X into /usr/X11, KF5 into /opt/kf5 and QT5 into /opt/qt5.  When I am starting SDDM using Breeze theme, I receive an error.  It does not seem to find QML files into /opt/kf5, I copied them into QT folder.  Now I am receiving these messages : 

sep 11 23:12:48 lfs-7-5 sddm-greeter[333]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
sep 11 23:12:48 lfs-7-5 sddm-greeter[333]: QObject: Cannot create children for a parent that is in a different thread.
                                           (Parent is SDDM::GreeterApp(0x7fff04dc3f40), parent's thread is QThread(0x25e9e60), current thread is QThread(0x2625670)
sep 11 23:12:46 lfs-7-5 sddm-greeter[333]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
sep 11 23:12:46 lfs-7-5 sddm-greeter[333]: QObject: Cannot create children for a parent that is in a different thread.
                                           (Parent is SDDM::GreeterApp(0x7fff04dc3f40), parent's thread is QThread(0x25e9e60), current thread is QThread(0x2625670)
sep 11 23:12:46 lfs-7-5 sddm-greeter[333]: QObject: Cannot create children for a parent that is in a different thread.
                                           (Parent is SDDM::GreeterApp(0x7fff04dc3f40), parent's thread is QThread(0x25e9e60), current thread is QThread(0x2625670)
sep 11 23:12:46 lfs-7-5 sddm-greeter[333]: QObject: Cannot create children for a parent that is in a different thread.
                                           (Parent is SDDM::GreeterApp(0x7fff04dc3f40), parent's thread is QThread(0x25e9e60), current thread is QThread(0x2625670)

How can I get Breeze theme to show up correctly ?

**Comment by jam3z** [comment]
I found where this comes from :

GreeterApp.cpp :

    GreeterApp::GreeterApp(int &argc, char **argv) : QGuiApplication(argc, argv) {
        // point instance to this
        self = this;

        // Parse arguments
        bool testing = false;

        if (arguments().contains("--test-mode"))
            testing = true;

        // get socket name
        QString socket = parameter(arguments(), "--socket", "");

        // get theme path
        QString themePath = parameter(arguments(), "--theme", "");

        // create view
        m_view = new QQuickView();
        m_view->setResizeMode(QQuickView::SizeRootObjectToView);

        m_view->engine()->addImportPath(IMPORTS_INSTALL_DIR);

        // read theme metadata
        m_metadata = new ThemeMetadata(QString("%1/metadata.desktop").arg(themePath));

        // Translations
        // Components translation
        m_components_tranlator = new QTranslator();
        if (m_components_tranlator->load(QLocale::system(), "", "", COMPONENTS_TRANSLATION_DIR))
            installTranslator(m_components_tranlator);

        // Theme specific translation
        m_theme_translator = new QTranslator();
        if (m_theme_translator->load(QLocale::system(), "", "",
                           QString("%1/%2/").arg(themePath, m_metadata->translationsDirectory())))
            installTranslator(m_theme_translator);

        // get theme config file
        QString configFile = QString("%1/%2").arg(themePath).arg(m_metadata->configFile());

        // read theme config
        m_themeConfig = new ThemeConfig(configFile);

        // set default icon theme from greeter theme
        if (m_themeConfig->contains("iconTheme"))
            QIcon::setThemeName(m_themeConfig->value("iconTheme").toString());

        // set cursor theme according to greeter theme
        if (m_themeConfig->contains("cursorTheme"))
            qputenv("XCURSOR_THEME", m_themeConfig->value("cursorTheme").toString().toUtf8());

        // create models

        m_sessionModel = new SessionModel();
        m_screenModel = new ScreenModel();
        m_userModel = new UserModel();
        m_proxy = new GreeterProxy(socket);
        m_keyboard = new KeyboardModel();

        if(!testing && !m_proxy->isConnected()) {
            qCritical() << "Cannot connect to the daemon - is it running?";
            exit(EXIT_FAILURE);
        }

        // Set numlock upon start
        if (m_keyboard->enabled()) {
            if (mainConfig.Numlock.get() == MainConfig::NUM_SET_ON)
                m_keyboard->setNumLockState(true);
            else if (mainConfig.Numlock.get() == MainConfig::NUM_SET_OFF)
                m_keyboard->setNumLockState(false);
        }

        m_proxy->setSessionModel(m_sessionModel);

        // connect proxy signals
        QObject::connect(m_proxy, SIGNAL(loginSucceeded()), m_view, SLOT(close()));

        // set context properties
        m_view->rootContext()->setContextProperty("sessionModel", m_sessionModel);
        m_view->rootContext()->setContextProperty("screenModel", m_screenModel);
        m_view->rootContext()->setContextProperty("userModel", m_userModel);
        m_view->rootContext()->setContextProperty("config", *m_themeConfig);
        m_view->rootContext()->setContextProperty("sddm", m_proxy);
        m_view->rootContext()->setContextProperty("keyboard", m_keyboard);

        // get theme main script
        QString mainScript = QString("%1/%2").arg(themePath).arg(m_metadata->mainScript());

        // set main script as source
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////
        // The messages appear after this line is called
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////
        m_view->setSource(QUrl::fromLocalFile(mainScript));

        // connect screen update signals
        connect(m_screenModel, SIGNAL(primaryChanged()), this, SLOT(show()));

        show();
    }

**Comment by ace13** [comment]
My solution for running Breeze with KF5 in /opt/kf5;
```
$ ls -l /usr/share/sddm/themes/breeze
lrwxrwxrwx 1 root root 34 Jun 17 23:13 /usr/share/sddm/themes/breeze -> /opt/kf5/share/sddm/themes/breeze/

$ cat /usr/lib/systemd/system/sddm.service
[Unit]
Description=Simple Desktop Display Manager
Documentation=man:sddm(1) man:sddm.conf(5)
Conflicts=getty@tty1.service
After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service

[Service]
ExecStart=/usr/bin/sddm-kf5
Restart=always
#PrivateTmp=yes

[Install]
Alias=display-manager.service

$ cat /usr/bin/sddm-kf5
#!/bin/sh

export KF5=/opt/kf5
export PATH=$KF5/bin:$PATH
export QT_PLUGIN_PATH=$KF5/lib/plugins:$KF5/lib64/plugins:$QT_PLUGIN_PATH
export QT_SELECT=5
export QML2_IMPORT_PATH=$KF5/lib/qml:$KF5/lib64/qml:$QML2_IMPORT_PATH
export QML_IMPORT_PATH=$QML2_IMPORT_PATH
export XDG_DATA_DIRS=$KF5/share:/usr/share
export XDG_CONFIG_DIRS=$KF5/etc/xdg:/etc/xdg
export LD_LIBRARY_PATH=$LF_LIBRARY_PATH:$KF5/lib:$KF5/lib64

sddm $@
```

**Comment by plfiorini** [comment]
Closing because it's not really an issue, if you build the whole Qt and KF5 stacks on your own you need to set the paths properly like @ace13 suggested.
