### ISSUE TITLE
failsafe session fails

### ISSUE THREAD

**Issue by xiangzhai** [sddm/sddm#515]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800158

Let`s review the source code

* add failsafe session https://github.com/sddm/sddm/blob/master/src/greeter/SessionModel.cpp#L133
* but failsafe session is invalid! https://github.com/sddm/sddm/blob/master/src/daemon/Display.cpp#L244
* there is ***NO*** failsafe.desktop https://github.com/sddm/sddm/blob/master/src/common/Session.cpp#L128

Regards,
Leslie Zhai

**Comment by plfiorini** [comment]
To be honest I'm in favor of killing the failsafe session (fake) entry.
Users can replace that with a .desktop entry that executes xterm an twm.

What do you think @jleclanche and @davidedmundson ?

**Comment by xiangzhai** [comment]
totally agree!!!

**Comment by jleclanche** [comment]
Yeah I'm ok with that. I think I mentioned it on IRC too, failsafe can in fact fail if you don't have xterm installed (which you won't if you're on arch and it wasn't pulled in by some other app).
