### ISSUE TITLE
SDDM Breeze Theme needs color scheme customization

### ISSUE THREAD

**Issue by danikvsn** [sddm/sddm#516]
The Breeze theme in SDDM needs a similar system of color scheme customization that exists in Plasma 5 for windows

**Comment by plfiorini** [comment]
SDDM doesn't ship with the Breeze theme which is part of KDE Plasma.
Please ask the KDE guys.

**Comment by jleclanche** [comment]
@plfiorini @davidedmundson should we consider tracking breeze issues here?
