### ISSUE TITLE
sddm crashes on booting, but runs OK right after boot from console prompt

### ISSUE THREAD

**Issue by JohnA3** [sddm/sddm#518]
I'm running a Opensuse 13.2 + KDE desktop.   It's been working OK.

After package upgrades the other day, when I reboot, it doesn't boot to KDE anymore.  I get a message about a segfault in sddm.

But it does drop to console prompt.  If I just log in, and launch 'sddm', then KDE boots with no problems.

I have these versions

    rpm -qa |egrep -i "libQt5Core|sdd" | sort
        kcm_sddm-5.4.90git~20150912T152736~4fa05b9-2.1.x86_64
        libQt5Core5-5.5.1-120.1.x86_64
        libQt5Core-devel-5.5.1-120.1.x86_64
        libQt5Core-private-headers-devel-5.5.1-120.1.noarch
        sddm-0.99-1.1.x86_64
        sddm-branding-openSUSE-0.99-1.1.x86_64

    rpm -q --changelog sddm | head -n 10
        * Sat Oct 24 2015 tchvatal@suse.com
        - Add upstream patches to fix multihead in some cases
          (also fixes boo#950293):
          * 0001-always-create-window-for-each-screen.patch
          * 0002-screen-model-for-each-window.patch

        * Sun Oct 18 2015 hrvoje.senjan@gmail.com
        - openSUSE branding now needs to require plasma5-workspace-branding

        * Thu Oct 15 2015 hrvoje.senjan@gmail.com

And after boot, running sddm, and getting to the KDE desktop, I can see

    journactl -b
        ...
        Oct 25 08:23:12 solomon systemd[1]: Started User Manager for UID 0.
        Oct 25 08:23:12 solomon dbus[1946]: [system] Activating via systemd: service name='org.freedesktop.ColorManager' unit='colord.service'
        Oct 25 08:23:12 solomon logger[2258]: /etc/init.d/xdm: No changes for /etc/X11/xdm/Xservers
        Oct 25 08:23:12 solomon logger[2258]: /etc/init.d/xdm:
        Oct 25 08:23:12 solomon logger[2258]: /etc/init.d/xdm: ATTENTION: You have modified /etc/X11/xdm/xdm-config.  Leaving it untouched...
        Oct 25 08:23:12 solomon logger[2258]: /etc/init.d/xdm: You can find my version in /etc/X11/xdm/xdm-config.SuSEconfig...
        Oct 25 08:23:12 solomon logger[2258]: /etc/init.d/xdm:
        Oct 25 08:23:13 solomon startproc[2574]: startproc:  signal catched /usr/bin/sddm: Segmentation fault
        Oct 25 08:23:13 solomon kernel: sddm[2575]: segfault at 2ee4078 ip 00007fad01eabc8d sp 00007ffe2fddc4a0 error 4 in libQt5Core.so.5.5.1[7fad01d63000+4cc000]
        Oct 25 08:23:13 solomon display-manager[2220]: Starting service sddm..failed
        Oct 25 08:23:13 solomon systemd[1]: Failed to start X Display Manager.
        Oct 25 08:23:13 solomon systemd[1]: Unit display-manager.service entered failed state.
        ...
        Oct 25 08:24:21 solomon.localhost display-manager[3360]: /etc/vconsole.conf available
        Oct 25 08:24:21 solomon.localhost display-manager[3360]: KEYMAP: us
        Oct 25 08:24:21 solomon.localhost display-manager[3360]: Command: localectl set-keymap us
        Oct 25 08:24:21 solomon.localhost display-manager[3360]: I: Using systemd /usr/share/systemd/kbd-model-map mapping
        Oct 25 08:24:21 solomon.localhost dbus[1946]: [system] Activating via systemd: service name='org.freedesktop.locale1' unit='dbus-org.freedesktop.locale1.service'
        Oct 25 08:24:21 solomon.localhost dbus[1946]: [system] Successfully activated service 'org.freedesktop.locale1'
        Oct 25 08:24:22 solomon.localhost logger[3381]: /etc/init.d/xdm: No changes for /etc/X11/xdm/Xservers
        Oct 25 08:24:22 solomon.localhost logger[3381]: /etc/init.d/xdm:
        Oct 25 08:24:22 solomon.localhost logger[3381]: /etc/init.d/xdm: ATTENTION: You have modified /etc/X11/xdm/xdm-config.  Leaving it untouched...
        Oct 25 08:24:22 solomon.localhost logger[3381]: /etc/init.d/xdm: You can find my version in /etc/X11/xdm/xdm-config.SuSEconfig...
        Oct 25 08:24:22 solomon.localhost logger[3381]: /etc/init.d/xdm:
        Oct 25 08:24:22 solomon.localhost kernel: sddm[3416]: segfault at 2cc6078 ip 00007f70913f7c8d sp 00007ffd7a2eaa20 error 4 in libQt5Core.so.5.5.1[7f70912af000+4cc000]
        Oct 25 08:24:22 solomon.localhost startproc[3415]: startproc:  signal catched /usr/bin/sddm: Segmentation fault
        Oct 25 08:24:22 solomon.localhost display-manager[3360]: Starting service sddm..failed
        Oct 25 08:24:22 solomon.localhost systemd[1]: Failed to start X Display Manager.
        Oct 25 08:24:22 solomon.localhost systemd[1]: Unit display-manager.service entered failed state.
        Oct 25 08:25:28 solomon.localhost acpid[1913]: client connected from 3737[0:0]
        Oct 25 08:25:28 solomon.localhost acpid[1913]: 1 client rule loaded
        Oct 25 08:25:29 solomon.localhost sddm-helper[3757]: [PAM] Authenticating...
        Oct 25 08:25:29 solomon.localhost sddm-helper[3757]: Starting: "/etc/X11/xdm/Xsession" "/usr/bin/startkde"
        Oct 25 08:25:29 solomon.localhost sddm-helper[3759]: Adding cookie to "/home/johna/.Xauthority"
        ...

**Comment by purpleankh** [comment]
This is possibly a bug in KDE.
In Debian the latest update to libqt5x11extras5 (library to access X11 stuff from within Qt 5) seems to have killed KDE - it affects all Display Managers (sddm/lightdm/kdm for me anyway)
The Debian bug report is https://bugs.debian.org/802811

**Comment by jleclanche** [comment]
Closing per last comment.
