### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by koesherbacon** [sddm/sddm#519]
Hi.  I just got SDDM set up and themed, and it's completely beautiful!  I **love** it!

I have two questions for you, which are probably not that complicated but I'm new to Linux in general and am always more and more about it.

**Question the First:** How do I take a screenshot of the SDDM login screen to include when I package the theme and put it on DeviantArt, Gnome-Look, etc?  I have already read that I should be able to [Alt]++[fn]+[Shift]+[F2] to bring up a terminal, but that doesn't seem to work.  I probably disabled this optoin somewhere and do not know how to turn it on again.  If there's an easier way to take a screenshot of the login screen, I'd love to hear it!

**Question the Second:** Whenever I log out, my password area has 2 ●

 bubbles already typed in for some reason.  I have tried typing the rest of my password in, but that didn't work, so these two mystery characters are not actually the first two characters of the password.  Now this isn't a huge deal, I don't really mind pressing backspace twice and then typing it in, it's just a weird little artifact I've noticed.

I'm linking you to an archive with the theme I created as well as my current sddm.conf file for you to take a look at and see if you can figure out this weird password thing.  I tried attaching it, but I guess GitHub doesn't want people adding anything other than images and office-type files.  Oh well, here's the link, let me know if you have any trouble with it:
[Dragon SDDM Theme](http://bit.ly/1Gw6KhN)

Thank you very much!

~ Ev

**Comment by jleclanche** [comment]
If you want to screenshot sddm it's simpler to run it with `sddm-greeter --test` (https://github.com/sddm/sddm/blob/master/docs/THEMING.md) or under Xephyr.

I don't know about that other issue. How do you log out? @plfiorini any idea?
