### ISSUE TITLE
Export general environment variables earlier

### ISSUE THREAD

**Issue by choreutes** [sddm/sddm#53]
While trying to set some additional environment variables via my ~/.pam_environment, I noticed that other variables like ${HOME} are not available when this file is read during session initialization. I then took a look into the pam_env.conf man page and I found this:

"For example, HOME is used below several times, but many PAM applications don't make it available by the time you need it."

I don't have any experience in writing display managers but it seems that in the source code (/src/daemon/Authenticator.cpp, lines 300 to 330) the two actions in question could easily be exchanged. Are there any reasons for this specific order?

**Comment by Ilya87** [comment]
I still has this issue. Maybe I don't understand someting and I should manually set this variable in ~/.profile file?
My OS is Arch Linux x86_64, build from latest git commit.

systemd[545]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
