### ISSUE TITLE
Is There a Way Refresh Available Desktop Environments

### ISSUE THREAD

**Issue by koesherbacon** [sddm/sddm#538]
Is there a way to update the available Desktop Environments?  For instance, I installed LxQT and didn't end up liking it so I removed from my Arch distro, but it and other DEs I have removed still being shown in the dropdown box.  I'm sure there must be a command to refresh this, but I can't seem to find it anywhere.

Thanks!

**Comment by jleclanche** [comment]
lxqt.desktop is provided by lxqt-common which I'm guessing you didn't remove.

**Comment by plfiorini** [comment]
Anyways we currently don't rescan the sessions list when the file system changes.

**Comment by jleclanche** [comment]
@plfiorini So this is kinda theoretical but if a DE is uninstalled while the greeter is open, we could propose a non-existant session?

Or is it more serious than that? (= having to restart sddm altogether if you were logged on)

**Comment by plfiorini** [comment]
@jleclanche If a DE is uninstalled while the greeter is running we would propose a session entry that will fail.

We could use a file system watcher and monitor for changes.

**Comment by jleclanche** [comment]
How about refreshing the list every time someone reaches the greeter?

**Comment by plfiorini** [comment]
That would be even easier to do.
