### ISSUE TITLE
sddm.conf: preexisting /etc/sddm.conf incorporated at build time

### ISSUE THREAD

**Issue by pmattern** [sddm/sddm#540]
If SDDM gets built on a system where `/etc/sddm.conf` preexists the latter gets incorporated in the `sddm.conf` that's generated at build time.
Seen on Arch Linux x86_64 or i686.
On i686 the preexisting file didn't get incorporated as-is, rather a line `HideUsers=fritz,lieschen` was turned into `HideUsers=fritz,lies!\200`. No clue whether this is due to the architecture or something else, but basically the system was set up exactly the same as the x86_64 one where this replacement could not be seen.

**Comment by jleclanche** [comment]
Ah shit, @plfiorini `--example-config` does not generate a clean default-only config.

**Comment by MartinBriza** [comment]
Hmm, I thought the description in the PR would close this issue. It should be fixed now.
