### ISSUE TITLE
Avoid white screen when the theme fails to load

### ISSUE THREAD

**Issue by plfiorini** [sddm/sddm#551]
A theme can have errors preventing SDDM from loading it.
This result in a white screen making the login screen totally unusable.
The same happens if sddm.conf has a theme that cannot be found.

We can either move the "maui" theme to the resources and always load it in case of failure or provide an internal QML file that shows a red screen with an error message.

Not sure which one is better.

**Comment by valeriodean** [comment]
In my opinion, to have a backup strategy is really a very good idea, in this way no matter how broken is the theme or the path to the theme, the user can still log in his/her pc (it is crucial for a beginner linux user).
That begin said, a complete red screen with on error message on top can be a bit too much aggressive, at leas the user already notice that his/her favourite theme is no more loaded by SDDM, no?
So I guess that a maui theme with a gentle error message on top of the background should be suffice. :-)

**Comment by jleclanche** [comment]
Worst case scenario sddm should exit so the user can log in from the command line.

But yeah a theme in the base resources would be good. The maui theme is fine for that.
