### ISSUE TITLE
keyboard and mouse not working in sddm login prompt

### ISSUE THREAD

**Issue by aremai** [sddm/sddm#555]
Hi,

I'm facing the problem that since my latest update of sddm, I can't login anymore.
This means neither my keyboard nor mouse are recognized so that I could enter my credentials. The sddm greeter loads just fine, but apart from that I can't do anything with it.
However I can enter the ttys with CTRL+ALT+F2
so I do know that it's no hardware problem with my keyboard/mouse.

I'm using a Intel HD 4000 graphics cards and using Arch Linux
at the moment I can only use "startx" through the ttys, therefore it's a bit hard to paste any logs here. I'm happy to pastebin any logs if it helps with the troubleshooting.

If I start my desktop environment within an existing/running session, through startkde
I'm only see this colourful wallpaper/breeze theme. No taskbar, no mouse cursor, nothing :(

**Comment by aremai** [comment]
currently using the latest version of SDDM 0.13.0-1

**Comment by plfiorini** [comment]
could be the Xorg input driver missing, do you have that installed?

**Comment by aremai** [comment]
unlikely, because everything is working fine with LightDM.
when I run "startx" in X11-mode, keyboard and mouse are working in xterm...
however I will close this now, as I've switched to LightDM now.

**Comment by sergiocallegari** [comment]
Same here, on a machine with nvidia graphics and noveau.
