### ISSUE TITLE
sddm can't lanuch after update KaOS

### ISSUE THREAD

**Issue by open-src** [sddm/sddm#558]
Today, I updated my KaOS using pacman -Syu, but it always frezzes when running sddm. I tried to remove ~/.config, and "systemctl restart sddm", but it doesn't work. Here is the error:
*** Error in `sddm': corrupted double-linked list:0x0000000002530f30 ***

**Comment by plfiorini** [comment]
Could you post a backtrace taken from coredumpctl.
It won't be 100% helpful without debug symbols but it might still point to a direction.

**Comment by ellisistfroh** [comment]
Suggesting to close that issue, as no not replied within a reasonable gap of time.

**Comment by plfiorini** [comment]
Closing for no response. Please reopen if you still have problems.
