### ISSUE TITLE
Lists in sddm.conf not read correctly

### ISSUE THREAD

**Issue by pierrewillenbrock** [sddm/sddm#560]
Any list entry in sddm.conf with more than one element gets misread on my system. This may be compiler dependent, but it does not depend on optimization setting(i.E. happens without). The compiler is the gentoo flavour of gcc-4.9.3.

The visible effect is that only the first entry of HideUsers gets filtered out. Internally, the `QStringList` holding the entries has the correct number of entries, correct lengths of entries but incorrect contents, except for the first.

The function responsible for parsing lists in the config file is `QTextStream &operator>>(QTextStream &str, QStringList &list)`:

```
QTextStream &operator>>(QTextStream &str, QStringList &list)  {
    list.clear();
    foreach(const QStringRef &s, str.readLine().splitRef(QLatin1Char(',')))
    {
        QStringRef trimmed = s.trimmed();
        if (!trimmed.isEmpty())
            list.append(trimmed.toString());
    }
    return str;
}
```

The compiler creates a temporary `QString` object for the result of `str.readLine()` that gets referenced by pointer in the `QVector<QStringRef>` result of `splitRef()`. This object gets destructed once the expression is finished evaluating. Later, the compiler needs another temporary `QString` object for the result of `trimmed.toString()` and reuses the storage of the temporary `Qstring` used earlier for `str.readLine()`, changing the string referenced by all the `QStringRef` objects.

My solution was to explicitly create a `QString` object holding the result of `str.readLine()` which stays alive for the whole lifetime of the `QStringRef` objects.

**Comment by plfiorini** [comment]
This should be fixed now.
