### ISSUE TITLE
sddm does not properly read locale

### ISSUE THREAD

**Issue by jayeshbadwaik** [sddm/sddm#561]
I am using Archlinux packages and this happens only with the breeze theme, not with maui theme. So I am not sure exactly where is the bug.  I have provided the description of what happens below:
1. Copy /usr/share/i18n/locales/en_GB to /usr/share/i18n/locales/en_IN, so that both locales should match perfectly
2. Set LANG=en_IN.UTF-8 in /etc/locale.conf
3. Restart SDDM/computer. 
4. SDDM shows 12 hour AM/PM clock time
5. set LANG=en_GB.UTF-8 in /etc/locale.conf
6. Restart SDDM/computer.
7. SDDM shows 24 hour clock time.

SDDM should read the locales, same locale should produce same results irrespective of the name.

**Comment by plfiorini** [comment]
Which theme are you using?
The standard clock component doesn't even use locale for the time format.

**Comment by jayeshbadwaik** [comment]
I use the Breeze KDE theme, and I am sorry if I am mistaken, but I thought 
that providing the locale depends on sddm. Maui works correctly. May be a 
problem with the Breeze theme as I said in the bug report. I have also opened 
a [similar bug](https://bugs.kde.org/show_bug.cgi?id=355703) with KDE, so lets see.

**Comment by plfiorini** [comment]
Breeze uses its components and it's not part of SDDM.

**Comment by deepentim** [comment]
I did not see l`ocale.conf `file at /etc/ in Mint 18 KDE

**Comment by deepentim** [comment]
I did not see a file /etc/locale.conf in Mint 18 KDE
