### ISSUE TITLE
0.13 breaks multi-monitor theme

### ISSUE THREAD

**Issue by github-cygwin** [sddm/sddm#565]
Hi,

On system with two screens, layout like this (view using fixed size font):

          +----------+
    +-----+          |
    |     |          |    screen 1, HDMI1, 1600x1200
    |  1  |     2    |
    |     |          |    screen 2,   DP1, 2560x1440
    +-----+          |
          +----------+

Using my own sddm theme with different background pictures on screeen 1
and 2 and the login dialog offered on screen 1.  To make sure both
screens are handled correctly, /etc/sddm.conf contains this:

  [XDisplay]
  DisplayCommand=/usr/share/sddm/scripts/Xsetup.CV

The file /usr/share/sddm/scripts/Xsetup.CV is executable and contains
this:

  #!/bin/sh
  xrandr --output HDMI2 --auto --pos 0x100 --primary \
         --output DP1 --auto --pos 1600x0

This worked fine for some time now.  After an upgrade of my distro from
sddm 0.10 to 0.12 the theme was broken.  I reported the bug which
resulted in a distro upgrade to 0.13.  This update fixed the 0.12
problem, but it still breaks my theme:

With 0.13, screen 2 is just a mirror image of screen 1, thus the login
dialog and the background image for screen 1 show up on both screens.

It is as if the aforementioned DisplayCommand= line is simply ignored.

The distro maintainer asked me to report the bug upstream, so here I am :}

If you need any more info, feel free to ask.  It's rather awkward having
to stick to 0.10.

Thanks in advance,
Corinna

**Comment by github-cygwin** [comment]
Btw., if required for testing, my theme is available as attachment to my original
bug report: https://bugzilla.redhat.com/attachment.cgi?id=1094061
Tar files are not supported for upload by github, unfortunately.

Thanks,
Corinna

**Comment by plfiorini** [comment]
With SDDM 0.13 there is a new "primaryScreen" boolean variable that you can use to determine whether the screen where the main QML file is loaded is primary or not.

Use it to show the password prompt only on the primary screen like this:

https://github.com/sddm/sddm/blob/master/data/themes/maui/Main.qml#L66

Yes that line is commented out because sometimes Xorg has mirrored mode enabled by default. When that happens and the mirrored screen is not recognized as primary the user would not get a password prompt at all.

So it is commented out in the official themes until a xrandr script is crafted add officially added to Xsetup, the problem is that this script should work on all setups thus it should not have assumptions on screen size etc...

**Comment by github-cygwin** [comment]
Ok, I'll try that, but I wonder how this works for the different background pictures?  Note that
my theme has two different background pictures for the two screens.  Right now the theme
has this hack:
 
   Background {
      property variant geometry: screenModel.geometry(screenModel.primary + 1)
      [...]
    }
    Background {
      property variant geometry: screenModel.geometry(screenModel.primary)
      [...]
    }

How do I *correctly* specify which background picture is shown on which screen?  For the one
on the primary screen it seems I could add a "visible: primaryScreen" as well, but what would I
have to do for the other one?

Thanks,
Corinna

**Comment by plfiorini** [comment]
Something like this untested code:

```qml
Loader {
    id: bgPrimary
    anchors.fill: parent
    active: primaryScreen
    sourceComponent: Component {
        Image { ... }
    }
}

Loader {
    id: bgOthers
    anchors.fill: parent
    active: !primaryScreen
    sourceComponent: Component {
        Image { ... }
    }
}
```

**Comment by github-cygwin** [comment]
Never mind my last question.  I added "visible: primaryScreen" to the second of the above
Background object descriptions and now my theme works as desired with 0.13.  That's
sufficient for me.

Thanks for your help!
Corinna

**Comment by plfiorini** [comment]
Ok but you can experiment with the Loader thing which should be more efficient if you want to load less images into memory.

**Comment by github-cygwin** [comment]
Ok, will do, thanks again,
Corinna

**Comment by piomiq** [comment]
Unfortunately multi-monitors support stopped work in version 0.18 and maybe didn't work also in earlier.
