### ISSUE TITLE
The height of middle black strip is smaller than what is shown in the greeter of breeze theme

### ISSUE THREAD

**Issue by sudhirkhanger** [sddm/sddm#570]
I am using Breeze theme on Fedora 23. SDDM Breeze theme has a black strip in middle. KDE Splash also has a similar strip so does the lock screen. The height of this black strip is same for both splash and lock screen but smaller in SDDM. When I run greeter `sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze` I see that the height is same for all three that is SDDM theme, KDE Splash, and the lock screen which gives a consistent experience. It is not so for the actual SDDM when system loads.

**Comment by plfiorini** [comment]
Might be font related. @davidedmundson Do you use fonts to size elements in KDE?
Could you take a look if this is SDDM fault?

**Comment by sudhirkhanger** [comment]
I can't find a quick way to change or see what fonts are being used. I looked into sddm.conf and theme.conf. #204 suggests that SDDM should be using Oxygen. I do use Oxygen everywhere.

**Comment by davidedmundson** [comment]
Not sddm at fault. Please report to plasma.
