### ISSUE TITLE
Passwordless logins?

### ISSUE THREAD

**Issue by likewhoa** [sddm/sddm#577]
This is related to the very second issue #2. My use case would be a livecd which would automatically start sddm and have two features.

<ul>
<li> Auto-Login by user
<li> Password-less Login by user
</ul>

The first point is already supported in sddm by the use of https://goo.gl/eDI3YJ. The last point is what it's not supported and I would really really enjoy having in sddm. The use-case above would allow a pre-defined set of users to pick and choose multiple XSessions to start by just entering their username then the ENTER key.

**Comment by jleclanche** [comment]
Dupe of #505
