### ISSUE TITLE
Option to focus password from Last user

### ISSUE THREAD

**Issue by buildcomplete** [sddm/sddm#582]
I have to use the mouse to hover over the login rectangle before I can type in my password and login.

I would be nice that I did not have to use the mouse, in Windows I remember that it was possible just to use the arrow keys to start toggling/focusing the password entries. something similar could be nice.

Alternative when RememberLastUser=true, the password field could start being focused.

**Comment by AlfredoRamos** [comment]
It's a bug, see #501
