### ISSUE TITLE
Cannot login, unless I try many times

### ISSUE THREAD

**Issue by aelog** [sddm/sddm#587]
I have no idea why, but since a couple days it happens very often that I cannot login to Plasma 5 or LXQt from sddm.
I'm on an Archlinux laptop with Intel graphics and sddm 0.13

The issue is basically the following:

* I boot the laptop and sddm is shown
* I type my user password
* sddm disappears and I see the systemd boot messages for a little while --> expected result: Plasma 5 or LXQt desktop is loaded
* sddm is shown again, asking me the password  --> this looks like sddm just resumed from a crash, but according to `coredumpct list` it's not the case.

After many trials, e.g. switching plasma and lxqt from the session combobox, I eventually achieve to login.

Note that my password is correct. If I type a wrong password sddm shows "Login failed"  as expected. Also note that I have another desktop with Archlinux, sddm 0.13 and nvidia proprietary drivers, and I cannot reproduce this problem there.

From the log files (journalctl, dmesg, Xorg.log, .xsession-errors) everything seems ok. So for now I'm attaching only `/etc/sddm.conf`:

```
[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=
RebootCommand=

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
MaximumUid=65000
MinimumUid=1000
```

Let me know which other config/log file you may need.

**Comment by davidedmundson** [comment]
Apparently chanigng theme to Maui makes this go away.
Lets track this bug here https://bugs.kde.org/show_bug.cgi?id=358171
