### ISSUE TITLE
sddm 0.13.0 freezes after resume from suspend 

### ISSUE THREAD

**Issue by alex-oleshkevich** [sddm/sddm#597]
Hi all, I have a rare issue with SDDM which I see once in 2 days, but regulary.

Symptoms:
1. Black screen (power-saved, stand-by);
2. Move mouse to activate it or press any key on keyboard;
3. the display is on, SDDM shown but frozen;
4. The password input is inactive (even cursor is not blinking in this input). Same to other UI elements like users, poweroff\restart buttons. It does not react on keyboard events but mouse is still active.

Distro: Arch Linux 64 bit
Plasma: 5.5.4 (X11)
Qt: 5.5.1
Kernel: 4.4.1 (same issue with 4.3, but worked fine with 4.2)
Hardware: ASUS N551JK laptop.

I'm not able to reproduce this issue on demand. It happens from time to time. 
How to (try to) reproduce:
1. Boot laptop;
2. Do some stuff (2-3 hrs);
3. Go have lunch (1hr);
4. Get back to laptop unlock it.
30% chance to get SDDM frozen.

[journal.txt](https://github.com/sddm/sddm/files/117332/journal.txt)
[Xorg.0.log.txt](https://github.com/sddm/sddm/files/117335/Xorg.0.log.txt)
[xsession-errors.txt](https://github.com/sddm/sddm/files/117339/xsession-errors.txt)
[sddm.conf.txt](https://github.com/sddm/sddm/files/117337/sddm.conf.txt)
[lspci.txt](https://github.com/sddm/sddm/files/117340/lspci.txt)
[dmesg.txt](https://github.com/sddm/sddm/files/117341/dmesg.txt)

Video record: https://www.youtube.com/watch?v=U-ulrBKfoHo

UPD: in most cases I'm able to unlock session with:
```bash
loginctl unlock-sessions
```

At about 13:40 I left laptop idle and at about 14:18:53 I resumed it from stand-by and observed that freeze and restarted SDDM via systemctl. Hope this helps.

**Comment by alex-oleshkevich** [comment]
I was able to unlock session via 
```bash
# loginctl unlock-sessions
```

**Comment by pagnotta** [comment]
I am having the exact same issue since about two or three months. Keep loosing work due to this.

**Comment by ellisistfroh** [comment]
Well I did have this issue, and it looks like DPMS is the culprit. Hitting ALT+CTRL+DEL (then ESC) made Plasma come alive. Needed quite a time to discover my personal workaround to unfreeze it..

**Comment by polarathene** [comment]
@alex-oleshkevich Are you sure this was due to SDDM? I was having a similar issue with Antergos (Arch) with Gnome and LightDM(Webkit2-greeter). It's been a while since I fixed it, but in my case I think it was either due to not having Swap at the time or some bug that installing libinput fixed.

**Comment by alex-oleshkevich** [comment]
@polarathene, that issue seems ran away with latest plasma. 
Cannot reproduce anymore.

**Comment by polarathene** [comment]
@alex-oleshkevich Good to hear, planning to switch to SDDM and try out KDE soon :) Perhaps close this issue?

**Comment by alex-oleshkevich** [comment]
Good point, but as I read above some more people suffer that. But yes, less mess for sddm devs.
