### ISSUE TITLE
Segfault on startup via systemd

### ISSUE THREAD

**Issue by yanfali** [sddm/sddm#605]
From systemd I was left with no login prompt, but was able to remotely login. I switched to lxdm just to get a working desktop again. Hope this trace helps someone debug it.
- Distro: Arch
- Kernel: 4.4.3-1-Arch x86_64
- CPU: AMD FX-8350
- RAM: 16G ECC
  *Video: Radeon Driver (BONAIRE chipset)
- packages: `sddm-0.13.0-2-x86_64.pkg.tar.xz, sddm-kcm-5.5.5-1-x86_64.pkg.tar.xz, xorg-server-1.18.1-3-x86_64.pkg.tar.xz, qt5-base-5.5.1-9-x86_64.pkg.tar.xz`
- 2 Monitors connected via DVI - 2560x1440

I was running plasma desktop, but since I wasn't sure what was going on I switched over to xfce4 to troubleshoot.

Thanks In Advance.

```
Mar 05 13:54:49 seshat systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Mar 05 13:54:49 seshat systemd[1]: sddm.service: Unit entered failed state.
Mar 05 13:54:49 seshat systemd[1]: sddm.service: Failed with result 'core-dump'.
Mar 05 13:54:49 seshat systemd-coredump[1719]: Process 1716 (sddm) of user 0 dumped core.

                                               Stack trace of thread 1716:
                                               #0  0x00007fb0f3b957ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                               #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                               #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                               #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                               #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                               #5  0x000000000041a410 n/a (sddm)
                                               #6  0x000000000045623d __libc_csu_init (sddm)
                                               #7  0x00007fb0f312b69f __libc_start_main (libc.so.6)
                                               #8  0x000000000041aa69 _start (sddm)
-- Subject: Process 1716 (sddm) dumped core
```

**Comment by NOhs** [comment]
I think this (http://unix.stackexchange.com/questions/331233/arch-linux-hang-on-reached-target-graphical-interface) might be the same, or a related issue, the stack trace looks very similar.

**Comment by NOhs** [comment]
Anyone else can reproduce the issue? The link above contains a minimal script to setup arch which reproduces this issue in virtualbox 100% for me. Here is the output from journalctl:

Jan 27 21:47:49 host sddm[243]: Failed to start display server process.
Jan 27 21:47:49 host sddm[243]: Display server failed to start. Exiting
Jan 27 21:47:50 host systemd-coredump[248]: Process 243 (sddm) of user 0 dumped core.
                                            
                                            Stack trace of thread 243:
                                            #0  0x00007f94cd6ec04f raise (libc.so.6)
                                            #1  0x00007f94cd6ed47a abort (libc.so.6)
                                            #2  0x00007f94ce0894f1 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                                            #3  0x000000000043cd8f _ZN4SDDM7Display5startEv (sddm)
                                            #4  0x000000000044eabd _ZN4SDDM4Seat13createDisplayEi (sddm)
                                            #5  0x000000000044ecc4 _ZN4SDDM4SeatC2ERK7QStringP7QObject (sddm)
                                            #6  0x00000000004500cf _ZN4SDDM11SeatManager10createSeatERK7QString (sddm)
                                            #7  0x000000000043bbfc _ZN4SDDM9DaemonAppC1ERiPPc (sddm)
                                            #8  0x000000000041caac main (sddm)
                                            #9  0x00007f94cd6d9291 __libc_start_main (libc.so.6)
                                            #10 0x000000000041cdaa _start (sddm)
                                            
                                            Stack trace of thread 244:
                                            #0  0x00007f94cd79848d poll (libc.so.6)
                                            #1  0x00007f94ca547786 n/a (libglib-2.0.so.0)
                                            #2  0x00007f94ca54789c g_main_context_iteration (libglib-2.0.so.0)
                                            #3  0x00007f94ce2d246f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                            #4  0x00007f94ce27be9a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                            #5  0x00007f94ce09e053 _ZN7QThread4execEv (libQt5Core.so.5)
                                            #6  0x00007f94cf042de5 n/a (libQt5DBus.so.5)
                                            #7  0x00007f94ce0a2ce8 n/a (libQt5Core.so.5)
                                            #8  0x00007f94cd4a3454 start_thread (libpthread.so.0)
                                            #9  0x00007f94cd7a17df __clone (libc.so.6)

**Comment by enkore** [comment]
I'm seeing the exact same trace on a fresh Arch install.

**Comment by enkore** [comment]
Looks like it's just missing a dependency here'n'there. Installing emacs, sddm, i3 among other things doesn't pull in xorg-server and friends. It still looks kinda buggy -- the trace would suggest that sddm tries to log a `fatal` error message here, but doesn't manage to (abort/raise).

**Comment by NOhs** [comment]
@enkore indeed!

**Comment by gnot18** [comment]
@enkore I don't understand in "installing that..." part. Does it mean reinstalling xorg-server?

**Comment by enkore** [comment]
Yes

**Comment by RiQuY** [comment]
> From systemd I was left with no login prompt, but was able to remotely login. I switched to lxdm just to get a working desktop again. Hope this trace helps someone debug it.

You can login changing the TTY using CTRL+ALT+FX and then executing your WM/DE from the terminal, in my case I used this command to launch KDE Plasma under Wayland:
```sh
dbus-run-session startplasma-wayland
```
