### ISSUE TITLE
Update documentation [X11] -> [XDisplay]

### ISSUE THREAD

**Issue by cpfeiffer** [sddm/sddm#607]
It took me a while to figure out why sddm.conf doesn't work. Your [frontpage](https://github.com/sddm/sddm) says to configure the [X11] section and your [manpage as well](https://github.com/sddm/sddm/blob/master/data/man/sddm.conf.rst.in), while it should be the [XDisplay] section.

**Comment by plfiorini** [comment]
No it was changed to X11 in git master.
Released version have XDisplay.
