### ISSUE TITLE
Enabling DRI3 causes SDDM failing to start

### ISSUE THREAD

**Issue by mightyCelu** [sddm/sddm#608]
After enabling DRI3 on my intel driver I experienced behavior similar to the one described in #415.
This is the log I get for the user sddm when trying to boot:
[sddm.log.txt](https://github.com/sddm/sddm/files/172602/sddm.log.txt)

**Comment by ellisistfroh** [comment]
@ mightyCelu: pls add version of Linux-Distro in use and version of sddm.

Interesting to read: How to report bugs effectivley [1]

[1] http://www.chiark.greenend.org.uk/~sgtatham/bugs.html (*multi-lingual)

**Comment by mightyCelu** [comment]
Sorry for the lack of detail.
I use Archlinux (so there is no version number) and SDDM has version 0.13.0.

**Comment by ellisistfroh** [comment]
Not a sddm-issue

https://bbs.archlinux.org/viewtopic.php?id=207705

Before placing a bug-report . pls consult Distro-Forum.

**Comment by mightyCelu** [comment]
Okay, sorry I missed that. I'll try again with newer packages.
