### ISSUE TITLE
GREETER: This program requires an X86 processor that supports SSE2 extension, at least a Pentium 4 or newer

### ISSUE THREAD

**Issue by PaddyMac** [sddm/sddm#609]
I get the error "GREETER: This program requires an X86 processor that supports SSE2 extension, at least a Pentium 4 or newer" in /var/log/sddm.log. Please implement support for non-SSE2 processors.

**Comment by plfiorini** [comment]
This is a requirement set by Qt.
Your distro should consider building Qt with -no-sse2 for x86 (32 bit), please note that x86 CPUs sold in the last 10 years all have support for SSE.

See also https://bugreports.qt.io/browse/QTBUG-35430

**Comment by PaddyMac** [comment]
I apologize. I should have followed up because shortly after I filed this bug, I found some other reports that indicated that this *particular* issue was due to QT5 compiled with SSE2 support. My desktop computer currently runs Debian which I recently upgraded from Jesse to Stretch (the current testing). It is what provided this error. I also tried using the SLIM login manager to login to Plasma 5 with no success.

You see I have a desktop and 2 other non-sse2 desktop computers I'm using as home servers and a somewhat recent 64-bit netbook which does support SSE2. All 3 of these computers (which I was fortunate enough to get second-hand for free) are running Funtoo, so I compiled them from source code. The two 32-bit desktops were explicitly compiled without SSE2 support, and the 64-bit netbook was compiled with SSE2 support since the CPU does support SSE2.

The netbook is the only one that will start SDDM.

I have no control over how Debian's packages were compiled. The other 3 were compiled from source using gcc flags customized for the host systems. The only one that will start SDDM is the one that has SSE2 support. So surely you can see why I would suspect that SDDM must require SSE2 since everything -- including the QT5 libraries -- were custom-compiled for the CPU, and SDDM still failed to run because sddm-greeter segfaulted. The only difference is that Debian is the only one that provided any kind of useful error message in the sddm.log.

I also apologize that I cannot afford to buy a new computer. I am well aware that new computers in the past several years all support SSE2. I've been reminded of this frequently. I can't buy a new computer without putting myself at risk of being unable to pay the bills to keep a roof over my family's head and food on the table. So please pardon me that the only reason I have even one computer with SSE2 support is the fact that someone who bought it secondhand for $50 gave it to me because it was too slow.

I have nothing against you personally, and I appreciate the fact that you are developing this software. You are doing this out of generosity by developing open source software. But some of us use open source software not only because of a belief in the philosophy behind it but because we are financially unable to obtain the latest and greatest software OR hardware. So I am really sick and tired of hearing the response "all new computers support SSE2 (or whatever)". I've heard this answer over and over from many different people. If I could afford it, I'd get a new computer. And there are plenty of us who use and support open source in some way or another who haven't the advantage of being financially prosperous enough to have a computer newer than 15 years old. At the very least, that should at least theoretically be one of the advantages of compiling your programs from source code -- it is guaranteed to run on your processor....or *should* be unless a programmer opts to use mandatory codepaths which require certain CPU functions even if the compiler is instructed to not use those instructions.

So *maybe* it's two different issues, but the fact remains that I have 4 different test systems, 3 of them are compiled from source optimized for the host CPU, only one of them will start SDDM (the one with SSE2 support), and the only one that can be explained away by QT5's reliance on SSE2 is the single system running Debian because it uses precompiled binaries.

**Comment by beojan** [comment]
PaddyMac, you should report this as a bug to Debian. I know Debian's bug tracker is a little complicated, so I would suggest using [reportbug-ng](https://packages.debian.org/jessie/reportbug-ng) to do this.

You should report this as a bug in the qtbase-opensource-src source package on the i386 architecture, and include a link to this page.
