### ISSUE TITLE
SDDM takes 90 seconds to exit when restarting the system from within KDE

### ISSUE THREAD

**Issue by Xavion** [sddm/sddm#610]
Over the last few weeks, I've noticed that my Arch Linux system takes forever to restart or shutdown.  This morning, I narrowed down the problem to SDDM (v0.13.0) and my encrypted swap partition.

It seems that SDDM and the swap stay active until the 90 second process termination limit is reached.  However, I noticed that this only happens when I trigger the restart/shutdown from within my DE (KDE).  If I log out first and initiate the restart/shutdown from SDDM itself, there are no delays.

So that you can see what I mean, I've attached the relevant sections of two debug restart logs.  To cut to the chase (in the "Bad.txt" file), simply search for "timed out".  If this problem isn't caused by SDDM, let me know where the blame should be placed.

[Bad.txt](https://github.com/sddm/sddm/files/180612/Bad.txt)
[Good.txt](https://github.com/sddm/sddm/files/180611/Good.txt)

**Comment by ellisistfroh** [comment]
If this is only from within KDE than it's KDE related. Easy to test 
1. Select logout from menu to arrive at the SDDM-screen. Then select shutdown/reboot.Delay?
2. Select shutdown/reboot from KDE directly. Delay? Compare

Had the same in Antergos and Manjaro, both KDE. In common I do close all programs before shutdown anyways (oldfashioned). Changed to a virtual terminal (VT1) and requested shutdown there. Less than a second as result.

Some things you can test without harm. 
- KDE comes with the preset option "restore previous session". You can disable that within the Systemsettings (same as below but section "on login"). Remember to save any open work before! 
- KDE enabled a 30 sec's grace time shutdown delay (popup wt option now/cancel) as standard awhile ago, when ext4 was introduced to be on the safe side. This standard got never removed but received the option to disable that when ext4 was considered to be stable enough not to suffer dataloss from immediate shutdown.

 Can be disabled via Systemsettings/Start & Finish/Desktop-session / section "General" / confirm logout (remove hook)

If this doesn't help try to find out if there are problems reported for LVM/encrypted swap (if I read your logs correrectly). Some Arch users may also have reported this against SystemD. And they say they are not the culprit.

**Comment by tpgxyz** [comment]
Sounds like this issue which got fixed in systemd-230
https://github.com/systemd/systemd/issues/2691

**Comment by plfiorini** [comment]
Closing the issue since it seems an upstream problema that got fixed.
