### ISSUE TITLE
HiDPI setting in Kubuntu

### ISSUE THREAD

**Issue by MadEgg** [sddm/sddm#614]
I'd like to change the DPI / screen scaling for SDDM on my Kubuntu (Xenial).

The front page mentions a file /etc/sddm.conf but there doesn't seem to be a sddm.conf on my system. I do have a /etc/sdm/ folder that contains a file called Xsession, but this seems to be executed after X.org is started, not before, so that's too late to change the ServerArguments variable.

Any clue on where to look / configure in this case?

**Comment by ellisistfroh** [comment]
This is dependent of the Qt version in use.

Possibly it's much easier to say more if you could reveal what distro is appropriate use and such (DE, graphics-hardware).

**Comment by MadEgg** [comment]
Like I said, Kubuntu Xenial.

So:

Distribution: Kubuntu 16.04 (beta 2)
Desktop environment: KDE / Plasma 5.5.4
SDDM version: 0.13.0-1ubuntu5
SDDM theme: breeze 5.5.4-0ubuntu1
QT-version: 5.5.1-4ubuntu3

Graphics hardware: Intel HD530 IGP / nvidia GTX965M DGP
Resolution : 4k / 3840x2160 (15'' panel -> ~280 PPI)

**Comment by MadEgg** [comment]
I have been able to work around this. I first tried creating /etc/sddm.conf which is absent on Kubuntu. I then added:

[XDisplay]
ServerArguments=-nolisten tcp -dpi 168

However, this prevented SDDM from starting altogether. It seems that this configuration file is actually red.

I then added:

/usr/bin/xrandr --output eDP-1 --fbmm 345x194 --dpi 168

to /usr/share/sddm/scripts/Xsetup

which makes SDDM use the alternative DPI setting (actually using 280 makes things too big to my taste).

I have no clue why Ubuntu decided to not ship the configuration file, and I'm also not sure why my limited sddm.conf doesn't work (or does it need to specify all options, regardless of whether defaults are used?) but it is working now.

**Comment by opensas** [comment]
same problem here with kubuntu 20.04 beta (see related question at https://askubuntu.com/questions/1225750/change-login-screen-resolutionn-sddm-on-kde-plasma-5-68)

**Comment by opensas** [comment]
I tried you solution and it works, but I see it way too big (even with 168 dpi) I tried lowering it but with the same result. How can I try different resolutions?
thanks a lot

**Comment by EgbertW** [comment]
I actually solved it 'the proper way' now, by creating the directory `/etc/sddm.conf.d` and creating a file in there called `dpi.conf` containing:

```
[X11]
ServerArguments=-nolisten tcp -dpi 168
```

I just experiment with the value for 168 and `systemctl restart sddm` after each modification - when I make it 90 everything is way too small, when I put at  280, everything is way too big.

**Comment by opensas** [comment]
great, I just found a workaround in kubuntu. In Settings, Startup and Shutdown, Login, Advanced tab, check "automatically login" (you can later uncheck it) and the file `/etc/sddm.conf.d/kde_settings.conf` is automatically created, with the same configuration you posted.
