### ISSUE TITLE
SDDM and LightDM can run in parallel (thus create conflict)

### ISSUE THREAD

**Issue by ellisistfroh** [sddm/sddm#620]
This issue has been reported under Kubuntu/Ubuntu Mate 15.10 (Wily Werewolf)

https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1446760
evaluated wt severity="critical" & status=confirmed by other users.

This appears when a multi Desktop-Environment gets installed. Obviously `sudo dpkg --reconfigure ...` doesn't lead to a reliable result. The start screen shows a scattered image, when it comes to login. 

So remaining options are to deinstall/purge SDDM or stop the journald-service.

Would be nice if anyone could look into that. Informations in Launchpad bug-report should be sufficient. Thanks in advance!

**Comment by ellisistfroh** [comment]
Just added a comment on LP-bug-report, diving a bit more int that.
https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1446760/comments/12
Thinking that the current version of SDDM in Wily 15.10 is not representing the actual state of development (stable). So it may be fixed from your side already.

**Comment by jleclanche** [comment]
What's the actual issue there? Shouldnt the distro have a package level conflict between the two packages?

**Comment by Mikaela** [comment]
I also think the issue is distribution side as I have been unable to reproduce it on other distributions (mainly Arch).

*I am the original opener of that Ubuntu bug.*
