### ISSUE TITLE
HideShells not working when multiple shells are specified

### ISSUE THREAD

**Issue by meyergru** [sddm/sddm#621]
The option HideShells in /etc/sddm.conf does not work correctly. When more than one shell is specified, the filter does not work and the matching users are listed in the greeting screen notwithstanding.

Downstream Ubuntu bug:

https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1566542

**Comment by marcan** [comment]
HideUsers is similarly broken, and `sddm --example-config` returns bogus data for those options. I think the QStringList parsing for the config options is broken in general.

**Comment by marcan** [comment]
Ah, this was already fixed in 56f64173 and cdd6552b. I guess that just needs to be released.

**Comment by meyergru** [comment]
The problem is that even doing that will not fix anything for downstream releases like Ubuntu 16.04 LTS for the next two years.

**Comment by marcan** [comment]
Sounds like it'd be up to Ubuntu to backport the patch to their stable release in that case...

**Comment by plfiorini** [comment]
Fixed

**Comment by davestechshop** [comment]
I'm experiencing this exact problem in Arch Linux in 2018. 
# pacman -Qi sddm
Name            : sddm
Version         : 0.17.0-5
