### ISSUE TITLE
sddm switches to tty7 during shutdown

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [sddm/sddm#623]
When MinimumVT is set to (for example) 7, and the system is shutdown (OpenRC-0.19.1). First KDE is closed and i see tty1 where the shutdown process starts, then when it comes to stopping sddm, it switches to tty7 and stays there for the rest of the shutdown process. Which is annoying, and unpractical, since i can no longer see what's happening. 

SDDM-Version:  0.13.0-r3
OS: Gentoo KDE x86_64
Name: Toshiba Satellite L850-1KT
GPU: AMD Radeon HD 7670M
CPU: Intel Core i7 3630QM
Full Specifications: https://tinyurl.com/k9sucx9

**Comment by ellisistfroh** [comment]
hi!

you need to argue this with the Distro in question as SDDM follows the systemd convention [1] of starting the first graphical session on tty1. So it's likely that this got changed in the distribution for specific reasons. On Kubuntu I can just use the [arrow-right/~-left key] to see text messages, also I prefer to have the VT1-VT6 resereved for getty-tty's.

[1] http://0pointer.de/blog/projects/serial-console.html

**Comment by greyhare** [comment]
It sounds like the real problem is "when it comes to stopping sddm, it switches to tty7". The solution would be for sddm to simply not switch the tty. I don't see how this would break systemd. If a global behavior change isn't feasible, maybe just have a config option for it.

**Comment by plfiorini** [comment]
MinimumVT=7 is an option that restores the behavior for non-systemd systems where usually the login manager runs on vt 7.
This is completely ignored on systemd systems where SDDM greeter runs in vt 1.

I could switch to vt 1 but dunno where other init systems are going to show shutdown messages.

As far as I'm concerned MinimumVT=7 does what it says, try setting it to 1.
