### ISSUE TITLE
sddm.conf: HideUsers / RememberLastUser settings not effective

### ISSUE THREAD

**Issue by mathias-w** [sddm/sddm#626]
With sddm, it is not possible to have a login screen that does not reveal existing user names. The graphical config page under KDE does not a present such an option at all (like KDM did). According to its man page, /etc/sddm.conf does have the option 'HideUsers=' and 'RememberLastUser=' which can be set to the user names resp. true/false. But whatever is put there, is ignored by sddm. 

System: gentoo, x64, openrc, plasma 5

Reproducible: Always.

Steps:
1. Insert lines 'HideUsers=foo' and 'RememberLastUser=false' into [Users] section of /etc/sddm.conf.
2. Start sddm/X, login as foo.
3. Logout.

Result:
1. /var/lib/sddm/state.conf contains line 'User=foo'.
2. Upon next login, foo is already filled in as username.

Expected:
1. state.conf should have an entry like 'User='.
2. The sddm login screen should have an empty username field.

I already tried to manually erase the User entry in state.conf, to no avail (see: https://forums.gentoo.org/viewtopic-t-1042836.html).

It's not a duplicate of, but somehow close to this: https://github.com/sddm/sddm/issues/560.

**Comment by plfiorini** [comment]
This should be fixed now.

**Comment by rybak** [comment]
To those, who find this link while trying to hide users from greeter. To do that, edit or create the file `/etc/sddm.conf.d/uid.conf` if it doesn't exist (directory `/etc/sddm.conf.d/` may also need to be created manually). In section `[Users]`, assign a comma-separated list of users to variable `HideUsers`. For example:

```
[Users]
HideUsers=git,joe
```

Source: https://wiki.archlinux.org/index.php/SDDM

For detailed description, see `man sddm.conf`

**Comment by edwardp3** [comment]
> To those, who find this link while trying to hide users from greeter. To do that, edit or create the file `/etc/sddm.conf.d/uid.conf` if it doesn't exist (directory `/etc/sddm.conf.d/` may also need to be created manually). In section `[Users]`, assign a comma-separated list of users to variable `HideUsers`. For example:
> 
> ```
> [Users]
> HideUsers=git,joe
> ```
> 
> Source: https://wiki.archlinux.org/index.php/SDDM
> 
> For detailed description, see `man sddm.conf`

Debian 11, the above does not work, username still displayed.
