### ISSUE TITLE
sddm-helper exits with 1

### ISSUE THREAD

**Issue by rohshall** [sddm/sddm#627]
`
 ~ % sudo systemctl start sddm
[sudo] password for swadnerkar: 
 ~ % sudo systemctl status sddm
● sddm.service - Simple Desktop Display Manager
   Loaded: loaded (/usr/lib/systemd/system/sddm.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-04-19 07:20:26 PDT; 30s ago
     Docs: man:sddm(1)
           man:sddm.conf(5)
 Main PID: 1691 (sddm)
    Tasks: 4 (limit: 512)
   CGroup: /system.slice/sddm.service
           ├─1691 /usr/local/bin/sddm
           └─1703 /usr/libexec/Xorg -nolisten tcp -auth /var/run/sddm/{57e0283b-92b8-4dce-b188-c1a2fa349dce} -background none -noreset -displayfd 

Apr 19 07:20:46 acer sddm-helper[1896]: PAM _pam_load_conf_file: unable to open config for system-login
Apr 19 07:20:46 acer sddm-helper[1896]: [PAM] Starting...
Apr 19 07:20:46 acer sddm-helper[1896]: PAM _pam_load_conf_file: unable to open config for system-login
Apr 19 07:20:46 acer sddm-helper[1896]: [PAM] Authenticating...
Apr 19 07:20:46 acer sddm-helper[1896]: [PAM] authenticate: Permission denied
Apr 19 07:20:46 acer sddm-helper[1896]: [PAM] returning.
Apr 19 07:20:46 acer sddm[1691]: Authentication error: "Permission denied"
Apr 19 07:20:46 acer sddm[1691]: Authentication failure
Apr 19 07:20:46 acer sddm-helper[1896]: [PAM] Ended.
Apr 19 07:20:46 acer sddm[1691]: Auth: sddm-helper exited with 1
lines 1-21/21 (END)
`

My Linux system:
`
 ~ % uname -a
Linux acer 4.5.1-300.fc24.x86_64 #1 SMP Tue Apr 12 18:55:06 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 ~ % cat /etc/fedora-release 
Fedora release 24 (Twenty Four)
 ~ % which sddm
/usr/local/bin/sddm
`

**Comment by plfiorini** [comment]
Fedora uses SELinux and has a policy for SDDM, please make sure you apply the policy to your sddm-helper.
If I recall there should be some SELinux context to set probably xdm_t, check /usr/libexec/sddm-helper shipped by Fedora.
