### ISSUE TITLE
Theme maui ineligible due to getting hard-coded

### ISSUE THREAD

**Issue by pmattern** [sddm/sddm#632]
Commit f7d3f67 makes theme maui ineligible.

That is, choosing the theme by setting
```
[Theme]
Current=maui
```
in `sddm.conf` does not have an effect any longer. Instead, the first theme in alphabetical among those in `/usr/share/sddm/themes` is chosen.

On a side note I could not get that fallback feature to work yet.
E. g. when some files of a particular theme `/usr/share/sddm/themes/foo` get deleted a corresponding limited version of the greeter is shown. When all files of a particular theme or all themes in `/usr/share/themes/` are removed the greeter crashes and dumps core upon start.
I do not know what is meant to be considered as "theme error" in terms of the commit message of f7d3f67. But I think incomplete or lacking themes should be mitigated by that fallback functionality and not trigger a crash.

**Comment by greyhare** [comment]
IMHO hard-coding Maui is not a great idea; a hard-coded, fallback theme should be something absolutely bare-bones with minimal resource needs, whose primary purpose is to allow logins some way somehow, and not to show off the wide range of capabilities SDDM has. Such a theme shouldn't be much more than a couple text-entry boxes for username and password, a menu for session selection, and maybe buttons for restart/shut down.

The hard-coded theme should only be seen when everything fails, and if it is exactly the same as the default, shipped theme, then it hides the fact that there are theme-loading faults, i.e. it fails silently, which isn't a good thing.

**Comment by plfiorini** [comment]
@pmattern the PR was never finished but got merged nevertheless

**Comment by plfiorini** [comment]
@greyhare that what maui is

**Comment by plfiorini** [comment]
@pmattern will get this fixed today

**Comment by plfiorini** [comment]
@pmattern done, looks like it works. please give it a test and feel free to reopen the issue if it has problems.

**Comment by pmattern** [comment]
The problem isn't solved really yet.

Theme `maui` is only used when no theme is set at all
```
[Theme]
# Current theme name
Current=
```
but the problem as depicted above persists when it is explicitely set
```
[Theme]
# Current theme name
Current=maui
```

78e1d9a on Arch Linux.

@plfiorini 
I cannot reopen this issue as it was closed by a team member.

**Comment by plfiorini** [comment]
@pmattern the maui theme is deprecated like circles. we just need to write it down in the release notes.

**Comment by pmattern** [comment]
On the one hand it seems a bit odd it has been chosen as the hard-coded fallback theme in f7d3f67 no too long ago then.

More importantly this issue is basically not about theme maui but about the fact that hard-coding a theme to make it serve as fallback doesn't seem to work as expected so far.
In other words, isn't it likely that the problem which remains, namely the embedded theme isn't used when explicitely set in sddm.conf, persists should maui be replaced by another theme?

On a personal side note I for one found it at pity if you dropped maui at least as long as no other theme than maldives allows for chosing users by mouse click and not by filing their name in a form only.

**Comment by plfiorini** [comment]
@pmattern i mean that you don't need to set Current=maui in sddm.conf anymore just Current= (which is the default now) and it will automatically use maui embedded in the resources.

**Comment by plfiorini** [comment]
In other words:

* maui is now embedded into the greeter itself and it's the default theme, SDDM installations will automatically have maui
* The default Current= value is now empty, with an empty value the greeter will automatically use the embedded maui theme
* Since /usr/share/sddm/themes/maui is no longer physically availabe, If you set Current=maui, SDDM will use the first theme in alphabetical order because maui as a standalone theme is no longer available. If no theme will be found (nuked /usr/share/sddm/themes for example) then SDDM will fallback to the embedded maui theme. The release notes will state all of that.
* If the user choose another theme that have QML errors, SDDM will fallback to the embedded maui theme.

maui theme is not gone forever, it was just shoved into the sddm binary

**Comment by pmattern** [comment]
As of 1d6acdc all problems addressed in the initial comment are fixed.
When `Current` in section `[Theme]` of `sddm.conf` is stating either nothing, 'maui' or some string that does not refer to a working theme in the themes folder, then theme maui is used. An incomplete greeter or crashes due to faulty themes have gone in favour of correctly falling back to the embedded theme as well.

Two additional notes:

If SDDM falls back to the embedded theme because the chosen theme is faulty, e. g. lacking `Main.qml`, then the greeter displays a corresponding warning. But when SDDM falls back to the embedded theme because the theme folder (`/usr/share/sddm/themes/`) is empty, then the greeter comes up as usual.
I think it would improve the UX if the greeter displayed a warning when falling back due to an empty themes folder, too.

While I think the fallback feature as implemented right now is absolutely the right thing to do I still don't think using maui as embedded theme was a good choice.
As written above it is the only among the themes provided by SDDM which allows for selecting users by clicking icons instead of filing a form. Also, it's somewhat odd that a theme that has been around for quite some time is no longer eligible in configuration GUIs like sddm-config-editor or sddm-kcm but keeps existing somehow. Also, I agree with what @greyhare has written about the nature of fallback themes [above](https://github.com/sddm/sddm/issues/632#issuecomment-217643488).
So I still think it would be good to turn maui into a regular theme again and introduce a dedicated theme to fall back upon. The latter could be something really simple, e. g. just a white background with a minimal form that's enough to log in, which would even provide another well noticeable hint for users that there's something wrong with the themes on their system.

**Comment by dreaming-augustin** [comment]
Yes. These are also the thoughts I just expressed in #771 .
Thanks.

The default theme doesn't need to be ugly. Maui could very well be *both* an unnamed, fallback, internal theme, and a full-fledged seems alongside the other themes in /usr/share/sddm/themes/.
We'd get the best of both worlds: 1) stability and usability, 2) user choice and configurability.

**Comment by pmattern** [comment]
I think having one and the same theme included in the binary and available in `/usr/share/sddm/themes` in parallel would be a constant source of confusion.
But that aside we seem to agree that losing maui as regular theme due to picking it as built-in fallback isn't a good thing.
