### ISSUE TITLE
Kick a new scan on Coverity

### ISSUE THREAD

**Issue by 1ace** [sddm/sddm#634]
Last one is over a year old, and doesn't contain anything useful anymore.
https://scan.coverity.com/projects/sddm

**Comment by plfiorini** [comment]
Thanks, just sent a request to get access to it

**Comment by 1ace** [comment]
Right, I should've checked. I just assumed you were the one to own it :]

In case this is not something you can see, the owner is kde@davidedmundson.co.uk
You can mail him and ask to make you at least an admin, if not transfer ownership :+1:
