### ISSUE TITLE
should kill and then terminate logind sessions

### ISSUE THREAD

**Issue by apachelogger** [sddm/sddm#636]
Sometimes it happens that sessions have lingering applications which prevent the session from closing.

This regularly happens with Plasma sessions as the shutdown procedure doesn't always manage to kill all processes belonging to the session (such as gpg-agent if it was started via Xsession scripts).
In the end this causes a severe reboot/shutdown delay while waiting for the session, which is in state:closing but not going to close because of lingering processes that do not know they are supposed to terminate.

To prevent this SDDM should make sure the logind session gets cleaned once the xsession exists by at least sending a kill to the logind session and possibly also a terminate if the session doesn't close after a short while.

This is mostly reproducible by having pulseaudio on per-client socket activation and starting a Plasma session, then logging out of the session.

```loginctl list-sessions``` will now list a session that is 'closing' but still has a pulseaudio unit attached as seen with ```loginctl session-status $id```.

It also happens on Debian systems which autostart gpg-agent via /etc/X11/Xsession.d/90gpg-agent which apparently prevents the plasma session from noticing it and attempting to kill it.

**Comment by beojan** [comment]
In the past I've had a problem where killing those processes prevented logging back into Plasma until a reboot.

**Comment by apachelogger** [comment]
This actually is a daft idea. Killing the session via logind would also nuke a screen/tmux.
