### ISSUE TITLE
Lockscreen: show suspend button

### ISSUE THREAD

**Issue by azrdev** [sddm/sddm#649]
Using Archlinux rolling with KDE5 and SDDM 0.13.0-2 here. When I put the system to sleep, the screen locks, and the sddm lockscreen is shown upon resume.
If I accidentally wake up the computer and would like to immediately go back to sleep, I have to enter my password and unlock, before being able to do so.
Thus the request: Please add a "suspend" button to the lockscreen.

**Comment by plfiorini** [comment]
The locker is not done by SDDM, rather by the desktop which in this case happens to be Plasma.
SDDM's greeter is closed when a user session starts thus it doesn't have any graphical part alive.

**Comment by azrdev** [comment]
Yes, thank you and sorry for the confusion. The bug actually is in kscreenlocker: https://bugs.kde.org/show_bug.cgi?id=336369
