### ISSUE TITLE
Allow closing session

### ISSUE THREAD

**Issue by azrdev** [sddm/sddm#650]
In my sddm lockscreen, I have the option to *start a new session*. If I do so, apparently a new sddm instance is spawned on a different tty. There is a button to switch between these sessions, but none to close the current one.

**Comment by plfiorini** [comment]
Same as the other issue, the lock screen has the button.

**Comment by azrdev** [comment]
Here, too, thanks for pointing that out. (For the reference: the other issue was #649)
Filed the bug against kscreenlocker: https://bugs.kde.org/show_bug.cgi?id=364499
