### ISSUE TITLE
sddm-helper exited with 6 - Greeter not displayed - see #412

### ISSUE THREAD

**Issue by gbcox** [sddm/sddm#651]
Downstream bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1350107

This just started happening to me on a Lenovo ideapad 500 when I upgraded to F24.  I read through the comments on #412 and also the Gentoo downstream bugs.  If I put in the sddm.timer with a value of 30 I can get it to work.  Adding sddm to video group doesn't apply because Fedora has pam and systemd.  Apparently SDDM needs something that is not available when it starts, hence the delay helps - but not all users are going to (or should have to) trudge through Google and a bunch of bug reports to find the work around.  They're just going to give up.  I'll help in anyway I can to get this resolved.
Thanks!

**Comment by gbcox** [comment]
Also, instead of using a timer, wouldn't it be better to just find out whatever it is waiting for and add that to the After in the systemd service file?

**Comment by rdieter** [comment]
in the other referenced issue, the issue there was (most likely):
lug 05 17:38:27 PC-Gentoo sddm-greeter[382]: QXcbConnection: Could not connect to display :0

Which implies it may be a permissions or xauth issue.  for example, I've seen wierd things happen like this if dhcp (re)sets hostname while sddm is starting.

But I don't recall your logs including anything about that.

**Comment by gbcox** [comment]
Rex, I do have that error, see below.  I'll also get the logs here.

Jun 26 12:13:33 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=sddm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel audit[962]: USER_AUTH pid=962 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_permit acct="sddm" exe="/usr/libexec/sddm-helper" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel audit[962]: USER_ACCT pid=962 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_permit acct="sddm" exe="/usr/libexec/sddm-helper" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel audit[962]: CRED_ACQ pid=962 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_permit acct="sddm" exe="/usr/libexec/sddm-helper" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel audit[966]: USER_ACCT pid=966 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="sddm" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel audit[966]: USER_START pid=966 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_selinux,pam_selinux,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="sddm" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 26 12:13:40 asphodel sddm-helper[962]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Jun 26 12:13:40 asphodel audit[962]: USER_START pid=962 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_unix,pam_systemd acct="sddm" exe="/usr/libexec/sddm-helper" hostname=? addr=? terminal=:0 res=success'
Jun 26 12:13:40 asphodel systemd[966]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
Jun 26 12:13:40 asphodel systemd[1]: Created slice User Slice of sddm.
Jun 26 12:13:40 asphodel systemd-logind[678]: New session c1 of user sddm.
Jun 26 12:13:40 asphodel systemd[1]: Started Session c1 of user sddm.
Jun 26 12:13:41 asphodel audit[990]: ANOM_ABEND auid=4294967295 uid=992 gid=988 ses=4294967295 pid=990 comm="sddm-greeter" exe="/usr/bin/sddm-greeter" sig=6
Jun 26 12:13:41 asphodel sddm-greeter[990]: QXcbConnection: Could not connect to display :0
Jun 26 12:13:41 asphodel abrt-hook-ccpp[1026]: Process 990 (sddm-greeter) of user 992 killed by SIGABRT - dumping core
Jun 26 12:13:50 asphodel sddm[767]: Auth: sddm-helper exited with 6
Jun 26 12:13:50 asphodel systemd[975]: pam_unix(systemd-user:session): session closed for user sddm
Jun 26 12:13:50 asphodel systemd[1]: Removed slice User Slice of sddm.
~

**Comment by gbcox** [comment]
I'm using the breeze theme.  What I found was that the other themes worked fine.  I then did a compare between the 01-breeze-fedora theme and the breeze theme.  What I found was that the permissions on the file:

/usr/share/sddm/themes/breeze/components/artwork/background.png
/usr/share/sddm/themes/01-breeze-fedora/components/artwork/background.png

were different.  In the 01-breeze-fedora version it was 777, in the breeze version (which has the issue) it is 644.  Apparently, that is the issue.

I changed the permissions for:
/usr/share/sddm/themes/breeze/components/artwork/background.png
to 777

and it now is working correctly.  The sddm-timer is no longer needed.

**Comment by gbcox** [comment]
Closing, since this issue was caused by permissions on a file within the breeze theme.

**Comment by gbcox** [comment]
Update, the permissions fix was anecdotal.  The problem appears with the breeze theme and the 01-fedora-breeze theme which are identical, with the exception of the background.png file.  The issue does not appear with the other themes, such as maui.

**Comment by m-guggenmos** [comment]
Same problem here with kde-neon, sddm-0.13.0. Using theme breeze results in a black screen, while all other tested themes (e.g. maui, kdm) work.
