### ISSUE TITLE
how to enable touchtap tapping click in sddm?

### ISSUE THREAD

**Issue by esmeetu** [sddm/sddm#657]
Problem is that I have to use mouse to click the button in sddm. 
But i prefer to use touchpad tapping. Is that possible?

OS info: Arch+KDE plasma 5.7.

**Comment by goetzc** [comment]
If SDDM is running on Xorg, and you use libinput, just add `Option "Tapping" "on"` to a xorg conf file in /etc//X11/xorg.conf.d/  
You can use this:

`cat /etc/X11/xorg.conf.d/20-touchpad.conf`  
```bash
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"

        Option "NaturalScrolling" "on"
        Option "MiddleEmulation" "on"
        Option "Tapping" "on"
        Option "DisableWhileTyping" "on"
EndSection

```

**Comment by esmeetu** [comment]
@goetzc Thanks for your reply! 
I install the `libinput` instead of the previous driver `xf86-intel-synaptics`, and that works.
