### ISSUE TITLE
SDDM unable to start GNOME classic desktop session

### ISSUE THREAD

**Issue by ovitters** [sddm/sddm#658]
As per https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables, the Exec= key in a .desktop file is defined as:
"The Exec key must contain a command line. A command line consists of an executable program optionally followed by one or more arguments"

The gnome-classic desktop xsession file contains (https://git.gnome.org/browse/gnome-shell-extensions/tree/data/gnome-classic.desktop.in):
Exec=env GNOME_SHELL_SESSION_MODE=classic gnome-session --session gnome-classic

Meaning: a command (env) with multiple arguments.

From what I can see in https://github.com/sddm/sddm/blob/master/src/helper/UserSession.cpp, it seems that QProcess will only interpret things as per the desktop standard if arguments are left out for QProcess::start. Currently SDDM gives a path as an argument. What could possibly be done is to special case this: In case of a space in the Exec= key, start via QProcess without giving any arguments. 

It seems that QProcess tries to start the whole Exec= as one command, which does not work. As a result, trying to login to a GNOME classic session will fail to work.

Mailing list post by Mageia QA: https://ml.mageia.org/l/arc/qa-discuss/2016-07/msg00218.html
Bug report where I noticed the cause for SDDM: https://bugs.mageia.org/show_bug.cgi?id=18199#c30

**Comment by plfiorini** [comment]
It's better if we give QProcess the full command line from Exec, that should work.

**Comment by plfiorini** [comment]
Actually it should go through the Xsession script so the inverstigation should lead there
