### ISSUE TITLE
keyboard and mouse not working in sddm login prompt

### ISSUE THREAD

**Issue by atilaneves** [sddm/sddm#659]
This is a dup of [issue 555](https://github.com/sddm/sddm/issues/555), I'd reopen that one but I can't since I wasn't the one who filed it. I'm on Arch Linux, as I write this the most recent version of sddm is 0.13.0-3. For now I've downgraded to 0.10.0-1.

My symptons are the same as the previous bug: there is no mouse pointer to move and click on the password field, and pressing the keyboard does nothing _unless_ I use Ctrl+Alt+Fx to change tty, which works fine.

I have two monitors on one X screen using base mosaic. The multiple monitor thing has caused issues with sddm in the past but I can't find the original bug or when it got fixed. It seems it's back.

**Comment by allan2** [comment]
I have the same issue on a fresh install. I can type into my tty on boot but if I start sddm, I cannot type or move the mouse/trackpad, or access the tty.

No `xorg.conf`, input driver is `xf86-input-libinput`. Using exact same config as a few other working setups.
sddm version is 0.13.0-r3

**Comment by verwilst** [comment]
I'm also having this issue. Sddm 0.14.0. After each boot, i have to switch to a vt, login there, and issue a sudo pkill sddm. This bring sddm back up and keyboard + mouse work.

**Comment by sergiocallegari** [comment]
Same here, on a machine with nvidia graphics and noveau.

The weird aspect is that, after logout from the graphical environment (KDE Plasma 5), sddm works fine and can get the mouse and keyboard input. However, if I leave it there for enough time, the keyboard and the mouse are lost.

**Comment by verwilst** [comment]
Turning off one of my screens during boot allows me to type and login as well. Turning on the screen while I'm at the initial SDDM login screen still disables my mouse and ability to type. Entering my credentials while the second screen is off works, and I can turn the screen back on once I reach the desktop.

**Comment by sergiocallegari** [comment]
Same here, on a machine with nvidia graphics and noveau.

The weird aspect is that, after logout from the graphical environment (KDE Plasma 5), sddm works fine and can get the mouse and keyboard input. However, if I leave it there for enough time, the keyboard and the mouse are lost. By "enough time" I mean a long time. If I check after a couple of hours the keyboard is still working. If I check the day after, it is not.

**Comment by jonwarghed** [comment]
Same problem on 0.14.0-2, dual monitors, no mouse or keyboard in the sddm greeter but using another tty to bring it back up everything works. Unable to troubleshoot myself but able to help with logs if someone wants.

**Comment by davidedmundson** [comment]
Setup issue

**Comment by PunkmeisterDuy** [comment]
@davidedmundson How did you fix this?

**Comment by robin-rpr** [comment]
Not sure why this issue has been closed with a "Setup issue" Comment. I unfortunately can't see how users are supposed to solve this issue with such.

**Comment by YeesterPlus** [comment]
davidedmundson is ur average arch user
