### ISSUE TITLE
Broken Lock Screen

### ISSUE THREAD

**Issue by Marvellousnet** [sddm/sddm#674]
Hi family! I am new to linux and i have installed Manjaro Linux KDE edition. I have been playing around with it for sometime now and i just installed Mint Display manager. Now when i click the lockscreen the screen flahes and error message appears telling me i have broken screen. Please how do i fix the broken screen issue?
Thanks in advance

**Comment by plfiorini** [comment]
@Marvellousnet When you say lock screen do you actually mean lock screen or login screen? The way to tell is: are you already logged in Plasma or are do you still have to enter the desktop?

I'm not familiar with Manjaro, what is Mint Display manager?

**Comment by davidedmundson** [comment]
No reply. Closing
