### ISSUE TITLE
sddm 0.14.0 xorg-server not found

### ISSUE THREAD

**Issue by dvc94ch** [sddm/sddm#679]
So after the update to 0.14.0 when I run sddm --example-config it looks like the sections [XDisplay] was renamed to [X11] and [WaylandDisplay] -> [Wayland]. sddm doesn't find the configuration under the new sections names. If the old section names are kept sddm --example-config doesn't show the current system values anymore.

**Comment by plfiorini** [comment]
This is similar to #680

**Comment by plfiorini** [comment]
Closing as duplicate of #680
