### ISSUE TITLE
sddm 0.14 creates ~/.local/share/sddm dir which results in empty themes in kcm_sddm

### ISSUE THREAD

**Issue by robby81** [sddm/sddm#682]
using openSUSE Tumbleweed sddm 0.14 (frameworks repo) after each logout-login a sddm-directory in home/.local/share/ is created which results in am empty theme pane in plasma 5.7 sddm_kcm

**Comment by plfiorini** [comment]
@davidedmundson sddm_kcm is yours please take a look, i don't have a clue about that

**Comment by davidedmundson** [comment]
Will do.

**Comment by plfiorini** [comment]
@davidedmundson thanks, since i'm clueless i don't know if the problem is here or sddm_kcm in case let me know

**Comment by plfiorini** [comment]
this is a sddm_kcm issue
