### ISSUE TITLE
Face files in /var/lib/AccountsService/icons is ignored

### ISSUE THREAD

**Issue by brmmm3** [sddm/sddm#683]
Please apply the patch attached to support the faces location for AccountsService.
Currently SDDM seems to have problems with user faces when home directories are encrypted.
In /var/lib/AccountsService/icons the face files can be found without .icon extension.

[accountsservice.diff.zip](https://github.com/sddm/sddm/files/448320/accountsservice.diff.zip)

**Comment by MartinBriza** [comment]
Can you please make this into a pull request so you're properly attributed in case it gets merged?
Seems the discussion around #525 has stalled so before or even if it gets merged, this could be a good substitute.

**Comment by davidedmundson** [comment]
FWIW, this is the approach I used in KDE code.  No point being overly complicated asking a daemon when we can copy the effectively same code in one line.

I would ask to make the path a cmake value though.
