### ISSUE TITLE
Greeter stops immediately 

### ISSUE THREAD

**Issue by bkchr** [sddm/sddm#687]
Hi,
I often have the problem when I'm starting my computer that greeter immediately stops. I have sddm  version 0.14.0-1 installed. To get sddm working, I have to restart it multiple times until sddm greeter works. 

Here is the log:

> Sep 03 10:53:36 BastiTowerLinux sddm[2127]: Greeter stopped.
> Sep 03 10:53:36 BastiTowerLinux sddm[2127]: Auth: sddm-helper exited successfully
> Sep 03 10:53:36 BastiTowerLinux sddm-helper[2368]: [PAM] Ended.
> Sep 03 10:53:36 BastiTowerLinux sddm-helper[2368]: pam_unix(sddm-greeter:session): session closed for user sddm
> Sep 03 10:53:36 BastiTowerLinux sddm-helper[2368]: [PAM] Closing session
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: Message received from daemon: HostName
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: Message received from daemon: Capabilities
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: QDBusConnection: name 'org.freedesktop.UDisks2' had owner '' but we thought it was ':1.23'
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: Adding view for "DP-1" QRect(1920,0 1920x1080)
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: file:///usr/share/sddm/themes/breeze/components/InfoPane.qml:54:22: Unable to assign [undefined] to int
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: Adding view for "DVI-I-1" QRect(0,0 1920x1080)
> Sep 03 10:53:36 BastiTowerLinux sddm-greeter[2424]: file:///usr/share/sddm/themes/breeze/components/InfoPane.qml:54:22: Unable to assign [undefined] to int
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: QObject: Cannot create children for a parent that is in a different thread.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Message received from greeter: Connect
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: Connected to the daemon.
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: inotify_add_watch("/usr/share/wayland-sessions") failed: "No such file or directory"
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: Reading from "/usr/share/xsessions/plasma.desktop"
> Sep 03 10:53:35 BastiTowerLinux sddm-greeter[2424]: Reading from "/usr/share/xsessions/plasma-mediacenter.desktop"
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Greeter session started successfully
> Sep 03 10:53:35 BastiTowerLinux systemd[2386]: pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
> Sep 03 10:53:35 BastiTowerLinux systemd[1]: Started Session c1 of user sddm.
> Sep 03 10:53:35 BastiTowerLinux systemd-logind[1755]: New session c1 of user sddm.
> Sep 03 10:53:35 BastiTowerLinux systemd[1]: Created slice User Slice of sddm.
> Sep 03 10:53:35 BastiTowerLinux sddm-helper[2368]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
> Sep 03 10:53:35 BastiTowerLinux sddm-helper[2368]: [PAM] returning.
> Sep 03 10:53:35 BastiTowerLinux sddm-helper[2368]: [PAM] Authenticating...
> Sep 03 10:53:35 BastiTowerLinux sddm-helper[2368]: [PAM] Starting...
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Adding cookie to "/var/run/sddm/{984fa823-886d-492a-a7d7-12a1613518a1}"
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Greeter starting...
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Socket server started.
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Socket server starting...
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Display server started.
> Sep 03 10:53:35 BastiTowerLinux sddm[2127]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
> Sep 03 10:53:33 BastiTowerLinux sddm[2127]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{984fa823-886d-492a-a7d7-12a1613518a1} -background none -noreset -displayfd 18 vt1
> Sep 03 10:53:33 BastiTowerLinux sddm[2127]: Display server starting...
> Sep 03 10:53:33 BastiTowerLinux sddm[2127]: Adding new display on vt 1 ...
> Sep 03 10:53:33 BastiTowerLinux sddm[2127]: Starting...
> Sep 03 10:53:33 BastiTowerLinux sddm[2127]: Initializing...

**Comment by CySlider** [comment]
I experience the same.

After reboot I have about a second to enter the password or I have to switch to tty1 and restart sddm which gives me another try to enter it quickly. Strangely on future invocations without rebooting (lock/suspend (NO S3)/switch user/etc.) everything is fine. (On my company workstation I experienced this also coming from S3 suspend. But this behavior is gone for now there, after an graphics driver update)

I appreciate the additional security to lock out any user that is not able to type fast, but I fear my wife will not like it as much ;-)

I experience this with Kubuntu 16.04 with KDE backport enabled as well as a freshly installed Kubuntu 17.04 or 17.10 beta. 
In fact the Kubuntu 16.04 was working fine unchanged in my previous build, which makes me believe this might be related to problems with Ryzen X1800. But neither disabling SMT nor Opcache improved things. And the system is stable beside this quirk. 
I have a Nvidia GTX 970, which worked fine in the previous build. But if I replace it with my other older Nvidia Quadro, this problem is gone as well.

Additional behavioral observations:

* After the second, the screen seems frozen. No courser blinking in input field. No mouse cursor (none showing at all, not only stuck)
* When switching to tty1 and back to tty7 screens are black
* In the moment of changing to tty1 I see the input cursor in the password field blink again before the switch to tty1 happens

My assumption is that the graphics output dies (And comes right back when pressing alt+f1). Maybe inputting the password would still work if I could focus an input field as other bugs reported suggest. But I can't without seeing the mouse pointer.

My setup:

Ryzen X1800
16Gb DDR3200
Nvidia GTI 970 with nvidia-384 driver
EVO960 SSD as system
3 Monitors (2 HD and an 4K)
Steelseries Apex Keyboard
sddm version : 0.14.0-4ubuntu1
kubuntu: 17.10 Beta 1 / 16.04

My logs

> ==== Boot finishes and first SDDM screen shows and freezes ====
> 24.09.2017 12:22:33:710	systemd	Startup finished in 17ms.
> 24.09.2017 12:22:33:710	systemd	Started User Manager for UID 119.
> 24.09.2017 12:22:33:717	sddm-greeter	High-DPI autoscaling Not Enabled
> 24.09.2017 12:22:33:726	sddm-greeter	inotify_add_watch("/usr/share/wayland-sessions") failed: "No such file or directory"
> 24.09.2017 12:22:33:770	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:33:792	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffc19488ab0), parent's thread is QThread(0x55b5d77cfae0), current thread is QThread(0x55b5d783c700)
> 24.09.2017 12:22:33:792	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffc19488ab0), parent's thread is QThread(0x55b5d77cfae0), current thread is QThread(0x55b5d783c700)
> 24.09.2017 12:22:33:792	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffc19488ab0), parent's thread is QThread(0x55b5d77cfae0), current thread is QThread(0x55b5d783c700)
> 24.09.2017 12:22:33:792	sddm-greeter	QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> 24.09.2017 12:22:33:793	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffc19488ab0), parent's thread is QThread(0x55b5d77cfae0), current thread is QThread(0x55b5d783c700)
> 24.09.2017 12:22:33:852	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffc19488ab0), parent's thread is QThread(0x55b5d77cfae0), current thread is QThread(0x55b5d783c700)
> 24.09.2017 12:22:33:852	sddm-greeter	QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> 24.09.2017 12:22:33:873	sddm-greeter	Cannot watch QRC-like path ":/icons/hicolor/index.theme"
> 24.09.2017 12:22:33:919	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 24.09.2017 12:22:33:942	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:33:973	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 24.09.2017 12:22:33:989	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:34:027	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 
> ==== I beleive here I switch to tty1 ====
> 24.09.2017 12:22:37:265	sddm-helper	pam_unix(sddm-greeter:session): session closed for user sddm
> 24.09.2017 12:22:37:269	systemd-logind	Removed session 5.
> 24.09.2017 12:22:37:273	systemd	Stopping User Manager for UID 119...
> 24.09.2017 12:22:37:273	systemd	Stopped target Default.
> 24.09.2017 12:22:37:274	systemd	Stopped target Basic System.
> 24.09.2017 12:22:37:274	systemd	Stopped target Timers.
> 24.09.2017 12:22:37:274	systemd	Stopped target Paths.
> 24.09.2017 12:22:37:275	systemd	Stopped target Sockets.
> 24.09.2017 12:22:37:275	systemd	Reached target Shutdown.
> 24.09.2017 12:22:37:275	systemd	Starting Exit the Session...
> 24.09.2017 12:22:37:281	systemd	Received SIGRTMIN+24 from PID 4356 (kill).
> 24.09.2017 12:22:37:300	systemd	pam_unix(systemd-user:session): session closed for user sddm
> 24.09.2017 12:22:37:301	systemd	Stopped User Manager for UID 119.
> 24.09.2017 12:22:37:301	systemd	Removed slice User Slice of sddm.
> 24.09.2017 12:22:41:813	acpid	client 4314[0:0] has disconnected
> 24.09.2017 12:22:42:047	polkitd(authority=local)	Registered Authentication Agent for unix-process:4357:11358 (system bus name :1.45 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8)
> 
> ==== I restart SDDM. This time I manage to enter password in time ====
> 24.09.2017 12:22:47:127	polkitd(authority=local)	Operator of unix-process:4357:11358 successfully authenticated as unix-user:cyslider to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.46 [systemctl restart sddm.service] (owned by unix-user:cyslider)
> 24.09.2017 12:22:47:128	systemd	Stopping Simple Desktop Display Manager...
> 24.09.2017 12:22:47:128	sddm	Signal received: SIGTERM
> 24.09.2017 12:22:52:153	kernel	nvidia-modeset: Freed GPU:0 (GPU-04f8f361-da53-e548-8af5-954cbdadec14) @ PCI:0000:0e:00.0
> 24.09.2017 12:22:52:178	nvidia-persistenced	Received signal 15
> 24.09.2017 12:22:52:179	nvidia-persistenced	Socket closed.
> 24.09.2017 12:22:52:179	systemd	Stopping NVIDIA Persistence Daemon...
> 24.09.2017 12:22:52:179	nvidia-persistenced	PID file unlocked.
> 24.09.2017 12:22:52:179	nvidia-persistenced	PID file closed.
> 24.09.2017 12:22:52:179	nvidia-persistenced	The daemon no longer has permission to remove its runtime data directory /var/run/nvidia-persistenced
> 24.09.2017 12:22:52:179	nvidia-persistenced	Shutdown (4320)
> 24.09.2017 12:22:52:181	systemd	Stopped NVIDIA Persistence Daemon.
> 24.09.2017 12:22:52:193	systemd	Stopped Simple Desktop Display Manager.
> 24.09.2017 12:22:52:194	systemd	Starting Detect the available GPUs and deal with any system changes...
> 24.09.2017 12:22:52:196	gpu-manager	/etc/modprobe.d is not a file
> 24.09.2017 12:22:52:197	gpu-manager	/etc/modprobe.d is not a file
> 24.09.2017 12:22:52:199	gpu-manager	/etc/modprobe.d is not a file
> 24.09.2017 12:22:52:201	gpu-manager	/etc/modprobe.d is not a file
> 24.09.2017 12:22:52:205	gpu-manager	/etc/modprobe.d is not a file
> 24.09.2017 12:22:52:213	gpu-manager	update-alternatives: Fehler: keine Alternativen für x86_64-linux-gnu_gfxcore_conf
> 24.09.2017 12:22:52:214	systemd	Started Detect the available GPUs and deal with any system changes.
> 24.09.2017 12:22:52:215	systemd	Starting Simple Desktop Display Manager...
> 24.09.2017 12:22:52:216	systemd	Started Simple Desktop Display Manager.
> 24.09.2017 12:22:52:218	polkitd(authority=local)	Unregistered Authentication Agent for unix-process:4357:11358 (system bus name :1.45, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8) (disconnected from bus)
> 24.09.2017 12:22:52:244	systemd	Starting NVIDIA Persistence Daemon...
> 24.09.2017 12:22:52:246	nvidia-persistenced	Verbose syslog connection opened
> 24.09.2017 12:22:52:246	systemd	Started NVIDIA Persistence Daemon.
> 24.09.2017 12:22:52:246	nvidia-persistenced	Now running with user ID 122 and group ID 129
> 24.09.2017 12:22:52:246	nvidia-persistenced	Started (4422)
> 24.09.2017 12:22:52:957	nvidia-persistenced	device 0000:0e:00.0 - registered
> 24.09.2017 12:22:52:957	nvidia-persistenced	Local RPC service initialized
> 24.09.2017 12:22:52:961	kernel	nvidia-modeset: Allocated GPU:0 (GPU-04f8f361-da53-e548-8af5-954cbdadec14) @ PCI:0000:0e:00.0
> 24.09.2017 12:22:53:194	acpid	client connected from 4416[0:0]
> 24.09.2017 12:22:53:194	acpid	1 client rule loaded
> 24.09.2017 12:22:53:746	sddm-helper	pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
> 24.09.2017 12:22:53:749	systemd	Created slice User Slice of sddm.
> 24.09.2017 12:22:53:750	systemd	Starting User Manager for UID 119...
> 24.09.2017 12:22:53:751	systemd-logind	New session 7 of user sddm.
> 24.09.2017 12:22:53:751	systemd	Started Session 7 of user sddm.
> 24.09.2017 12:22:53:752	systemd	pam_unix(systemd-user:session): session opened for user sddm by (uid=0)
> 24.09.2017 12:22:53:773	systemd	Reached target Sockets.
> 24.09.2017 12:22:53:773	systemd	Reached target Paths.
> 24.09.2017 12:22:53:773	systemd	Reached target Timers.
> 24.09.2017 12:22:53:774	systemd	Reached target Basic System.
> 24.09.2017 12:22:53:774	systemd	Reached target Default.
> 24.09.2017 12:22:53:774	systemd	Startup finished in 18ms.
> 24.09.2017 12:22:53:774	systemd	Started User Manager for UID 119.
> 24.09.2017 12:22:53:780	sddm-greeter	High-DPI autoscaling Not Enabled
> 24.09.2017 12:22:53:789	sddm-greeter	inotify_add_watch("/usr/share/wayland-sessions") failed: "No such file or directory"
> 24.09.2017 12:22:53:835	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:53:856	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffd0a055e70), parent's thread is QThread(0x55cf4e449ae0), current thread is QThread(0x55cf4e4b6700)
> 24.09.2017 12:22:53:857	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffd0a055e70), parent's thread is QThread(0x55cf4e449ae0), current thread is QThread(0x55cf4e4b6700)
> 24.09.2017 12:22:53:857	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffd0a055e70), parent's thread is QThread(0x55cf4e449ae0), current thread is QThread(0x55cf4e4b6700)
> 24.09.2017 12:22:53:857	sddm-greeter	QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> 24.09.2017 12:22:53:857	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffd0a055e70), parent's thread is QThread(0x55cf4e449ae0), current thread is QThread(0x55cf4e4b6700)
> 24.09.2017 12:22:53:915	sddm-greeter	QObject: Cannot create children for a parent that is in a different thread.
> (Parent is SDDM::GreeterApp(0x7ffd0a055e70), parent's thread is QThread(0x55cf4e449ae0), current thread is QThread(0x55cf4e4b6700)
> 24.09.2017 12:22:53:916	sddm-greeter	QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> 24.09.2017 12:22:53:937	sddm-greeter	Cannot watch QRC-like path ":/icons/hicolor/index.theme"
> 24.09.2017 12:22:53:979	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 24.09.2017 12:22:54:002	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:54:039	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 24.09.2017 12:22:54:050	sddm-greeter	Loading file:///usr/share/sddm/themes/breeze/Main.qml...
> 24.09.2017 12:22:54:087	sddm-greeter	file:///usr/share/sddm/themes/breeze/components/VirtualKeyboard.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed
> 24.09.2017 12:22:56:230	sddm-helper	pam_kwallet(sddm:auth): (null): pam_sm_authenticate
> 24.09.2017 12:22:56:287	sddm-helper	pam_kwallet5(sddm:auth): (null): pam_sm_authenticate
> 24.09.2017 12:22:56:287	sddm	Oops, secure memory pool already initialized
> 24.09.2017 12:22:56:333	sddm-helper	pam_kwallet(sddm:setcred): pam_kwallet: pam_sm_setcred
> 24.09.2017 12:22:56:333	sddm-helper	pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
> 24.09.2017 12:22:56:333	sddm-helper	pam_unix(sddm:session): session opened for user cyslider by (uid=0)
> 24.09.2017 12:22:56:335	systemd-logind	New session 9 of user cyslider.
> 24.09.2017 12:22:56:335	systemd	Started Session 9 of user cyslider.
> 
>

**Comment by Pointedstick** [comment]
Is this still happening to anyone with a recent version like 0.19?

**Comment by bkchr** [comment]
I have not experienced this anymore.

**Comment by Pointedstick** [comment]
Awesome, thanks.
