### ISSUE TITLE
can sddm connect to an existing X session 

### ISSUE THREAD

**Issue by fpemud** [sddm/sddm#690]
I access my system both locally and through RDP.
I may start the PC in the morning and leave it on the sddm interface.
Then when I'm home in the evening, I'd like to reuse the same X session I create through RDP in my office, simply by login from sddm.

In my experience, sddm always starts a new X session.

**Comment by davidedmundson** [comment]
It does.

You can mod the startup scripts to do this, it won't be supported upstream.
