### ISSUE TITLE
SDDM login fails with LUKS crypted home partition image

### ISSUE THREAD

**Issue by thommierother** [sddm/sddm#694]
My home partition is crypted with LUKS (home partiton as crypted image) according to https://www.suse.com/documentation/sled11/book_security/data/sec_cryptofs_y2_homes.html and https://en.opensuse.org/SDB:Encrypted_filesystems. The authentication is done with pam and the image decrypted upon login. 

After upgrade from OpenSUSE 13.2 to leap 42.1, login with kdm as displaymanager was still successful. I changed /etc/sysconfig/displaymanager from kdm to sddm, then the login failed. 

The entered PW string (***) is "visible", but after hitting "enter" the mouse icon changes to an "X" and no further pw entries are possible, although the X windows does not crash (at least i can not see a crash). 

I want to get rid of the old kdm and would welcome some ideas how to debug this...
Environment: OpenSUSE LEAP 42.1, plasmashell Version:

**Comment by vivianw** [comment]
I am also having the same issue.  I am running Arch Linux with plasma 5, using sddm as a window manager, my drives are also encrypted usnig dm-crypt.  I am thinking that this could be more of an issue with the graphics card as opposed to the encyption.

I have installed the xf86-video-intel video driver for my intel video card, but the problem persists!  I am still working on it and I will let you know if I am able to solve it.  I have also tried using slim instead of sddm and again I am having login issues.

**Comment by thommierother** [comment]
Confirmed for a fresh Install of OpenSuse Leap 42.2 with sddm-0.13.0-8.1.x86_64.
SDDM is not usable with crypted (LUKS) home partitions. A am still limited to kdm ;-(

**Comment by adamreichold** [comment]
As mentioned in the OpenSUSE bug tracker, I have the same issue with a clean install of Leap 42.2. Also of interest is that if I login on a virtual terminal before I try to login using SDDM, so that my encrypted home partition is already mounted, everything works as expected. I otherwise SDDM seems to hang indefinitely as described here.

A typical extract from the system journal for a failed login attempt looks like this
````
Nov 26 18:11:06 host systemd[1]: Starting X Display Manager...
Nov 26 18:11:06 host display-manager[1093]: /etc/vconsole.conf available
Nov 26 18:11:06 host display-manager[1093]: KEYMAP: de
Nov 26 18:11:06 host display-manager[1093]: Command: localectl set-keymap de
Nov 26 18:11:07 host.domain display-manager[1093]: I: Using systemd /usr/share/systemd/kbd-model-map mapping
Nov 26 18:11:07 host.domain display-manager[1093]: error: unexpectedly disconnected from boot status daemon
Nov 26 18:11:08 host.domain systemd[1]: display-manager.service: PID file /var/run/displaymanager.pid not readable (yet?) after start: No such file or directory
Nov 26 18:11:08 host.domain display-manager[1093]: Starting service sddm..done
Nov 26 18:11:08 host.domain sddm[1277]: Initializing...
Nov 26 18:11:08 host.domain systemd[1]: Started X Display Manager.
Nov 26 18:11:08 host.domain sddm[1277]: Starting...
Nov 26 18:11:08 host.domain sddm[1277]: Adding new display on vt 7 ...
Nov 26 18:11:08 host.domain sddm[1277]: Display server starting...
Nov 26 18:11:08 host.domain sddm[1277]: Running: /usr/bin/X -nolisten tcp -auth /run/sddm/{4a47ad16-c608-4cdf-bedf-dc7af5cabedc} -background none -noreset -displayfd
Nov 26 18:11:12 host.domain sddm[1277]: Running display setup script  "/etc/X11/xdm/Xsetup"
Nov 26 18:11:12 host.domain sddm[1277]: Display server started.
Nov 26 18:11:12 host.domain sddm[1277]: Socket server starting...
Nov 26 18:11:12 host.domain sddm[1277]: Socket server started.
Nov 26 18:11:12 host.domain sddm[1277]: Greeter starting...
Nov 26 18:11:12 host.domain sddm[1277]: Adding cookie to "/run/sddm/{4a47ad16-c608-4cdf-bedf-dc7af5cabedc}"
Nov 26 18:11:12 host.domain sddm-helper[1355]: [PAM] Starting...
Nov 26 18:11:12 host.domain sddm-helper[1355]: [PAM] Authenticating...
Nov 26 18:11:12 host.domain sddm-helper[1355]: [PAM] returning.
Nov 26 18:11:13 host.domain sddm-helper[1355]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Nov 26 18:11:13 host.domain sddm[1277]: Greeter session started successfully
Nov 26 18:11:14 host.domain sddm[1277]: Message received from greeter: Connect
Nov 26 18:12:13 host.domain sddm[1277]: Message received from greeter: Login
Nov 26 18:12:13 host.domain sddm[1277]: Reading from "/usr/share/xsessions/plasma5.desktop"
Nov 26 18:12:13 host.domain sddm[1277]: Session "/usr/share/xsessions/plasma5.desktop" selected, command: "/usr/bin/startkde"
Nov 26 18:12:13 host.domain sddm-helper[1423]: [PAM] Starting...
Nov 26 18:12:13 host.domain sddm-helper[1423]: [PAM] Authenticating...
Nov 26 18:12:13 host.domain sddm-helper[1423]: [PAM] Preparing to converse...
Nov 26 18:12:13 host.domain sddm-helper[1423]: [PAM] Conversation with 1 messages
Nov 26 18:12:13 host.domain sddm-helper[1423]: [PAM] returning.
Nov 26 18:12:13 host.domain sddm[1277]: Authenticated successfully
Nov 26 18:12:13 host.domain sddm-helper[1423]: pam_unix(sddm:session): session opened for user user by (uid=0)
Nov 26 18:12:15 host.domain sddm[1277]: Auth: sddm-helper exited successfully
Nov 26 18:12:15 host.domain sddm[1277]: Greeter stopped.
Nov 26 18:12:34 host.domain sddm[1277]: Session started
Nov 26 18:12:35 host.domain sddm[1277]: Auth: sddm-helper exited with 1
````

**Comment by tonyw99** [comment]
I also did a clean install fully dm-crypted including the root partition
using btrfs and I was able to use sddm to access plasma.  I think that the
packages that are installed for the X window system makes a difference as
to wheather or not sddm will work with the encrypted partition.

Here are the packages that I installed along with Plasma 5:

base packages: xorg xorg-xinit xorg-server plasma kdebase sddm sddm-kcm

Then some extras:
kf5 kf5-aids ttf-freefont qt4 qt5 gtk-engines gtk2 gtk3
gnome-themes-standard gnome-icon-theme pulseaudio pulseaudio-alsa

Then for networking:
networkmanager net-tools plasma-nm

Try this and see if it works for you.

**Comment by adamreichold** [comment]
@tonyw99 I do not think that full system encryption is comparable to this scenario: The root partition is mounted and fully accessible before SDDM is even started. In this case, the user's home directory resides within an encrypted image file which is mounted via a loopback device using a PAM module which is part of the login process itself.
Hence I do not think installing the mentioned packages will make any difference. I'd rather speculate that the `sddm-helper` process is not compatible with the non-standard login procedure due to the presence of the `pam_mount` PAM module.

**Comment by adamreichold** [comment]
My guess is also that #693 is basically the same issue...

**Comment by thommierother** [comment]
Can someone of the developers comment here if it makes sense to do a test with the latest SDDM 0.14.x instead of SDDM 0.13.x which is delivered in current Leap 42.2? Then I would plan this task for my spare time after christmas ...

**Comment by adamreichold** [comment]
As discussed in the OpenSUSE bug tracker, this is resolved by adjusting the SDDM-specific service configuration to include the `pam_mount`module using
```
pam-config --service sddm -a --mount
```

Hence this rather looks like a configuration issue and should probably be solved downstream in the distributions. I would therefore suggest closing this one.

**Comment by thommierother** [comment]
I'll do a test on leap 42.2, maybe we can file a a new bug for Opensuse, then as a configuration issue. The solution would be similar for all distros, I assume ?

**Comment by thommierother** [comment]
Test was successful on opensuse leap 42.2. We need an additional module in the pam config, for opensuse at /etc/pam.d/sddm, just add 

session  optional	pam_cryptpass.so
