### ISSUE TITLE
Possible security vulnerability 

### ISSUE THREAD

**Issue by shaygover** [sddm/sddm#695]
Hi everyone,

I think i found a way to bypass the login and get root permissions:
My system (Arch) froze so I switched to tty2 (cmd). I've entered my username and password but the system froze (It was stuck logging in). So I pressed Ctrl+C and got myself a root session (instead of a new login request).

Can you check this?

Shay

**Comment by plfiorini** [comment]
@shaygover I need to understand how is this related to SDDM.
So you switched to tty2 (a text console) and typed your credentials, managed to interrupt the login process with Ctrl+C and somehow got a root session?
Doesn't sound related to SDDM to me, it rather seem to be related to login or getty.

**Comment by shaygover** [comment]
Yes.

I thought that in KDE Plasma sddm is responsibly for the whole process. If not, just point me in the right direction.

**Comment by plfiorini** [comment]
@shaygover SDDM is not responsible for text consoles, you should report this to your distribution
