### ISSUE TITLE
sddm black screen on tv screen with AA_EnableHighDpiScaling

### ISSUE THREAD

**Issue by ynsta** [sddm/sddm#699]
SDDM stay on black screen when started on my TV screen with nvidia drivers 370.28-1.

After investigation I found that the screen geometry is wrongly reported by Qt when QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling); is used.

Removing this line in GreeterApp.cpp permits sddm to start properly.

with QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling): 
   Geometry: 0 0 -2147483648 x -2147483648
   Logical DPI: inf
   Logical DPI X: inf
   Logical DPI Y: inf
   Physical DPI: -4.7349e+07
   Physical DPI X: -3.40913e+07
   Physical DPI Y: -6.06068e+07
  Physical size: 1600 x 900 mm

without:
  Geometry: 0 0 1920 x 1080
  Logical DPI: 30.0029
  Logical DPI X: 29.9926
  Logical DPI Y: 30.0131
  Physical DPI: 30.48
  Physical DPI X: 30.48
  Physical DPI Y: 30.48
  Physical size: 1600 x 900 mm

It might be a Qt bug but It could be interesting to add a verification on sddm-greater to remove this flag when dpi are wrongly reported.

My Xorg is 1.18.4 and Qt is 5.7.0 from archlinux.

**Comment by plfiorini** [comment]
@ynsta What Xorg and Qt versions are you running?

**Comment by ynsta** [comment]
@plfiorini Xorg 1.18.4 and Qt 5.7.0 from arch linux.

**Comment by ynsta** [comment]
Maybe you should add a configuration option that permits to disable hidpi autoscale, it seems to be also the source of issue #692

**Comment by ynsta** [comment]
I made a pull request to add this option if you want.

https://github.com/sddm/sddm/pull/701

**Comment by plfiorini** [comment]
Good idea

**Comment by plfiorini** [comment]
Anyway that negative geometry is funny, looks like Qt cannot determine the screen resolution or Xorg reports an invalid one.
Just out of curiosity, @ynsta is the physical size correct?
