### ISSUE TITLE
sddm fails to switch to Plasma5

### ISSUE THREAD

**Issue by jobermayr** [sddm/sddm#712]
see: https://bugzilla.opensuse.org/show_bug.cgi?id=987487

Logfiles, dmesg and journalctl don't show any errors which help to debug.

**Comment by davidedmundson** [comment]
Switching back to the greeter means Plasma failed to start.
Not an SDDM bug.

**Comment by jobermayr** [comment]
> Not an SDDM bug.
How would you know that without knowing the real issue? "startx" starts a Plasma5 session. Maybe SDDM calls something incorrectly?
