### ISSUE TITLE
boot to wayland with autologin does not work

### ISSUE THREAD

**Issue by miku84** [sddm/sddm#720]
I am trying to boot to wayland with autologin (plasma 5.8), but it does not work, I get black screen.
What needs to be done to autologin to wayland? I edited /etc/sddm.conf:
# Session=plasma.desktop

Session=plasmawayland.desktop 
SessionCommand=/usr/share/sddm/scripts/wayland-session 
SessionDir=/usr/share/wayland-sessions

Thanks.

**Comment by miku84** [comment]
It could be also solved by selecting wayland at the sddm menu, in the autologin section. Could it be added to be able to select it from here?
![screenshot_20161220_203131](https://cloud.githubusercontent.com/assets/10956141/21365242/db16f0ce-c6f4-11e6-9e24-eb6e56c1ea82.png)

**Comment by miku84** [comment]
It does work now with the above sddm.conf configuration.

**Comment by nortexoid** [comment]
Doesn't work for me. I've tried selecting the wayland session from the kcm GUI, and it doesn't work. And I've manually added the required information into /etc/sddm.conf and it doesn't work. I'm running KDE Neon User Edition(Plasma 5.11.4). I just can't get sddm to autologin to a wayland session.
