### ISSUE TITLE
How to change lock screen background?

### ISSUE THREAD

**Issue by liangjs** [sddm/sddm#721]
I'm using kde plasma on Archlinux.
After recently updating sddm to 0.14.0-2, I found the breeze theme of sddm has changed. The background of login and lock screen has changed to a blue one. I've selected a new background using sddm-kcm. Then the login screen is now using my new background, but the lock screen background is still the blue one. How to change it?
![1014_2](https://cloud.githubusercontent.com/assets/10512425/19377570/c403de3e-9219-11e6-9ef3-d4c5c3b5d92d.jpg)

**Comment by eliasp** [comment]
The lockscreen is not provided by sddm, but by KDE Plasma.

Use:
→ System Settings
→ Desktop Behavior
→ Screen Locking
→ Wallpaper

**Comment by zyf0330** [comment]
It cannot solve the whole problem.
When I lock screen, above setting is effect. But if I logout and background is not changed.

**Comment by zyf0330** [comment]
I find a place to change. In system settings - Startup and Shutdown - Login Screen(SDDM), at right side, there is a background could be changed. But it doesn't work too.

**Comment by BlueManCZ** [comment]
> @zyf0330 there is a background could be changed. But it doesn't work too.

Yes, login-manager and lock-screen are two different services.

Do this for setup background in sddm login-manager:
1. Copy your <your_image> into `/usr/share/sddm/themes/breeze` folder.
2. In file `/usr/share/sddm/themes/breeze/theme.conf` specify this image in `background` variable.
```
[General]
background=/usr/share/sddm/themes/breeze/<your_image>
```
3. Restart sddm service or just restart computer.

**Comment by zyf0330** [comment]
Thanks, but it has been a settings got fixed.

**Comment by zyf0330** [comment]
@BlueManCZ You are right, but I must explain more.
May there is a theme.conf.user, and this will override settings in theme.conf.
And, besides `background` you must set `type=image` if this key exists.
Finally, you don't need to set `background` to absolute path

**Comment by BlueManCZ** [comment]
@zyf0330 Yes, that makes sense.
But I don't know, what application has effect to `theme.conf.user`. In my case this file is empty.
I'm glad I could help find a solution.

**Comment by zyf0330** [comment]
I just see it is there and test it. I don't know

**Comment by saleyn** [comment]
If you just want to change the `sddm`'s background to some solid color, use something like this:
```
$ cat /usr/share/sddm/themes/breeze/theme.conf
[General]
type=color
color=#242424
background=
```

**Comment by davidedmundson** [comment]
That only works on the breeze theme.

**Comment by james-h-dt** [comment]
Worked for me with breeze theme on Arch, altho needed to amend test command:

`sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze`
