### ISSUE TITLE
Plasma listed in sessions but not installed

### ISSUE THREAD

**Issue by urgle2203** [sddm/sddm#727]
When in SDDM, Plasma is listed in the sessions list but is not installed - I have no KDE packages and attempting to select KDE shows an error message: All shell packages missing. How can I remove Plasma from the list of sessions?

**Comment by davidedmundson** [comment]
Can you ls your /usr/share/cessions

**Comment by davidedmundson** [comment]
That should of course say /usr/share/xsessions

**Comment by plfiorini** [comment]
Closing for no reply, plus I doubt SDDM lists session that do not exist in /usr/share/xsessions or /usr/share/wayland-sessions
