### ISSUE TITLE
MPD client

### ISSUE THREAD

**Issue by Dietr1ch** [sddm/sddm#731]
How feasible is to control an mpd server from the lockscreen (also login if server is system-wide)?

**Comment by eliasp** [comment]
You might rather want to configure auto-login to launch a dedicated WM session which does exactly what you want in terms of media control.

Controlling MPD from the login screen is totally off sddm's scope.

**Comment by Dietr1ch** [comment]
I know that it seems really out of scope, but there are qml mpd clients, so I thought that maybe some themes can sport an mpd client, but I don't know if that is feasible or not, is it?

**Comment by plfiorini** [comment]
Don't know how MPD works, consider that SDDM runs with the sddm so you are limited, besides it's not its scope.
