### ISSUE TITLE
Add support for elogind

### ISSUE THREAD

**Issue by Yamakuzure** [sddm/sddm#741]
For users who do not want to run the full systemd suite, but do not want to patch sddm to use ck-launch-session either, https://github.com/wingo/elogind might be the solution.

Please have a look at the attached patch to enable elogind support in sddm.

[sddm-enable-elogind.patch.txt](https://github.com/sddm/sddm/files/586515/sddm-enable-elogind.patch.txt)

**Comment by mrueg** [comment]
@Yamakuzure you probably want to submit this as a pull request https://github.com/sddm/sddm/pulls

**Comment by Yamakuzure** [comment]
@mrueg Sorry for the late reply. For a pull request I'd had to fork the repo first. Isn't that a bit much for such a small addition? I do not think that I'll do much more with it in the future, although there *are* a few issues I'd like to have changed... (Like sddm not dropping back to the console when you hit the reboot or shutdown button, completely masking the shutdown output.)
Oh, very well, here we go...
