### ISSUE TITLE
Don't let SDDM have a timer when pressing Enter on an empty password box

### ISSUE THREAD

**Issue by Mayzie** [sddm/sddm#745]
Quite often I press the Enter key to wake up the screen, and it wakes up fast but the timer is counting down because it thinks I've entered an invalid password (thus making me unable to enter a password to login for a little while, which is annoying).

**Comment by eliasp** [comment]
Although I don't agree to change the behavior of the password input, it might make sense to act like some/most WMs here and dismiss the first key event when DPMS is active.

**Comment by mirh** [comment]
Could this timer have anything to do with me inserting password on wake, pressing enter, logging.. Then after a second everything gets back to sddm?

**Comment by BabyPuncher** [comment]
How about having the first key press raise the password input if it is not visible. I frequently run into scenarios where I'm on SDDM, and it's showing my wallpaper, so I press enter to wake it and it immediately treats that as a login attempt.

**Comment by Pointedstick** [comment]
Needs to be handled in the greeter theme itself. I will submit a merge request to do so for the Breeze theme.

**Comment by ciferkey** [comment]
I still see this behavior today. Can you point me to the merge request for the Breeze theme you opened so I can track the progress of it? Thanks!
