### ISSUE TITLE
Login and lock screens are missing artwork after failed update

### ISSUE THREAD

**Issue by fleskesvor** [sddm/sddm#757]
After a failed update due to an unreachable mirror, I'm having some issues with the login and lock screens. It's only a cosmetic issue, but it's very glaring, and I hope there's an easy fix for it. I'm not sure what information to provide, but currently my lock screen looks like this:

http://imgur.com/a/0B2yA

This is on Linux Mint 18 KDE version.

**Comment by davidedmundson** [comment]
1) that's a KDE theme not an sddm issue

2) that's the intended look in Plasma 5.7 with the plain blue background

**Comment by fleskesvor** [comment]
Oh, sorry. It looks really nice and clean with a background now. I just wish the default look was a bit better looking.
