### ISSUE TITLE
Black screen with amdgpu-pro (rx480)

### ISSUE THREAD

**Issue by alihakkidemiral** [sddm/sddm#759]
When install amdgpu-pro sddm not work only black screen not work ctrl+alt+f1-f2... . (kdeneon kernel 4.4)
i try with kernel 4.9 again black screen but this time ctrl+alt+f1 is work.
i added sddm to video group.
i login in ctrl+alt+f1 and sudo sddm it work. But not start when pc opening.
there isnt problem with lightdm it start when pc opening.

sorry for bad english :cry:

**Comment by GomesMarcos** [comment]
I'm whit the same issue... :'(

**Comment by alihakkidemiral** [comment]
not problem anymore. install new linux-firmware (16.10)
http://packages.ubuntu.com/yakkety/linux-firmware
