### ISSUE TITLE
At first login, nothing is copied from /etc/skel

### ISSUE THREAD

**Issue by boospy** [sddm/sddm#769]
Hello, 

using here 0.13.0-1ubuntu5 in Kubuntu 16.04. When i try the first login with an user, nothing will be copied from /etc/skel. Is there an option for this?

Thanks a lot
Mario

**Comment by agaida** [comment]
thats not an sddm problem - skel will be copied at user creation time

**Comment by boospy** [comment]
Hello Agaida, 

thanks for the fast reply. Yes skel will copied at user creation time, but only with an local user. But when you have an ldapuser, or created an user with command that not copy from skel, then you have an empty profile. 

I tested it with sshlogin, lxdm and gdm. On all 3 skel will be copied at the first login. I think this is an important feature for business with ldap surroundings.

Is there a way to enable it, maybe in pam.d/xxx ? 

Thanks :)

**Comment by bieberbau** [comment]
I can confirm. Tested it with ssh-login and xdm. With both skel will be copied at first login of AD-users.
But with sddm nothing is copied.

**Comment by boospy** [comment]
> We realized that with SSSD service and Realmd system DBus service.
Nice, will test sssd. I we use still nslcd for ldap.

**Comment by efeciftci** [comment]
I can confirm sddm can not copy /etc/skel into home directories of ldap accounts as well.

Tested on Kubuntu 16.04.3 (sddm 0.13.0-1) and KDE Neon User Edition (sddm 0.14.0-1). Both operating systems have been configured correctly for using LDAP. pam_mkhomedir.so is referenced in /etc/pam.d/common-session file as:
`session required pam_mkhomedir.so skel=/etc/skel umask=0022`

In both operating systems, contents of /etc/skel is copied to a newly created home directory when
1. logged on from tty (**both** for local and ldap accounts)
2. logged on from sddm (**only** for local accounts)

I've tested with Ubuntu 16.04.3 as well; contents of /etc/skel is successfully copied to a newly created home directory when logged into ldap accounts using lightdm (1.18.1).

**Comment by efeciftci** [comment]
I've found a workaround: it seems kwallet and mkhomedir can't get along together. By commenting out kwallet lines in /etc/pam.d/sddm and adding the required pam_mkhomedir.so line, SDDM started copying contents of /etc/skel into newly created home directories of LDAP users.

**Comment by boospy** [comment]
@efeciftci 
Very Thanks for this information. This is working really great :) 
Do you know what effects that have for kwallet?

**Comment by efeciftci** [comment]
@boospy 
Unfortunately kwallet is not needed in my installation, therefore I have no ideas if kwallet is affected or not. Maybe someone can better observe the outcome :)

**Comment by davidedmundson** [comment]
Ubuntu uses forked PAM files for everything. 
Can you attach them in full please.

**Comment by adocampo** [comment]
That was giving me a great headache. I'm migrating the entire city council desktop computers to Plasma from MATE and this issue was driving me crazy.

**Comment by orclex** [comment]
Thanks for the workaround, I was searching for this a long time!

Does this bug has to be fixed in sddm or in kwallet?

**Comment by cleary** [comment]
I've just run into this bug as well -

I've logged it upstream with kwallet-pam:
https://bugs.kde.org/show_bug.cgi?id=395947

Reason being, you can break this for any *dm by using pam_kwallet5.so in common-* configs (I use ubuntu, not sure how this applies for other distros)

**Comment by Vogtinator** [comment]
I'll copy my comment from the pam_kwallet report:

>This should be fixed in pam_kwallet 5.13.0 - not sure why it wasn't added to Plasma/5.12.
>
> Can you build pam_kwallet with https://cgit.kde.org/kwallet-pam.git/commit/?id=06760eed821f5383d03dc83a9a077a377ba39541 to confirm that it's fixed or try pam_kwallet 5.13.x? Should be relatively easy, pam_kwallet has no dependencies on other parts of Plasma.

As this is not an sddm issue, I'll close this now.
