### ISSUE TITLE
No way to obtain the position of the monitor from QML theme

### ISSUE THREAD

**Issue by Grief** [sddm/sddm#775]
Position of the monitor is erased in ScreenModel: `return QRect(QPoint(0, 0), d->screen->geometry().size());`

I'd like to modify a theme to set different wallpappers (parts of the big 5760x1080 one) on different screens. But with the latest code it's not possible to obtain the coordinates of the top left corner of the current screen to choose the correct wallpapper piece since that information is incapuslated in ScreenModel.cpp without a way to obtain it.

**Comment by davidedmundson** [comment]
There's an attached Screens object in QML
