### ISSUE TITLE
KDE PAM support provides kwallet empty password on autologin

### ISSUE THREAD

**Issue by polarathene** [sddm/sddm#780]
When using login requiring my password the wallet support to use the same password to unlock automatically works. However when having SDDM set to autologin the password provided to kwallet is empty. Is this intentional or a bug?

**Comment by eliasp** [comment]
@polarathene if you don't type a password (auto-login), there's no way a password could be passed to kwallet…
It's not like PAM would store your password in plain-text for auto-login purposes, it simply permits a login in defined cases.

**Comment by polarathene** [comment]
Ah, apologies I wasn't sure how autologin worked :) I guess a solution(albeit not secure) is to use a blank password for kwallet.
