### ISSUE TITLE
Unlock Plasma Session with SDDM in Wayland crash in Intel graphic

### ISSUE THREAD

**Issue by raneon** [sddm/sddm#790]
If I unlock my plasma session with SDDM in Wayland with a Intel graphic card results in a black screen. I need to go to an other terminal to restart the computer to continue working. SDDM is crashing silently.

**Comment by archderwelt** [comment]
Are you sure about :

> SDDM is crashing silently.

It looks like it's not SDDM that is crashing:
https://bugs.kde.org/show_bug.cgi?id=360931

**Comment by raneon** [comment]
This issue seems to be solved by KDE upstream.
