### ISSUE TITLE
Random backgrounds

### ISSUE THREAD

**Issue by rayanayar** [sddm/sddm#801]
Is there a way to show random backgrounds? For example from configured folder.

Unfortunately, plasma5 killed screensavers. It was very comfortably in previous versions when screensaver show random photos from PhotoAlbum folder.
Is there a way to add this function to sddm themes? At least show random background on start, or on lockscreen. Ideally - change background every minute.

**Comment by davidedmundson** [comment]
There is not.

**Comment by dango301** [comment]
I was able to do this with a custom script, so I thought I would share the steps in case anybody else is interested:


- This was a tricky one because sddm doesn't allow to just specify a path so that a random image is selected each time
- instead, I wrote a script that creates a symbolic link to a randomly selected image and gives it the same name -> sddm can read the same sym link but the sym link is overwritten every time with a link to a different randomly selected background image
- create a bash script, placed in `/usr/share/sddm/scripts/createRandomSymLinkToWallpaper.sh`:
	```bash
	#!/bin/bash

	# Get a random image file from the background image folder.
	IMAGE_FILE=$(find /usr/share/HDD/Backgrounds/All -type f | shuf -n 1)
	
	# Get the path to the sddm backgrounds folder.
	SDDM_BACKGROUNDS_FOLDER="/usr/share/sddm/themes/tokyo-night-sddm/Backgrounds"
	
	# Create a symbolic link to the random image file in the sddm backgrounds folder (overwrite with the force flag).
	ln -sf "$IMAGE_FILE" "$SDDM_BACKGROUNDS_FOLDER/randomlySelectedWallpaper"
	```
- to execute the script, I edited this file, that's run by sddm whenever the X session is closed: `/usr/share/sddm/scripts/Xstop`
	- instead, I could have done the same for `Xsetup` but I figured that I might shave off a few milliseconds at start up by actually changing the image on shutdown / logout instead of on startup
	- the file contents are:
		```bash
		#!/bin/sh
		# Xstop - run as root after stopping X
		
		sudo /usr/share/sddm/scripts/createRandomSymLinkToWallpaper.sh
		```
	- hint: make sure to provide the full path to the script; the relative path didn't work!
	- you can actually verify that this script is called in `/usr/lib/sddm/sddm.conf.d/default.conf` under "\[XDisplay\]", where `DisplayCommand=/usr/share/sddm/scripts/Xsetup` and the same for `Xstop` are called

**Comment by Vogtinator** [comment]
> This was a tricky one because sddm doesn't allow to just specify a path so that a random image is selected each time

SDDM itself doesn't, but themes can do whatever they want, including this.

**Comment by tomchiverton** [comment]
When I try to do this, I just get an all white background on the login screen

```
falken@frame:/usr/share/sddm/themes/breeze$ ls -laht|grep random ; file random
lrwxrwxrwx 1 root root   34 Feb  1 20:31 random -> /home/falken/My Backgrounds/random
random: symbolic link to /home/falken/My Backgrounds/random
falken@frame:/usr/share/sddm/themes/breeze$ 
```
```
falken@frame:/usr/share/sddm/themes/breeze$ ls -laht /home/falken/My\ Backgrounds/random  ; file /home/falken/My\ Backgrounds/random ; file  /home/falken/My\ Backgrounds/sci-fi/wingCommander/17359467_834145046733481_1410460193815825018_o.jpg
lrwxrwxrwx 1 falken falken 99 Jan 30 19:53 '/home/falken/My Backgrounds/random' -> '/home/falken/My Backgrounds/sci-fi/wingCommander/17359467_834145046733481_1410460193815825018_o.jpg'
/home/falken/My Backgrounds/random: symbolic link to /home/falken/My Backgrounds/sci-fi/wingCommander/17359467_834145046733481_1410460193815825018_o.jpg
/home/falken/My Backgrounds/sci-fi/wingCommander/17359467_834145046733481_1410460193815825018_o.jpg: JPEG image data, JFIF standard 1.02, aspect ratio, density 1x1, segment length 16, progressive, precision 8, 1280x720, components 3
falken@frame:/usr/share/sddm/themes/breeze$ 
```
