### ISSUE TITLE
SDDM will not build without PAM?  Installation notes wrong?

### ISSUE THREAD

**Issue by BrianA-MN** [sddm/sddm#804]
The basic sddm page under INSTALLATION states that sddm built with PAM and SystemD then greeter will use logind, and distributions without PAM and Systemd will need to add the sddm user to the video group.  That would mean that if PAM and systemd are NOT present on the build system the build would still occur.  However, the 0.13 and 0.14  CMakeList.txt has two lines, one that is an option to ENABLE_PAM and on the findpkg PAM line it indicates REQUIRED.  I'm not a programmer, but would like to install SDDM on my Slackware 14.2 64 bit with qt5.7.1, gcc 5.3.0, cmake 3.5.2,, and extra-cmake-modules 5.3.1, however when the build process gets to the line for findpkg PAM (PAM REQUIRED) the build stops because "PAM was not found".  So my question:  Is PAM now a requirement and the sddm main page INSTALLATION lines are incorrect?  

I've tried modifying the CMakeList.txt to ENABLE_PAM OFF in both the 0.13 and 0.14 releases, but always the same PAM not found error.  0.12 which doesn't have the ENABLE or REQUIRED statements builds to completion and installs without trouble.  So, my second question. What mods are required in the CMakeList.txt file to turnoff the PAM requirement, the two lines I've found or is it not possible to build without PAM? 

Thank you for the support.  I understand all the developers have PAM and SystemD on their development platforms.  What would really help me is to understand the  "C" programming calls and I'm simply not a programmer, just a Linux enthusiast.  

Thank you for the help and guidance.

**Comment by a17r** [comment]
Optional PAM build works fine. `find_package(PAM REQUIRED)` is inside a conditional `if(ENABLE_PAM)`, `ENABLE_PAM` option is `ON` by default, to switch it off you pass `-DENABLE_PAM=OFF` to cmake.

**Comment by BrianA-MN** [comment]
Thank you, but that solution did NOT work, see my original question.  I believe that although you pass the -DENABLE_PAM=OFF that the later REQUIRED statement ( I believe it is at line 73) in the CMakeList.txt overrides the passed parameter.

**Comment by a17r** [comment]
No, you're doing something wrong then. As I said, the REQUIRED statement is *within* the ENABLE_PAM conditional so it does not even get to that line if you passed the argument properly.

**Comment by BrianA-MN** [comment]
OK, I apologize the command must have been wrong or at the wrong point in my package build  the last time I tried..  I've modified my build script that includes the -DENABLE_PAM=OFF and it now will build to conclusion the 0.13.0 release src.  Thank you for getting back to me.  If I run in to other problems I'll start a new issue.  Cheers
