### ISSUE TITLE
System user "libvirt qemu" appears at login screen

### ISSUE THREAD

**Issue by Zhigalin** [sddm/sddm#816]
Same issue as here https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1667113

**Comment by Zhigalin** [comment]
QEMU, ceph, ifmail, netqmail and probably some other I don't know about are creating high-UID system users...
Maybe a filter for `shell=/bin/false` ?

**Comment by davidedmundson** [comment]
Then they shouldn't. 
There's a known convention for what UIDs are system or user. 

Note the cutoff UID between system and user is customisable in /etc/sddm.conf as Fedora starts them at different numbers.
