### ISSUE TITLE
sddm ignores the kdeglobals [KDE Action Restrictions] switch_user=false directive

### ISSUE THREAD

**Issue by cleary** [sddm/sddm#822]
Hi folks, 
I'm updating my kiosk style live images for Plasma/KDE 5 - one of the requirements I have is that the switch user option in the DM is disabled.

I'm working with the [Kiosk Keys documentation](https://userbase.kde.org/KDE_System_Administration/Kiosk/Keys) which says:

> switch_user
> defines whether user switching via kdm is allowed.

Obviously you are not kdm, but working through [some blog](http://blog.davidedmundson.co.uk/blog/display_managers_finale)s on the topic, the recommendations all point to sddm being the preferred DM for plasma5, hence this report. 

Thanks a lot -

**Comment by davidedmundson** [comment]
That kiosk key should stop plasma from calling switch user on sddm.

Sddm doesn't have to do anything.

Where exactly are you still having a switch user option?

**Comment by cleary** [comment]
Hi David, 
Thanks for the reply. It's in (at least) two places - 
1. The kickoff plasma widget -> Leave menu (I don't think this is your issue though)
2. The lock screen - which I assumed was an sddm issue based on the doco (I'm thinking that may be a mistake now though...)
I've got a screenshot - please let me know if I've got it wrong, and I'll go to the KDE guys:

![spectacle je7904](https://cloud.githubusercontent.com/assets/2577966/26045315/f4236dc6-398c-11e7-8ea4-4c52018a43e0.png)

**Comment by davidedmundson** [comment]
That's not sddm...

It's just the kde lockscreen is themed the same.

Let's follow this up on bugs.kde.org.
Can you post your full kiosk lines please.

**Comment by cleary** [comment]
Ah ok, my apologies -

This is the whole section from my kdeglobals:
```
[KDE Action Restrictions][$i] 
logout=false 
switch_user=false 
```
The logout=false directive is functional (which confirms the [KDE Action Restrictions] section is functional)

**Comment by cleary** [comment]
While we're going, I'm about to check the 

> start_new_session
> defines whether the user may start a second X session

directive

**Comment by cleary** [comment]
> Let's follow this up on bugs.kde.org.

P.P.S I'm assuming by this that you wanted to create the bug, if not I'll take care of it tomorrow ;)

**Comment by cleary** [comment]
Just for completeness, I'll post the solution here - I did a bit of digging on bugs.kde.org, found this post:
https://bugs.kde.org/show_bug.cgi?id=340097#c2

> **Martin Flöser 2015-02-10 09:05:04 UTC**
> I just investigated and conclude that the code is correct. These are actions and thus the correct restriction must be:
> 
> [KDE Action Restrictions][$i]
> action/start_new_session=false
> action/switch_user=false
> 
> At least under Plasma 5 with this action restriction in a global kdeglobas the lock screen does not offer new session or session switching. I assume the same should be the case on Plasma 4.

In short, it was just a syntax issue - thanks again for taking a look
