### ISSUE TITLE
SDDM remains in the background after i3wm login

### ISSUE THREAD

**Issue by StanczakDominik** [sddm/sddm#830]
I couldn't find the issue here.
Once I log in via SDDM to i3wm, the SDDM greeter remains in the background and stays there.
There's an issue on arch linux wiki open for this, which I could not find here:

https://bbs.archlinux.org/viewtopic.php?id=213468

I'd like to help debug this however I can.

**Comment by waphire** [comment]
Same problem here with xmonad. Been facing it since the past year. The only solution I have found is to switch to another DM like LightDM.

**Comment by davidedmundson** [comment]
Probably means i3wm doesn't blank the root window.

Try running xsetroot -color and see if that fixes it, if so you can put it in your Xsessions.d folder.

**Comment by davidedmundson** [comment]
Didn't hear back. Closing

**Comment by tehcyanz** [comment]
I had the same issue, `xsetroot -grey` fixed it.

**Comment by cindrmon** [comment]
> I had the same issue, `xsetroot -grey` fixed it.

which config file do you put that?
