### ISSUE TITLE
SDDM's Breeze theme should use the the standard plasma background image "Next"

### ISSUE THREAD

**Issue by Pointedstick** [sddm/sddm#831]
Linux distro: Kubuntu 17.04
SDDM version

SDDM's default Breeze theme uses a boring plain blue background. This doesn't provide a very expressive visual experience. The screen locker matches the desktop by using use the Next wallpaper at `/usr/share/wallpapers/Next` by default, and it looks great. SDDM's Breeze theme would be improved by doing the same thing.

**Comment by davidedmundson** [comment]
1) That's up to Plasma not SDDM
2) Plasma's visual design group decided to do the blue background deliberately.

**Comment by Pointedstick** [comment]
Ok, thanks.

https://bugs.kde.org/show_bug.cgi?id=381407
