### ISSUE TITLE
Calling shutdown directly, without *kit.

### ISSUE THREAD

**Issue by lebarondemerde** [sddm/sddm#835]
Hello,

Is there a way to make sddm call the shutdown command directly? I mean, without relying on *kit?

I am not a programmer or something, but I am willing to use sddm on FreeBSD where it is possible to shutdown/reboot without root privileges if the user is in the 'operator' group.

I did a blind test adding the sddm user to that group but does not work. However I could shutdown/reboot from KDE directly, what I am using on that test VM - _my user was in the operator group already_.

I currently use 'slim + i3wm' on my "real" machine, and I do not even have anything *kit or hal installed, and I would not like to have to install those just to have functional shutdown/reboot at the login manger. :-)

 I would like to swap slim for sddm.

Thanks!

**Comment by MartinBriza** [comment]
Hey,
there's the HaltCommand configuration option. By default, it contains a call to systemctl.

**Comment by lebarondemerde** [comment]
Hmm. It is already configured in there. It should be something related with the implementation yet.

Thanks!
