### ISSUE TITLE
User face pixellised

### ISSUE THREAD

**Issue by ArchangeGabriel** [sddm/sddm#840]
I’m using the same picture for screen locking and SDDM, and it shows heavily pixellised in SDDM. Is that expected/is there anything I can do about it?

**Comment by surajmandalcell** [comment]
same problem here

**Comment by davidedmundson** [comment]
Which theme?

**Comment by surajmandalcell** [comment]
https://github.com/surajmandalcell/Elegant-sddm, i forked it and currently am working on it. the original one also had problem so it not my fault i guess.

**Comment by plfiorini** [comment]
This is a theme specific issue, not SDDM's fault.
