### ISSUE TITLE
DESKTOP_SESSION is inconsistent with other display managers

### ISSUE THREAD

**Issue by adrienbeau** [sddm/sddm#852]
Investigating why my `XDG_DATA_DIRS` environment variable appears so broken:

    $ echo $XDG_DATA_DIRS
    /usr/share//usr/share/xsessions/plasma:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop

I discovered that, on Ubuntu, it is computed in part from DESKTOP_SESSION, in the `/etc/X11/Xsession.d/60x11-common_xdg_path` script. It boils down to:

    XDG_CONFIG_DIRS=/etc/xdg/xdg-"$DESKTOP_SESSION":/etc/xdg
    XDG_DATA_DIRS=/usr/share/"$DESKTOP_SESSION":/usr/local/share/:/usr/share/

Apparently other display managers and/or distros put a basename in DESKTOP_SESSION, such as `gnome`, `kde` or `kde-plasma` (though it is not clear who is doing what). sddm explicitly uses an absolute path (in Session::setTo() and then Session::desktopSession()), and seems to be the only one doing so. Is there a reason why? Should it align with others?

Some links:
* Ubuntu bug report from 2011 that led to the creation of the script: https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/804734
* Ubuntu bug report from 2017 that complains about the content of the variable: https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1668722
* Similar bug report for KDE neon: https://bugs.kde.org/show_bug.cgi?id=366180

**Comment by tsimonq2** [comment]
This is likely an X bug. As explained on the Ubuntu bug report, it's an Ubuntu-specific script that resides in src:xorg that's setting things like this.

**Comment by tsimonq2** [comment]
Here's the patch that fixed this in Ubuntu:
```
--- a/src/common/Session.cpp
+++ b/src/common/Session.cpp
@@ -106,7 +106,7 @@ namespace SDDM {
 
     void Session::setTo(Type type, const QString &_fileName)
     {
-        QString fileName(_fileName);
+        QString fileName = _fileName;
         if (!fileName.endsWith(s_entryExtention))
             fileName += s_entryExtention;
 
@@ -160,6 +160,8 @@ namespace SDDM {
 
         file.close();
 
+        m_fileName = fileName;
+
         m_type = type;
         m_valid = true;
     }
```

You're free to grab it and tweak it under any terms you'd like provided this issue is referenced.

**Comment by Vogtinator** [comment]
There can be sessions with the same filename in both wayland and X session directories. How would `$DESKTOP_SESSION` differentiate those? If it's not supposed to do that, this can be changed to only write the base name into `$DESKTOP_SESSION`.

The patch above is broken btw, it changes the semantics of `Session::fileName()`, which other components rely on (https://github.com/sddm/sddm/issues/1319).
