### ISSUE TITLE
Want to ask always for username and password

### ISSUE THREAD

**Issue by adocampo** [sddm/sddm#854]
I'm setting up a corporate linux workstation. On the installation I've set up a normal pam account and the users are coming from an AD.

My problem is every time I turn on the computer or re-login, the local account is shown instead the last user succesfully logged in (on /var/lib/sddm/state.conf apperas the user I want to appear) or at least no user at all, forcing my users to enter their logon.

I tried with HideUsers=localuser, but then, the logon screen ask for a password and well, the logon users is indeed hidden, but that's not what is desirable.

How can I force sddm to show last logged in user to be shown instead the local account? If that is not possible, how can I force to ask both username and password?

Best, 
Angel

**Comment by Renderke** [comment]
Did you try RememberLastUser=false? Then SDDM should ask you at least everytime for username and password. Thats what I chose for our company.
If the local Users have distinct UIDS, try to avoid them with MinimumUid=... Or if they are not many, enter them  comma seperated in  HideUsers=.. See more in the manpage: http://manpages.ubuntu.com/manpages/zesty/man5/sddm.conf.5.html
Greetings, Nina

**Comment by mmiat** [comment]
i've the same problem, I can't reinsert username everytime, how to put a default username?

**Comment by adocampo** [comment]
@mmiat according the Arch wiki, you can generate a default sddm.conf file with
`sddm --example-config > /etc/sddm.conf`
Inside this sddm.conf file you can see the [Autologin] section perhaps you miss the "Relogin=true" directive.

@Renderke No, it doesn't works. I tried all the combinations of RememberLastSession and RemberLastUser, but sddm insists in showing to me the local user I used on the installation. Not even deleting that user and letting only root and the Active Directory users sddm works as I want. It always shows a password field (with no user) and I must to choose first "login with another user" to be able to insert a username and a password.

**Comment by Pointedstick** [comment]
Needs to be done in individual themes. The Breeze themes now offers this. If you have further issues, please file bugs on the theme itself.
