### ISSUE TITLE
SDDM core dump

### ISSUE THREAD

**Issue by tSte** [sddm/sddm#857]
I just checked journal and found this coredump. I am not sure when it happened. I am on ArchLinux (4.12.4-1-ARCH), SDDM 0.14.0.

```
systemd-coredump[443]: Process 394 (sddm) of user 0 dumped core.
                                           
                                           Stack trace of thread 394:
                                           #0  0x00007fe85384d57d _ZN7QObject7connectEPKS_PKcS1_S3_N2Qt14ConnectionTypeE (libQt5Core.so.5)
                                           #1  0x0000000000434cb5 _ZN4SDDM4Auth7Private9setSocketEP12QLocalSocket (sddm)
                                           #2  0x0000000000436822 _ZN4SDDM4Auth12SocketServer19handleNewConnectionEv (sddm)
                                           #3  0x00007fe853847786 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                           #4  0x00007fe853d78a18 n/a (libQt5Network.so.5)
                                           #5  0x00007fe853847786 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                           #6  0x00007fe8538540a9 _ZN15QSocketNotifier9activatedEiNS_14QPrivateSignalE (libQt5Core.so.5)
                                           #7  0x00007fe853854484 _ZN15QSocketNotifier5eventEP6QEvent (libQt5Core.so.5)
                                           #8  0x00007fe853817bb2 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                           #9  0x00007fe853872cfe n/a (libQt5Core.so.5)
                                           #10 0x00007fe8500f0a57 g_main_context_dispatch (libglib-2.0.so.0)
                                           #11 0x00007fe8500f0c88 n/a (libglib-2.0.so.0)
                                           #12 0x00007fe8500f0d1c g_main_context_iteration (libglib-2.0.so.0)
                                           #13 0x00007fe853872061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                           #14 0x00007fe853815ffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                           #15 0x00007fe85381f048 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                           #16 0x000000000041cab1 main (sddm)
                                           #17 0x00007fe852c634ca __libc_start_main (libc.so.6)
                                           #18 0x000000000041cdaa _start (sddm)
                                           
                                           Stack trace of thread 416:
                                           #0  0x00007fe852d26e9d poll (libc.so.6)
                                           #1  0x00007fe8500f0c09 n/a (libglib-2.0.so.0)
                                           #2  0x00007fe8500f0d1c g_main_context_iteration (libglib-2.0.so.0)
                                           #3  0x00007fe853872061 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                           #4  0x00007fe853815ffb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                           #5  0x00007fe85362f40e _ZN7QThread4execEv (libQt5Core.so.5)
                                           #6  0x00007fe85489c396 n/a (libQt5DBus.so.5)
                                           #7  0x00007fe85363415b n/a (libQt5Core.so.5)
                                           #8  0x00007fe852a2c049 start_thread (libpthread.so.0)
                                           #9  0x00007fe852d30f0f __clone (libc.so.6)

```

**Comment by enghamid** [comment]
I have the same issue.


    Feb 01 11:45:18 kaicox systemd-coredump[809]: Process 772 (sddm) of user 0 dumped core.
                                              
                                              Stack trace of thread 772:
                                              #0  0x00007f5fd290ef25 raise (libc.so.6)
                                              #1  0x00007f5fd28f8897 abort (libc.so.6)
                                              #2  0x00007f5fd2d2e96c _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                                              #3  0x0000559611eb40f5 n/a (sddm)
                                              #4  0x0000559611ef8ebe _ZN4SDDM4Seat13createDisplayEi (sddm)
                                              #5  0x0000559611ef9102 _ZN4SDDM4SeatC2ERK7QStringP7QObject (sddm)
                                              #6  0x0000559611efb0c1 _ZN4SDDM11SeatManager10createSeatERK7QString (sddm)
                                              #7  0x0000559611efbee2 n/a (sddm)
                                              #8  0x00007f5fd2f7a3be n/a (libQt5Core.so.5)
                                              #9  0x0000559611efa130 _ZN4SDDM10LogindSeat19canGraphicalChangedEb (sddm)
                                              #10 0x0000559611efa443 n/a (sddm)
                                              #11 0x00007f5fd2f7a3be n/a (libQt5Core.so.5)
                                              #12 0x00007f5fd3937a10 _ZN23QDBusPendingCallWatcher8finishedEPS_ (libQt5DBus.so.5)
                                              #13 0x00007f5fd3937b11 n/a (libQt5DBus.so.5)
                                              #14 0x00007f5fd2f721ba _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                                              #15 0x00007f5fd2f44890 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                              #16 0x00007f5fd2f47116 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
                                              #17 0x00007f5fd2f9d6f4 n/a (libQt5Core.so.5)
                                              #18 0x00007f5fd1b0239e g_main_context_dispatch (libglib-2.0.so.0)
                                              #19 0x00007f5fd1b041b1 n/a (libglib-2.0.so.0)
                                              #20 0x00007f5fd1b041f1 g_main_context_iteration (libglib-2.0.so.0)
                                              #21 0x00007f5fd2f9cd40 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                              #22 0x00007f5fd2f4341c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                              #23 0x00007f5fd2f4b426 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                              #24 0x0000559611eb78da main (sddm)
                                              #25 0x00007f5fd28fa153 __libc_start_main (libc.so.6)
                                              #26 0x0000559611eb7bde _start (sddm)
                                              
                                              Stack trace of thread 794:
                                              #0  0x00007f5fd29c79ef __poll (libc.so.6)
                                              #1  0x00007f5fd1b04120 n/a (libglib-2.0.so.0)
                                              #2  0x00007f5fd1b041f1 g_main_context_iteration (libglib-2.0.so.0)
                                              #3  0x00007f5fd2f9cd40 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                              #4  0x00007f5fd2f4341c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                              #5  0x00007f5fd2d68e62 _ZN7QThread4execEv (libQt5Core.so.5)
                                              #6  0x00007f5fd38d3b28 n/a (libQt5DBus.so.5)
                                              #7  0x00007f5fd2d69fd6 n/a (libQt5Core.so.5)
                                              #8  0x00007f5fd28ba4cf start_thread (libpthread.so.0)
                                              #9  0x00007f5fd29d22d3 __clone (libc.so.6)
