### ISSUE TITLE
No signal when display is connected to integrated gpu

### ISSUE THREAD

**Issue by xzz53** [sddm/sddm#873]
I have a desktop with two GPUs: integrated IntelHD and Nvidia Geforce GTX 1080. Recently I had to connect my display (VGA connector) to IntelHD, and found out that SDDM greeter doesn't show up. Instead I get "No signal" text on my display, and then it goes to standby mode. After some experimentation, I discovered that starting KDE directly via startx (I have "exec startkde" in my .xinitrc) works fine. I also tried a DVI-D display, with exactly same results. I should note that BIOS, grub and framebuffer console show up on the correct display. Blacklisting nvidia kernel module is not an option for me, as I use Nvidia GPU for CUDA computations. My Linux ditribution is Arch, and the versions of relevant packages are as following:

local/sddm 0.14.0-3
local/xorg-server 1.19.3-3 (xorg)
local/linux 4.12.8-2 (base)

All logs and configs I find relevant are attached to this issue. I can provide any additional information upon request.

[lspci.txt](https://github.com/sddm/sddm/files/1263102/lspci.txt)
[sddm.conf.txt](https://github.com/sddm/sddm/files/1263103/sddm.conf.txt)
[sddm.log.txt](https://github.com/sddm/sddm/files/1263104/sddm.log.txt)
[Xorg.0.log.sddm.txt](https://github.com/sddm/sddm/files/1263099/Xorg.0.log.sddm.txt)
[Xorg.0.log.startx.txt](https://github.com/sddm/sddm/files/1263100/Xorg.0.log.startx.txt)
[xrandr.startx.txt](https://github.com/sddm/sddm/files/1263101/xrandr.startx.txt)

**Comment by grahamperrin** [comment]
@xzz53 please: is this still an issue?

**Comment by xzz53** [comment]
I'm afraid I can't replicate the mentioned setup any more, so closing this.
