### ISSUE TITLE
SDDM 0.15.0 doesnt source /etc/profile.d/* anymore

### ISSUE THREAD

**Issue by gabm** [sddm/sddm#879]
After the upgrade on Arch it seems that my files under `/etc/profile.d/..` don't get sourced anymore... various environment variabled don't work anymore. A downgrade to 0.14.0 helped...

**Comment by eliasp** [comment]
Why should it source `/etc/profile.d/*`?
- For the service, it's the service manager's job to provide an appropriate environment.
- For the user, it's PAM or the session manager's job to provide the environment

**Comment by gabm** [comment]
hmm didn't know that.. but its actually a fact, that it stopped working after thee upgrade and continue to work after the downgrade of sddm .. that's rather strange?!

You say its PAM's/session-managers job: where can I try to find whats going on? Is systemd the place to check?

**Comment by davidedmundson** [comment]
@eliasp Actually we did (and still do) explicitly source /etc/profile.
(what a DM should and shouldn't do isn't very well defined TBH)

We do this is in your Xsession script.
This is normally /usr/share/sddm/scripts/Xsession

but can be overriden by the SessionCommand= in your config.

Between 0.14 and 0.15 there was some added support for esoteric shells, possibly relevant.
If you could try 0.15 with the Xsession script from 0.14 that'd be helpful,

**Comment by gabm** [comment]
@davidedmundson thank you, that was really helpful..

In fact I am using fish and it seems that in my case the profile.d stuff is not parsed. Temporarily changing back the default shell to bash resolves the problem in 0.15. However, using fish shell, `/etc/profile` is not read as expected.. 

Is this a regression in sddm or is my configuration faulty?

**Comment by davidedmundson** [comment]
It's a regression.
You can see what's wrong about 7a27e1a4ad291725c3905f1e2e18d0fcaf7943c5 and try and fix it.

It's weird that it went worse *after* someone added fish support.

**Comment by davidedmundson** [comment]
Oh, in that commit you can see it clearly not sourcing
       [ -f /etc/profile ] && . /etc/profile 

which the default unhandled shell (line 42) used to do

Can you test if we need to source $HOME/.profile ?

**Comment by gabm** [comment]
well I relied that it would be sourced too, yes - but I'm not an expert on shells so i don't really know whether all this should be done... sorry

**Comment by gabm** [comment]
@davidedmundson is there any news on this? its still happening when I update sddm in arch. Still i downgrade to 14.0 to resolve.. How can I help to resolve? I'd create a PR and re-add the missing lines but I'm unsure of what sddm is supposed to do or not...

**Comment by gabm** [comment]
ok I'm still not sure what is the proper way to go but maybe its true that sddm shouldn't source /etc/profile as [this wiki entry](https://wiki.archlinux.org/index.php/Fish#Not_setting_fish_as_default_shell) suggests that bash should read /etc/profile instead. 

I did as suggested, use bash as the default and start fish in bashrc.. at least that got rid of the bug. Not sure whats the right thing to do here...

**Comment by Vogtinator** [comment]
It's a bit strange that this happens, because `/usr/share/sddm/scripts/Xsession` which does the `/etc/profile` reading is run by `/bin/sh`, which has to be a POSIX compatible shell, so not fish. fish should then just inherit the environment.

**Comment by soredake** [comment]
@Vogtinator 
> fish should then just inherit the environment.

It works like this in my case.

**Comment by soredake** [comment]
https://github.com/sddm/sddm/pull/1331#issuecomment-780413599

**Comment by ThisNekoGuy** [comment]
This appears to prevent Flatpaks from populating KDE properly, from what I can tell, even after reboots.

I was just reading over in https://github.com/flatpak/flatpak/issues/3109 about it acknowledgement on how to properly solve it has been rather lacking.
Having to just create a desktop file for every flatpak is rather annoying

**Comment by DarkArc** [comment]
So I manually applied https://github.com/sddm/sddm/pull/1331 via editing /usr/share/sddm/scripts/Xsession.

I still have:
```
echo $XDG_DATA_DIRS
/usr/share/kde-settings/kde-profile/default/share:/usr/local/share:/usr/share
```

While `bass source /etc/profile.d/flatpak.sh` does pull in the right environment variable changes. I'm not sure what's not working here... :disappointed: 

----

I can also confirm everything is set properly when using bash instead of fish.
