### ISSUE TITLE
error pam_elogind.so

### ISSUE THREAD

**Issue by loup001** [sddm/sddm#881]
Hi guys, just upgraded my arch xfce install. Part of the upgrade was the sddm package.
After rebooting, sddm had this error : PAM unable to dlopen(/usr/lib/security/pam_elogind.so): /usr/lib/security/pam_elogind.so: cannot open shared obj 
PAM adding faulty module: /usr/lib/security/pam_elogind.so
Since i do not use systemd login, i commented out : session	optional pam_elogind.so in /etc/pam.d/sddm-greeter as a temporary fix

**Comment by schober-ch** [comment]
I do see the same issue with a fresh arch linux install. Is this something possibly better suited for some arch bug tracker? Thoughts?

**Comment by Hi-Angel** [comment]
@schober-ch did you try upgrading, i.e. `sudo pacman -Syu`? My buddy have had the problem, so I refrained from upgrading; but recently I did, I see the same `pam_elogind.so` in the sddm-greeter, however it works. So I thought it might be a fixed packaging problem.

**Comment by davidedmundson** [comment]
It's "session optional", it's just a warning with no consequences.

It should have a - in front to supress messages.

**Comment by Hi-Angel** [comment]
@davidedmundson for my buddy sddm didn't start until he commented out the line.

**Comment by loup001** [comment]
putting a - in front of session optional in sddm-greeter boot to black screen .... revert back to a #

**Comment by Tids** [comment]
It would be nice, if sddm has a buildtime switch, lets say "nosystemd", that activates ```session                optional pam_elogind.so``` and disables ```session         optional pam_systemd.so```, and if not set ```session         optional pam_systemd.so``` would be active and ```session                optional pam_elogind.so``` not.
