### ISSUE TITLE
SDDM fails to start Plasma Wayland when SDDM is restarted

### ISSUE THREAD

**Issue by sandy-8925** [sddm/sddm#890]
I am using Arch Linux with SDDM as default DM, and the KDE Plasma desktop.

If I restart SDDM by executing "sudo systemctl restart sddm" I am unable to login to the Plasma Wayland session after the restart. It works perfectly fine on a fresh boot,

Please let me know if you need logs or any other info.

**Comment by davidedmundson** [comment]
After you restart SDDM is kwin_wayland still running from the old session?

**Comment by sandy-8925** [comment]
Yes.

**Comment by sandy-8925** [comment]
I killed the KWin processes and then logging in to Plasma Wayland works. Is
this a KWin bug?

**Comment by plfiorini** [comment]
Closing this issue, looks like a Plasma bug. The plasma session should end its processes like other desktop environment do.
