### ISSUE TITLE
sddm login dialog is super small on my HiDPI laprop display after upgrading to 0.15

### ISSUE THREAD

**Issue by bigunyak** [sddm/sddm#894]
Everything worked fine for me with `sddm-0.14` when the login dialog was scaled according to my laptop display size parameters specified in the `/etc/X11/xorg.conf.d/90-monitor.conf`
After upgrading to `sddm-0.15` I always get super small dialog with tiny not readable font.
I thought maybe the cause is in the new `EnableHiDPI` parameter in `sddm.conf` file which is set to `false` by default and for some reason specified in two sections: `[Wayland]` and `[X11]`. But setting this parameter to `true` doesn't have any affect.

It might be that changes in some other package cause the problem, as I upgraded quite a few of them, but since this is sddm which is not functioning properly now, I think it's fair to report this here.

P.S. this might be related to another issue #692

**Comment by akontsevich** [comment]
I have same issue in 0.15 version (openSUSE Tumbleweed): fonts and dialog are very small if nvidia proprietary driver selected and look ok with noveau.

**Comment by bigunyak** [comment]
Have just installed `sddm-0.16`, the problems is still there.
Tried to set `EnableHiDPI=false` inside `[Wayland]` and `[X11]` sections, has absolutely no effect, still get  tiny login dialog on my HiDPI laptop screen.

I wonder why did it get broken in `sddm-0.15` in the first place??

**Comment by genkiel** [comment]
This is completely broken on my deployment as well. We had a good solution with -dpi 240 and now this is broken as well.

**Comment by CraigAD** [comment]
I have tried many suggestions, e.g. the sddm readme file, Arch Linux HiDPI tips, and xrandr --help but all to no avail.  It would seem that, at least in my case, the Nvidia does not take scaling or panning, etc. The system already knows what the details of the monitors are, but it does not really matter.

For example, if I remind SDDM what the DPI is of each monitor is, the login screen looks great -- like it should. Adding this line to /usr/share/sddm/scripts/Xsetup

/usr/bin/xrandr --dpi 282/eDP-1-1 --dpi 110/HDMI-1-1

But then after login, the KDE Plasma scaling is all wrong -- Ubuntu 17.10 on Xorg only uses a single DPI setting -- so having two monitors with different DPI means that one will always have the wrong scaling.

The best solution that I have found is to stop fighting the bug and add this line to /usr/share/sddm/scripts/Xsetup

/usr/bin/xrandr --dpi 96 --ouput HDMI-1-1 --off

This just turns off the external HDMI monitor for the login screen ONLY and uses the 96 dpi setting for the OS and desktop to get the correct scaling -- once again, the system knows the details of your monitors i.e. size, pixels, etc. This does result in an extra small font used in the login screen, but all os/desktop scaling after login is correct.

A potential fix would exist if you could set the DPI for the login screen, but then convert back to 96dpi before entering the desktop -- by I have not figured out how to do that -- I thought that Xstop sounded like a logical place but it made no difference.

BTW, after login and using the system and performing a lock screen, the login screens are perfect sizes for each monitor -- Huhm.

**Comment by Vogtinator** [comment]
In openSUSE we fixed https://github.com/sddm/sddm/issues/680 so you need to use

```
[XDisplay]
EnableHiDpi=true
```

as documented in the man pages.

**Comment by Vogtinator** [comment]
The issue is simple. In the greeter's `main` we do:

```    // HiDPI
    bool hiDpiEnabled = false;
    if (QGuiApplication::platformName() == QLatin1String("xcb"))
        hiDpiEnabled = SDDM::mainConfig.X11.EnableHiDPI.get();
    else if (QGuiApplication::platformName().startsWith(QLatin1String("wayland")))
        hiDpiEnabled = SDDM::mainConfig.Wayland.EnableHiDPI.get();
    if (hiDpiEnabled) {
        qDebug() << "High-DPI autoscaling Enabled";
        QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    } else {
        qDebug() << "High-DPI autoscaling not Enabled";
    }
```

but at that point the configuration isn't read yet, so it always reads the default value.

**Comment by akontsevich** [comment]
> [XDisplay]
EnableHiDpi=true

@Vogtinator, please tell: where to set this and what sddm version to use? Thanks!

**Comment by Vogtinator** [comment]
As I wrote in https://github.com/sddm/sddm/issues/894#issuecomment-371082001 it probably doesn't have any effect no matter where you put it :-/

**Comment by akontsevich** [comment]
So bug still exists?

**Comment by damex** [comment]
hi,
i am here on 0.17.0 version and bug is still here.
hidpi option is still ignored.

**Comment by slokhorst** [comment]
@damex I think this only works from 0.18 onwards. (unreleased)

**Comment by slokhorst** [comment]
HiDPI is fixed for me in SDDM 0.18 with the following config: :smile: 
```
[X11]
EnableHiDPI=true
```

**Comment by akontsevich** [comment]
I set above in `/etc/sddm.conf` and nothing happened: still small fonts and controls. Something I need to do more? Any ideas?

**Comment by Vogtinator** [comment]
@akontsevich If nvidia detects your DPI correctly, you have LoDPI and not HiDPI.

If at all, Qt would scale buttons down with automatic scaling...

**Comment by akontsevich** [comment]
@Vogtinator, yes I have LowDPI, so what?! Software is buggy definitely. KDE have proper scaling.

**Comment by Vogtinator** [comment]
Please explain what you expect then.

**Comment by Vogtinator** [comment]
@akontsevich:

The nouveau driver always reports 96x96 DPI and ignores the monitor.

If you want the same behaviour for NVIDIA, set `ServerArguments=-nolisten tcp -dpi 96`.

This is also a symptom of https://bugreports.qt.io/browse/QTBUG-67928 though.

**Comment by akontsevich** [comment]
> If you want the same behaviour for NVIDIA, set ServerArguments=-nolisten tcp -dpi 96.

What is it? Where to set it?

**Comment by Vogtinator** [comment]
In /etc/sddm.conf:

```
[X11]
ServerArguments=-nolisten tcp -dpi 96
```

**Comment by akontsevich** [comment]
> If you want the same behaviour for NVIDIA, set ServerArguments=-nolisten tcp -dpi 96.

Yes, this works, thanks!

**Comment by akontsevich** [comment]
> This is also a symptom of https://bugreports.qt.io/browse/QTBUG-67928 though.

In this case Electron bug https://github.com/electron/electron/issues/12076 could be caused by wrong Qt/KDE scaling as I run electron applications under KDE. Need to check how it works under Gnome/Cinnamon/Mate.

**Comment by Vogtinator** [comment]
@akontsevich To clarify, that fonts get rendered at 52 DPI in Qt applications is not a bug. It's correct. The nvidia driver is to blame there.

**Comment by akontsevich** [comment]
No, Gtk3 renders different: 13pt system font looks ok, in Qt - very small, 17pt - very big in Gtk and normal in Qt/KDE. Let me check Gtk DEs work first. I can't get correct A4 paper size on my screen with any driver: nouveau or nvidia.

**Comment by Vogtinator** [comment]
Well, GTK does it wrong as well. NVIDIA configures X to render fonts at 52 DPI.

**Comment by akontsevich** [comment]
Not clear to me who is wrong, however I see Gtk DEs renders same fonts sizes as Qt/KDE. I just increased fonts sizes to 17pt.

**Comment by Vogtinator** [comment]
Most DEs, including Plasma and GNOME set Xft.dpi to 96 * scale factor by default. This means that the 52 DPI value of the monitor is ignored and 96 used instead. In Plasma it's visible as the "Force font DPI" option in the fonts kcm.

SDDM doesn't do any DPI configuration (it can't - at the point QApplication is instantiated the settings are already loaded) so it has to work with whatever the X server provides.

**Comment by akontsevich** [comment]
Hmm, switched off "Force font DPI" things become better a little in KDE: 
- true paper size in LibreOffice.
- I had 96 dpi and 13 pt system font, now set 52 and 16pt font
- Electron apps fonts look smaller however still big.

Hope this will be fixed some day globally in Linux :)

**Comment by Vogtinator** [comment]
That's a libreoffice bug which you need to report - the font DPI is not the correct one for accurate measurements...

**Comment by akontsevich** [comment]
Bug?! It shows things correctly.

**Comment by Vogtinator** [comment]
> Bug?! It shows things correctly.

You reported that with "force fonts dpi" it didn't.

**Comment by akontsevich** [comment]
Bug still exists, forced to use `ServerArguments=-nolisten tcp -dpi 96`

**Comment by jarrard** [comment]
> Bug still exists, forced to use `ServerArguments=-nolisten tcp -dpi 96`

I actually needed this line for my use because the UI elements were WAY too big and overlapping on each other (4k problems). Using a nvidia card obviously. 

The UI/text elements get too large when using a custom theme for SDDM, the default one appears ok.

**Comment by xuancong84** [comment]
Bug still exists today, if I use `ServerArguments=-nolisten tcp -dpi 96`, then after login, since I set resolution to 1920x1080 rather than the highest 3840x2160 (to save power), everything appears huge.

A temporary solution that works is to create or add a file `/etc/X11/xorg.conf.d/10-monitor.conf` containing the following:
```
## /etc/X11/xorg.conf.d
Section "Monitor"
	Identifier	"eDP1"
	Option		"Primary" "true"
	Option		"PreferredMode" "1920x1080"
EndSection

Section "Monitor"
	Identifier	"DP2"
	Option		"LeftOf" "eDP1"
	Option		"PreferredMode" "1366x768"
EndSection
```
whereby the identifier eDP1 can be different on different computers, e.g., eDP-1 for my Dell laptop, and eDP1 does not work.
You can get the monitor identifier by `xrandr --listactivemonitors`

This SDDM is pretty much broken even today.

**Comment by parrenin** [comment]
I also have this problem on Debian 12 using sddm 0.19.0: sddm text is too small on my 4k screen.

**Comment by xanaddams** [comment]
Hi, KDE Neon user. hp spectre x360 convertible 15-bl0xx 4K screen. Still an issue. Login screen resolution is too small to see font. Logs in, resolution is as set. ServerArguments=-nolisten tcp -dpi 96 does nothing.

**Comment by Pointedstick** [comment]
96 is the default DPI, so specifying it again isn't doing anything. For your screen, you want the value of the -dpi argument to be 192.

**Comment by xanaddams** [comment]
Changing it to 192 works. And triple thank you.  But, why is this still a bug that has to be hunted down and then applied via adding files to it? Creating dpi.conf, pasting "[X11] ServerArguments=-nolisten tcp -dpi 192" in /etc/sddm.conf.d/ wasn't even listed above. I did that via one other site I found. I don't even know if this will work for others, but I spent 4 hours hunting this down and I'm in IT. A regular end user will never find this. Will adding this to a non-4K hidpi monitor effect it? If not, why isn't it there. Shouldn't it be a basic script that's added to display driver install?

**Comment by Pointedstick** [comment]
If you use KDE's "apply Plasma Settings" feature in the System Settings SDDM page, it does that for you.

When SDDM is in native Wayland mode, hidpi works out of the box (or will in the next release) and finally nobody will need to do anything.

**Comment by xanaddams** [comment]
Unfortunately, like many people have posted both on the kde forum, here, and from majaro to suse, the sync does not work for hidpi 4k screens. If I remove this file that we created, it not only returns to the issue, but the sync does nothing. Even rebooting after sync does not correct the issue. This is both with x11 and Wayland. I had recommended on kde's community page that a dropdown for the login screen to set the resolution be made just to show how sync does not work. Every forum I found this issue on had the same, "use sync" response and each time the op said it doesn't work. Perhaps on 2k screens it does, but def not 4k.

**Comment by Pointedstick** [comment]
I'm typing this response on a laptop with a 4k screen where the hidpi scaling in SDDM in X11 mode works properly by adding 

```
[X11]
ServerArguments=-dpi 192
```

into my `/etc/sddm.conf.d/kde_settings.conf` file. As Fabian mentioned earlier, this won't work for NVIDIA and you'll also need to aff `-nolisten tcp` into the arguments list. This is something we *don't* do in our sync code in KDE, so if it's harmless, perhaps we should.

@Vogtinator Do you know if this is harmless to add for non-NVIDIA users, or does it regress anything?

**Comment by Vogtinator** [comment]
> As Fabian mentioned earlier, this won't work for NVIDIA

It should. The issue with the proprietary NVIDIA driver was the opposite: It did effectively set `-dpi` itself, based on the exact monitor DPI. 

> @Vogtinator Do you know if this is harmless to add for non-NVIDIA users, or does it regress anything?

Behavior of that option should be identical for all graphics drivers.

> you'll also need to aff -nolisten tcp into the arguments list. This is something we don't do in our sync code in KDE, so if it's harmless, perhaps we should.

I would hope that `-nolisten tcp` is the Xserver's default already. Otherwise passing this option is important, as otherwise the Xorg session is accessible remotely over the network.

**Comment by zhexyez** [comment]
Okay, but how to ignore scaling when in `--test-mode`? When it's loading at startup, everything is fine. In `--test-mode` the size is absolutely enormous. I'm in Hyprland with scale factor 2.<br/>
Sorry, I've found it in `sddm.conf`

**Comment by xuancong84** [comment]
As a more experienced Linux developer, now I treat SDDM as some sort of test beds for amateurs. Not only the resolution handling is lousy, there is no security at all: after screen lock, simply press `Ctrl+Alt+F[0-9]` can unlock the session for any user without any password; the reason is very simple: you cannot simply switch to a different TTY seat to lock the screen. And the same stupid mistake applies to `lightdm` as well.

**Comment by Vogtinator** [comment]
Screen locking is handled by the DE, not sddm.

**Comment by xuancong84** [comment]
> Screen locking is handled by the DE, not sddm.

Theoretically true, but practically false. I have tested that KDE Plasma on sddm/lightdm can have screen unlocked using the Ctrl+Alt+F# trick, but the same DE on gdm does not have this problem.

**Comment by Vogtinator** [comment]
It's also practically true - SDDM just does not handle screen locking.

If you expect Plasma to lock the screen on VT switches, please file a report on https://bugs.kde.org.

In any case, that is off topic on this issue.

**Comment by xuancong84** [comment]
Thanks @Vogtinator for your reply!
From what I found out, the exact behaviour of Plasma is as follows:
- in SDDM, every user's login session will allocate a TTY Seat from Ctrl+Alt+F7 onwards, so 2nd user will be on F8,  3rd user on F9, if any user locks a session, a new TTY Seat will be allocated (e.g., Ctrl+Alt+F10 (TTY10), so simply switching to Ctrl+Alt+F7 will unlock the screen for that user), which makes screen locking superficial but absent intrinsically.
- in GDM, the main login screen has Ctrl+Alt+F1 (TTY1), each subsequent user login will allocate Ctrl+Alt+F2/F3/... (TTY2/3/...) onwards, when a user locks the screen, the corresponding TTY will be locked instead of switching to a different TTY which makes screen lock working. 
This behaviour could very likely be due to your explanation:
> SDDM just does not handle screen locking.

And the same applies to `lightdm` as well.

On this topic, I think it is SDDM's responsibility to detect high-resolution display and either:
- auto rescale all GUI elements
- (or) switch to a medium resolution (e.g., closest to 2K) and render
rather than requiring user to manually modify `sddm.conf` to do that. That is why I found `sddm` extremely user unfriendly and switching to GDM instead. Despite its greeter screen somehow looks nicer than GDM's previous one.

**Comment by Vogtinator** [comment]
> auto rescale all GUI elements

It should already do that unless you set `EnableHiDPI=false`.

**Comment by Vogtinator** [comment]
> when a user locks the screen, the corresponding TTY will be locked instead of switching to a different TTY which makes screen lock working.

I don't understand that part - if I lock the screen, the screen lock locked here, and it does not switch to a different TTY.

**Comment by xuancong84** [comment]
> I don't understand that part - if I lock the screen, the screen lock locked here, and it does not switch to a different TTY.

Actually not that complicated, just try to press Ctrl+Alt+F1/F2/all the way to F12 at each step to get a feeling of what stupid sddm/lightdm is doing, and you will know everything.

> It should already do that unless you set EnableHiDPI=false.

If you are a top-notch developer, you should realize that the very existence of this option is an demonstration of incompetent programming and clumsy design of sddm/lightdm/etc., because in the server room, typically we plug in this monitor today and that monitor on another day, each monitor can have very different resolution limit ranging from 1024x768 to 3840x2160 or even higher/lower, and there is no time for you to change `EnableHiDPI` before switching to a different monitor (if that is indeed the case, then we would not call it Linux at all). So it is the Display Manager's responsibility to show the greeter GUI correctly on all types of monitors by either setting the correct resolution or scale GUI properly or both. The late versions `gdm` is programmed to cater to all types of monitors without manually changing any options or restarting `gdm` service. And lightdm/sddm should learn from it.

**Comment by Vogtinator** [comment]
The `EnableHiDPI` default is `true` for that reason. The only reason it exists at all is to handle the case that automatic scaling misbehaves, like for monitors which provide invalid EDID values. That is unfortunately not that uncommon.

**Comment by Vogtinator** [comment]
> If you are a top-notch developer, you should realize that the very existence of this option is an demonstration of incompetent programming and clumsy design of sddm/lightdm/etc.,

Please refrain from such insults, that's not constructive.

**Comment by zhexyez** [comment]
Ah, EnableHiDPI works only outside hyprland, as `--test-mode` runs it as an internal window, so assigns its `monitor` scale from `hyprland.conf`. Since there is no way to ignore that, test mode will always be scaled regardless of its settings. Now I see it.

**Comment by MistyDragon7** [comment]
> Ah, EnableHiDPI works only outside hyprland, as `--test-mode` runs it as an internal window, so assigns its `monitor` scale from `hyprland.conf`. Since there is no way to ignore that, test mode will always be scaled regardless of its settings. Now I see it.

This. I was _this_ away from banging my head in the wall before I realised this and tested the actual sddm by killing my session.
