### ISSUE TITLE
sddm v0.16.0 issues with NVIDIA drivers

### ISSUE THREAD

**Issue by NuLL3rr0r** [sddm/sddm#904]
I have issues with v0.16.0 with NVIDIA drivers. After upgrading my PC at work, X refused to start with the following error:
 
    [ 2542.994] (II) NVIDIA(0): ACPI: failed to connect to the ACPI event daemon; the daemon
    [ 2542.994] (II) NVIDIA(0): may not be running or the "AcpidSocketPath" X
    [ 2542.994] (II) NVIDIA(0): configuration option may not be set correctly. When the
    [ 2542.994] (II) NVIDIA(0): ACPI event daemon is available, the NVIDIA X driver will
    [ 2542.994] (II) NVIDIA(0): try to use it to receive ACPI event notifications. For
    [ 2542.994] (II) NVIDIA(0): details, please see the "ConnectToAcpid" and
    [ 2542.994] (II) NVIDIA(0): "AcpidSocketPath" X configuration options in Appendix B: X
    [ 2542.994] (II) NVIDIA(0): Config Options in the README.

No matter what I did it refused to start.  Last night at home I upgraded my home PC and it refused to start X too. After much investigation and downgrading to sddm-0.15.0 it works again.

I reported it on my [distribution bug-tracker](https://bugs.funtoo.org/browse/FL-4292) but thought it might be an upstream issue.

**Comment by abucodonosor** [comment]
well the distro bug you point to is about bug #903

from your log you have some APCI problem and I don't think these have anything to do with
sddm.

**Comment by NuLL3rr0r** [comment]
Thanks for the respone. Well, even building the NVIDIA driver without ACPI support won't stop the error. And, as I said it works with the previous release of SDDM.

**Comment by NuLL3rr0r** [comment]
Well, today I update my distro and it look likes sddm had an update. I'm not sure what solved the issue in sddm upgrade but since the issue was gone, I'll close this issue.
