### ISSUE TITLE
Sound disappears on KDE 5 logout/relogin

### ISSUE THREAD

**Issue by akontsevich** [sddm/sddm#914]
Sound disappears on logout/relogin. Problem is in pulseaudio process which remains from previous login session. Killing it solves the problem - new instance start automatically then and sound plays again. In KDE bugzilla they said it is a SDDM problem: https://bugs.kde.org/show_bug.cgi?id=385829#c1

**Citation:**
> Then that's not a plasmashell problem. Whether SDDM should clear up stray processes, is up for debate (on the SDDM tracker), but there's some complexities there.

**Comment by rdieter** [comment]
I'd argue this isn't sddm's job either.  pulseaudio's default timeout before exiting is 30 seconds, either wait that long before logging in again, or reduce it to satisfy your needs, /etc/pulse/daemon.conf:
exit-idle-time = 5
for example.

**Comment by plfiorini** [comment]
A desktop environment that starts programs and doesn't terminate their processes at logout has clearily a bug that shouldn't be attributed to a login manager.

**Comment by akontsevich** [comment]
> A desktop environment that starts programs and doesn't terminate their processes at logout has clearily a bug that shouldn't be attributed to a login manager.
Why KDE team says it is a [SDDM bug](https://bugs.kde.org/show_bug.cgi?id=385829#c1)?! Could you discuss with them please?

**Comment by plfiorini** [comment]
This doesn't happen with Liri for example, there the session manager launches autostart programs (including `/etc/xdg/autostart/pulseaudio.desktop`) and SIGTERM and SIGKILL if needed are sent to the process upon logout.

@davidedmundson Plasma should just keep track of the processes it starts and kills them on logout. Is it possible?

**Comment by rdieter** [comment]
logind supports (something like) that too (logind.conf : KillUserProcesses=yes )
