### ISSUE TITLE
Prevent SDDM from looking for faces in users' home directories

### ISSUE THREAD

**Issue by paulo1205** [sddm/sddm#921]
Is there a way to prevent SDDM from looking for faces in users' home directories?

I ask that because SDDM is taking hours searching for users' faces by mounting remote 9000+ users' home directories over NFS, from several different NFS servers.  I tried several themes, and even themes that don't show any pictures for the user still hang, with the greeter looking for faces that will never be shown.

(This is with Kubuntu 16.04 stock version of SDDM).

**Comment by plfiorini** [comment]
From `man 5 sddm.conf`, `General` section:

```
       EnableAvatars=
              When enabled, home directories are searched for ".face.icon" images to display as their avatars. This can be slow on some file systems.  When disabled, all avatars will be default. Themes may choose to hide them altogether.   Default
              value is true.

```
