### ISSUE TITLE
ACPI and PCIe Bus Errors with sddm 0.16.0-1

### ISSUE THREAD

**Issue by YouRik** [sddm/sddm#924]
I get ACPI and PCIe Bus errors which would not allow me to get to the sddm login screen on my laptop with sddm 0.16.0-1.

A workaround was to boot with the parameter `single`, so on the same screen I get the errors, I would get prompted to enter a maintenance password or press CTRL+D. Pressing CTRL+D on this screen would continue to the sddm login screen.

The errors do not appear when using 0.15.0-2, so I downgraded back to this version.

Screenshot of the errors:
https://i.imgur.com/1HTmb2H.jpg

Thread where I tried to track down what caused the errors:
https://www.reddit.com/r/ManjaroLinux/comments/799x9r/errors_on_boot_since_system_upgrade/

**Comment by plfiorini** [comment]
This has nothing to do with SDDM, please ask in your distribution forum.

**Comment by YouRik** [comment]
Thanks for the comment. Maybe the errors themselves don't have anything to do with SDDM but on 0.16.0-1 SDDM won't start up properly. As I mentioned in my original post, I get stuck on the screen where the errors get shown to me and downgrading SDDM "fixes" it.

I also found another person with the same issue, also on an HP laptop, so this is definitely not an isolated case.

I would appreciated if you could take a look into this.
