### ISSUE TITLE
SDDM seems to ignore desktop files when choosing session type.

### ISSUE THREAD

**Issue by slackhead** [sddm/sddm#927]
SDDM 0.16.0

Choosing a session isn't working for me. I will only start whichever DE/WM was chosen with xwmconfig, as if I was going 'startx'.

I have fluxbox.desktop in /usr/share/apps/kdm/sessions/ and /usr/share/xsessions/ but they seem to be ignored when choosing fluxbox, and i3wm loads instead. It's the same with any of the other DEs/WMs.

**Comment by davidedmundson** [comment]
We process Xsession scripts, if something on your setup there launches i3 and blocks continuing, you'll get i3.

**Comment by slackhead** [comment]
There's nothing else that could be launching i3. If I run xwmconfig and choose fluxbox, then sddm runs fluxbox.

**Comment by davidedmundson** [comment]
Not all display managers correctly source xsession scripts

**Comment by davidedmundson** [comment]
It might be something else, but please grep and check.

**Comment by slackhead** [comment]
I found the problem: I had an ~/.xsession script that was overridding whatever I chose in SDDM session chooser.

**Comment by slackhead** [comment]
I should add that .xsession is created by xwmconfig, so maybe it's not a great idea to run it.
