### ISSUE TITLE
Recognize keyboard input even when textbox isn't focused

### ISSUE THREAD

**Issue by Brli** [sddm/sddm#928]
I'm on Arch linux with SDDM version 0.16.0, using breeze theme.

I noticed that at first boot, the textbox isn't focused (probably a theme problem), but I can still input password (where there is no "dot" appears at the password box), press Enter and log into KDE aka. enter the splash phase, and blend into plasma desktop.

**Comment by Brli** [comment]
lock screen also have this problem :/

**Comment by plfiorini** [comment]
Sounds like a Plasma bug because you are using a theme that is not provided by SDDM, and lock screen is definitely a Plasma responsibility since it doesn't even run on SDDM.

You should file a bug report to the KDE people.

CC: @davidedmundson

**Comment by Brli** [comment]
sorry for a late reply, but it occurs in Maui also, please reopen.
