### ISSUE TITLE
Starting qtVirtualKeyboard on SDDM

### ISSUE THREAD

**Issue by adocampo** [sddm/sddm#932]
Hi again,

I'm trying to start qtVirtualKeyboard on boot. I have it working on Plasma lock screen. And I can test it on breeze SDDM theme with:
```
export QT_IM_MODULE=qtvirtualkeyboard
sddm-greeter --theme /usr/share/sddm/themes/breeze
```
And it shows correctly :) So, I modified the systemd unit file [Service] section like this
```
[Service]
Environment=QT_IM_MODULE=qtvirtualkeyboard
ExecStart=/usr/bin/sddm
Restart=always
```
Am I doing something wrong? Is this expected to work like this?

Best,
Angel

**Comment by dastbar** [comment]
Another way is to set QT_IM_MODULE in /etc/environment.

**Comment by eliasp** [comment]
> Another way is to set QT_IM_MODULE in /etc/environment.

This won't work - systemd luckily makes sure services are started with an untainted/defined environment, where only environment variables explicitly defined are present.

**Comment by aleixpol** [comment]
This seems to suggest that `InputMethod=qtvirtualkeyboard` is the entry you want, and it seems like a sane default, so I created a PR.

https://github.com/sddm/sddm/pull/940

**Comment by plfiorini** [comment]
The issue shall be closed now since I merged the PR.

**Comment by adocampo** [comment]
Awesome! Now it seems to work perfectly with breeze theme, which is the theme I use on logon screen :) Thank you very much! Right now I'm doing a clean installation to see if it logs in well through Active Directory, but so far is a great improvement! :D

Just for your information, on maui theme also works, but no "Keyboard" shortcut appears anywhere, just selecting the user, the virtualkeyboard appears occuping almost all the screen. Perhaps is the behaviour you want. Personally I don't like and I don't use this theme anywhere.
