### ISSUE TITLE
Login Hangs for 15s

### ISSUE THREAD

**Issue by himbeere** [sddm/sddm#938]
Hello Devs.

sddm-0.16 here and plasma-5.11.3 here.

I'm suffering for a few weeks now from a hanging login session. The splash screen stays for around 15s. Then everything starts up fine. No further problems at all. Is there a way to debug? Nothing special in xorg.log or .local/share/sddm/xorg-session.log. Any help is really appreciated.

thanks and cheers

**Comment by himbeere** [comment]
![img_20171114_191921](https://user-images.githubusercontent.com/631865/32823763-9ed5fa2c-c9de-11e7-9fa9-f12838a1e51e.jpg)

**Comment by plfiorini** [comment]
Check also `journalctl -b` although I'm convinced this is not a SDDM issue since the user session has already been started. This is the Plasma boot sequence that is frozen.

**Comment by himbeere** [comment]
You're right it's not sddm it's plasma. https://bugs.launchpad.net/ubuntu/+source/breeze/+bug/1584604.
