### ISSUE TITLE
How to change the clock format of sddm-greeter?

### ISSUE THREAD

**Issue by debianroot20200524** [sddm/sddm#941]
I need to change the clock format to"YYYY-MM-DD HH:MM:SS",but I can't found any options in sddm-kcm and sddm configuration file,what should I do?

**Comment by NucleaPeon** [comment]
I would like a 24 hour clock setting. My plasma taskbar clock is set to that and my locale is us.UTF-8.
Running gentoo. Is there a possible conf file setting that could enable this?

**Comment by a5pire** [comment]
How is this issue still open... Im looking for this option too.

**Comment by belveruski** [comment]
Up

**Comment by davidedmundson** [comment]
Change your LC_ env vars.

**Comment by eyeonus** [comment]
> Change your LC_ env vars.

That would be GREAT advice if it *worked*

![Image](https://github.com/user-attachments/assets/c82aa650-ab9c-4202-abef-e90f63c1cbff)

![Image](https://github.com/user-attachments/assets/9b5cb26d-453d-47fb-a27b-2f422c39c3a2)

![Image](https://github.com/user-attachments/assets/e209423d-92ea-4db5-9c46-457ecd401173)
