### ISSUE TITLE
SDDM needs to use a different location for Xauthority

### ISSUE THREAD

**Issue by Vogtinator** [sddm/sddm#944]
The hostname of a system can change, for instance if it's automatically configured with DHCP and a connection changes. If it changes during a running X11 session, started clients try to connect using the new hostname and get rejected by the server.
By exporting XAUTHLOCALHOSTNAME to the hostname that was written into the auth cookie, clients always use the correct hostname for connecting.

**Comment by Vogtinator** [comment]
There's a second bug that prevents this from being as useful as it should be - entries for old hostnames are still kept in XAUTHORITY (since https://github.com/sddm/sddm/commit/72175056a0af1b523e92861e75d602fb740dc238). Unfortunately those get preferred over the new cookie and auth fails.

**Comment by Vogtinator** [comment]
I talked with some X11 experts on this and the best solution is to:

* Truncate the Xauthority file again on login
* Use a different location for Xauthority by default (which won't be written to outside of sddm)

As it's not possible to login twice as the same user, the file truncation then does not matter anymore.

Any thoughts/opionions about that?

**Comment by davidedmundson** [comment]
>As it's not possible to login twice as the same user,

it is possible

**Comment by Vogtinator** [comment]
Shouldn't it reuse the existing session instead?

**Comment by davidedmundson** [comment]
I had bugs on KDM which didn't saying it should.
I had bugs on LightDM which did saying it shouldn't.

SDDM didn't till last release which made it a config option.

**Comment by Vogtinator** [comment]
Current SDDM releases (which don't include my "Do not truncate .Xauthority" commit) would nuke other X sessions' cookies instantly during login, so I would say that logging in twice never worked on any released sddm.

**Comment by Vogtinator** [comment]
What would work in all cases: Create a Xauthority file in /run/sddm and make it readable by the user only. Then that file can be used as $XAUTHORITY.

**Comment by mpictor** [comment]
@Vogtinator since you closed #947, should this be closed as well?

**Comment by Vogtinator** [comment]
Having .Xauthority in .local/share/sddm is not the best option (it should be either .Xauthority or somewhere in /run) but I don't think it causes any issues anymore, so yes.
