### ISSUE TITLE
nvidia-prime + xorg 1.19 + sddm = artifacts around mouse on first login 

### ISSUE THREAD

**Issue by sudopluto** [sddm/sddm#954]
This has been an issue for ubuntu users of sddm for a while now. With newer xorg versions, sddm has an artifact around the mouse that carries on into the desktop session. 

[https://bugs.launchpad.net/ubuntu/+source/plasma-workspace/+bug/1684240](https://bugs.launchpad.net/ubuntu/+source/plasma-workspace/+bug/1684240)

[https://www.kubuntuforums.net/showthread.php/72149-Mouse-artifact-introduced-in-7-26-update](https://www.kubuntuforums.net/showthread.php/72149-Mouse-artifact-introduced-in-7-26-update)

I have this issue so I am willing to be a guinea pig for any testing.

**Comment by davidedmundson** [comment]
if it affects the desktop session too then it's not an SDDM bug.

**Comment by sudopluto** [comment]
It doesn't occur at all when using other display managers. Even SDDM doesn't display this behavior after logging in and out. Something about the first login with SDDM triggers this bug.

**Comment by sudopluto** [comment]
Does sddm use opengl? Is there any logs I can post of sddm startup / opengl use that might help?

**Comment by sudopluto** [comment]
Seems to be an issue with the nvidia driver, pursuing this on their forum for now.
