### ISSUE TITLE
sddm 0.17.0-3 doesn't execute XSetup correctly on startup

### ISSUE THREAD

**Issue by pentix** [sddm/sddm#959]
I've set up the `/usr/share/sddm/scripts/Xsetup` script to run `setxkbmap` to change the keyboard layout.

However since I've upgraded (0.17.0-2) to  0.17.0-3 the keyboard layout isn't set correctly anymore, so I guess it started to ignore the Xsetup script?

**Comment by Vincent43** [comment]
See my comment in https://github.com/sddm/sddm/issues/958#issuecomment-353714073

**Comment by pentix** [comment]
Perfectly, I used the absolute path and it worked fine. Thank you! 👍
