### ISSUE TITLE
sddm no longer shows MATE, and one of two i3 options

### ISSUE THREAD

**Issue by isaacwhanson** [sddm/sddm#960]
I have been building and rebuilding VMs that use sddm lately, using a script to make reproducible builds.

Just today (no changes to build process) sddm no longer displays "MATE".  I also have i3 installed.  It should be displaying "i3" and "i3 (with debug log)" but I get the latter as the only option available.

running Arch Linux

**Comment by jleclanche** [comment]
Yeah it's not finding lxqt session either, only Openbox. Any idea @plfiorini? I think we're going to need a 0.17.1 once this is fixed.

**Comment by plfiorini** [comment]
@isaacwhanson I need more info.

Output of `ls -al /usr/share/xsessions`

SDDM logs from journal

**Comment by jleclanche** [comment]
@plfiorini Sessions are still present in  /usr/share/xsessions:

-rw-r--r--   1 root root 2309 Oct 22 03:21 lxqt.desktop
-rw-r--r--   1 root root  186 Dec 23 06:10 openbox.desktop
-rw-r--r--   1 root root  198 Feb 20  2016 openbox-kde.desktop

Looked at sddm logs and there's nothing unusual in there, it just doesn't find lxqt or openbox-kde.

**Comment by Vincent43** [comment]
Possibly repleted to https://github.com/sddm/sddm/issues/958#issuecomment-353714073

**Comment by isaacwhanson** [comment]
This was fixed in sddm 0.17.0-4 via the bug posted by @Vincent43
