### ISSUE TITLE
theme changing after update

### ISSUE THREAD

**Issue by vendforce** [sddm/sddm#962]
Why is the new releases deleting the theme when you update

OS: arch
DE: kde

Ive notice in the last month theres been a couple of updates 0.17.2/0.17.4 etc

each time my sddm theme is reset to the default and I have to change it
is this an aur PKGBUILD fault or sddm build fault

the theme shouldnt have to be changed or reset

**Comment by davidedmundson** [comment]
pkgbuild. They removed an important file to try and "fix" something

**Comment by vendforce** [comment]
thanks for your reply
