### ISSUE TITLE
SDDM Crash when password is extreamly big

### ISSUE THREAD

**Issue by AlkindiX** [sddm/sddm#963]
Using KDE neon with built in sddm version 0.17.0 crash after entering too big password (more than 10,000 or even 100,000) using the same login session and by entering the same password serveral times (5 times or more), This crash sddm and a black screen appears with instructions about login manually.

I am using Ubuntu 16.04 LTS with KDE neon  version 4+p16.04+git20171020.0022 from this source [http://archive.neon.kde.org/user](http://archive.neon.kde.org/user)

**Comment by davidedmundson** [comment]
If you're getting instructions you're almost certainly talking about kscreenlocker not sddm.

Is this at the login screen or the lock screen for an already logged in user.

**Comment by AlkindiX** [comment]
This only happen in lock screen

**Comment by davidedmundson** [comment]
select product kscreenlocker, component greeter.

You'll get me again, but me with my KDE hat on instead of my SDDM one.
