### ISSUE TITLE
Buggy when the cursor size get changed

### ISSUE THREAD

**Issue by jacob-emery** [sddm/sddm#965]
I am using KDE Neon Standard Edition with the latest SDDM.
Since my laptop features a 14' 1080p screen, I prefer to use a cursor that is at least 36 pixel. In the Plasma desktop I managed to change the size without problems. However, having the cursor's size small in the SDDM Login screen and getting the right one after the login is not very appealing. After a lot of research, I figured out how to set another size for the SDDM Login. I opened the console and I executed:
SUDO_EDITOR=kwrite sudoedit /etc/environment
Afterwards, I added the line:
XCURSOR_SIZE=36
I think that I also did something else because the tweak wasn't working in the beginning.

There are still some bugs:

a) The size of the cursor is initially the default one. At the smallest mouse/touchpad movement, the size gets fixed. It should start already with the right size.

b) If you press on other Desktop Environments dialog you will have to choose which desktop environment you want to use. When you haven't choosen yet the mouse gets the smaller size again. It gets the right size automatically after choosing a DE. It would be nice if it has always the same size.

c) It seems that when the password to login is given, the password changes again for a vary small span of time.

I think it would be a good idea to fix these bugs and to give a possibility to choose not only which cursor theme to use, but also its dimention in /etc/sddm.conf.
Thank you for your attention and for the effort you devs put into this project!

**Comment by joshuakraemer** [comment]
I do not see changing cursor sizes with sddm-0.19.0_3, so this is probably solved.
