### ISSUE TITLE
Error with QT 5.10.0

### ISSUE THREAD

**Issue by anupam-git** [sddm/sddm#969]
Hi,

Facing issues with SDDM when the system has QT 5.10.0 installed.

Here's what I did : 
1. Installed KDE Neon
2. Enabled the testing repository, `deb https://archive.neon.kde.org/testing`
3. Ran `sudo apt update`
4. Ran `sudo apt upgrade`
5. Reboot

After rebooting, not able to log in and also this error message is being shown at the login screen : ![`Error screenshot`](https://user-images.githubusercontent.com/5106648/35583019-919ca17a-0616-11e8-81cc-70befb2099c9.png)

**Comment by davidedmundson** [comment]
SDDM is detecting there's an issue with KDE's theme stuff and falling back properly. SDDM is fine.

And it's not really a KDE issue either, recompile your kdeclarative.
