### ISSUE TITLE
[Proposal] Dynamic online background images

### ISSUE THREAD

**Issue by adocampo** [sddm/sddm#977]
I'd just wondering if configure sddm to set dynamic background images from online services like NASA or 500px is near in the radar of the sddm project?

Is a cool feature to have. I remember there was a way to configure Bing's Image of the day as a desktop wallpaper, I would love to see something similar on the login (and lock) screen of Plasma!

**Comment by davidedmundson** [comment]
I may add a way for the Breeze theme to use Plasma wallpaper eventually, but it's not within the scope of SDDM. Sorry. 

Also it's difficult as not many users have network at this point, and it introduces a world of security issues that we don't want.

**Comment by MurzNN** [comment]
> Also it's difficult as not many users have network at this point, and it introduces a world of security issues that we don't want.

This can be optional plugin, so users that have network at SDDM can see cool dynamic wallpapers instead of static. Also "Image of the day" wallpapers can be downloaded after user login and connect to network (via some script), and displayed statically after downloading to local folder.
