### ISSUE TITLE
Power and Reboot buttons not working

### ISSUE THREAD

**Issue by ivokosir** [sddm/sddm#978]
I have fresh install of arch. All default settings. `sddm 0.17.0`

When I log in poweroff and reboot buttons don't work. (With default theme they are not even shown)
Still, I recieve messages in `journalctl`:

```
Message received from greeter: Reboot
Message received from greeter: PowerOff
```

**Comment by ivokosir** [comment]
[Here](https://bbs.archlinux.org/viewtopic.php?id=234450) is the link for discussion I created in archlinux forum.

There is a problem with `sddm.service`. It should be run after `systemd-logind.service`, but this is not the case. Atleast, not in archlinux default configuration. I fixed the issue by adding `systemd-logind.service` in `After=` line in `sddm.service`.

`sddm.service` after change:
```
[Unit]
Description=Simple Desktop Display Manager
Documentation=man:sddm(1) man:sddm.conf(5)
Conflicts=getty@tty1.service
After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service systemd-logind.service

[Service]
ExecStart=/usr/bin/sddm
Restart=always

[Install]
Alias=display-manager.service

```

**Comment by NerosTie** [comment]
Thanks, same issue on my side. Your solution fixed it.

**Comment by ivokosir** [comment]
@NerosTie I'm interested, are you also using archlinux?

**Comment by NerosTie** [comment]
@ivokosir Yes.

**Comment by MarianArlt** [comment]
Funny. As mentioned in the forum by somebody else I'm on a settled arch install and I'm having no issues at all with the default sddm.service

**Comment by gruel** [comment]
Same problem on archlinux, same solution: adding systemd-logind.service in the service.

**Comment by ssergiienko** [comment]
This is a definily race condition between services - I've tried to reboot few times and in 80% cases the bug is present, but in 20% all works fine (my system is on fast ssd).
And I can confirm that explicit dependencie fixes the problem.

/cc @MarianArlt

**Comment by chris21k** [comment]
Same here on Debian Testing/Buster on my bare metal machine. My VM (also unter Debian Buster) does not show the behavior.
The workaround to add After=systemd-logind.service works also for me.
Many thanks to @ivokosir .

Chris
