### ISSUE TITLE
Updates break user set background image

### ISSUE THREAD

**Issue by RaitaroH** [sddm/sddm#985]
So I am using KDE Neon 5.12 and every time the sddm is getting updated the theme.conf file ends up like this:
```
[General]
type=color
color=#1d99f3
background=
```
As you can see the background image is getting removed. Also it does not fallback on the color either. Instead it looks white.

![screenshot_20180302_152112](https://user-images.githubusercontent.com/19552720/36900779-5ecd7d26-1e2d-11e8-889f-8cb9f0ea337d.png)

**Comment by davidedmundson** [comment]
Downstream problem
