### ISSUE TITLE
User Picture

### ISSUE THREAD

**Issue by vendforce** [sddm/sddm#986]
when login as root sddm isn't showing face/picture in login is there any way to modify the Main.qml to allow root user picture

default theme : breeze
os: arch
de: kde plasma 5.12

**Comment by eliasp** [comment]
Besides the fact, that this might be a bug, don't do this - don't ever login as root to an X11 session!

I wonder whether sddm should rather prevent a user from shooting into his own feet by preventing a root login…

**Comment by vendforce** [comment]
> I wonder whether sddm should rather prevent a user from shooting into his own feet by preventing a root login…

pointless option people will make a patch why threat people 

really open source ?? 

what are you my mother ?? If I want to  login as root I will

what is it with Linux community and telling users what they can or can't do , when the basic of linux was designed for hacking and tweaking and the freedom to do with what ever you want

please refrain and desist from tell people how to, and what way to use Linux 

Many people login as root and use a root env for some sessions so this is absurd

there should always be an option whether you want to or not use root ..

**Comment by vendforce** [comment]
forget it , I figured it out . I don't know why I bothered asking I should have just figured it out myself 

so for anyone that wants to enable root pic in sddm enter the below into your terminal and logout
```

sed -i 's/disableAvatarsThreshold/enableAvatarsThreshold/g' /usr/share/sddm/themes/breeze/Main.qml
EXCLUDE_USERS=$(sed 's/:.*//' /etc/passwd | grep -v root | tr '\n' ' ' | awk '{$1=$1}1' OFS=",")
sed -i 's/HideUsers=/HideUsers='$EXCLUDE_USERS'/g' /usr/lib/sddm/sddm.conf.d/sddm.conf
```

**Comment by vendforce** [comment]
Let me give you a lesson on how to respond to such a question 

I wouldn't recommend using root regarding security it isn't safe unless you know know what your doing 

but If you so wish and aware that using root has security issues this is how you go about it if your using the below specs as declared 

OS: ARCH
DE :KDE PLASMA
SDDM THEME:BREEZE

sed -i 's/disableAvatarsThreshold/enableAvatarsThreshold/g' /usr/share/sddm/themes/breeze/Main.qml
EXCLUDE_USERS=$(sed 's/:.*//' /etc/passwd | grep -v root | tr '\n' ' ' | awk '{$1=$1}1' OFS=",")
sed -i 's/HideUsers=/HideUsers='$EXCLUDE_USERS'/g' /usr/lib/sddm/sddm.conf.d/sddm.conf

logout and the root pic will be present

**Comment by vendforce** [comment]
opps I missed there was an option to set max and min users 
```
sed -i 's/disableAvatarsThreshold/enableAvatarsThreshold/g' /usr/share/sddm/themes/breeze/Main.qml
sed -i 's/.*MaximumUid=.*/MaximumUid=0/g' /usr/lib/sddm/sddm.conf.d/sddm.conf
sed -i 's/.*MinimumUid=.*/MinimumUid=0/g' /usr/lib/sddm/sddm.conf.d/sddm.conf

```
