### ISSUE TITLE
[PROPOSAL] Automatic Screen Locking after Auto Login

### ISSUE THREAD

**Issue by notorand-it** [sddm/sddm#993]
I think it could make a lot of sense to add this capability to lock the screen after an Auto Login.
This makes sense for single user workstations.
Normally, without the auto login, you enter the password and wait for the DE to finish its boot.
With auto-login you jump straight into the DE, but with no password check. I know this is intrinsic to the "auto login".
By adding the proposed feature you can have the workstation completely booted to the DE, but still with an access password required.
This for example used to be available in KDM, the KDE display manager.

**Comment by Vogtinator** [comment]
That's not possible to implement in the display manager itself - that can only be controlled by the DE.

For Plasma, you can export `DESKTOP_LOCKED` as environment variable before calling `startkde` for example, but I don't think it's portable.

The best option is probably to add a new session file which sets this environment variable, such as "Plasma (with screen locked)" and use it as autologin session.

**Comment by notorand-it** [comment]
Where's the file that says to sddm to run startkde?
(I am a newbie for this kind of things).

**Comment by davidedmundson** [comment]
/usr/share/xsessions

**Comment by davidedmundson** [comment]
Out of scope for SDDM. Sorry.

See @Vogtinator comment for a solution
