### ISSUE TITLE
Compile Failure in master

### ISSUE THREAD

**Issue by jriddell** [sddm/sddm#994]
Compiling master for KDE neon dev stable edition we get a compile failure

https://build.neon.kde.org/job/xenial_stable_3rdparty_sddm_bin_amd64/17/console

11:40:52 /workspace/build/src/helper/UserSession.cpp: In member function ‘virtual void SDDM::UserSession::setupChildProcess()’:
11:40:52 /workspace/build/src/helper/UserSession.cpp:159:47: error: base operand of ‘->’ has non-pointer type ‘passwd’
11:40:52                  .arg(QString::fromLocal8Bit(pw->pw_dir))
11:40:52                                                ^
11:40:53 src/helper/CMakeFiles/sddm-helper.dir/build.make:182: recipe for target 'src/helper/CMakeFiles/sddm-helper.dir/UserSession.cpp.o' failed

Our git unstable edition builds sddm 'develop' git branch which compiles fine
https://build.neon.kde.org/view/2%20unstable%20☣%20git%20master/job/xenial_unstable_3rdparty_sddm/

**Comment by rikmills** [comment]
Same error on Kubuntu CI.

**Comment by Vogtinator** [comment]
The master branch is not used, it should probably be removed.

**Comment by plfiorini** [comment]
The `master` branch is used, it contains the last released code, and `develop` is merged in `master` at release time.

**Comment by Vogtinator** [comment]
Really? It says for me `Latest commit d4b6c44  on 10 Sep 2015`. That might be a GitHub bug though, showing the commit date instead of the push date.

**Comment by plfiorini** [comment]
It was an old PR that was recently merged, it was still targeting `master` instead of `develop`. Now I have aligned the two branches and fixed the build.

**Comment by Vogtinator** [comment]
IMO it should be reverted in master and only be added to develop.
